### PR TITLE
bug fixed for Unable to use off for enum values in yaml file #17798

### PR DESCRIPTION
**Pull request by freekry**
bug fixed for Unable to use off for enum values in yaml file #17798 and the [comment](https://github.com/spring-projects/spring-boot/issues/17385#issuecomment-518825344)

I found that `off` and `false` resolved to `Boolean false` in yaml, but it can't found mapping logging lever，so i added some codes to make Boolean to String.I am not sure if the location of the code is appropriate, but it works fine.

### CODE REVIEW

**Comment by freekry** [comment]
checkstyle and spring-javaformat maked me crazy （︶︿︶）

**Comment by mbhave** [comment]
Thanks for creating a PR @freekry. I think we'd like to fix this slightly differently. Specifically, we don't want to add `ON` to `LogLevel` and `YamlPropertySourceLoader` shouldn't need to know about the `logging.level` property. Thanks anyway.

**Comment by freekry** [comment]
@mbhave I got you code and run it. when i set `false` or `off` it worked, but when i set `true` or `on` it throw Exception:`Caused by: java.lang.IllegalArgumentException: No enum constant org.springframework.boot.logging.LogLevel.true`

**Comment by philwebb** [comment]
@freekry "true" and "on" aren't valid logging levels so that exception is correct.

**Comment by freekry** [comment]
@philwebb  I am sorry.I am just confused by [this](https://github.com/spring-projects/spring-boot/commit/835108e522ca4a1969d35a96ecf731e63f554ea2):`Support binding of YAML style true/false values to 'ON'/'OFF'.Thank you for your reply.


`

**Comment by freekry** [comment]
@philwebb I am sorry.I am just confused by [this](https://github.com/spring-projects/spring-boot/commit/835108e522ca4a1969d35a96ecf731e63f554ea2):`Support binding of YAML style true/false values to 'ON'/'OFF'.`

Thank you for your reply.



.Thank you for your reply.

**Pull request closed without merging**
