### PR TITLE
Fix capitalization of Testcontainers in Howto docs

### PR DESCRIPTION
**Pull request by rnorth**
Unfortunately 3e3ff26 included a minor capitalization issue. `TestContainers` is incorrect; `Testcontainers` is the correct way to write the name.

Refs #20734

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rnorth Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=21417)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=21417) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by rnorth** [comment]
@pivotal-issuemaster This is an Obvious Fix
per https://cla.pivotal.io/about#obvious-fixes

**Comment by pivotal-issuemaster** [comment]
@rnorth This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by snicoll** [comment]
@rnorth good catch, thank you.

**Pull request closed without merging**
