### PR TITLE
Configure the ActiveMQ connection pool - Fixes gh-1598

### PR DESCRIPTION
**Pull request by herau**
Refactor the configuration `spring.activemq.pooled:false` to `spring.activemq.pool.enabled:false`, to be able to add configuration for the `pooledConnectionFactory`:

```
spring.activemq.pool.enabled=true
spring.activemq.pool.max-connections=1 
spring.activemq.pool.max-sessions-per-connection=500
spring.activemq.pool.time-between-eviction-runs-millis=-1
spring.activemq.pool.idle-time-millis=30000
spring.activemq.pool.expiry-time-millis=0
```

> Waiting review to see if you add all the available configuration properties for the PooledConnectionFactory .

```
BlockIfSessionPoolIsFull : boolean
BlockIfSessionPoolIsFullTimeout : boolean
CreateConnectionOnStartup : boolean
ReconnectOnException : boolean
UseAnonymousProducers : boolean
```

> I choose `spring.activemq.pool` prefix because it's the prefix used in the [PooledConnectionFactory class](http://activemq.apache.org/maven/apidocs/src-html/org/apache/activemq/pool/PooledConnectionFactory.html#line.44)

### CODE REVIEW

**Comment by snicoll** [comment]
:+1:

**Comment by herau** [comment]
If we want to have all the available configuration for the [`PooledConnectionFactory`](http://activemq.apache.org/maven/apidocs/org/apache/activemq/jms/pool/PooledConnectionFactory.html) class, i have to add other entries (boolean parameters):

```
BlockIfSessionPoolIsFull
BlockIfSessionPoolIsFullTimeout
CreateConnectionOnStartup
ReconnectOnException
UseAnonymousProducers
```

**Comment by snicoll** [comment]
I am not sure I am a big fan of that.

**Comment by herau** [comment]
@snicoll what do you mean ? you talk about the ability to configure the PooledConnectionFactory or about the way i do in my PR ?

**Comment by snicoll** [comment]
Dumping all the keys that ActiveMQ support. I'd start wit the most useful ones only. So your original PR looks alright to me at first sight.

**Comment by snicoll** [comment]
I forgot to ask if you've signed the CLA already. I need a confirmation before I merge this.

**Comment by herau** [comment]
Yes I did :-)

**Comment by snicoll** [comment]
Alright with a polish commit, see 3d4a9d9 - I actually changed my mind and the `PooledConnectionFactory` is available for configuration now. We do this in other places (especially for data sources) so I felt this was close enough.

Let me know if you find any issue.

**Comment by herau** [comment]
Yes indeed the `spring.activemq.pool.configuration.*` is nice !

**Comment by herau** [comment]
@snicoll Why your polish commit isn't in the history of the PR ? 
Can i delete my branch ? because i don't see that the PR has been merged whereas it's closed and the code is in the master branch.

**Comment by snicoll** [comment]
uh? What are you talking about? Your commit is https://github.com/spring-projects/spring-boot/commit/e41d42171bfb9cdb1c3edbb119f6e155b08c1618 - Of course you can delete your branch.

**Pull request closed without merging**
