### PR TITLE
Replace Base64Encoder with Base64Utils

### PR DESCRIPTION
**Pull request by izeye**
`Base64Encoder` can be replaced with `Base64Utils`.

### CODE REVIEW

**Comment by philwebb** [comment]
I'm afraid that it can't. `Base64Utils` offers a wrapper around commons-digest or Java 8's `java.util.Base64` class. We want to remain compatible with Java 6 and we don't want to force people to have a `commons-digest` dependency.

**Comment by izeye** [comment]
@philwebb `Base64Utils. encodeToString()` which I used here uses JAXB `DatatypeConverter` as a fallback. So no additional dependency is needed.

See https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/util/Base64Utils.java#L31

Am I missing something?

**Comment by jhoeller** [comment]
@philwebb, as of 4.2, we have an additional fallback to the JAXB variant for String encoding and decoding. See https://jira.spring.io/browse/SPR-12938.

**Comment by philwebb** [comment]
Cool, I totally missed that.

**Pull request closed without merging**
