### PR TITLE
OAuth2 Resource Server Opaque Token configuration property namespace has a hyphen in its name

### PR DESCRIPTION
**Pull request by rossdrew**
Fix for bug #17265 in which "OAuth2 Resource Server Opaque Token configuration property namespace has a hyphen in its name"

A rename from: `spring.security.oauth2.resourceserver.opaque-token.`

to: `spring.security.oauth2.resourceserver.opaquetoken.`

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rossdrew Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=17290)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=17290) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rossdrew Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=17290)!

**Comment by mbhave** [comment]
Thanks for the PR @rossdrew. We also need to rename the class name from `OpaqueToken` to `Opaquetoken ` and the corresponding getter in `OAuth2ResourceServerProperties`. Can you update the PR with that change?

**Comment by rossdrew** [comment]
> Thanks for the PR @rossdrew. We also need to rename the class name from `OpaqueToken` to `Opaquetoken ` and the corresponding getter in `OAuth2ResourceServerProperties`. Can you update the PR with that change?

@mbhave Does this include declarations which also mention `OpaqueToken`
 - `OpaqueTokenIntrospectionClientConfiguration`
 - `OAuth2ResourceServerOpaqueTokenConfiguration`
 - `OpaqueTokenConfiguration`
 - `ReactiveOAuth2ResourceServerOpaqueTokenConfiguration`

and such things as assertion methods 
 - `assertFilterConfiguredWithOpaqueTokenAuthenticationManager`

and tests
- `autoConfigurationForOpaqueTokenWhenSecurityWebFilterChainConfigPresentShouldNotAddOne`

**Comment by mbhave** [comment]
@rossdrew I think all those can stay as they are.

**Comment by rossdrew** [comment]
I seems I can't rewrite my history to hide those messy commits and I'm not sure why the build is failing, all I can see is

```
task config 'git-repo/ci/tasks/build-smoke-tests.yml' not found
```

**Comment by wilkinsona** [comment]
Thanks, @rossdrew. I think that CI failure is because we've updated our pipeline and the commit upon which you changes are based is from before that change. Please don't worry about it. We can take care of things and check everything builds as part of the merge.

**Comment by wilkinsona** [comment]
Thanks very much for making your first contribution to Spring Boot, @rossdrew. The proposed changes have been merged into master.

**Pull request closed without merging**
