### PR TITLE
Add Elide as 3rd party Spring Boot Starter

### PR DESCRIPTION
**Pull request by aklish**
Adding Elide Spring Boot starter to list of starters.

https://elide.io

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@aklish Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=19397)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=19397) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@aklish Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=19397)!

**Comment by bclozel** [comment]
Quick question: why isn't [the sample Elide+Spring Boot application](https://github.com/yahoo/elide-spring-boot-example/blob/master/pom.xml) using the Spring Boot parent / BOM?

**Comment by aklish** [comment]
Good call.  I changed the example to use the spring-boot parent pom.  It
shaved down the length.

**Comment by snicoll** [comment]
Good catch, I think also the Spring integration (at least) could use some harmonization with what's going on in practice. I've created https://github.com/yahoo/elide/issues/1116

**Pull request closed without merging**
