### PR TITLE
Update StartupInfoLogger.java

### PR DESCRIPTION
**Pull request by shenjianeng**
change access level

### CODE REVIEW

**Comment by bclozel** [comment]
Could you explain why this change is needed? What is the use case behind this?
We don't expose contracts unless necessary.

**Comment by shenjianeng** [comment]
这是来自邮箱的自动回复邮件，我已收到邮件。-------------------------------------------------

**Comment by shenjianeng** [comment]
it is a utility class.

I want to use it in my project.

thanks.

**Comment by wilkinsona** [comment]
Thanks for the suggestion but we do not view it as a utility class. Making it public will limit our ability to change it in the future and we do not want that restriction. If you want similar functionality in your own application, you  are free to copy the code and adapt it to meet your needs.

**Pull request closed without merging**
