### PR TITLE
Fix failed test in travis

### PR DESCRIPTION
**Pull request by htynkn**
The test in travis failed, but in `build.spring.io`, it passed.

I know `DROP TABLE IF EXISTS` is not standard, but drop table first makes all tests pass.

I'm not sure is there any better way to fix this issue?

### CODE REVIEW

**Comment by alexandertokarev** [comment]
The problem is that some tests do not shutdown in-memory database after execution.
If the db is created by EmbeddedDataSourceConfiguration then this db will be shutdown while application context closing. So if a unit test closes application context in tearDown method the db will be shutdown as well. But if some DataSource class is found in the classpath then EmbeddedDataSourceConfiguration will not be used and application context closing will not shutdown the db. I have provided a simple workaround here https://github.com/axibase/spring-boot/commit/1eebd0b70341df891b440aca5b507dc404d996c7 to get travis build passed.
The problem test is TransactionAutoConfigurationTests.singleTransactionManager

**Comment by wilkinsona** [comment]
@alexandertokarev Thank you. I think your approach is a better way to tackle the problem as it avoids wasting memory on an unwanted in-memory database. Would you like to submit a PR?

**Comment by htynkn** [comment]
Yeah, I think alexandertokarev's solution is better. Feel free to close this PR :+1:

**Comment by alexandertokarev** [comment]
This commit is already included in this PR: https://github.com/spring-projects/spring-boot/pull/4066
But I can send a separate PR if needed.

**Comment by wilkinsona** [comment]
@alexandertokarev No need for another PR. Given that you've signed the CLA, I can cherry-pick your change from #4066.

**Comment by wilkinsona** [comment]
@htynkn Thanks anyway for taking the time to provide a PR.

**Pull request closed without merging**
