### PR TITLE
Polish access modifiers for test classes

### PR DESCRIPTION
**Pull request by izeye**
This PR polishes access modifiers for test classes.

### CODE REVIEW

**Comment by philwebb** [comment]
I thought we has a checkstyle for this at one point. Perhaps it's not working or I'm misremembering.

**Comment by dreis2211** [comment]
@philwebb I think this just checks for method visibility. See https://github.com/spring-io/spring-javaformat/blob/main/spring-javaformat/spring-javaformat-checkstyle/src/main/java/io/spring/javaformat/checkstyle/check/SpringJUnit5Check.java#L153

**Comment by philwebb** [comment]
Thanks @dreis2211!

**Comment by wilkinsona** [comment]
Thanks very much, @izeye.

**Pull request closed without merging**
