### PR TITLE
Add a missing `else` in ConfigFileApplicationListener.onApplicationEv…

### PR DESCRIPTION
**Pull request by izeye**
…ent()

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks for the PR but I see no reason why these events must be mutually exclusive. There's nothing wrong by checking the identity sequentially as we do IMO.

**Comment by izeye** [comment]
@snicoll I thought they are mutually exclusive. Thanks for the feedback!

**Comment by snicoll** [comment]
They are right now  but semantically speaking it does not have to be. If we change that in the future, that code change of yours will break.

**Comment by izeye** [comment]
@snicoll Ok. Thanks for the additional comment :+1:

**Pull request closed without merging**
