### PR TITLE
Add WebMvcRegistrations for custom MVC components

### PR DESCRIPTION
**Pull request by bclozel**
Developers can provide their custom instances
of MVC infrstructure components such as `RequestMappingHandlerMapping`
and `RequestMappingHandlerAdapter` by using advanced configuration
strategies.
Those advanced configurations involved subclassing
`WebMvcConfigurationSupport` which effectively turns off MVC
auto-configuration in Boot.

This PR aims at making this easier to achieve, without turning
off Boot's auto-configuration.

Because of the nature of the MVC configuration infrastructure,
using regular `@Bean` methods isn't possible without creating
dependency cycles or breaking existing auto-configuration
conditions.

The name `WebMvcRegistrations` can be refined; its main goal
is to provide central components in the MVC configuration,
possibly custom subclasses, without disabling MVC and Boot
standard configurations and customizations.

Declaring a `WebMvcRegistrations` component in an application allows
to provide custom instances of `RequestMappingHandlerMapping`,
`RequestMappingHandlerAdapter` and `ExceptionHandlerExceptionResolver`.
Those instances are then used and processed by the Boot MVC
configuration (i.e. all Boot configurations apply here).

### CODE REVIEW

**Comment by philwebb** [comment]
Sorry for the delay getting to this one. It generally looks good but I'm wondering if we can drop `WebMvcRegistrations` and just support direct bean registration? I.e. `RequestMappingHandlerMapping`, `RequestMappingHandlerAdapter` and `ExceptionHandlerExceptionResolver` instances could just be registered as beans. If they don't exist then we use the default.

Thoughts?

**Comment by snicoll** [comment]
I prefer the current solution as it gives you full control over what gets registered and what isn't. Could it be that one of these are registered as a bean and you don't want them registered that way maybe?

**Comment by bclozel** [comment]
If I remember correctly, I tried the following:

* a custom user configuration with a `@Bean RequestMappingHandlerMapping`
* a method overriding `createRequestMappingHandlerAdapter` that fetches an existing bean in the `ListableBeanFactory`

This didn't work since it created a cycle trying to fetch a bean that's being defined at the same time.
The `createRequestMappingHandlerAdapter` method is itself called by `@Bean RequestMappingHandlerMapping requestMappingHandlerAdapter()` so at that point it's already too late.

Or am I missing something?
It seems this is a recurring issue with Spring Configuration classes provided by the framework. Is there something we could do to break that cycle in future configuration infrastructures (like reactive web?).

**Comment by philwebb** [comment]
Ahh yes. I totally missed that `WebMvcConfigurationSupport` is itself a `@Bean` method:

```java
	@Bean
	public RequestMappingHandlerMapping requestMappingHandlerMapping() {
		RequestMappingHandlerMapping handlerMapping = createRequestMappingHandlerMapping();
```

You're approach makes totally sense, I'll merge it today.

**Comment by philwebb** [comment]
Now merged with [these](https://github.com/philwebb/spring-boot/commit/c3a7b56f41ddaf54997200246f4f3485f3a80263) minor changes. I also changed the commit message to start with the change details (rather than "prior with").

**Pull request closed without merging**
