### PR TITLE
Take MethodType into account to deduce main application class

### PR DESCRIPTION
**Pull request by quaff**

### CODE REVIEW

**Comment by philwebb** [comment]
See #31701

**Comment by wilkinsona** [comment]
I don't think this is a bug. The code that was contributed is equivalent to what we had before. This suggestion improves things in a way that wasn't possible before.

**Comment by quaff** [comment]
> I don't think this is a bug. The code that was contributed in #31701 is equivalent to what we had before. This suggestion improves things in a way that wasn't possible before.

Yes, It's just an improvement.

**Comment by wilkinsona** [comment]
Thanks very much, @quaff.

**Comment by snicoll** [comment]
This breaks running a Spring Boot application as a native image as follows:

```
Exception in thread "main" java.lang.UnsupportedOperationException
        at java.lang.StackWalker$StackFrame.getMethodType(StackWalker.java:148)
        at org.springframework.boot.SpringApplication.lambda$findMainClass$1(SpringApplication.java:290)
```

We should figure out what to do here. Maybe a fallback although that would change the behavior between JVM and native.

**Comment by snicoll** [comment]
For the reason above, I've reverted this change. We can follow-up in https://github.com/spring-projects/spring-boot/issues/31858

**Pull request closed without merging**
