### PR TITLE
Add graceful shutdown support to undertow

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@chirino Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7438)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7438) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by chirino** [comment]
retest this please

**Comment by pivotal-issuemaster** [comment]
@chirino Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7438)!

**Comment by chirino** [comment]
Helps out with issue #4657

**Comment by philwebb** [comment]
Closing in favor of #7440

**Pull request closed without merging**
