### PR TITLE
Update Spring Social Facebook dependency to 2.0.1.RELEASE

### PR DESCRIPTION
**Pull request by habuma**

### CODE REVIEW

**Comment by wilkinsona** [comment]
@philwebb Given that older versions of Spring Social Facebook will stop working on 30 April, I'm wondering if you should make an exception and do this upgrade in 1.2.4? It'll be a breaking change, but the Facebook API changes will already have broken people and putting this in 1.2.4 is the quickest and easiest way for us to help them to get things up and running again. Thoughts?

**Comment by habuma** [comment]
Note that I just pushed Spring Social Facebook 2.0.1.RELEASE and have updated spring-boot-dependencies/pom.xml accordingly.

Also, it is possible to use Spring Social Facebook 2.0.1.RELEASE with older versions of Spring Boot...just not as conveniently. You just have to explicitly request it as a dependency to override the dependency in the starter.

**Comment by wilkinsona** [comment]
@habuma Phil and I discussed this and we'd like to include it in 1.2.4. Unfortunately, the changes don't compile as-is. `FacebookAutoConfiguration` calls the default constructor on `FacebookTemplate` which no longer exists. Can you please update the PR with appropriate changes to `FacebookAutoConfiguration` or offer some guidance about what's appropriate for the new API?

**Comment by cemo** [comment]
@wilkinsona if it is open to discuss, I think that It is better to not support Spring Social. I do not know why it is not actively developed this wonderful project anymore but current situation is really terrible. There are tons of issues to be resolved and waiting a lot of PR's to be applied. People are creating forks, as we do. We have tried to contact with @habuma but had no chance.

**Comment by habuma** [comment]
@wilkinsona Sorry about the mixup. Should be fixed now.

**Pull request closed without merging**
