### PR TITLE
Quickly to find the main

### PR DESCRIPTION
**Pull request by burnandgun**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@burnandgun Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=25598)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=25598) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@burnandgun Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=25598)!

**Comment by wilkinsona** [comment]
Unfortunately, we can't reverse the search order when looking for the main method as it would result in the main method of Spring Boot's jar and war launchers incorrectly being identified as the application's main method. Thanks anyway.

**Comment by burnandgun** [comment]
I just realize it, thanks for your response.

**Comment by burnandgun** [comment]
> Unfortunately, we can't reverse the search order when looking for the main method as it would result in the main method of Spring Boot's jar and war launchers incorrectly being identified as the application's main method. Thanks anyway.

I just realize it, thanks for your response.

**Pull request closed without merging**
