### PR TITLE
Remove useless code in SpringNamingStrategy.class

### PR DESCRIPTION
**Pull request by alexVengrovsk**
Oleksandr Vengrovskiy ovengrovsk@i.ua
Confirmation number is 133720150811071904.

There were an unnecessary local variable creation of String type in foreignKeyColumnName method of SpringNamingStrategy.class.

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks for the PR but it's no useless code at all. You [may find this article](https://sourcemaking.com/refactoring/remove-assignments-to-parameters) useful.

**Comment by alexVengrovsk** [comment]
Thank you. I didn't know about that.

**Comment by alexVengrovsk** [comment]
I think, that in case of String type parameter, it is non necessary to assign parameter value to local variable in the method's body. Just because of using a String pool by JVM you will get two references to the same String object.

For example, the output of the following class will be ```true``` anyway:
```
public class Starter {

	public static void main(String[] args) {

		Starter st = new Starter();
		System.out.println(st.do1("do") == st.do2("do"));
	}

	public String do1(String param) {
		String param_ch = param;
		return do2(param_ch);
	}

	public String do2(String param) {
		return param;
	}
}
```
Maybe you should reopen the pull request.
But it is up to you.
Anyway, thanks for showing an interesting info.

**Comment by alexVengrovsk** [comment]
I was wrong in my previous comment. Sorry for bothering you.

**Pull request closed without merging**
