### PR TITLE
Make WebMvcAutoConfigurationAdapter.FaviconRequestHandler package private

### LINKED ISSUE #16233: Make WebMvcAutoConfigurationAdapter.FaviconRequestHandler package private
There's a new private class in `spring-boot-autoconfigure`. Can I ask that `WebMvcAutoConfigurationAdapter.FaviconRequestHandler` be package private please?

### PR DESCRIPTION
**Pull request by pkostrzewa**
Makes `WebMvcAutoConfigurationAdapter.FaviconRequestHandler` class package private.

Fixes #16233 .

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. As noted in the issue, @mrifni is already working on this.

**Comment by pkostrzewa** [comment]
- It was not assigned directly.
- No response since yesterday.

**Comment by wilkinsona** [comment]
Unfortunately, GitHub does not allow issues to be assigned to anyone outside of the core team. Please don't try to jump the queue, particularly when someone's only had a day to work on something.

**Comment by pkostrzewa** [comment]
I will reopen the PR then if that issue won't be fixed in following days.

**Comment by snicoll** [comment]
@pkostrzewa as Andy already indicated, there's no need for such pressure and I'd appreciate if you let the person who requested to contribute to try: it is pretty obvious from the exchange on the issue that they're going to work on it. If that doesn't work out, we'll figure out what the next steps are.

**Pull request closed without merging**
