### PR TITLE
Allow customization of Flyway migration process.

### PR DESCRIPTION
**Pull request by aahlenst**
Fixes gh-1814.

### CODE REVIEW

**Comment by wilkinsona** [comment]
@aahlenst Thanks for the PR. Have you [signed the CLA](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#sign-the-contributor-license-agreement)?

**Comment by aahlenst** [comment]
@wilkinsona Yes, on 2014-12-26.

**Comment by philwebb** [comment]
Fixed in a slightly different way. See ebccedcfdde14a64280aa0e3b5a8438bc84f6fd2.

Thanks for the PR!

**Comment by aahlenst** [comment]
Thanks a lot. And your solution looks much better.

**Comment by jimbasilio** [comment]
Any way this can be backported to 1.2.x? Looks well contained and I know I'd surely benefit from it. :)

**Pull request closed without merging**
