### PR TITLE
Upgrade to Micrometer 1.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by jkschneider**
* We now have [Jersey 2 support](https://github.com/micrometer-metrics/micrometer/pull/228) with the module `micrometer-jersey2`. It's not clear to me how we could register `MetricsApplicationEventListener` for Jersey 2 based Boot apps.
* I think the servlet filter is generic enough now to call it `MetricsFilter` rather than `WebMvcMetricsFilter`. At any rate, the goal is to make it _not_ WebMvc specific.

The following issues are addressed by this PR:
* #11348
* #11338

### CODE REVIEW

**Comment by jkschneider** [comment]
I'll delete this comment when I'm done pushing changes.

**Comment by philwebb** [comment]
I'm having a bit of a difficult time getting this one into a state that we can merge. I've so jar just been working on the first commit in the set. I've split it apart and tried to create smaller commits with related concerns. I've rename the MVC classes back to their old names (they are still very tied to MVC so I don't like the very generic `ServletMetricsFilter` name.

My branch is [here](https://github.com/philwebb/spring-boot/commits/gh-11776).

Things go relatively OK until the last commit. The changes to `WebMvcMetricsFilter` are a big concern to me. I've added some FIXME comments in the code but the main worry is around the `asyncTimingContext` and the fact that it's a synchronized map.

**Comment by jkschneider** [comment]
@philwebb Good idea on the request attribute. Tested it against `micrometer-spring-legacy` successfully and committed there: https://github.com/micrometer-metrics/micrometer/commit/44a5d8834cd92a03c5b92adc1f37bb2f877f8c36#diff-974dd55a85a31feb0d4a829577d72046d

**Comment by ITman1** [comment]
I suggest to add `@ConditionalOnMissingBean` on every `XxxxxxxMeterRegistry` bean auto-configuration. I know there is currently `@ConditionalOnProperty("management.metrics.export.xxxxxxx.enabled")`, which might be enough for application using spring-boot directly, but not for libraries which needs some customizations without affecting properties.

**Comment by philwebb** [comment]
Sorry but there is just way too much going on in the PR for me to be able to merge it before RC1. I've split out the following issues which we can prioritize and deal with on a case-by-case basis:

#11797
#11798
#11799
#11800
#11801
#11802
#11803

**Pull request closed without merging**
