### PR TITLE
Append $log_file instead of overwritting

### PR DESCRIPTION
**Pull request by michitomo**
$log_file should not be overwritten when restarting the app.

    replaced
    > $log_file
    by
    >> $log_file

I have signed the CLA.

### CODE REVIEW

**Comment by vpavic** [comment]
IMO actually it's a good thing that ```launch.script``` overwrites this log each time.
Otherwise, the file could grow quite large without log rotation strategy which would in this case be left to the user.

This is just a redirection of console output, for more sophisticated logging file logging should be used.

**Comment by joshiste** [comment]
@vpavic

 I totally disagree. When overwriting past errors/logs can't be analyzed.
Imho for most applications on *nix-systems appending is the default.
To prevent overgrowing logfiles in ``/var/log`` you should use according tools (e.g. [logrotate](http://linux.die.net/man/8/logrotate)).

And I disagree that you should use file logging fo

**Comment by vpavic** [comment]
Spring Boot is great at providing sensible defaults out of the box. My point is that generating a log file that grows without any control is not a sensible default at all (or at least I don't consider it such).

Of course there's always the possibility to use ```logrotate``` or similar utility, but I as said in my previous comment that would be left to the user.

IMO most users would still prefer to use logging framework to handle file logging aspects (rolling policy, log file retention etc.) within the app rather than externally.

**Comment by shakuzen** [comment]
> This is just a redirection of console output, for more sophisticated logging file logging should be used.

I fail to see why keeping previous log output when restarting or deploying a new version of an application should be considered "sophisticated" or require file logging to be configured. That is not sensible to me. That cannot be run in production - it's not viable in any environment but local, IMO.

> Spring Boot is great at providing sensible defaults out of the box. My point is that generating a log file that grows without any control is not a sensible default at all (or at least I don't consider it such).

I think we disagree on the current behavior being a sensible default. If an application is left running, the "log file grows without any control." Therefore the problem of possibly running out of space remains and is up to the user to deal with - I find this being up to the user sensible as long as the user knows a log file is produced in the first place.

> IMO most users would still prefer to use logging framework to handle file logging aspects (rolling policy, log file retention etc.) within the app rather than externally.

Those users are unaffected by the change in this pull request, aren't they? This is for people whose needs do not warrant configuring such things in file logging configuration and simply want console logs redirected to a file (which is functionality already provided - this pull request is just to enhance that functionality).

For full disclosure, I'm the one who raised this issue initially in [this Gitter conversation](https://gitter.im/spring-projects/spring-boot?at=564930d58b242470793df23e).

**Comment by joshiste** [comment]
> That is not sensible to me. That cannot be run in production - it's not viable in any environment but local, IMO.

I agree. The defaults should be sensible for production. And that's not getting lost of valuable informations due to a restart.

**Pull request closed without merging**
