### PR TITLE
Optimize some StringBuilder.append() calls

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

I noticed that sometimes we do `StringBuilder.append((i != 0) ? "," : "");` . This will still call `System.arrayCopy()` eventually and therefore is slower than simply omitting the call to `StringBuilder.append()` at all.

E.g. testing `ConfigurationPropertyName.toString()` shows the following results:
```
MyBenchmark.testNew                                                  thrpt   50  4331037,115 ± 40253,270   ops/s
MyBenchmark.testNew:·gc.alloc.rate                                   thrpt   50     1056,753 ±     9,813  MB/sec
MyBenchmark.testNew:·gc.alloc.rate.norm                              thrpt   50      256,000 ±     0,001    B/op
MyBenchmark.testNew:·gc.count                                        thrpt   50      346,000              counts
MyBenchmark.testNew:·gc.time                                         thrpt   50      244,000                  ms
MyBenchmark.testOld                                                  thrpt   50  1943977,722 ± 38335,644   ops/s
MyBenchmark.testOld:·gc.alloc.rate                                   thrpt   50     3408,980 ±    67,227  MB/sec
MyBenchmark.testOld:·gc.alloc.rate.norm                              thrpt   50     1840,001 ±     0,001    B/op
MyBenchmark.testOld:·gc.count                                        thrpt   50      504,000              counts
MyBenchmark.testOld:·gc.time                                         thrpt   50      469,000                  ms
```

This PR optimizes those places. Where applicable, this PR touches the surrounding code in order to avoid string concatenations inside `StringBuilder.append()` calls that are somewhat wasteful themselves.

Let me know what you think.
Cheers,
Christoph

### CODE REVIEW

**Comment by dreis2211** [comment]
@snicoll Sure. I wasn't sure about the style, as there are examples for both chained and individual statements throughout the code. I don't mind.

Give me a second.

**Comment by dreis2211** [comment]
Done

**Comment by dreis2211** [comment]
Tests seems to fail because of some weird timeouts to https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.2.tgz

**Comment by snicoll** [comment]
Sweet, thanks again Christoph!

**Pull request closed without merging**
