### PR TITLE
Add max http response header size configuration for tomcat and jetty

### PR DESCRIPTION
**Pull request by michaelweidmann**
This PR adds the feature described in #33380.

The configuration of the maximum size of the HTTP response header is only available on Tomcat and Jetty. That's why the configuration is only implemented for these two servers.

Besides the implementation the tests and smoke tests are extended.

### CODE REVIEW

**Comment by mhalbritter** [comment]
Thank you very much for your contribution.

I had to polish the PR quite a bit. For the next time, please take a look at our [documentation how to set up your IDE](https://github.com/spring-projects/spring-boot/wiki/Working-with-the-Code). This way the imports, code style etc. will all be taken care of.

**Comment by mhalbritter** [comment]
I somehow lost the merge commit. It's in main, https://github.com/spring-projects/spring-boot/commit/93d46d11e91d21ccbe2e5b451c051e9efdc57b2d

**Comment by fstorz** [comment]
@aamotharald there is no property [server.max-http-response-header-size](https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.server.server.max-http-response-header-size). Still, rather there are server implementation specific ones for [Tomcat](https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.server.server.tomcat.max-http-response-header-size) & [Jetty](https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.server.server.jetty.max-http-response-header-size). Undertow & Netty do not support the configuration of a max response header size.

**Comment by mhalbritter** [comment]
Thanks @fstorz, that's correct.

**Pull request closed without merging**
