### PR TITLE
A new spring-boot-starter-camel module with sample also.

### PR DESCRIPTION
**Pull request by davsclaus**
Ticket is #5425

This allows Spring Boot users to get easily started with Spring Boot and add Camel to their application.
This PR includes two new modules

- spring-boot-starter-camel
- spring-boot-sample-camel

The former is similar to all the other starters with a simple maven pom.xml file that provides camel-spring-boot.
The latter is a sample that uses starter-camel with a little sample project with Spring Boot and Apache Camel.

The Apache Camel project already includes a camel-spring-boot module that integrates with Spring Boot and does
the discoveries of Camel routes and add those into the Spring framework. And listens on the spring events
to start/stop Camel accordingly to Spring.

Signed-off-by: Claus Ibsen <claus.ibsen@gmail.com>

### CODE REVIEW

**Comment by davsclaus** [comment]
I had those test failures as well locally when I was buidling the entire source code.

This PR has the same errors on the CI server
https://travis-ci.org/spring-projects/spring-boot/builds/116369786#L1619

I do not see my PR has caused these tests to fail. They failed before.

**Comment by snicoll** [comment]
@davsclaus we actually have numerous 3rd party starters these days. What prevents you from providing the starter (and the sample) from your own code base?

**Comment by davsclaus** [comment]
@snicoll what prevents spring-boot to be an open project that take in contributions?

Isn't the idea to have a list of good projects in your starter list?

**Comment by snicoll** [comment]
Sorry, maybe I wasn't clear. We have a bunch of 3rd party starters (see [this list](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-starters/README.adoc)). Since the integration code is on your side, it make sense to also publish the starter there. That way you manage the camel version alongside the integration. [mybatis](https://github.com/mybatis/mybatis-spring-boot) is doing this already.

Please [read the documentation regarding 3rd party starter](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter) first.

I didn't get what you mean by "open project".

**Comment by davsclaus** [comment]
@snicoll thanks for the link.

So what would it take for a starter to be listed on eg: http://start.spring.io/. I can see vaadin is listed there, and its a 3rd party starter.

So if we move this code to another organization such as Apache Camel, and provide a starter module using your naming convention. Would it then be applicable to be listed on the starter page at http://start.spring.io/?

If not, what is the "rules" for that?

**Comment by snicoll** [comment]
That's not the place to discuss this. Once you have created the starter on your end, you can create an issue [in the Initializr tracker](https://github.com/spring-io/initializr/issues) and we can take it from there. How does that sound?

**Comment by davsclaus** [comment]
Thanks @snicoll that sounds like a good way.

I may have missed it, but could not find details in that "list of 3rd party starters" page, a link or a hint how a starter can be listed on that website in that spring initializer project. Other users of 3rd party starters may find that interesting to know.

I will try to get the starter into Apache Camel instead and use the naming convention in your guide. Then I will reach out to the initializer and you guys can see if it can be considered for the list.

**Comment by davsclaus** [comment]
Closing this PR

**Pull request closed without merging**
