### PR TITLE
Fixes: #3988: Remote Shell does not honor custom banner.txt

### PR DESCRIPTION
**Pull request by cjstehno**
I added the formal code for my suggestion. There are no existing unit tests and other than runtime testing, I am not sure how to test this change. It's fairly minimal and it works in local testing.

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks @cjstehno! Have you signed the CLA?

**Comment by cjstehno** [comment]
Yes, I have signed it.

**Comment by wilkinsona** [comment]
Thanks for the PR. It's definitely an improvement, but it doesn't take into consideration a custom `banner.location`. I wonder if there's a further refinement to be made?

**Comment by cjstehno** [comment]
Ah, good point! I forgot about that configuration option. I will update my pull request to account for that within the next few days.

**Comment by cjstehno** [comment]
Not sure how my second merge got in there... nothing in it. I will use the code added by michael-simmons once his branch is merged in.

**Comment by snicoll** [comment]
@cjstehno the banner bean is now available. Could you please go ahead and update your PR? Thanks!

**Comment by cjstehno** [comment]
I am working on the updated fix - having some issues with `checkstyle` failing during the build which is odd since I never touched that area of the code and `-Dcheckstyle.skip=true` is not working (it's been a while since I worked with maven so I may be missing something simple). Should have this ready to push soon.

**Comment by philwebb** [comment]
Don't worry too much about checkstyle, if you've got something your happy with we can fixup the errors.

**Comment by cjstehno** [comment]
I just updated the PR and it's building - I did not end up using the new bean since it seems that it's more geared towards the console banner. I added support for the location property and tested locally under a few different scenarios (with and without location property and with and without a locally defined banner). Should be good to go.

**Comment by wilkinsona** [comment]
@cjstehno Thanks for the updates, but I think you'll need to use the bean. Your latest changes will still ignore a banner that's been set on SpringApplication.

**Comment by cjstehno** [comment]
Ok, I will take another look at it - I should be able to have the fix in by Monday morning.

**Comment by cjstehno** [comment]
I am a little unclear about what to use for the `sourceClass` argument in the `printBanner` method. It seems to want the main application class - is there a means of getting that information from the `beanFactory` instance I have (or some means of getting the enclosing `SpringApplication` reference?

**Comment by wilkinsona** [comment]
I'd missed that piece of the puzzle. `SpringApplication` isn't available as a bean, and I don't think it should be, so we'll need some other mechanism to get hold of the source class. I'll give it some thought.

**Comment by philwebb** [comment]
Perhaps we can register a decorated version of `Banner` than knows about `sourceClass` and can therefore allow it to be called with `null`.

**Comment by philwebb** [comment]
Thanks for the PR, I've tweaked the last bits required to use the `Banner` interface.

**Pull request closed without merging**
