### PR TITLE
Replace org.json with json-simple

### PR DESCRIPTION
**Pull request by kartoffelsup**
Replace `org.json` with `json-simple` due to licensing issues with `org.json`.

See #5929 gh-5929

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kartoffelsup Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7400)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7400) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kartoffelsup Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7400)!

**Comment by kartoffelsup** [comment]
Closing, as `json-simple` is not suited for the job after all.

**Comment by wilkinsona** [comment]
Sorry that you wasted some time on this, @kartoffelsup. Thank you very much for trying.

**Comment by kartoffelsup** [comment]
I had fun implementing it, so it was not a waste :)

**Pull request closed without merging**
