### PR TITLE
Add setters for `JacksonProperties` to expose properties in `/configprop...

### PR DESCRIPTION
**Pull request by izeye**
...s` endpoint.

### CODE REVIEW

**Comment by snicoll** [comment]
I'd rather fix whatever algorithm we use to detect fields than adding fake/unecessary setters there

**Comment by izeye** [comment]
@snicoll Ok, I just thought it's harmless workaround.

I created a PR to fix it in Jackson:

https://github.com/FasterXML/jackson-databind/pull/755

**Comment by snicoll** [comment]
I may have misunderstood your original request. It's about serializing json properties, right? 

Your jackson PR is likely to be rejected. We can revisit the situation then (there are more than this POJO that exposes Maps and/or lists

**Comment by izeye** [comment]
@snicoll Sorry that I didn't provide enough information because I thought it's trivial.

Current version of `JacksonProperties` doesn't have setters

for `serialization`, `deserialization`, `mapper`, `parser`, `generator`.

So they are not rendered in `/configprops` endpoint.

That's why I created this PR to work it as I expected.

I didn't think on this deeply so I might be wrong as you said.

BTW why do you think my PR in Jackson is incorrect?

I think collecting properties based on getters not setters for serialization makes sense.

Do I assume something wrong?

**Comment by snicoll** [comment]
that's an obvious breaking change, that's why I think the Jackson team will reject it but let's leave that discussion over there. 

My confusion was about binding (which we do) and JSON rendering of `JacksonProperties` (what you asked). Since we are responsible of the binding and you don't need a setter for collections/maps, I didn't find a compelling reason to add them for your use case. But I obviously got it all wrong. That being said, maybe there's a way to configure jackson to use the getters only and we'd be good.

**Comment by izeye** [comment]
@snicoll Ok, thanks for the explanation :-)

**Comment by philwebb** [comment]
I think finding a way to fix this without introducing setters would be better. @izeye could you raise a new issue please.

**Pull request closed without merging**
