### PR TITLE
Add support for Apache Phoenix's jdbc:phoenix: JDBC URL prefix

### PR DESCRIPTION
**Pull request by vpelikh**
Small pr for supporting of automatically determination for apache phoenix driver.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@vasilypelikh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=24114)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=24114) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@vasilypelikh Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=24114)!

**Comment by wilkinsona** [comment]
Thanks for the PR, @vasilypelikh.

**Comment by snicoll** [comment]
@vpelikh thank you for making your first contribution to Spring  Boot.

**Pull request closed without merging**
