### PR TITLE
Don't change state upon UserInfoTokenServices#loadAuthentication

### PR DESCRIPTION
**Pull request by denyska**
UserInfoTokenServices#loadAuthentication spoils state of the wired RestTemplate. The following flow doesn't work:
* Initiate OAuth2.0 authentication with refresh_token;
* OAuth2ClientAuthenticationProcessingFilter#attemptAuthentication calls tokenServices.loadAuthentication(accessToken.getValue())
* OAuth2ClientAuthenticationProcessingFilter#successfulAuthentication can't access refresh_token, as it was replaced less-complete token containing the same opaque string in the previous call.

Discussion:  http://stackoverflow.com/questions/31018377/why-isnt-oauth2-client-refreshing-expired-access-token

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks, have you signed the CLA?

**Comment by denyska** [comment]
@philwebb yes, I've signed CLA under  denyska {_at_} google (!dot) com email address.

**Comment by wilkinsona** [comment]
I'm not sure that this is the right way to fix the problem as the logic that captures the original access token and then reinstates it isn't thread-safe. Perhaps we can be certain that `UserInfoTokenServices` will never be called on multiple threads at the same time?

**Comment by dsyer** [comment]
It's thread safe if the context is (by default it's usually in session scope so it should be fine from that point of view). I'd need some time to analyze the scenario outlined above, but I sense there is something else wrong here, nonetheless.

**Comment by denyska** [comment]
Alternatively we can clone OAuth2RestTemplate every time request to be made, i.e.
```java
private Map<String, Object> getMap(String path, String accessToken) {
	this.logger.info("Getting user info from: " + path);
	try {
		final OAuth2ProtectedResourceDetails resource;
		if (this.restTemplate != null && this.restTemplate.getResource() != null)
		{
			resource = this.restTemplate.getResource();
		}
		else
		{
			resource = new BaseOAuth2ProtectedResourceDetails();
			((BaseOAuth2ProtectedResourceDetails) resource).setClientId(this.clientId);
		}

		final OAuth2RestOperations tempRestTemplate = new OAuth2RestTemplate(resource);
		DefaultOAuth2AccessToken token = new DefaultOAuth2AccessToken(accessToken);
		token.setTokenType(this.tokenType);
		tempRestTemplate.getOAuth2ClientContext().setAccessToken(token);
		return tempRestTemplate.getForEntity(path, Map.class).getBody();
	}
	catch (Exception ex) {
		this.logger.info("Could not fetch user details: " + ex.getClass() + ", "
				+ ex.getMessage());
		return Collections.<String, Object>singletonMap("error",
				"Could not fetch user details");
	}
}
```

**Comment by dsyer** [comment]
I'm not quite clear on how this scenario would arise (step 1 above). As far as I can tell the only way to trigger the problem is to login, wait for the access role to expire (but keep the session cookie alive), and then hit the authentication endpoint again. The last step is unnecessary, given that you are already authenticated, but I suppose you can't stop users doing it. Is that an accurate description of the problem?

If it is then I can fix it in a similar way to this PR (I would choose a slightly different strategy, and actually there's no need to reset the state).

**Pull request closed without merging**
