### PR TITLE
Remove Maven wrapper leftovers

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

`mvnw` and `mvnw.cmd` seem to be unused now. At least the actual wrapper seems to be gone as well.

Let me know when I'm missing something.
Cheers,
Christoph

### CODE REVIEW

**Comment by dreis2211** [comment]
Concourse seems to fail to create a volume. Seems unrelated to my change.

**Comment by philwebb** [comment]
Yup, sorry. We're having issues with it at the moment.

**Comment by dreis2211** [comment]
No worries. Just want to make sure I didn't break stuff ;)

**Comment by wilkinsona** [comment]
Thanks very much, @dreis2211.

**Pull request closed without merging**
