### PR TITLE
Infinispan 9.3.0 update

### PR DESCRIPTION
**Pull request by galderz**
* Update to Infinispan 9.3.0.Final.
* Remove Infinispan uber jar dependencies.
* Update to Hibernate to use Infinispan cache provider compatible with that Hibernate version.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. We generally try to keep changes has focussed as possible and the proposal here is mixing a few different changes. Some of those changes, such as removing dependency management for modules that still exist, shouldn't be made at all. We already have an issue for upgrading to Hibernate 5.3.x (#11725). Can you please re-work this pull request so that it focuses solely on the changes that are required for the Infinispan upgrade? If the Hibernate upgrade is a prerequisite then we can take care of that separately.

**Comment by galderz** [comment]
Actually, Hibernate 5.3 has already been updated. I'll just fix the cache provider then.

**Comment by galderz** [comment]
Should be ready now :)

**Comment by wilkinsona** [comment]
Thanks for the updates. Do the modules that you have removed from dependency management no longer exist in Infinispan 9.3?

We have a policy of providing dependency management for all of a library's modules. This makes it easier to keep a library's dependencies in sync even for those modules that Boot itself doesn't use. If the modules still exist, we should keep the dependency management for them and just add entries for any new modules.

**Comment by galderz** [comment]
* `org.hibernate:hibernate-infinispan` - the hibernate/infinispan integration is no longer in this location, the cache provider is now in Infinispan source tree and the module names have changed to adjust to individual Hibernate versions. Hence, the Hibernate 5.3 compatible Infinispan cache provider is located in `org.infinispan:infinispan-hibernate-cache-v53`

* `infinispan-embedded-query`, `infinispan-embedded`, `infinispan-cli` - these are Infinispan uber jar dependencies which cause issues in Maven environments. They should never have been there in the first place. These uber jars are for environments with no dependency management capabilities, e.g. ant wo/ ivy.

**Comment by wilkinsona** [comment]
>  these are Infinispan uber jar dependencies which cause issues in Maven environments. They should never have been there in the first place.

I don't agree with that. We don't presume to know why someone may be using a dependency. It could be for inclusion in an assembly, for example, rather than something that's used for compilation. Either way, the changes are unrelated to an upgrade to 9.3 so they do not belong here.

**Comment by galderz** [comment]
> I don't agree with that. We don't presume to know why someone may be using a dependency. It could be for inclusion in an assembly, for example, rather than something that's used for compilation.

We're trying to avoid people using them at all since most of the time people are using them for compilation and have had issues like [this](https://issues.jboss.org/browse/ISPN-6865). So, if they're not there, less chances of making the mistake. 

Besides, in recent Infinispan versions we don't publish them to Maven any more. For example, `infinispan-embedded` no longer published to Maven since 9.1.x: http://repo2.maven.org/maven2/org/infinispan/infinispan-embedded 

> Either way, the changes are unrelated to an upgrade to 9.3 so they do not belong here.

Fair point. I'll remove that and open a new PR with the other changes.

**Comment by wilkinsona** [comment]
Thanks.

> Besides, in recent Infinispan versions we don't publish them to Maven any more.

The modules that are no longer published in 9.3 should be removed as part of the upgrade. Any other removals should be considered separately.

**Comment by galderz** [comment]
I have updated the PR removing the uber jar removals

**Comment by galderz** [comment]
Rebased PR. @wilkinsona What is going to be in the end? I've left the uber jars for now and then I'll send another PR to remove them.

**Comment by wilkinsona** [comment]
Thanks for the PR, @galderz. The proposed changes are now in master, along with [another commit](https://github.com/spring-projects/spring-boot/commit/bc65c4cb2c733ec88837eacbc618d6c11e5642c9) that aligned the dependency management with modules that have been added or removed between Infinispan 9.1.7 and 9.3.0.

For the reasons explained above, we want to keep the dependency management for any remaining uber jars so I don't think any further changes are necessary here.

**Comment by galderz** [comment]
Thanks @wilkinsona :)

**Pull request closed without merging**
