### PR TITLE
Autoconfigure Spring Integration's `LockRegistryLeaderInitiator`

### PR DESCRIPTION
**Pull request by vpavic**
This PR adds support for auto-configuring Spring Integration's `LockRegistryLeaderInitiator` if user registers a `LockRegistry` `@Bean`. Additionally, if `Candidate` `@Bean` is found it will be used with configured `LockRegistryLeaderInitiator`.

/cc @artembilan

### CODE REVIEW

**Comment by philwebb** [comment]
@artembilan @garyrussell I don't know enough about `LockRegistryLeaderInitiator`. Can you comment on this suggested change?

**Comment by artembilan** [comment]
Since `LockRegistry` can be used in many other places, like an `Aggregator` or `SimpleMessageStore` (just make a search through the SI project), I don't think that there is a simple answer that we can provide `LockRegistryLeaderInitiator` instance "unconditionally". 

Even if we have a `Candidate` bean in the context, that doesn't answer to the question which `LeaderInitiator` implementation should we instantiate.

So, I don't see (yet) the simple way to auto-configure `LeaderInitiator`...

**Comment by vpavic** [comment]
One thing I was also considering since opening the PR was to introduce a specific `@Qualifier` that would be a signal that given `LockRegistry` `@Bean` is candidate for use in `LockRegistryLeaderInitiator`.

**Comment by artembilan** [comment]
Well, not sure that it is going to simplify the life...

The `LockRegistryLeaderInitiator` configuration isn't so complicated that I don't think that it is a big deal to continue to specify its bean manually.

**Comment by vpavic** [comment]
It's a convenience thing really. We use Spring Integration with `LockRegistryLeaderInitiator` in all of our current projects so I might be subjective, but I feel it would be a nice addition (that fits with Boot's general philosophy) to be able to somehow signal that user would like `LockRegistryLeaderInitiator` configured.

**Comment by artembilan** [comment]
>  We use Spring Integration with LockRegistryLeaderInitiator in all of our current projects 

That sounds like you just should have a custom auto-configuration in the separate jar and carry it to all your project with simple entity in the POM 😉 

I really don't see yet any general use-case to introduce one more annotation feature or some configuration property meanwhile the simple bean definition is fine.

**Comment by philwebb** [comment]
Thanks for the PR @vpavic but I think for now we'll follow @artembilan's advice and leave this out.

**Pull request closed without merging**
