### PR TITLE
Add the possibility to enable JNDI namin on tomcat startup

### PR DESCRIPTION
**Pull request by josetesan**
By setting the property
```server.tomcat.namingEnabled=true``` Tomcat connector will start with JNDI enabled, as the default opposite.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. Can you please elaborate a bit on why you think having a property to enable JNDI would be useful? AFAIK, [as shown in this sample](https://github.com/wilkinsona/spring-boot-sample-tomcat-jndi/blob/master/src/main/java/sample/tomcat/jndi/SampleTomcatJndiApplication.java#L56-L62), you'll stlll need to write some code to register the JNDI resources. I'm not sure that splitting enabling JNDI and configuring the resources across two separate locations would be an improvement.

**Comment by snicoll** [comment]
+1

**Comment by josetesan** [comment]
Yes, you are right.

Makes nonsense having splitted jdni configuration and naming resources.

I'm having a problem in migrating our legacy application ( still uses JNDI ), when having the main spring boot application starting the jndi environment and populating the JDNI datasource, while having 3 servlets started from a ```ServletContextInitializer::onStartup``` method failing because could not find the JNDI datasource, ( race condition ?), so i thought enabling JNDI from the very beggining will help me out.

Thanks a lot.

**Comment by wilkinsona** [comment]
Thanks, I'll close this PR. Interesting problem, though. Feel free to [join us on Gitter](https://github.com/spring-projects/spring-boot) if you want to discuss further. In your position I'd explore using `ServletRegistrationBeans` to register the servlets rather than a `ServletContextInitializer`. That should allow you to populate JNDI before they're started.

**Pull request closed without merging**
