### PR TITLE
SystemPublicMetrics add threads.totalStarted

### PR DESCRIPTION
**Pull request by bohrqiu**

### CODE REVIEW

**Comment by snicoll** [comment]
There is no need to close your previous PR, you can push force on the same branch and the PR will be updated.

**Comment by bohrqiu** [comment]
ok, I use IDEA add these lines at the beginning,and load checkstyle check to  fail.and then switch STS,  all test is passed.

**Comment by philwebb** [comment]
@bohrqiu have you signed the CLA?

**Comment by bohrqiu** [comment]
yes

**Comment by bohrqiu** [comment]
yes

**Comment by bohrqiu** [comment]
yes

**Comment by snicoll** [comment]
Merged, thanks for the contribution!

**Pull request closed without merging**
