### PR TITLE
GitProperties, BuildProperties support encoding.

### PR DESCRIPTION
**Pull request by hengyunabc**

### CODE REVIEW

**Comment by hengyunabc** [comment]
@wilkinsona 

https://github.com/spring-projects/spring-boot/pull/10748

**Comment by wilkinsona** [comment]
Please see #10748 for background. This revised proposal seems like a good compromise to me. Unlike the encoding for `application.properties`, we can be sure that any configuration setting for the encoding of Git properties or build properties has been read before trying to read the properties file.

**Comment by snicoll** [comment]
Do the plugins control how the `properties` file is encoded? For sure `build.properties` is written with `ISO-9959-1` encoding. I haven't seen a property for the git plugin.

**Comment by wilkinsona** [comment]
Good question, @snicoll. @hengyunabc How are you configuring your build to write UTF-8 characters to the properties files?

**Comment by 13567436138** [comment]
how to efficiently communicate in github? is there IM tools.

**Comment by 13567436138** [comment]
how guys communicate with each other?

**Comment by hengyunabc** [comment]
@snicoll @wilkinsona 

https://github.com/ktoso/maven-git-commit-id-plugin/blob/v2.2.3/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java#L319 

My project `project.build.sourceEncoding` is utf-8. 

The content in git.properties:

```
git.commit.user.name=中文
```

**Comment by snicoll** [comment]
@hengyunabc thanks, that's quite interesting. I guess we should do the same thing. That doesn't help Gradle users though.

**Comment by wilkinsona** [comment]
The equivalent Gradle plugin [always uses `UTF-8`](https://github.com/n0mer/gradle-git-properties/blob/master/src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy#L103).

**Comment by snicoll** [comment]
@hengyunabc thanks for your contribution, I've merged it with a [polish commit](https://github.com/spring-projects/spring-boot/commit/c91d9bfda8f9c7203f6f45f08f55eebbf3e4b0cf)

**Pull request closed without merging**
