### PR TITLE
Make chkconfig variable

### PR DESCRIPTION
**Pull request by nysd**
we want to use [chkconfig:         2345 80 20]
but currently chkconfig is  fixed to [chkconfig:         2345 99 01]
so i make chkconfig variable.

### CODE REVIEW

**Comment by philwebb** [comment]
Seems sensible although we should also update the docs.

**Comment by philwebb** [comment]
@nysd Have you signed the CLA?

**Comment by nysd** [comment]
I haven't signed CLA yet. How can i sign CLA?
I registered 'https://support.springsource.com/spring_committer_signup' now.
Confirmination no is 152220151202094537

**Comment by wilkinsona** [comment]
Thanks, @nysd. That's all that's needed.

**Pull request closed without merging**
