### PR TITLE
gh-2313: support incremental builds

### LINKED ISSUE #2313: spring-boot-configuration-processor doesn't work correctly for incremental builds
This is a problem when the processor is used from Eclipse. It manifests when the project has more than one type annoted with @ConfigurationProperties.

The processor rewrites the metadata file with a summary of information from all the types it processed. This produces the correct result on FULL builds but produces incomplete information on incremental builds (as the processor is only presented with some of the types based on what has changed in the workspace since the last build).

The result is that on incremental builds information from non-changed types is deleted from the metadata file.

### PR DESCRIPTION
**Pull request by kdvolder**
Fixes #2313

### CODE REVIEW

**Comment by kdvolder** [comment]
Hold of on merging this for a little while longer. I'm still looking into whether its feasible to add some regression tests for the incremental build.

**Comment by kdvolder** [comment]
Okay, I'm done with it for now. There are now some regression tests for the incremental builds.
All commits squashed into a single one.

As far as I'm concerned is good for merge. But I wouldn't mind a 'code review' and some feedback (this is my first substantial PR to spring outside of spring-ide).

So do let me know if there's some thing(s) I need to change.

**Comment by kdvolder** [comment]
I added 'waiting-for-feedback' tag. But I'm not sure if it means:

  - spring boot team is waiting for feedback from submitter or...
  - issue is waiting feedback from spring-boot team

Anyhow... what I meant to indicate is that I'm no longer working on this and consider it 'done'. 
Unless someone provides me with feedback that there's something more for me to do before this can be merged.

**Comment by philwebb** [comment]
It's used when the team is waiting for feedback from someone that raised a bug report.

**Comment by kdvolder** [comment]
I'm somewhat eager to get this merged. Without this the configuration-processor doesn't work correctly in Eclipse/STS. Any chance it can be merged soon-ish?

**Pull request closed without merging**
