### PR TITLE
Add an outcome tag to RestTemplate metrics similar to that provided for WebMVC and WebFlux

### PR DESCRIPTION
**Pull request by nishantraut**
See #15420

### CODE REVIEW

**Comment by nishantraut** [comment]
New test file is already formatted but still it is failing with formatting violations, can someone help me to understand what i am doing wrong here.

**Comment by snicoll** [comment]
@nishantraut I am assuming you are on Windows and have not configured your client to properly format line endings as CRLF. See, for instance, [this thread](https://stackoverflow.com/questions/11534035/git-crlf-for-windows-users). 

On a related note, your copy of the repository is not clean (see all the Merge from `spring-projects/master`) so you may want to fix that as well. If you need some help, please ask on StackOverflow.

**Comment by nishantraut** [comment]
> 
> 
> @nishantraut I am assuming you are on Windows and have not configured your client to properly format line endings as CRLF. See, for instance, [this thread](https://stackoverflow.com/questions/11534035/git-crlf-for-windows-users).
> 
> On a related note, your copy of the repository is not clean (see all the Merge from `spring-projects/master`) so you may want to fix that as well. If you need some help, please ask on StackOverflow.
> 
> Please do not open a duplicate PR if you intend to fix this. You can push force on your branch and the PR will update itself automatically

Thanks @snicoll yes i am on windows applied core.autocrlf true hope it will fix. 

I still need to figure out what is the best way to update my master branch as i do using compare-across forks by raising reverse PR. Thanks i will check/ask on stakcoverflow

**Comment by michaelmcfadyen** [comment]
What would be the outcome tag value when the client call times out?

**Comment by nishantraut** [comment]
It should be SERVER_ERROR

**Comment by nishantraut** [comment]
Sorry i will try to fix formatting issue on weekend. Apologize for inconvenience.

**Comment by nishantraut** [comment]
Hi @michaelmcfadyen, Depends what status code is returned if it is 4xx (guess client timeout is 408)  then CLIENT_ERROR or 5xx then SERVER_ERROR. This changes are aligned with WebMvc and WebFlux outcomes.

**Comment by michaelmcfadyen** [comment]
In the case of the http call timing out (read/connect) there will be no status in the response. In my opinion, setting the outcome tag as `SERVER_ERROR` for a timeout from the http client is misleading.

**Comment by nishantraut** [comment]
I am quite new to this code base, can someone springboot team revert on above question

**Comment by nishantraut** [comment]
> 
> 
> @nishantraut I am assuming you are on Windows and have not configured your client to properly format line endings as CRLF. See, for instance, [this thread](https://stackoverflow.com/questions/11534035/git-crlf-for-windows-users).
> 
> On a related note, your copy of the repository is not clean (see all the Merge from `spring-projects/master`) so you may want to fix that as well. If you need some help, please ask on StackOverflow.
> 
> Please do not open a duplicate PR if you intend to fix this. You can push force on your branch and the PR will update itself automatically

Hi @snicoll I have cleaned up unnecessary commits and merged into one, can you please review PR and merge if it looks ok. Thank you for the support.

**Comment by bclozel** [comment]
Thanks for your contribution @nishantraut - I've polished things a bit in d5ae59dad7 to address the comments here - if the response status cannot be resolved, we'll settle with `UNKNOWN` for the outcome tag information. I've also refined the error cases around status resolution.

**Pull request closed without merging**
