### PR TITLE
gRPC Server Starter for Spring Boot

### PR DESCRIPTION
**Pull request by saturnism**
Hi all,

This is my first stab at creating a starter for Spring Boot. This is the first set, which configures and starts a gRPC server, and also discovers gRPC service implementations.

### CODE REVIEW

**Comment by wilkinsona** [comment]
As [listed here](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters#community-contributions) there's already a third-party starter for gRPC. I don't think that we want to duplicate that effort with a first-party starter as well. If there is functionality in this PR that's not supported by the existing starter, perhaps this PR could be reworked as an enhancement to the existing third-party project?

**Comment by saturnism** [comment]
Hiya - I developed this independently from the other. Let me see how we can combine forces.

There are a couple of minor differences, but the major one is that if we can get plugin preconfigured in the parent POM, the getting started experience is very awesome. Finally, it'll also be great to get on start.spring.io.

Secondly, this is focused on the server side. The client side can be a different autoconfigurer. And in most cases, we don't want to start the server if we are only a client.

Thanks!

**Comment by philwebb** [comment]
I'll close this one for now and we'll see how the efforts go over on https://github.com/LogNet/grpc-spring-boot-starter/issues/1. It probably makes sense to develop things there a little more before we consider adding a starter directly to Boot.

**Comment by jvmlet** [comment]
Hello Phil
I'm the author of [LogNet/grpc-spring-boot-starter](https://github.com/LogNet/grpc-spring-boot-starter).
What additional features/test scenarios do you want to see in this starter in order to include it to Boot ?
Thanks

**Comment by wilkinsona** [comment]
IMO, it's not just additional features or test scenarios that we'd like to wait for. It's also seeing if the functionality is used by a broad set of Boot users as we need to be careful not to spread the core Boot team's focus too thinly.

**Comment by jvmlet** [comment]
I got your point, thanks.

**Pull request closed without merging**
