### PR TITLE
Methods in KafkaConnectionDetails are named inconsistently

### PR DESCRIPTION
**Pull request by izeye**
This PR polishes the changes made in gh-34770 a bit by completing renaming nodes to servers.

It contains a breaking change, but I didn't do anything for it as I don't know what the preference for it is here.

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks @izeye! I wonder what we should do about that method rename since 3.1 is already out. We could deprecate the old one or we could risk it since 3.1 hasn't been out that long and we're probably the only implementers right now.

**Comment by wilkinsona** [comment]
@izeye If it's not too much trouble, would you mind rebasing this PR on top of the latest main? I'm trying to figure out why the PR build ran for 6 hours(!) and hoping that rebasing on top of https://github.com/spring-projects/spring-boot/commit/3922f1ba9d6180915830738dcb6b4713bca6556c will help with that.

**Comment by izeye** [comment]
@wilkinsona Sure, done!

**Comment by wilkinsona** [comment]
Thanks very much, @izeye. The PR build was cancelled but we got a thread dump this time which revealed https://github.com/spring-projects/spring-boot/issues/35771. If you can be bothered, another rebase would be much appreciated.

**Comment by izeye** [comment]
@wilkinsona Great, done again.

**Comment by wilkinsona** [comment]
We discussed this and decided that we'd risk the breaking API change. It's a shame we didn't get this into 3.1.1 but I don't think that should change the decision.

**Review by wilkinsona — APPROVED** [review]

**Comment by wilkinsona** [comment]
Thanks very much, @izeye.

**Pull request closed without merging**
