### PR TITLE
Provide dependency management for logback-access.

### PR DESCRIPTION
**Pull request by izeye**
It would be good to provide dependency management for logback-access.

### CODE REVIEW

**Comment by philwebb** [comment]
Interesting, is any additional configuration required to make this work with embedded Tomcat/Jetty?

**Comment by spencergibb** [comment]
http://logback.qos.ch/access.html

**Comment by wilkinsona** [comment]
Neat. Looks like there's room for some auto-configuration too

**Comment by izeye** [comment]
@philwebb I'm using `TeeFilter` although it's not recommended for production.

This is a sample project using it in Spring Boot:
https://github.com/izeye/samples-spring-boot-branches/tree/rest-with-tee-filter

**Comment by wilkinsona** [comment]
I've opened #2609 to provide auto-configuration

**Pull request closed without merging**
