### PR TITLE
Provide a configuration property for the observation patterns of Spring Integration components

### PR DESCRIPTION
**Pull request by artembilan**
Spring Integration can instrument its component with an `Observation` according to the `@EnableIntegrationManagement.observationPatterns` value

* Expose `spring.integration.management.observation-patterns` configuration property
* Propagate this property into an `@EnableIntegrationManagement` in the `IntegrationAutoConfiguration.IntegrationManagementConfiguration`
* Verify that property has an effect via `IntegrationAutoConfigurationTests.integrationManagementInstrumentedWithObservation()`

### CODE REVIEW

**Comment by philwebb** [comment]
Considering this one a bug of omission, but we can't add it yet because we can't move to SNAPSHOTs before our next RC.

**Comment by artembilan** [comment]
No. This is not a bug or omission. 
An observation instrumentation is a new feature in Spring Integration 6.0.
Yes, we can squeeze this for the next release for Spring Boot in two week.
Or you can just move it as a theme of next Spring Boot `3.1` (or `3.0.1` if any).

Thanks

**Comment by philwebb** [comment]
By "bug of omission" I meant that it's a feature we should ideally have support for in the 3.0 release since the feature was added in Spring Integration 6. I guess you're right though, it's really an enhancement. I still think it might be worth adding to 3.0 if we can. It seems low risk.

**Comment by artembilan** [comment]
Sounds good, Phil!
Sorry that I came up with this property a bit late.
Let's see if it can make it into `3.0`!

**Pull request closed without merging**
