### PR TITLE
Drop deprecated spring.version pom property in favor of spring-framework.version

### PR DESCRIPTION
**Pull request by gauravbhtngr**
Creating this pr (for https://github.com/spring-projects/spring-boot/issues/17037) to help removing deprecated  pom property spring.version

### CODE REVIEW

**Comment by mbhave** [comment]
Since there were a lot of usages of `spring.version` which hadn't been changed to `spring-framework.version`, we might need to split this PR and merge the usages and deprecate `spring.version` at a later time.

**Comment by gauravbhtngr** [comment]
Hey @mbhave  Thanks for the reply 
I see spring-framework-version itself using spring.version 
```<spring-framework.version>${spring.version}</spring-framework.version>```
Do you think it still will cause the issue ?

How do you want me to split the pr ? leave the usages changes and do not remove spring.version with this pr, spring.version is already deprecated

**Comment by mbhave** [comment]
@wilkinsona pointed out that most usages are only in integration tests so we can merge this as is.

**Comment by gauravbhtngr** [comment]
Thanks

**Comment by gauravbhtngr** [comment]
Hey @mbhave  When can we merge this ?

**Comment by snicoll** [comment]
@gauravbhtngr there is really no rush, please be patient.

**Comment by gauravbhtngr** [comment]
Resolved the conflict and rebased

**Comment by philwebb** [comment]
Thanks very much @gauravbhtngr, this change has now been merged into master.

**Pull request closed without merging**
