### PR TITLE
Remove spock caveat in the doc as it's been fixed.

### PR DESCRIPTION
**Pull request by ceilfors**
Issue is fixed at https://github.com/spockframework/spock/commit/718bf4261d3abaa6217ee059639c3aae2f8a5803

### CODE REVIEW

**Comment by snicoll** [comment]
how about documenting that limitation still (mentioning that Spock 1.0 did solve that issue)? Have you signed the CLA? Thanks!

**Comment by ceilfors** [comment]
I didn't realise that I have overridden the spock-core version to 1.0 in my project (managed version is 0.7 now in spring boot)! It's my mistake, I'll close the ticket.

**Comment by snicoll** [comment]
no, no. We're fine. master is using 1.0 as far as I can see so the PR is still good but needs to be rephrased. Are you willing to do that? If so, please let me know and push force a new proposal on your branch.

**Comment by ceilfors** [comment]
@snicoll Sorry, price of context switching. :smiley:

I have just signed the CLA.

CMIIW but won't documenting the limitation means that the documentation will grow over time with all of the limitation workarounds? I would expect developers to read the documentation specific to the version that they are developing against e.g. if using 1.2.3.RELEASE, read the 1.2.3.RELEASE documentation which contains spock limitation. If using 1.3.0.RELEASE, which means using spock 1.0, read the 1.3.0.RELEASE which means the limitation is now automatically fixed hence not worth documenting.

**Comment by snicoll** [comment]
Alright, convinced. I didn't saw that 1.2.x was still on 0.7 - Thanks!

**Pull request closed without merging**
