### PR TITLE
New conditionals entries to control the memory and the number of cores in your system

### PR DESCRIPTION
**Pull request by jledo**
New conditionals entries to control the memory and the number of cores in your system

### CODE REVIEW

**Comment by joshiste** [comment]
Can you explain some use cases and give examples what you want to achieve with these conditionals?

**Comment by philwebb** [comment]
I'm also interested in the use-case. We've so far kept `@Conditional` implementations in Boot limited to things we actually need to use ourselves in the codebase.

**Comment by jledo** [comment]
I think it may be useful to establish the size of the cache ( JCache ) or the maximum number of concurrent threads in spring batch

**Comment by jledo** [comment]
(philwebb) Ok thanks for your time.

**Comment by wilkinsona** [comment]
This feels like a rather heavy solution to the problem of configuring things based on the capabilities of the host. For example, a common use case is to configure a number of threads that's equal to the number of cores. Unless you're deploying to a limited and predictable set of hosts, that'll require a large number of configuration classes. IMO, calling `availableProcessors` or `totalMemory` at runtime, perhaps with a configurable multiplier (n * available processors, for example) is a better solution.

**Pull request closed without merging**
