### PR TITLE
Add Membrane Spring Boot Starter

### PR DESCRIPTION
**Pull request by helpermethod**
This PR adds membrane-spring-boot-starter to the list of community provided Spring Boot starters.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@helpermethod Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9072)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9072) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@helpermethod Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9072)!

**Comment by snicoll** [comment]
@helpermethod there are two entries in this PR. Was it intended?

**Comment by snicoll** [comment]
I've created a couple of issues in that repository. Let's see how that turns out.

**Comment by helpermethod** [comment]
Hi @snicoll,

both issues should be fixed now.

Thanks again for your help!

**Comment by snicoll** [comment]
Cool, the PR is now merged. Thanks!

**Pull request closed without merging**
