### PR TITLE
Determine Spring Boot version on startup correctly when using Jigsaw

### PR DESCRIPTION
**Pull request by hsellik**
In Java 9, a package may return null for its implementation version
even when the manifest attribute specifying the version is present
in the jar from which the package was loaded.

This commit updates SpringBootVersion to fall back to
accessing the jar and its manifest attributes directly when the
implementation version of its package is null.

Closes gh-10233

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks for the fix. Since this is just a cosmetic problem I'm tempted to target it to 2.2 rather the 2.1 (which #10233 was originally targeted to).

**Comment by pivotal-issuemaster** [comment]
@hsellik Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16182)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16182) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@hsellik Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16182)!

**Comment by hsellik** [comment]
@philwebb is there something I can do to get this merged or are 2.2 pull requests getting merged in a later point in time? I can make a new pull request, which is not on my master branch (sorry for that).

**Comment by philwebb** [comment]
@hsellik There's just a bit of a backlog at the moment as a lot of the team are away. There's no need for a new PR, we can just cherry-pick the commit.

**Comment by wilkinsona** [comment]
Thanks very much for the PR, @hsellik. I've cherry-picked the change and merged it into master along with a [polish commit](https://github.com/spring-projects/spring-boot/commit/15f28dcc68be23e15bece7b285051a23cc4c0290).

**Pull request closed without merging**
