### PR TITLE
Document using @Profile with @ConfigurationProperties

### PR DESCRIPTION
**Pull request by kedar-joshi**
Documented use of `@Profile` with `@ConfigurationProperties`.

See gh-16612

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks for the PR but I am not 100% sure that I want to document that with such a broad scope as this one. While `@Component` and `@Configuration` are clearly stereotypes linked to  component scan, `@ConfigurationProperties` isn't.

**Comment by wilkinsona** [comment]
I think this is worth documenting as proposed and/or by mentioning `@Profile` in the documentation for `@ConfigurationPropertiesScan`.

**Comment by mbhave** [comment]
I've added `merge-with-amendments` so that we can add documentation regarding [this](https://github.com/spring-projects/spring-boot/issues/16645#issuecomment-487415257) as part of merging the PR.

**Comment by mbhave** [comment]
Thanks @kedar-joshi. This is now merged into master.

**Pull request closed without merging**
