### PR TITLE
Refactor String#replaceAll

### PR DESCRIPTION
**Pull request by durigon**
If we repeatedly call String#replaceAll, we internally repeatedly call the regular expression pattern compilation every time as following:

```java
    public String replaceAll(String regex, String replacement) {
        return Pattern.compile(regex).matcher(this).replaceAll(replacement);
    }
```
The modifications are to keep the compiled pattern.
Therefore, compiling a relatively expensive regular expression pattern does not have to be done every time.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@durigon Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=14483)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=14483) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@durigon Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=14483)!

**Comment by wilkinsona** [comment]
@durigon Thank you very much for making your first contribution to Spring Boot. The proposed changes have been merged into master.

**Comment by durigon** [comment]
@wilkinsona Thank you for accepting my pull request.

**Pull request closed without merging**
