### PR TITLE
Remove Jetty/Netty/ApacheHttpClient checks for WebClient

### PR DESCRIPTION
**Pull request by anugrahsinghal**
adds the functionality according to [#33474](https://github.com/spring-projects/spring-boot/issues/33474)
- removes additional checks for netty/jetty/Apache HttpClient dependencies

### CODE REVIEW

**Comment by anugrahsinghal** [comment]
> At least in org.springframework.boot.test.web.reactive.server.WebTestClientContextCustomizerFactory we check for the presence of netty / jetty / apache httpclient. This check can be removed, and maybe such checks are somewhere else in the codebase.

@mhalbritter 
I have used [this sourcegraph query](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/spring-projects/.*+%22reactor.netty.http.client.HttpClient%22+or+%22org.eclipse.jetty.client.HttpClient%22+or+%22org.apache.hc.client5.http.impl.async.CloseableHttpAsyncClient%22+or+%22org.apache.hc.core5.reactive.ReactiveDataConsumer%22&patternType=standard&sm=1) to find the presence of similar dependencies in other places in the codebase, and could not find one that would need removal.

**Comment by anugrahsinghal** [comment]
@mhalbritter a little bit unsure of how to handle [this test](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-test/src/test/java/org/springframework/boot/test/web/reactive/server/WebTestClientContextCustomizerWithoutSupportedHttpClientTests.java#L35)


This test becomes invalid because there is always the `JdkClientHttpConnector` available
even after the `@ClassPathExclusions({ "reactor-netty*.jar", "jetty-client*.jar" })`

This means that the `WebTestClientContextCustomizerFactory` is always `non-null`

Do you have any suggestions on how to modify this test case?

**Comment by scottfrederick** [comment]
@anugrahsinghal I think the `WebTestClientContextCustomizerWithoutSupportedHttpClientTests` can be removed, since there is no longer a case where no client is availble.

**Comment by anugrahsinghal** [comment]
hey @scottfrederick 

I have removed the `WebTestClientContextCustomizerWithoutSupportedHttpClientTests` test.

**Comment by mhalbritter** [comment]
Thanks and congratulations to your first contribution to Spring Boot!

**Pull request closed without merging**
