### PR TITLE
Setting http-only to false has no effect when using embedded Tomcat

### PR DESCRIPTION
**Pull request by kedar-joshi**
Fixes gh-12580

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. I know that it's necessary to configure HTTP only on the context as well as on the session cookie config, but I'm not sure that's the case for the other properties. Have you verified Tomcat's behaviour? We also need some tests to verify that the problem's been fixed and isn't regressed in the future.

**Comment by kedar-joshi** [comment]
Yes, I have verified the behaviour and adding the tests for the same, as we speak.

**Comment by kedar-joshi** [comment]
> but I'm not sure that's the case for the other properties

Yes, only `HttpOnly` needs to be set. Updated the PR for the same.

**Comment by rfshelley** [comment]
What are the chances of getting this merged into a snapshot? Is there a good work around in the mean time? The WebServerFactoryCustomizer in 12580 doesn't seem to work for me as it throws an error "No ServletContext set" so I'm hoping to get a version with the preferred patch. Thanks!

**Comment by philwebb** [comment]
Turns out applying this to 1.5.x is a little more involved so I'm going to take a slightly different approach. Thanks anyway.

**Pull request closed without merging**
