### PR TITLE
Added Boxfuse + AWS deployment information

### PR DESCRIPTION
**Pull request by axelfontaine**
This Pull Request extends the manual with a cloud deployment section for AWS using Boxfuse.

I have signed the CLA (confirmation: 133920150813014419)

We have many users using this and we strongly believe this is the simplest way available today to deploy Spring Boot applications on AWS.

Best regards,
Axel

### CODE REVIEW

**Comment by axelfontaine** [comment]
FYI: The Travis CI build seems to have failed for a totally unrelated reason

**Comment by wilkinsona** [comment]
Thanks for the PR. Merged in d25b7ca.

**Comment by axelfontaine** [comment]
Thank you Andy. Would you be interested in a guest post on the Spring blog on "how to deploy Spring Boot microservices on AWS" sometime after the 1.3.0 release?

**Comment by cemo** [comment]
@axelfontaine please do :)

**Comment by wilkinsona** [comment]
@axelfontaine I believe @dussab is the gatekeeper for guest blog posts

**Comment by axelfontaine** [comment]
Thank you @wilkinsona 

@dussab Are you interested in this? If yes, what is the best way to proceed? Do you have a Github repo for the blog one could submit a PR against?

**Comment by dussab** [comment]
@axelfontaine sent you an email at https://axelfontaine.com/ and we can discuss next steps via email

**Pull request closed without merging**
