### PR TITLE
Add reactive mongodb sample

### PR DESCRIPTION
**Pull request by rajadilipkolli**
adds spring-boot-data-mongdb-responsive sample using new spring data mongodb reactive starter

### CODE REVIEW

**Comment by mp911de** [comment]
I'm not sure about the example. 

The code shows reactive API usage within a synchronous piece of code (`CommandLineRunner`) and heavily makes use of `.block()` methods. I think an example might make more sense in a different context, such as WebFlux or inserting data asynchronously (`Flux.interval(…)`).

**Comment by rajadilipkolli** [comment]
@mp911de  agreed that block shouldn't be used.  what is the reactive equivalent of `CommandLineRunner` ?

I have used this in my WebFlux project and copy pasted from there,hence it makes sense there but not here.

**Comment by rajadilipkolli** [comment]
@mp911de  Can you please review my latest changes and let me know if I need to improve on anything in this PR

**Comment by snicoll** [comment]
I am not sure we should add a reactive/non reactive variant of the data stuff, especially considering how the setup is similar. It feels to me that a Spring Data sample is a better place for it and perhaps such sample already exists.

Let's see what the rest of the team thinks.

**Comment by mp911de** [comment]
We have a few samples in our [Spring Data Examples repository](https://github.com/spring-projects/spring-data-examples/tree/master/mongodb/reactive/src/test/java/example/springdata/mongodb/people). We aren't entirely happy with our current samples because the majority of environments (`CommandLineRunner`, JUnit tests) follows an imperative programming model which is a limiting factor. An end-to-end reactive flow isn't possible without the appropriate runtime environment thus we are forced to use blocking calls or test facilities (such as `StepVerifier`).

A reactive sample would make sense in the context of WebFlux, but then it's no longer a pure MongoDB example.

**Comment by bclozel** [comment]
I agree with @snicoll, there's no point in adding all the possible variants out there, especially when the setup is so similar.

Now about the `CommandLineRunner`, you definitely have a point.
I've seen a lot of code samples out there just calling `Flux.subscribe(Consumer)` — this won't guarantee that the processing of that `Flux` is done before the application is shut down/the webapp is started.

We could create something like:

```java
@FunctionalInterface
public interface ReactiveCommandLineRunner {
  Mono<Void> run(String... args);
}
```

At processing time, we would need to concat all of them (to guarantee a processing order) and block, like:

```java
firstMono.concatWith(secondMono).then().block();
```

What do you think?

**Comment by snicoll** [comment]
@bclozel thanks for the reminder. Can we move the `CommandLineRunner` conversation to a dedicated issue? In the meantime, we're going to close this one as the Spring Data samples are already covering this.

**Pull request closed without merging**
