### PR TITLE
Custom classpaths for (Groovy) scripts

### PR DESCRIPTION
**Pull request by andrewglind**
Added `$CLASSPATH` as the first element in `CLASSPATH=` to allow a custom classpath to be exported before a script is run. This is useful in the instance where you might want to quickly prototype a Web Service, in my case I needed to have the Oracle JDBC driver on the classpath. 
Example below:

```
export CLASSPATH=/path/to/jdbc.jar
spring run server.groovy
```

server.groovy:

```groovy
import groovy.sql.*

@Controller
class SqlController {

 static def sql = Sql.newInstance("jdbc:oracle:thin:@localhost:1521:ORCL", "db", "password", "oracle.jdbc.OracleDriver")

 @RequestMapping(value = "/customer/{customerId}", method = RequestMethod.GET)
 @ResponseBody
 def handler(@PathVariable("customerId") Integer customerId) {
  def result = [:]
  sql.eachRow("select * from customers where customer_id = ?", [customerId]) { customer ->
   result << ["name":customer.name]
   result << ["emailAddress":customer.email_address]
  }

  result
 }
}
```

Have updated the spring.bat file to allow %CLASSPATH% to be specified.

In addition I have also added a fallback to the system class loader when running a groovy script, this allows the use of auto configuration, like in the example below:

server.groovy:
```groovy
@EnableAutoConfiguration
@Controller
class Server {

 @Autowired
 JdbcTemplate jdbcTemplate

 @RequestMapping(value = "/customer/{customerId}", method = RequestMethod.GET)
 @ResponseBody
 def handler(@PathVariable("customerId") Integer customerId) {
  def customer = jdbcTemplate.queryForObject("select * from customers where customer_id = ?",
   [customerId] as Object[],
   [mapRow: { rs, rowNum ->
     new Customer(name:rs.getString("name"), emailAddress:rs.getString("email_address"))
   }] as RowMapper
  )

  ["name":customer.name] << ["emailAddress":customer.emailAddress]
 }
}
```

with application.properties:

```
spring.datasource.initialize=false
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
spring.datasource.username=db
spring.datasource.password=password
spring.datasource.jmx-enabled=false
```

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks. Have you signed the CLA?

**Comment by andrewglind** [comment]
Have now, thanks

**Comment by andrewglind** [comment]
Have updated the pull request with fix to spring.bat and fall back to system class loader to allow this to work with auto configuration, thanks

**Comment by andrewglind** [comment]
Any reason this hasn't been merged?

**Comment by philwebb** [comment]
After some discussion we've decided that we're not comfortable with an environment variable effecting the classpath. We'd recommend that additional artifacts be added to a local maven repository and included via Groovy's `@Grab` annotation. That technique should also work with `spring jar`.

Thanks anyway for the suggestion.

**Pull request closed without merging**
