### PR TITLE
Allow shutdown endpoint to accept GET

### PR DESCRIPTION
**Pull request by polarbear567**

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks for the pull request. We're still having some discussion in #18241 about if we think this is a good idea or not.

**Comment by polarbear567** [comment]
Sure, and do you mean trigger a shutdown by preStop hook in Kubernetes?

**Comment by philwebb** [comment]
@polarbear567 Yes

**Comment by wilkinsona** [comment]
We haven't heard a concrete need for this on #18241 and it has now been closed. Thanks anyway, @polarbear567.

**Pull request closed without merging**
