### PR TITLE
Add mybatis auto-configuration

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by snicoll** [comment]
I had a a quick look and it looks quite complete. Wow, thanks!

**Comment by snicoll** [comment]
I don't like that we have to add `@MapperScan` explicitly. It should just do that on the application package by default. I've looked in the code to find a way to do that and backoff if a `@MapperScan` is defined explicitly and it's not easy. 

The other problem is that `MapperScannerRegistrar` does not only collect the entities to scan but also how to register them. It would be better if that part was only doing the scanning and a separate service (that we could defined and configure separately) would register them as mybatis entities. 

Any feedback on that is more than welcome.

**Comment by philwebb** [comment]
I wonder if Spring Boot support for Mybatis might be better off as part of https://github.com/mybatis/spring? We've had a few other contributions that have taken that approach when a project already has good Spring integration.

**Comment by emacarron** [comment]
Hi! Of course we are more than happy to accept any contribution specially if related with Spring boot.

@eddumelendez probably the contribution will need some minor package renamings.

@snicoll Honestly, we coded the MapperScannerRegistrar without a deep knowledge of Spring's @Configuration internals so probably it can be improved. Any suggestion will be welcomed!

**Comment by philwebb** [comment]
Thanks @emacarron, I'll close this one in favor of https://github.com/mybatis/spring/issues/79

**Pull request closed without merging**
