### PR TITLE
A component of operating elastic search

### PR DESCRIPTION
**Pull request by lihang212010**
Hello, I developed a component to operate elastic search. It has two ways to use it
1. It is similar to spring-boot-starter-data-elasticsearch, but it discards the chain of data, makes code writing simpler and cleaner, and makes code less in some methods, and checks null by default.
2. Similar to mybatis, it uses the format of JSON and code separation to adapt to more complex places
This component is very close to the default API of elastic search in the usage method, and is easy to use.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@lihang212010 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20924)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20924) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@lihang212010 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20924)!

**Comment by bclozel** [comment]
Hello @lihang212010 
This request is a bit unusual as in general such projects should live independently. A separate repository with a library and its companion starter is a better fit in this case. If you’re starting a project and a new community, it is wiser to bootstrap it in its own repository to evolve the project as its own pace.

We’ll be happy to reference this starter on our official 3rd party starter list: https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-starters

Because we have limited time and resources, the Spring Boot team cannot accept all new features and projects as we need to carefully consider interest from the community and our maintenance efforts.

I’m closing this PR as a result. Don’t hesitate to create a new one to add a reference link to your project once it’s found a proper home.

Thanks!

**Comment by lihang212010** [comment]
I wrote a simple use example, which may not be neat, but I can use this example to introduce the use of this component
demo url：https://github.com/lihang212010/Elasticsearch-ais-demo

**Pull request closed without merging**
