### PR TITLE
Set `HttpStatus.INTERNAL_SERVER_ERROR` status in case if response status has not been set before.

### PR DESCRIPTION
**Pull request by nosan**
see gh-13300

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR, @nosan, but I don't think this will address #13300. The problem there is that an exception is thrown and caught by the `WebMvcMetricsFilter`. At this point, no error has been sent and nothing has set the status. The filter then sets the status to 500 and rethrows the exception. The exception is then caught by Spring Security's filter which maps it to a 4xx status code and sets that on the response.

As far as I can tell, the change proposed here won't help with the problem described above as the status has not been set when `WebMvcMetricsFilter` is called. Have I misunderstood what your change does?

**Comment by nosan** [comment]
I've checked that `MetricsWebFilter` has `@Order(Ordered.HIGHEST_PRECEDENCE + 1)` and from the other end:
```java
/**
	 * Default order of Spring Security's Filter in the servlet container (i.e. amongst
	 * other filters registered with the container). There is no connection between this
	 * and the {@code @Order} on a WebSecurityConfigurer.
	 */
	public static final int DEFAULT_FILTER_ORDER = OrderedFilter.REQUEST_WRAPPER_FILTER_MAX_ORDER
			- 100;

```
So a chance when `spring-security-filters` replaces `HTTP status` is not as big as `MetricsWebFilter` could replace the actual status, that has already been sent. 

From my perspective, this MR tries to fix an issue when `HTTP status` has been already set but `MetricsWebFilter` overrides it.
Looks like, I'm trying to fix something else that could happen when a custom `HTTP status` is set and an unhandled exception has been thrown.

**Comment by wilkinsona** [comment]
If something sets the status and then throws an exception, the status will be overwritten. That will either happen because another filter catches the exception and sets the status or because the exception reaches the servlet container. In the latter case the container will set the status to 500. 

The container's behaviour is what that the filter currently tries to anticipate. It sets the status to 500 in anticipation of the container doing so if the exception reaches it. If nothing else catches the exception and changes the status, this means that the status recording in the metric for the request will match the status of the response to the request.

If we merge your proposed change, I think we'll increase the likelihood of the status in the metric not matching the status in the response. If something calls setStatus(201), for example, and then an exception is thrown which reaches the container, the change proposed here will result in the metric having a status of 201 but the response having a status of 500.

**Comment by nosan** [comment]
@wilkinsona 
fair enough, sorry for the inconvenience :(

**Pull request closed without merging**
