### PR TITLE
Added p6spy, datasource-proxy and flexy-pool starters reference

### PR DESCRIPTION
**Pull request by gavlyukovskiy**
Relates to https://github.com/spring-projects/spring-boot/issues/7863

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks for sharing your 3rd party starter(s). I had a quick look and created https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/issues/2

**Comment by ttddyy** [comment]
@gavlyukovskiy
Just a nit: I think the title of this commit meant `datasource-proxy` instead of `datasource-decorator`.
Or, rather _"added datasource-decorator starters reference"_.

sorry for nit picking :)

**Comment by gavlyukovskiy** [comment]
@ttddyy oh, yes, you're right

**Comment by gavlyukovskiy** [comment]
@snicoll thanks for raising this, it is resolved now.

**Comment by snicoll** [comment]
Unfortunately, I don't think it is. I've added a comment on the issue.

**Pull request closed without merging**
