### PR TITLE
Add Stackdriver metrics export support

### PR DESCRIPTION
**Pull request by grafjo**
Add spring-boot-autoconfiguration support for Stackdriver via micrometer-registry-stackdriver

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@grafjo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=19528)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=19528) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@grafjo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=19528)!

**Comment by snicoll** [comment]
@grafjo thank you for making your first contribution to Spring Boot. I've [polished your contribution](https://github.com/spring-projects/spring-boot/commit/462442e7d24ab11a7c0a2f9b8c56257662b1ed12) to address code formatting and checkstyle violations for the most part. Please consider running the build locally next time as it would exhibit those issues and offer a way to reformat the code.

**Comment by grafjo** [comment]
@snicoll you're welcome! I'll do that next time - thx fot this hint.
I have one question regarding the documentation. Right now, there is no mention to create / provide a google service account to make the Stackdriver export working. Maybe a reference to the Micrometer documentation is usefull https://micrometer.io/docs/registry/stackdriver#_configuring - what do you think?

**Comment by snicoll** [comment]
There is already a link to the micrometer doc [in the section I added](https://docs.spring.io/spring-boot/docs/2.3.0.BUILD-SNAPSHOT/reference/html/production-ready-features.html#production-ready-metrics-export-stackdriver).

**Pull request closed without merging**
