### PR TITLE
Change PropertiesLauncher equals method to use URI rather than URL

### PR DESCRIPTION
**Pull request by Konrado85**
We seem to have a little problem here:

"The equals and hashCode methods of URL are blocking"

### CODE REVIEW

**Comment by bclozel** [comment]
I guess you're referring to the DNS resolution issue with the URL class?
In this case, we should be dealing only with files on the file system - did you find a specific problem with this statement? Was that identified while profiling a particular application? Could you provide more information about this?

Note that the extra space in your PR is breaking the build.
Thanks!

**Comment by Konrado85** [comment]
I came across this problem while analyzing my own application, in which I
use Spring Boot version 2.2.6

For the analysis I used, among others, a program:

SopotBugs version 4.0.1

https://spotbugs.github.io/

Besides the problems in my projection, SopotBugs showed some problems in
Spring itself. I check these remarks, what hasn't been reported yet I try
to report if I think the problem actually exists.

"The equals and hashCode methods of URL are blocking" appears twice in the
report and concerns two Springs classes.

Tomorrow I will try to propose an amendment to the second, but first I want
to look into it.


wt., 7 kwi 2020 o 18:25 Brian Clozel <notifications@github.com> napisał(a):

**Comment by philwebb** [comment]
This has been raised previously in #10586

**Comment by snicoll** [comment]
@Konrado85 thank you for making your first contribution to Spring Boot.

**Pull request closed without merging**
