### PR TITLE
Change default value of refresh policy to NONE.

### PR DESCRIPTION
**Pull request by polarbear567**
Fix [issue](https://github.com/spring-projects/spring-boot/issues/30096)

### CODE REVIEW

**Comment by mhalbritter** [comment]
Hi, as [mentioned here](https://github.com/spring-projects/spring-boot/issues/30096#issuecomment-1061879608), we want to remove all `set` calls in the autoconfiguration and rely on Spring Boots defaults.

**Comment by polarbear567** [comment]
Sure, will update when I'm free.

**Comment by mhalbritter** [comment]
Please see also the discussion [in the issue](https://github.com/spring-projects/spring-boot/issues/30096#issuecomment-1063735160).

**Comment by snicoll** [comment]
@polarbear567 thanks for the PR but we're still trying to figure out how to approach this. One liner-PR like this are making things harder to track and we can take care of this ourselves.

**Pull request closed without merging**
