### PR TITLE
CXF Auto configuration with JAX-RS and JAX-WS spring boot examples

### PR DESCRIPTION
**Pull request by elans3**
Team,
I have created examples for CXF based JAX-RS and JAX-WS spring boot examples.
Please review & let me know anything required.

Thanks,
Elan.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Interesting, thanks. Have you [signed the CLA](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#sign-the-contributor-license-agreement)?

We typically only have samples that show off a specific piece of Spring Boot functionality. This makes these samples a little unusual. I know very little about CXF. Perhaps there's room for some Spring Boot auto-configuration here? For example, would it make sense to auto-configure `CXFServlet` when it's on the classpath?

**Comment by elans3** [comment]
I have signed the CLA. Will see if I can create auto configuration for CXF servlet. and get back to you soon.

**Comment by elans3** [comment]
wilkinsona,
I have signed the CLA already. Pull request #3312 has created with auto-config of CXFServlet. Please review and let me know your comments.
Thanks,
Elan

**Comment by vayalaivadivel** [comment]
Hi elans3, I need that example. Can you please share that link?

**Comment by wilkinsona** [comment]
The PR that is a prereq for this one #3312 has been closed due to lack of response so I'm going to close this one for now too.

**Comment by vayalaivadivel** [comment]
Can I have best suite versions for both cxf and spring boot annotations based?

**Comment by elans3** [comment]
Sorry for the late reply..
https://github.com/elans3/spring-boot/tree/76cb09e6de633530248eda25e740ec297f987323/spring-boot-samples/spring-boot-sample-rs-cxf

Thanks,
Elan

**Comment by vayalaivadivel** [comment]
Thanks..

**Pull request closed without merging**
