### PR TITLE
Add option to fail startup if the PID file cannot be written

### PR DESCRIPTION
**Pull request by bsodzik**
Having the ability to create PID file on startup is great, so great that sometimes deployment process makes strong assumptions on this file existence. If for some reason this file can not be created, application may be running and subsequent deployment can be quite surprised (because there is no PID file). Of course this is not only a hypothetical situation but one that happened in my project and was not easy to track.

My suggestion is to allow application to fail when PID file can not be created. Of course default behaviour is not changed, but there is new property that can change it: `spring.pidfile.continue-on-error=false` (convention based on `spring.datasource.continue-on-error`). What do you think?

I signed CLA and formatted code using your settings.

### CODE REVIEW

**Comment by philwebb** [comment]
Seems like a nice idea. I'll target this for 1.3.

**Comment by bsodzik** [comment]
Gentlemen, sorry for bothering you, but is there some more elegant way than `git merge spring/1.2.x` to get rid of current merge conflict? I would like to fix this conflict, but my experiments with cherry-picking commits from your repo as well as with rebasing ended with hard reset..

**Comment by philwebb** [comment]
Thanks, We've rebased this onto `master` and also made the following changes:

* The `continue-on-error-property` has been changed to `spring.pid.fail-on-write` since we think it's more obvious what the default behavior will be when it's missing.
* Rather than using `spring.pidfile.xxx` We've gone for `spring.pid.xxx`. This is so that we don't get overlap with the existing `spring.pidfile` property. 
* We've deprecated `spring.pidfile` and replaced it with `spring.pid.file` for the reasons above. This should give us more scope to add more properties in the future if we need to.
* We've updated the appendix in the docs and the config meta-data file.

Thanks for PR, it's a very worthwhile improvement I think!

**Comment by bsodzik** [comment]
Thank you Phillip, great to see this feature in `master`!

**Comment by bsodzik** [comment]
Hey friend, 


There is an  article I've  written recently, it is  quite nice I think, please feel free to read  it here <http://tushaxospa.specific-steps.com/e4wntkq>


Later, bsodzik

**Comment by bsodzik** [comment]
Greetings! 
I think you have to try this thing, it's so hilarious, take a  look  at <http://siposhindu.waytocart.info/e4juf>

Sincerely yours, bsodzik

**Pull request closed without merging**
