### PR TITLE
Remove usage of `HttpStatus` in Web Endpoints

### LINKED ISSUE #10348: Remove usage of HttpStatus in WebEndpointExtensions

### PR DESCRIPTION
**Pull request by vpavic**
This resolves #10348.

### CODE REVIEW

**Comment by philwebb** [comment]
It might be worth pulling some of the more common status codes up into `WebEndpointResponse`.

**Comment by wilkinsona** [comment]
That's a nice idea, @philwebb. I also wonder if we should add a Checkstyle import exclusion to stop `HttpStatus` from creeping in again.

**Comment by vpavic** [comment]
Both ideas (common status codes and Checkstyle) sound very nice to me. Once consensus is reached on those two topics I can easily update the PR to address them.

**Comment by philwebb** [comment]
Consider a consensus reached :)

**Comment by vpavic** [comment]
I've added a commit that defines common status codes in `WebEndpointResponse`.

Checkstyle rule is not so trivial though, as there are other `HttpStatus` usages across Actuator, for example:
- `org.springframework.boot.actuate.env.EnvironmentEndpoint.NoSuchPropertyException`
- `org.springframework.boot.actuate.metrics.web.reactive.server.WebFluxTags#status`
- `org.springframework.boot.actuate.trace.WebRequestTraceFilter#doFilterInternal`

**Comment by snicoll** [comment]
`NoSuchPropertyException` is unused and it looks like something is missing compared to what we had in `1.5.x`. The two others are legit so I guess we'd need to work with certain packages.

**Comment by snicoll** [comment]
I found some more issues so let's handle the checkstyle rule in #10358

**Pull request closed without merging**
