### PR TITLE
Add reference to ArangoDB starter

### PR DESCRIPTION
**Pull request by mpv1989**
Add arangodb-spring-boot-starter

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mpv1989 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15144)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15144) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mpv1989 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15144)!

**Comment by snicoll** [comment]
I've created a couple of issues in starter project.

**Comment by mpv1989** [comment]
@snicoll Thanks for your feedback. I changed everything you mentioned and the ArangoDB Team already released a new version.

**Comment by snicoll** [comment]
@mpv1989 that is awesome, thank you very much for the super fast turnaround.

**Comment by snicoll** [comment]
@mpv1989 thank you for making your first contribution to Spring Boot and your work on the ArangoDB starter. This is now merged in `master`.

**Pull request closed without merging**
