### PR TITLE
Add ObjectMapper to be used by Jersey

### PR DESCRIPTION
**Pull request by eddumelendez**
Reuse ObjectMapper from the application context in order
to be added in the Jersey's context.

### CODE REVIEW

**Comment by eddumelendez** [comment]
@snicoll thanks for feedback. I will work on this.

**Comment by snicoll** [comment]
Regarding 5, I just saw you were configuring jackson in `@IntegrationTest`. I think it would be nice to update an existing test with the same kind of request and assert that the result _is_ different.

**Comment by eddumelendez** [comment]
@snicoll PR updated. Hope to cover the requirement :)

**Comment by snicoll** [comment]
Thanks Eddu, I've polished your contribution in https://github.com/spring-projects/spring-boot/commit/a27176807f4b45bc768e019d9a0dab1ac8ec3dec

**Pull request closed without merging**
