### PR TITLE
Enabled SSL configuration customization in Undertow, Jetty and Tomcat EmbeddedServletContainerFactory

### PR DESCRIPTION
**Pull request by venilnoronha**
Hi,

Issue #5208 was still pending so I thought of giving it a try. As per the discussion there, I've created a SslContextCustomizer and used it in UndertowEmbeddedServletContainerFactory while setting up the builder. This should enable a user to customize the SSLContext very easily.

Please review and pull. My ICLA number is 149720151120072904.

Thanks,
Venil Noronha

### CODE REVIEW

**Comment by philwebb** [comment]
Cool, thanks! I wonder how easy it would be to get it working with Tomcat and Jetty as well?

**Comment by venilnoronha** [comment]
I'll add this support to tomcat and jetty too.

**Comment by venilnoronha** [comment]
I've created a similar customizers for Jetty and Tomcat named `JettySslContextFactoryCustomizer` and `TomcatSslProtocolCustomizer` respectively. @philwebb please review and let me know if it looks fine.

**Comment by philwebb** [comment]
Sweet! Thanks a lot, I'll take a look as soon as I can.

**Comment by venilnoronha** [comment]
@philwebb thank you!

**Comment by philwebb** [comment]
Unfortunately I don't think the customizer approach is going to work so well for SSL after all. Most of the existing customizers are applied in addition to anything that the `EmbeddedServletContainerFactory` does. With the SSL ones, this is not the case and I'm concerned that this might cause confusion. It also probably makes less sense to have multiple customizers for SSL.

I think ideally we should try to find a way for `Ssl` to accept some `Provider<KeyStore>` instances that could provide the trust store and key store. That would also allow complete parity across all the embedded servlet containers.

**Comment by venilnoronha** [comment]
Sounds fair. Shall i check the feasibility of having the `Provider<KeyStore>` in place? If it looks feasible I'll update the implementation as well.

**Comment by philwebb** [comment]
If you have time that would be fantastic. It looks like Jetty and Undertow should be fairly easy. Tomcat.... not so much :(

**Comment by venilnoronha** [comment]
Sure. I'll have a look. Thank you @philwebb for the review!

**Comment by venilnoronha** [comment]
I've updated the Ssl configuration implementation. Now, there's a `DynamicSsl` class which accepts `KeyStoreSupplier` instances, which in turn supply `KeyStore` instances. I've updated `ServerProperties` to use `DynamicSsl` instead of `Ssl` so that `KeyStoreSupplier`s are directly available to the `AbstractConfigurableEmbeddedServletContainer` on customization. A `DynamicSslConfigurerBeanPostProcessor` bean is registered to find `KeyStoreSupplier` beans from the `ApplicationContext` and set them to `AbstractConfigurableEmbeddedServletContainer`s `DynamicSsl` instances. `JettyEmbeddedServletContainerFactory` and `UndertowEmbeddedServletContainerFactory` then make use of the `KeyStore` instances supplied by these `KeyStoreSupplier`s during SSL configuration.

**Comment by venilnoronha** [comment]
I've updated the Ssl configuration implementation. Now, there's a `DynamicSsl` class which accepts `KeyStoreSupplier` instances, which in turn supply `KeyStore` instances. A `DynamicSslConfigurerBeanPostProcessor` bean is registered to find `KeyStoreSupplier` beans from the `ApplicationContext` and set them to `AbstractConfigurableEmbeddedServletContainer`s `DynamicSsl` instances. `JettyEmbeddedServletContainerFactory` and `UndertowEmbeddedServletContainerFactory` then make use of the `KeyStore` instances supplied by these `KeyStoreSupplier`s during SSL configuration.

@philwebb could you please review these changes. I'm planning to work on `TomcatEmbeddedServletContainerFactory` once I get a go ahead from you.

**Comment by venilnoronha** [comment]
I've updated the SSL configuration implementation. Now, `Ssl` accepts `KeyStoreSupplier` instances, which supply `KeyStore` instances. A `SslConfigurerBeanPostProcessor` bean is registered to find `KeyStoreSupplier` beans from the `ApplicationContext` and wire them to `Ssl` instances contained by `AbstractConfigurableEmbeddedServletContainer` beans. `JettyEmbeddedServletContainerFactory` and `UndertowEmbeddedServletContainerFactory` then make use of the `KeyStore` instances supplied by these `KeyStoreSupplier`s during SSL configuration.

@philwebb could you please review these changes. I'm planning to work on `TomcatEmbeddedServletContainerFactory` once I get a go ahead from you.

**Comment by venilnoronha** [comment]
I had some time so I put together a solution for Tomcat as well, it was a little tricky one though. Please review.

**Comment by philwebb** [comment]
Thanks for the PR, it was very helpful (especially the Tomcat stuff). In the end I've fixed this is a slightly different way (see b5679594826e7b609524bea1c4ac7806af62bd5a). Cheers!

**Comment by venilnoronha** [comment]
Thanks! I liked the use of tomcat `attributes`. :)

**Pull request closed without merging**
