### PR TITLE
GH-5340: Add Retry Config for RabbitTemplate and Listener

### LINKED ISSUE #5340: Add Retry Configuration to the RabbitTemplate Auto Configuration
If enabled, wire a `RetryTemplate` into the `RabbitTemplate`.

### PR DESCRIPTION
**Pull request by garyrussell**
Resolves #5340

### CODE REVIEW

**Comment by snicoll** [comment]
I am not super keen on adding a multi-words group (`publish-retry`). We have a group for the `listener`, maybe we need a group for the `sender`? (though sender may not be the right word for it).

Any insight @wilkinsona ?

**Comment by wilkinsona** [comment]
A group for the sender/publisher/template makes sense to me. In addition to the retry configuration, there are some other properties on `RabbitTemplate` that we might want to support at some point. I'm not sure what the name should be, though. Maybe `spring.rabbit.template`?

**Comment by garyrussell** [comment]
I made it `publish-retry` instead of just `retry` because you can also add a retry interceptor in the listener.

But, yes, there are other properties we could expose so `spring.rabbitmq.template.*` makes more sense.

I will rework it.

**Comment by snicoll** [comment]
`spring.rabbitmq.template.retry` may be a good candidate then. Thanks @garyrussell !

**Comment by garyrussell** [comment]
Reworked as discussed; also added retry to the listener config and a few more props.

**Pull request closed without merging**
