### PR TITLE
A slice annotation to test Cassandra components 

### PR DESCRIPTION
**Pull request by ayudovin**
this [enhancement](https://github.com/spring-projects/spring-boot/issues/16975)

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks very much for the PR, @ayudovin. As Phil said [here](https://github.com/spring-projects/spring-boot/issues/16975#issuecomment-497005353) we'd like to wait until we've tackled https://github.com/spring-projects/spring-boot/issues/16886 before implementing this. Your proposal still looks very useful, but we need to wait to see how things pan out with #16886 before making any necessary updates and merging it.

**Comment by ayudovin** [comment]
@wilkinsona ok, I have got it, no problem

**Comment by snicoll** [comment]
@ayudovin thanks again. I've rebased and polished the support in https://github.com/spring-projects/spring-boot/commit/313b2bef6fa396c16635914e1021f0af3418ee2c

**Comment by ayudovin** [comment]
@snicoll, thank you!

**Pull request closed without merging**
