### PR TITLE
Consider using %n which will produce a platform-specific line separator.

### PR DESCRIPTION
**Pull request by mnhock**
This format string include a newline character `\n`. consider using `%n`, which will produce the platform-specific line separator.

### CODE REVIEW

**Comment by philwebb** [comment]
Does the current `\n` format cause problems for you?

**Comment by mnhock** [comment]
No, I thought that it might be better for consistency.

**Comment by philwebb** [comment]
OK, thanks. I'll target this for 1.4 then just in case there are any unexpected side effects.

**Comment by mnhock** [comment]
Thanks!

**Pull request closed without merging**
