### PR TITLE
Add statsd autoconfiguration.

### PR DESCRIPTION
**Pull request by sbuettner**
This PR adds a simple autoconfiguration for the `StatsdMetricWriter`. Tests are included along with a short documentation. CLA has been signed: 133520150810110320

### CODE REVIEW

**Comment by snicoll** [comment]
Note to whoever merge this:  the root configuration namespace must be changed. Missing doc on configuration keys.

**Comment by tonyghita** [comment]
Looks good!

**Comment by philwebb** [comment]
Thanks for the contribution! I've reworked things a little to pull the code into the `MetricExportAutoConfiguration`. I've also moved the properties to use the `spring.metrics.export.statsd.*` key.

**Comment by sbuettner** [comment]
My pleasure.

**Pull request closed without merging**
