### PR TITLE
adding autoconfiguration for WebClient and OAuth2

### PR DESCRIPTION
**Pull request by ayudovin**
this [enhancement](https://github.com/spring-projects/spring-boot/issues/14352)

### CODE REVIEW

**Comment by ayudovin** [comment]
@philwebb, do you have any updates ?

**Comment by snicoll** [comment]
@ayudovin thanks for your patience. This PR is flagged `for: team meeting` which is happening next week so we'll cover it at that time.

**Comment by ayudovin** [comment]
@snicoll, no problem, thank you for your answer.

**Comment by bclozel** [comment]
#14352 has been declined so I'm closing this issue as a result.

Note that this PR needed more work:

* there was no `@ConditionalOnClass` that protects the auto-configuration; in its current form, applications without Spring Security would break with CNFEs.
* `WebClientOAuth2Customizer` is exposed publicly, it's not needed
* the `setDefaultOAuth2AuthorizedClient` option was enabled, whereas @rwinch said it shouldn't be

Thanks,

**Pull request closed without merging**
