### PR TITLE
Polish testsupport.junit.platform package

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

this is a polish PR for #17517 that's mostly updating copyright years, but also removes an unused method and its corresponding reflective wrapper.

Cheers,
Christoph

### CODE REVIEW

**Comment by philwebb** [comment]
Cool thanks. I guess my template is out of date.

**Comment by dreis2211** [comment]
That's the least I can do for your efforts today :)

**Comment by philwebb** [comment]
I'm kind of kicking myself for ignoring the error yesterday. I got that failure locally and just put it down to flaky internet, did `-fr` and continued the build.

**Comment by dreis2211** [comment]
Know that feeling...did so as well :/

**Pull request closed without merging**
