### PR TITLE
Add JUnit 4 and the Vintage Engine sample

### LINKED ISSUE #17070: Add a sample to verify the use of JUnit 4 and the Vintage Engine

### PR DESCRIPTION
**Pull request by ielatif**
This commit adds a sample to verify the use of JUnit 4 and the Vintage Engine.
Closes #17070.

### CODE REVIEW

**Comment by ielatif** [comment]
@philwebb @mbhave JUnit 5 checkstyle rules introduced in #17093 are applied to junit-vintage-sample which cause it to fail.
Any idea on how to disable only JUnit 5 checkstyle rules?

**Comment by ielatif** [comment]
May be add a suppression for SampleJunitVintageApplicationTests in checkstyle-suppressions.xml?

**Comment by wilkinsona** [comment]
@ielatif Yes, I think that's the right approach.

**Comment by ielatif** [comment]
@wilkinsona raised this [PR](https://github.com/spring-projects/spring-boot/pull/17106) to fix CI build failure

**Comment by snicoll** [comment]
@ielatif thanks for the PR. I've polished in two main areas:

1. I think what we want is to show that adding the starter with no further modification allows us to run a Junit 4-based test and the exclusions could potentially hide a problem. I've removed them
2. There is no need to start an embedded web server for such a sample so I rewrote the test to use mock MVC.

**Comment by ielatif** [comment]
@snicoll 
> 1. I think what we want is to show that adding the starter with no further modification allows us to run a Junit 4-based test and the exclusions could potentially hide a problem. I've removed them

Totaly agree 👍 


> 2\. There is no need to start an embedded web server for such a sample so I rewrote the test to use mock MVC.

I was thinking of the sample as a sample application (application running an embedded web server) and not as a smoke test like @philwebb mentioned in a newly raised feature.

**Pull request closed without merging**
