### PR TITLE
Minor enhancements to KotlinConstructorParametersBinderTests

### PR DESCRIPTION
**Pull request by katielevy1**
KotlinConstructorParametersBinderTests: 
- Minor enhancements to unit tests
   - Add new constructor for `MockConfigurationPropertySource` with map of configs
   - Inside of `KotlinConstructorParametersBinderTests`, create instances of `MockConfigurationPropertySource` with a map of configs
   - Use Kotlin property access on objects when possible
   - Assert against a whole expected object when validating a data class rather than individual properties of the object (`isEquals()` function is built into the data class)
- Added test case to Kotlin singleton object

Testing:
- Ran `./gradlew :spring-boot-project:spring-boot:test` on project with all tests succeeding

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@katielevy1 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=25532)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=25532) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by snicoll** [comment]
@katielevy1 thanks for the PR. Would you mind signing the CLA please.

**Comment by snicoll** [comment]
@katielevy1 how is it going? Sorry but we can't merge this PR until you sign the CLA.

**Comment by katielevy1** [comment]
@snicoll apologies for the delay! I'm working with my company's legal team to get approval to sign the CLA, it is taking longer than I expected.

**Comment by snicoll** [comment]
@katielevy1 Hi there. Any news?

**Comment by pivotal-issuemaster** [comment]
@katielevy1 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=25532)!

**Comment by katielevy1** [comment]
@snicoll finally got the thumbs up from legal, I just signed the contributor agreement!

**Comment by snicoll** [comment]
@katielevy1 thank you for making your first contribution to Spring Boot. I've polished things a bit in bac1016.

**Pull request closed without merging**
