### PR TITLE
#3009 :  Spring Mobile auto-configuration should configure AbstractDe…

### PR DESCRIPTION
**Pull request by yacota**
About changes : Although I have very few changes the whole file is replaced in github :|
I have not found any code formatter file for Netbeans in https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc

### CODE REVIEW

**Comment by snicoll** [comment]
Yeah, I don't really understand what happened but  please force push a change that only adds the code you changed. If there is a formatting issue we can deal with that.

**Comment by philwebb** [comment]
@yacota have you signed the CLA?

**Comment by yacota** [comment]
@philwebb Yes, the id is 121620150519031801

**Comment by philwebb** [comment]
Fixed in bd6f7a589c2f5ed1447c47be9fb5043298baeaf5

**Pull request closed without merging**
