### PR TITLE
Upgrade to Jersey 2.25

### PR DESCRIPTION
**Pull request by Dichotomia**

### CODE REVIEW

**Comment by snicoll** [comment]
Should have been more careful, this upgrade fails the build.

**Comment by Dichotomia** [comment]
The maven plugin seems to crash. Maybe we could launch the build with -X option
 [ERROR] Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.15:check (enforce-java-6) on project spring-boot-autoconfigure: Execution enforce-java-6 of goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.15:check failed. IllegalArgumentException -> [Help 1]

**Comment by Dichotomia** [comment]
Ok. Do you have the corresponding stack trace?

**Comment by wilkinsona** [comment]
The problem appears to be with ASM:

```
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.codehaus.mojo.animal_sniffer.ClassListBuilder.process(ClassListBuilder.java:71)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processJarFile(ClassFileVisitor.java:153)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:105)
	at org.codehaus.mojo.animal_sniffer.maven.CheckSignatureMojo.apply(CheckSignatureMojo.java:377)
	at org.codehaus.mojo.animal_sniffer.maven.CheckSignatureMojo.buildPackageList(CheckSignatureMojo.java:324)
	at org.codehaus.mojo.animal_sniffer.maven.CheckSignatureMojo.execute(CheckSignatureMojo.java:227)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

Animal Sniffer uses 5.0.3 by default. I've tried overriding the plugin's dependencies to use 5.0.4 but the same failure occurs.

**Comment by Dichotomia** [comment]
Thanks a lot for your work. I'm sorry that I hadn't time to investigate more.

**Pull request closed without merging**
