### PR TITLE
StartupInfoLogger should log version of more Spring project

### LINKED ISSUE #27: StartupInfoLogger should log version of more Spring project
Currently StartupInfoLoggerm only logs information on the Spring Boot and Spring Framework version. Would be nice if the versions of all used Spring portfolio products would be logged (Spring Batch, Spring Data (JPA), Spring Security etc.).

### PR DESCRIPTION
**Pull request by arnosthavelka**
I have prepared fix #27 to show (when configured) versions for all spring projects/libraries except Spring Boot (which is logged by default).

This feature is triggered by configuration `spring.main.show_versions` and it is by default disabled.

What's missing (when approved):
1. update documentation
2. update STS YML plugin to know such configuration item

### CODE REVIEW

**Comment by snicoll** [comment]
For the record since this is the second time that I see "update STS YML plugin to know such configuration item", there is nothing to update in STS. STS and other IDEs are driven by some meta-data that we generate at build time. Most are discovered automatically and we can also write the meta-data by hand for corner cases. See [this example](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L82) for an example.

**Comment by arnosthavelka** [comment]
Thanks for your information. I just fix it since it's so easy :-).

**Comment by arnosthavelka** [comment]
BTW. I forgot to mention the solution which is:
* read all manifests from spring package (exclude spring boot)
* when title is not known (several spring projects) than the version is deduced from URL (when is part of JAR) otherwise the project is skipped.

I believe it works sufficient (since manifests are not same for all spring projects).

**Comment by snicoll** [comment]
Thanks but we're not keen on reading the content of `manifest.mf` to figure out that information.

**Pull request closed without merging**
