### PR TITLE
Make locations list mutable in Flyway configuration file

### LINKED ISSUE #4972: FlywayProperties locations list is not mutable
The member `locations` in `FlywayProperties` is initialized as immutable and can't be modified by configuration file, it currently throws a `java.lang.UnsupportedOperationException` when trying to inject other location values in a yml configuration file.

### PR DESCRIPTION
**Pull request by jebeaudet**
This PR fixes #4972.

I've signed the contributor's agreement. Thanks!

### CODE REVIEW

**Comment by snicoll** [comment]
Would you mind adding the missing test please? Bear in mind that we have a release coming up Thursday and I'd like to merge this before. Thanks!

**Comment by jebeaudet** [comment]
No problem, I'll send this today.

**Comment by jebeaudet** [comment]
Good thing you made me look after the test, I blindly assumed that making the type mutable would solve the problem. 
I spent a good part of the day debugging this as I would get the following exception when trying to inject a list of locations (irrelevant parts removed) : 
```
Caused by: org.springframework.validation.BindException: org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanPropertyBindingResult: 1 errors
Field error in object 'flyway' on field 'locations': rejected value [classpath:db/migration,null]; codes [methodInvocation.flyway.locations,methodInvocation.locations,methodInvocation.[Ljava.lang.String;,methodInvocation]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [flyway.locations,locations]; arguments []; default message [locations]]; default message [Property 'locations' threw exception; nested exception is java.lang.NullPointerException]
	at org.springframework.boot.bind.PropertiesConfigurationFactory.validate(PropertiesConfigurationFactory.java:362) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:271) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:241) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:320) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	... 33 common frames omitted
```

I think the problem lies in the fact that the getter of the Flyway `locations` doesn't return a mutable object but an `String[]` but I'm not entirely sure. Explicitly setting it in `FlywayAutoConfiguration` solves the problem and doesn't break the any functionality. Hopefully it's fine for you, if you have the exact explanation as to why the `@ConfigurationProperties` fails for this property, I'd be glad to hear it.

Thanks!

**Comment by snicoll** [comment]
Yes, you are right. [See this comment for more details](https://github.com/spring-projects/spring-boot/issues/3659#issuecomment-173561580)

**Comment by snicoll** [comment]
Thanks for the PR, I have polished your proposal in https://github.com/spring-projects/spring-boot/commit/58ebfdcbd329658300e383b4582d8cd741ddfc5b (basically keep two separate tests since this particular property is a bit special at the moment).

**Pull request closed without merging**
