### PR TITLE
Similar guide links related to not found guide links

### PR DESCRIPTION
**Pull request by IMWoo94**
Version : [Spring Boot 3.3.4 Reference Doc.](https://docs.spring.io/spring-boot/index.html)

Changed the Not Found link provided in the Reference Doc to a link covering the Build Plugin.

The reference Doc already provides a direct content to Jar and War. I think it would create better synergy if you provided a link to the Build Tool rather than providing a removed guide.

Reference Doc : https://docs.spring.io/spring-boot/how-to/deployment/traditional-deployment.html#howto.traditional-deployment.convert-existing-application

Not Found Link : [Getting Started Guide on Converting a jar to a war.]( https://spring.io/guides/gs/convert-jar-to-war/ )

Suggest Link : [Build Tool Plugins](https://docs.spring.io/spring-boot/build-tool-plugin/index.html)

스크린샷 2024-10-15 오후 8 41 11

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks for the PR.

The guide has been dropped so this looks like an oversight, see https://github.com/spring-projects/spring-boot/issues/42110

**Comment by IMWoo94** [comment]
Thank you for finding the issue

The current PR provides a new link, but can I delete it and rewrite it with the code that's been removed?

**Comment by philwebb** [comment]
Thanks for the PR. I don't think we should reproduce the code from the old guide, but we should update the link when we merge this. It should be `xref:build-tool-plugin:index.adoc[]`

**Comment by IMWoo94** [comment]
Update can be carried out in two ways.

1. "See the Getting Started Guide on Converting a jar to a war." 문구 삭제
2. Modify links using xref:build-tool-plugin:index.adoc[]

#42110 and the comments
Number 2 provides the same link using xref:build-tool-plugin:index.adoc[] at the top.
This is overlapping, and I think option 2 is ambiguous because it is located not far away.

I think option 1 is correct.
Which of the two options do you think is more correct?

**Comment by philwebb** [comment]
Thanks @IMWoo94

**Pull request closed without merging**
