### PR TITLE
Autoconfigure Jersey Server Metrics in a JAX-RS environment

### PR DESCRIPTION
**Pull request by michael-simons**
This PR implements #12904 by 

* Adding micrometer-jersey2 to Spring Boots dependency management
* Extracting the necessary autoconfiguration code from the "legacy"-module (i.e. https://github.com/micrometer-metrics/micrometer/tree/master/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/jersey2/server)
* Adding some tests and documentation for the new feature.

### CODE REVIEW

**Comment by shakuzen** [comment]
Looks like this might duplicate the efforts in #12482

**Comment by michael-simons** [comment]
Yep. My search foo wasn’t good.

**Comment by michael-simons** [comment]
It might be a good idea to copy some aspects of each PR after a quick check. I wouldn’t duplicate the properties for example and you have more tests.

**Comment by wilkinsona** [comment]
Thank you, @michael-simons. We'll go ahead with #12482, modified to list you as a co-author.

**Pull request closed without merging**
