### PR TITLE
Check url inside the jar

### PR DESCRIPTION
**Pull request by fogone**
In case when url created from absolute path like '/some/path/', url parser replace jar-url with absolute path so code works incorrectly.

### CODE REVIEW

**Comment by philwebb** [comment]
@fogone can you provide a little more background for this change?

**Comment by fogone** [comment]
Struts 2 use `com.opensymphony.xwork2.util.ClassLoaderUtil#getResources` method which add slash at begin of path (for example `org/spring/someresource` translate to `/org/spring/someresource`). Url constructor `URL(context, spec)` (`sun.misc.URLClassPath.Loader#findResource` calls it) replace any path to global one (example: context: `file://some/path!/inside/jar` spec: `/org/spring/someresource` creates `file://org/spring/someresource` url). This url comes to `org.springframework.boot.loader.jar.JarURLConnection` constructor and next code
```
String spec = url.getFile().substring(jarFile.getUrl().getFile().length());
```
works incorrectly, because `jarFile.getUrl().getFile()` is not a substring of `url.getFile()`. In rarely cases `spec` is valid resource and `getResource` doesn't return null. 

My fix check only for `!/` (same as in `java.net.JarURLConnection#parseSpecs`), but maybe it needs check like
```
url.getFile().contains(jarFile.getUrl().getFile())
```
to sure that you trying load resource from passed `JarFile`.

p.s. sorry for my english

**Comment by pivotal-issuemaster** [comment]
@fogone Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=3963) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@fogone Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=3963)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=3963) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Pull request closed without merging**
