### PR TITLE
Add smoke tests for Spring Session Redis/Mongo

### PR DESCRIPTION
**Pull request by avillalain**
Add smoke tests that verify the correct behavior of the sessions
endpoint when using Spring Session with MongoDB and Redis.

See gh-28291

### CODE REVIEW

**Comment by mbhave** [comment]
Thanks @vpavic! I'd forgotten about that issue!

**Comment by avillalain** [comment]
Thanks @mbhave for all the feedback provided, I finished updating the PR. It is now using test containers.

Quick question @vpavic is the issue you mentioned something complicated, would it be a suitable first timer kind of issue? I basically am fishing for another issue considering this is done in case there are no additional feedback. 

@mbhave In case the issue is not suitable for a first timer, what could be another issue I could grab? 

Thanks for your help and support

**Comment by avillalain** [comment]
Is the Spring Session issue one that a newbie can work on? I might be interested on that one if possible since it's related, and I feel want to close the loop on the web session smoke tests :)

**Comment by mbhave** [comment]
@avillalain It would be better to ask on the Spring Session issue tracker and the Spring Session team can guide you from there.

**Comment by mbhave** [comment]
@avillalain Thanks for making your first contribution to Spring Boot. This has been merged into `main` along with a minor [polish commit](https://github.com/spring-projects/spring-boot/commit/2caa6cb227bea18be90aadf940b49768202d4bc3).

**Pull request closed without merging**
