### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by eximius313**
Upgrade Mockito and AssertJ to newest versions

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@eximius313 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=14268)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=14268) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by eximius313** [comment]
Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@eximius313 This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by snicoll** [comment]
@eximius313 thank for the PR but we don't accept dependency upgrades PR as we have a semi-automated process that takes care of them.

Also, please note our policy for maintenance releases is to only update to bugfix releases of third party dependencies. These feature upgrades will be available in Spring Boot 2.1

**Pull request closed without merging**
