### PR TITLE
Add reference to XChange starter

### PR DESCRIPTION
**Pull request by straumat**
I updated to spring boot starter list to add a spring boot starter we made for [XChange](https://github.com/knowm/XChange).

Our project : [https://github.com/cassandre-tech/cassandre-trading-bot](https://github.com/cassandre-tech/cassandre-trading-bot)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@straumat Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20830)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20830) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@straumat Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20830)!

**Comment by snicoll** [comment]
@straumat I had a quick look and create a couple of issues, can you please look at them?

**Comment by straumat** [comment]
@snicoll i'm sorry but i don't see where are the issues ? where should i read them ? Thx and sorry

**Comment by snicoll** [comment]
> @snicoll i'm sorry but i don't see where are the issues ? where should i read them ? Thx and sorry

In your project.

**Comment by straumat** [comment]
I don't see anything :(

**Comment by bclozel** [comment]
@straumat See https://github.com/cassandre-tech/cassandre-trading-bot/issues/91 and https://github.com/cassandre-tech/cassandre-trading-bot/issues/92

**Comment by straumat** [comment]
I'm sorry, I had no notifications for the issues. I fixed them both.

**Pull request closed without merging**
