### PR TITLE
Add configuration property for Tomcat's rejectIllegalHeader

### PR DESCRIPTION
**Pull request by dbyron-sf**
to make it easy to control without adding a TomcatConnectorCustomizer

Related to https://github.com/spring-projects/spring-boot/issues/22081

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dbyron-sf Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=26311)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=26311) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by dbyron-sf** [comment]
I signed the contributor license agreement a few hours ago, but even after syncing a few different times, the PR check is still failing.

**Comment by snicoll** [comment]
@dbyron-sf thanks for the PR and signing the CLA. This is odd, it should synchronize but that doesn't seem to be the case. @rwinch can you help us out please?

**Comment by rwinch** [comment]
@dbyron-sf I've checked and the tooling does not think you have signed the CLA yet. Can you provide me detailed steps on how you signed the CLA?

**Comment by dbyron-sf** [comment]
I went to https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=26311, clicked "Sign Corporate CLA", populated the fields, checked the "I have read and agree to the terms and conditions" checkbox, and clicked "Submit and Contribute."  I'm happy to do that again if those are the right steps.

**Comment by dbyron-sf** [comment]
I took a leap and followed re-submitted the corporate CLA.  I ended up back at https://cla.pivotal.io/#sign-form.  I tried syncing the PR again, but still no dice.  Sorry to be a bother.  Can you take another look please @rwinch? Thank you.

**Comment by rwinch** [comment]
@dbyron-sf There is something strange happening. It doesn't let you sign the CLA twice, so that is an indicator that the signature hasn't been registered. I looked and I do not see a corporate signature from you nor do I see an individual signature.

> I took a leap and re-submitted the corporate CLA. I ended up back at https://cla.pivotal.io/#sign-form. 

Were there any messages when you got to this point?

Note that I'd expect you to try and sign the individual CLA unless you are "representing a company wanting its employees to contribute".

**Comment by pivotal-issuemaster** [comment]
@dbyron-sf Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=26311)!

**Comment by dbyron-sf** [comment]
> Were there any messages when you got to this point?

Nope.  I clicked "Submit and Contribute" and went directly back to https://cla.pivotal.io/#sign-form with no other messages.  Perhaps important...I left the Github Organization field blank?

> Note that I'd expect you to try and sign the individual CLA unless you are "representing a company wanting its employees to contribute".

Fair enough.  I'm doing this on company time, so I figured the corporate CLA was the way to go.  I just completed the individual CLA.

**Comment by ooberuser** [comment]
Glad you got it working through the individual contributor.

If you are doing it on company time, you should work out with your company on if/how to sign the agreement. However, as described next to the button, you should not sign a corporate CLA unless you represent the entire or large group of the company. 

I double checked and submitting the form completely filled out except for GitHub organization results in being sent to https://cla.pivotal.io/sign/pivotal/ccla#sign-form The form indicates the GitHub organization is required. 

image

There is also a [test](https://github.com/pivotalsoftware/pivotal-cla/blob/b53fd3ec0aff22a3d9278d71f23c1cb320d3d136/src/test/java/io/pivotal/cla/webdriver/CclaControllerTests.java#L283) that verifies the code is working. Without more information I don't think I'll be able to make any changes to solve the problem you explained.

In any case, I'm glad you were able to sign the form and get past the CLA.

**Comment by rwinch** [comment]
Glad you got it working through the individual contributor.

If you are doing it on company time, you should work out with your company on if/how to sign the agreement. However, as described next to the button, you should not sign a corporate CLA unless you represent the entire or large group of the company. 

I double checked and submitting the form completely filled out except for GitHub organization results in me correctly being sent to https://cla.pivotal.io/sign/pivotal/ccla#sign-form This appears different that the URL you provided. The form indicates the GitHub organization is required. 

image

There is also a [test](https://github.com/pivotalsoftware/pivotal-cla/blob/b53fd3ec0aff22a3d9278d71f23c1cb320d3d136/src/test/java/io/pivotal/cla/webdriver/CclaControllerTests.java#L283) that verifies the code is working. Without more information I don't think I'll be able to make any changes to solve the problem you explained.

In any case, I'm glad you were able to sign the form and get past the CLA.

**Comment by dbyron-sf** [comment]
Yeah, I'm not sure why it let me through without filling in the github org...but I think I'm going to let that be a mystery.

Thanks for all of your help.  I think we're now beyond the administrative hurdles and with any luck someone can take a look at the guts of the PR from here.

**Comment by snicoll** [comment]
Perhaps because you're not part of any org? If we want to continue investigating, let's do that on a dedicated issue on the CLA issue tracker.

**Comment by snicoll** [comment]
Nope we're all good now that you've signed the CLA properly.

**Review by snicoll — APPROVED** [review]

**Comment by dbyron-sf** [comment]
Thanks for merging!

**Comment by snicoll** [comment]
It's not merged yet. I reviewed it pending the availability of a 2.6.x build.

**Comment by dbyron-sf** [comment]
Aaah, ok.

**Comment by snicoll** [comment]
@dbyron-sf thank you for making your first contribution to Spring Boot.

**Pull request closed without merging**
