### PR TITLE
Package name and class location mismatch

### PR DESCRIPTION
**Pull request by PiyalAhmed**
The class location and the package name should be the same.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks, @PiyalAhmed. Reviewing this has made me realise that we have a broader problem as none of the Kotlin code examples in the Testing section are showing up. I've opened https://github.com/spring-projects/spring-boot/issues/42094 to address that.

**Comment by PiyalAhmed** [comment]
> Thanks, @PiyalAhmed. Reviewing this has made me realise that we have a broader problem as none of the Kotlin code examples in the Testing section are showing up. I've opened #42094 to address that.

Thanks, I have already noticed that and was investigating. I would love to submit a PR for including Kotlin code examples in the Testing section.

**Comment by wilkinsona** [comment]
Thank you for the offer but I've just taken care of it in https://github.com/spring-projects/spring-boot/commit/d2f0b2b0903f4286f7cd66def5cce82f005de9fc.

**Comment by PiyalAhmed** [comment]
> Thank you for the offer but I've just taken care of it in [d2f0b2b](https://github.com/spring-projects/spring-boot/commit/d2f0b2b0903f4286f7cd66def5cce82f005de9fc).

Cool. No problem at all. Thank you again.

**Pull request closed without merging**
