### PR TITLE
Replace calls to verifyComplete() with expectComplete().verify(Duration) to avoid blocking indefinitely

### PR DESCRIPTION
**Pull request by ThomazPassarelli**
This pull request addresses the issue #35791, where it was required to replace `verifyComplete()` with `expectComplete().verify(Duration)` in test cases across multiple files. 

Changes made:

1. Replaced `verifyComplete()` with `expectComplete().verify(Duration.ofSeconds(5))` in all the necessary places. The decision to use `Duration.ofSeconds(5)` was influenced by its existing usage in another part of the project, ensuring consistency across the codebase.
2. Added `import java.time.Duration;` where it was not already imported.

I have successfully made changes to 23 files and built the project without any errors. All the tests ran successfully after the changes.

### CODE REVIEW

**Comment by philwebb** [comment]
When we merge this we should also consider this comment from the original issue:

> We should also consider introducing an ArchUnit rule to prevent usage of verifyComplete() from being reintroduced.

**Comment by wilkinsona** [comment]
I've got one locally.

We should also remove any calls to `StepVerifier.setDefaultTimeout` as they're unnecessary when using `expectedComplete().verify(Duration)` everywhere.

**Comment by wilkinsona** [comment]
@ThomazPassarelli can you please [sign the CLA](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=35915) when you have a moment?

**Comment by wilkinsona** [comment]
Thanks very much, @ThomazPassarelli.

**Pull request closed without merging**
