### PR TITLE
update starter doc for add teiid spring boot starter link

### PR DESCRIPTION
**Pull request by kylinsoong**
Base on Spring boot document [1] and another JBoss project infinispan [2], teiid developer has develop a Teiid Spring Boot Starter [3]. This PR is for **add a link to spring boot starter readme**.

[1] http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter
[2] https://github.com/infinispan/infinispan-spring-boot
[3] https://github.com/teiid/teiid-spring-boot

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kylinsoong Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9281)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9281) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by snicoll** [comment]
@pivotal-issuemaster this is an obvious fix

**Comment by pivotal-issuemaster** [comment]
@kylinsoong Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9281)!

**Comment by pivotal-issuemaster** [comment]
@kylinsoong Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9281)!

**Comment by pivotal-issuemaster** [comment]
@kylinsoong Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9281)!

**Comment by snicoll** [comment]
@kylinsoong I've reported [a few issues](https://github.com/teiid/teiid-spring-boot/issues/created_by/snicoll), let's see how it goes there.

**Comment by kylinsoong** [comment]
Thanks @snicoll , I am looking to

**Pull request closed without merging**
