### PR TITLE
@ConfigurationPropertiesScan should import ConfigurationPropertiesBindingPostProcessorRegistrar

### PR DESCRIPTION
**Pull request by ayudovin**
this [task](https://github.com/spring-projects/spring-boot/issues/16822)

### CODE REVIEW

**Comment by mbhave** [comment]
If there is a [framework change](https://github.com/spring-projects/spring-framework/issues/22995) that allows `@ConfigurationProperties` to be scanned by component scanning, we will not need the custom scanning feature. Placing this on hold till that's decided.

**Comment by ayudovin** [comment]
@snicoll, I'm not sure what I need to check by a test. Could you please provide a little bit more details or something which can help me? I'd appreciate it.

**Comment by snicoll** [comment]
Thanks for the feedback. What I had in mind is a test that showcases the situation that @mbhave has described in the related issue. So a simple context with no auto-configuration at all and just `@ConfigurationPropertiesScan` should not bind a scanned object without your fix. Then you should apply it and validate the test passes.

Let me know if you have another question.

**Comment by snicoll** [comment]
Thank you for the PR @ayudovin but I've started to work on a test and will follow-up on the original issue.

**Comment by ayudovin** [comment]
@snicoll, ok, no problem, sorry for it, I just could not find the time.

**Pull request closed without merging**
