### PR TITLE
Add reference to Oracle Spring Boot Starters

### PR DESCRIPTION
**Pull request by markxnelson**
Hi Spring Boot team,

This PR adds links to the Spring Boot Starter Community page for Oracle-written starters for cloud, Coherence and database.  Thank you for adding our starters to your community directory.  We have about eight so far, but are continuing to invest in creating more to continue to make it easy for Spring Boot users to consume Oracle products and services. 

Mark Nelson, Architect/Developer Evangelist - Oracle

### CODE REVIEW

**Comment by markxnelson** [comment]
I read the CLA FAQ, and I am not sure if a CLA is requried here - could you please advise if this would fall under the category of an "obvious fix"?  Or has Oracle already signed the CLA? Thanks

**Comment by markxnelson** [comment]
Thanks, I am checking on my end, and will get back to you soon.

**Comment by markxnelson** [comment]
Hi @wilkinsona - yes I got all the necessary approvals and so on, I am just waiting for a person with signing authority (as required by the CLA) to sign it for us.  Hopefully will be completed in the next few days.  Thanks for your patience.

**Comment by markxnelson** [comment]
Hi @wilkinsona - the CLA is signed now, but it is still telling me to sign it in the PR.

image

**Comment by wilkinsona** [comment]
Thanks, @markxnelson. I've managed to shake it loose and everything's in sync now.

**Comment by wilkinsona** [comment]
Thanks for making your first contribution to Spring Boot, @markxnelson.

**Pull request closed without merging**
