### PR TITLE
Update to Infinispan 9.4.0.Final

### PR DESCRIPTION
**Pull request by galderz**
Upgrade master (2.1.x) to Infinispan 9.4.0.Final. This is highly recommended for Hibernate 5.3 users.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR but, as noted in the pull request template, please do not open a pull request for a straightforward dependency upgrade (one that only updates the version property). We have a semi-automated process for such upgrades that we prefer to use. However, if the upgrade is more involved (such as requiring changes for removed or deprecated API) your pull request is most welcome.

**Comment by galderz** [comment]
@wilkinsona Right, but you don't explain how to make sure you don't slip up and forget to make the upgrade. How can we make sure your semi automated process will pick it up?

**Comment by galderz** [comment]
Besides, what guarantees do we have that the next 2.1 release will contain the updated dependency?

**Comment by wilkinsona** [comment]
We've successfully [upgraded Inifinispan 15 times](https://github.com/spring-projects/spring-boot/issues?q=is%3Aissue+Upgrade+to+Infinispan+label%3A%22type%3A+dependency-upgrade%22) so I'm confident that our process works.

**Pull request closed without merging**
