### PR TITLE
Deprecate DelegatingApplicationContextInitializer and DelegatingApplicationListener in favour of registering each delegate programatically or in spring.factories

### PR DESCRIPTION
**Pull request by bbulgarelli**
This PR is related to the issue #34779. I did what the issue suggested and deprecated `DelegatingApplicationContextInitializer` and `DelegatingApplicationListener`.

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks for the PR. We usually also add `@Deprecated` javadoc in the form described [here](https://github.com/spring-projects/spring-boot/wiki/Deprecations). We probably want something like "@deprecated since 3.2 for removal in 3.5 as property based initialization is not longer recommended".

**Comment by wilkinsona** [comment]
We also use the `since` and `forRemoval` attributes on `@Deprecated`:

```
@Deprecated(since = "3.2.0", forRemoval = true)
```

**Comment by bbulgarelli** [comment]
> @bbulgarelli can you please run the build before submitting a pull request? 
Sorry about that. I tried to run it this time, but I still got warnings related to the test classes, even though I already added the deprecation annotation to both test classes. I'm not sure what I'm doing wrong.


> We probably want something like `@deprecated since 3.2 for removal in 3.4 as property based initialization is not longer recommended`
OK. I added this to both the deprecated classes and the test classes.

**Comment by snicoll** [comment]
Thanks @bbulgarelli, I've polished your contribution in [60df7e3](https://github.com/spring-projects/spring-boot/commit/60df7e3bce6873a21351e2164e835233c7e3159f).

**Comment by izeye** [comment]
> We also use the `since` and `forRemoval` attributes on `@Deprecated`:
> 
> ```
> @Deprecated(since = "3.2.0", forRemoval = true)
> ```

It would be nice if it's also documented in [the "Deprecations" section](https://github.com/spring-projects/spring-boot/wiki/Deprecations) in the wiki.

**Comment by snicoll** [comment]
Thanks @izeye, I've updated the wiki.

**Comment by rishiraj88** [comment]
Nice idea, @izeye

**Pull request closed without merging**
