### PR TITLE
Fixes gh-3815

### PR DESCRIPTION
**Pull request by mrumpf**
I understand that Launcher diagnosis is currently based upon a logging framework that is part of the JDK, because there is no chance to add other logging frameworks easily.
Because Launcher diagnostics output is not relevant to application logging, my assumption is that dumping any information to STDERR is sufficient here (following the Cloud Native Application approach, this should probably be changed to STDOUT). So, when something is wrong with application startup, you can turn on debug mode and get the Launcher diagnostic messages at STDERR (STDOUT). Then, when the application provided logging framework gets initialized, the application is free to configure redirection for all logging frameworks, used by the application.

See https://github.com/spring-projects/spring-boot/issues/3815

I could not run the test-suite the usual way, see https://github.com/spring-projects/spring-boot/issues/3816

### CODE REVIEW

**Comment by mrumpf** [comment]
Another issue with running the full build is with Maven 3.3.3+:
https://issues.apache.org/jira/browse/MNG-5792
I had to switch back to Maven 3.2.1

**Comment by wilkinsona** [comment]
Thanks for the PR. I'm in favour of the end goal (removing the use of JUL from the launcher), but I'm not sure about the approach that you have taken. My main objection is the loss of control, for example there are a number of places where info logging will now only be produced when debug is enabled.

I haven't looked in detail to be sure that it will work, but I think we should explore an approach similar to [`DeferredLog`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/logging/DeferredLog.java) to address #3815.

**Comment by mrumpf** [comment]
For the JarLauncher and WarLauncher the parent class Launcher only declared the logger, but neither of those classes did any logging. The PropertiesLauncher set the log level to SEVERE if the debug flag was not set. So there was no INFO logging printed at all.
That was the reason why I've chosen the approach to dump only one level to STDERR when the debug flag is set.
But I agree with you that a feature to defer logging until everything is in place is a better approach.
I did not know the class "DeferredLog" but I will have a look and try to use it for the Launcher logging...

**Comment by mrumpf** [comment]
OK, I have reverted the changes now and I'm looking into using DeferredLog. The issue with that is that the stored log statements need to be replayed, once the logging sub-system has been fully initialized.
That means there must be
* either a Spring Bean which registers as ApplicationListener for context load events (see org.springframework.boot.context.config.ConfigFileEnvironmentPostProcessor)
* or a kind of DeferredLogRegistry where all deferred logs can be found and which iterates over all DeferredLog instances to replay the stored entries.

All the Launcher logic gets executed before an Spring application context starts, so I would assume the latter way to be the right choice, but because I'm relatively new to Spring I better discuss that first.

So, I would suggest having a DeferredLogRegistry where you could
* getDeferredLog - which stores a reference to the created DeferredLog instance in a list
* replayAll - which goes through all stored log entries and brings them in the right order when replaying  to an actual logger.

**Comment by wilkinsona** [comment]
@mrumpf Thanks for looking into it.

This problem is complicated by there being two class loader's involved – the one that loads the launcher classes and the one created by the launcher that can see all of the application classes and dependencies. We could avoid this complication by moving `DeferredLog` into a location where it's only loaded by the app class loader but we don't have any other code where that's the case so I've yet to convince myself that it's a good idea.

The Boot team are all a bit swamped with finishing off 1.3 and preparing for SpringOne so it might take us a little while to discuss and agree on the best course of action here.

**Comment by mrumpf** [comment]
I see the following phases:
1. Launcher Phase
Sets up the application classloader and invokes the Main-Class
2. Application Phase (Main-Class Invocation)
This is where all the Spring Framework and Spring Boot Auto-Configuration magic takes place.

In the first "Launcher Phase" we need to make sure not to use any logging frameworks to avoid the issues with accidentally configuring them (see JDK Logging init). Instead use something like DeferredLog.
In the second "Application Phase" the Spring Framework launches and it uses commons-logging internally. The logging-sub-system initialization needs to take place in a very early stage of the second phase because we do not know in advance what happens in the auto-configuration code. To prevent the auto-configuration logic to initialize JDK logging before Spring Boot initializes the JUL redirection, the logging sub-system must be initialized as the very first step.

My current impression is that we might need to add another redirection before starting the Spring Boot application:

    package com.company.app;

    import org.apache.log4j.LogManager;
    import org.springframework.boot.SpringApplication;

    /**
     * This class makes sure that the logging-subsystem gets initialized first.
     *
     * @author mrumpf
     */
    public class MySpringBootApplication {
        
        public static void run(Class<?> clazz, String[] args) {
            // Make sure Hibernate's internal logging uses SLF4J (and thus Log4j2)
            System.setProperty("org.jboss.logging.provider", "slf4j");
            // Make sure that the Tomcat Logging gets redirected
            System.setProperty("org.apache.juli.logging.diagnostics.dest", "STDERR");
            System.setProperty("org.apache.juli.logging.Log", "org.apache.juli.logging.impl.Log4JLogger");

            // JUL initialization must be done first
            initJul();
            initJcl();
            initSlf4j();
            initLog4j1();
            initLog4j2();

            SpringApplication.run(clazz, args);
        }

        private static void initLog4j2() {
            org.apache.logging.log4j.Logger log4j2Logger = org.apache.logging.log4j.LogManager
                    .getLogger(MySpringBootApplication.class);
            log4j2Logger.info("org.apache.logging.log4j.Logger: INFO");
        }

        private static void initSlf4j() {
            org.slf4j.Logger slf4jLogger = org.slf4j.LoggerFactory.getLogger(MySpringBootApplication.class);
            slf4jLogger.info("org.slf4j.Logger: INFO");
        }

        private static void initLog4j1() {
            try {
                Class.forName("org.apache.log4j.SimpleLayout");
                throw new LoggingAutoConfigurationException(
                        "It seems as if a Log4j 1.x JAR is on the classpath! Please make sure to exclude all Log4j 1.x JARs");
            } catch (ClassNotFoundException e) {
                // we expect not to find this class
            }

            org.apache.log4j.Logger log4jLogger = LogManager.getLogger(MySpringBootApplication.class);
            log4jLogger.info("org.apache.log4j.Logger: INFO");
        }

        private static void initJul() {
            System.setProperty("java.util.logging.manager", "org.apache.logging.log4j.jul.LogManager");

            java.util.logging.Logger julLogger = java.util.logging.Logger
                    .getLogger(MySpringBootApplication.class.getName());
            julLogger.info("java.util.logging.Logger: INFO");
        }

        private static void initJcl() {
            org.apache.commons.logging.Log jclLogger = org.apache.commons.logging.LogFactory
                    .getLog(MySpringBootApplication.class);
            jclLogger.info("org.apache.commons.logging.Log: INFO");
        }
    }

**Comment by mrumpf** [comment]
Closing this PR because it touched some of the proxy issues which are now fixed by #3816

**Pull request closed without merging**
