### PR TITLE
Use idiomatic AssertJ assertions

### PR DESCRIPTION
**Pull request by quaff**
1. Replace assertThat(x.isEmpty()).isTrue() with assertThat(x).isEmpty() Search for : assertThat\((.+).isEmpty\(\)\).isTrue\(\) Replace with : assertThat($1).isEmpty()
Search for : assertThat\((.+).isEmpty\(\)\).isFalse\(\) Replace with : assertThat($1).isNotEmpty()

2. Replace assertThat(x.iterator().next()) with assertThat(x).element(0) Search for : assertThat\((.+).iterator\(\).next\(\)\) Replace with : assertThat($1).element(0)

3. Replace assertThat(x.get(i)). with assertThat(x).element(i). Search for : assertThat\((.+)\.get\((\d+)\)\)\.
Replace with : assertThat($1).element($2).

### CODE REVIEW

**Comment by quaff** [comment]
> It's more verbose and I don't think it makes the code easier to read.

It will report more meaningful error not just for readable consideration.

**Comment by philwebb** [comment]
I like 1 but I don't think 2 or 3 give enough value given the number of files they change.

**Comment by quaff** [comment]
OK, I've updated the commit.

**Comment by mhalbritter** [comment]
Thank you!

**Pull request closed without merging**
