### PR TITLE
Polish: reorder the modifiers to comply with the Java Language Specification

### PR DESCRIPTION
**Pull request by igor-suhorukov**

### CODE REVIEW

**Comment by igor-suhorukov** [comment]
@snicoll Thank you for review and comments! In spring boot "main" classes it is only single occurrence of "static abstract"

**Comment by wilkinsona** [comment]
We seem to be rather inconsistent:

```
$ find . -name "*.java" | xargs grep "static abstract" | wc -l
      12
$ find . -name "*.java" | xargs grep "abstract static" | wc -l
      16
```

Irrespective of whether it's test or main code, it'd be nice to consistently use one or the other. My vote is to align main and test code with the JLS as proposed (for main code only) here. I'm also in favour of enabling Checkstyle's modifier order check so that things remain consistent.

**Comment by igor-suhorukov** [comment]
@wilkinsona this sounds reasonable with checkstyle rule and align rule with whole codebase. I have only one issue: my fork for this pull request is deleted. What I need to do?

**Comment by wilkinsona** [comment]
> I can create another PR

I think that might be what you have to do. I don't know how to resurrect a pull request once the fork that it comes from has been deleted.

**Comment by igor-suhorukov** [comment]
@wilkinsona @snicoll thank you for help! I fixed issues from this PR  in [PR 12432](https://github.com/spring-projects/spring-boot/pull/12432)

**Pull request closed without merging**
