### PR TITLE
Cannot initialize Quartz with scripts containing custom prefix comment

### PR DESCRIPTION
**Pull request by linkqu**
Quartz comment prefix include "#"

org/quartz/impl/jdbcjobstore/tables_mysql_innodb.sql

### CODE REVIEW

**Comment by linkqu** [comment]
Because Quartz init SQL script comment prefix include "#" , Quartz initialization failed！

**Comment by snicoll** [comment]
@linkqu I am not following. the auto-configuration for Quartz can initialize the store by creating tables automatically and that process has nothing to do with this component. 

Are you aware of `spring.quartz.jdbc.initialize-schema` ?

**Comment by linkqu** [comment]
Yes, I'm aware, But initialization failed and there's no mistake.

I run the following example to be successful，I doubt it's the problem of "ScriptUtils.DEFAULT_COMMENT_PREFIX"

ScriptUtils.executeSqlScript(
    dataSource.getConnection(), 
    new EncodedResource(new ClassPathResource("org/quartz/impl/jdbcjobstore/tables_mysql_innodb.sql")),
    false, false, “#”, ScriptUtils.DEFAULT_STATEMENT_SEPARATOR,
    ScriptUtils.DEFAULT_BLOCK_COMMENT_START_DELIMITER, 
    ScriptUtils.DEFAULT_BLOCK_COMMENT_END_DELIMITER
);

**Comment by wilkinsona** [comment]
Thanks, @linkqu. I see the problem now. A number of the `tables_*.sql` files in Quartz 2.3.0 use a comment prefix other than `--`.

To support this, the property needs to be added to `org.springframework.boot.autoconfigure.quartz.QuartzProperties.Jdbc` and then honoured in `org.springframework.boot.autoconfigure.quartz.QuartzDataSourceInitializer`.

Would you like to update this pull request?

**Comment by linkqu** [comment]
right!

**Comment by snicoll** [comment]
@linkqu I went ahead and fixed this in  8f53c2e - Thanks for the report

**Pull request closed without merging**
