### PR TITLE
Add to ApplicationFailedEvent.Exception information to debug log.

### PR DESCRIPTION
**Pull request by LiYing2010**
This commit provides exception information that can be used as diagnostics to a user when their application fails to start.

### CODE REVIEW

**Comment by LiYing2010** [comment]
@snicoll 
Sorry, this issue happened to me like a month ago, I got a `"Application failed to start with classpath: "` error log, but no Exception was output.
I don't remember the details now, I will try if I can create a sample app to reproduce this issue.

**Comment by snicoll** [comment]
@LiYing2010 it is a debug log and the actual exception is logged after that unless there is a failure analzer than can handle it (you can still set the exception when the debug mode is on). The reason I am asking for a sample is that I don't think we should make that change.

**Comment by LiYing2010** [comment]
@snicoll

Hi, It took me some time, but I finally reproduced this issue.

We have a web application using `Spring-boot` v1.5.7 + `Spring Framework` v4.3.11 .
(I am sorry, it happened in `Spring-boot` **v1.5.7**, but I did not test it in `Spring-boot` **v2.x**)

And someday, when I was developing a new feature, I modified our `application.yml` configuration file, but made some mistake by accident, and then:
1. Application failed to start, since YAML parser could not parse this incorrect yml file.
2. `SimpleApplicationEventMulticaster#multicastEvent` got executed, to notify all listeners about this `ApplicationFailedEvent`
3. `ClasspathLoggingApplicationListener#onApplicationEvent` got executed, and output `"Application failed to start with classpath: blah blah blah"` debug log.
4. `ClasspathLoggingApplicationListener#onApplicationEvent` try to call next listener, which is a `BackgroundPreinitializer`, and `BackgroundPreinitializer#onApplicationEvent` got executed
5. in method `BackgroundPreinitializer#onApplicationEvent`, it called `preinitializationComplete.await()`, and this call is blocked like forever
6. the `logger.warn("Unable to close ApplicationContext", ex)` error log never got a chance to execute, since `BackgroundPreinitializer#onApplicationEvent` caused a deadlock

So, the result is, we got a `"Application failed to start with classpath: blah blah blah"` debug log, but not exception information for diagnostics.

I understand the reason is something was going wrong at step 5, but it blocked step 6,
but in my opinion, is it better if we output error information ASAP?
which means, add exception info to the debug log in step 3

**Comment by wilkinsona** [comment]
Thanks for the additional details. This is a duplicate of #10362.

**Comment by LiYing2010** [comment]
Thanks, understood.

**Pull request closed without merging**
