### PR TITLE
Change the maven plugin to allow use a source with classifier. 

### PR DESCRIPTION
**Pull request by bjornlindstrom**
Changed the maven plugin so if a classifier is specified it will look for a source with that classifier and use it if it exists. If not found it will use the main artifact as before. #7659

### CODE REVIEW

**Comment by snicoll** [comment]
@bjornlindstrom can you please expand a bit the use case behind that change? Why are you trying to repackage a different artifact than the the one produced by the regular lifecycle.

**Comment by bjornlindstrom** [comment]
@snicoll Maybe I misunderstood #7659 but I thought the solution was to repackage the classifier jar produced by the maven-jar plugin.

**Comment by snicoll** [comment]
Oh my, sorry! I missed the reference to the existing issue.

**Comment by ggsenger** [comment]
@snicoll is there any further feedback you need? (the _waiting-for-feedback_ label is still present)

we would love to see this pull request merged as we have a similar issue as described in https://github.com/spring-projects/spring-boot/issues/7659

**Comment by snicoll** [comment]
Sorry that felt through the crack, thanks for reminding me

**Comment by bjornlindstrom** [comment]
Closing it since it seems to be wrong and I don't have the time to sort it out.

**Pull request closed without merging**
