### PR TITLE
Use flyway-bom provided in 9.15.0

### PR DESCRIPTION
**Pull request by eddumelendez**
Flyway 9.15.0 introduces `flyway-bom`.

See https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks very much for spotting this, @eddumelendez.

**Comment by wilkinsona** [comment]
I just noticed that the bom hasn't be published to Central and then found https://github.com/flyway/flyway/issues/3628.

**Comment by eddumelendez** [comment]
I didn't notice it until going to Maven Central, after PR was created. Once the issue is solved I will update the PR.

**Comment by wilkinsona** [comment]
The Flyway issue doesn't seem to be going anywhere so I'm going to close this one for now. We can re-open if they start publishing the bom.

**Pull request closed without merging**
