### PR TITLE
Add DataElasticsearchTest annotation

### PR DESCRIPTION
**Pull request by eddumelendez**
Add parity to other test annotations for spring data projects.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks, @eddumelendez. It looks like Testcontainers is required as a means of bootstrapping an ES node. Is that correct? It feels more viable than https://github.com/spring-projects/spring-boot/pull/8636 but it would be the only `@…DataTest` annotation where Testcontainers is required.

**Comment by eddumelendez** [comment]
>  It looks like Testcontainers is required as a means of bootstrapping an ES node.

Yes, tescontainers is setting a single node

**Comment by wilkinsona** [comment]
> it would be the only `@Data…Test` annotation where Testcontainers is required

I was wrong here. We already have `@DataRedisTest`, `@DataCassandraTest`, and `@DataNeo4jTest` where Testcontainers  will typically be used to manage the data store.

**Comment by wilkinsona** [comment]
Thanks very much, @eddumelendez.

**Pull request closed without merging**
