### PR TITLE
Narayana JTA integration

### PR DESCRIPTION
**Pull request by gytis**
Hello,

from time to time we get Narayana users asking how to integrate it with Spring. Thus I've implemented the extension for Spring Boot to add an option to use Narayana as a JTA provider.
I would appreciate any feedback on the code. I've tried to comply with your guidelines, but please let me know if anything is missing.

Thanks,
Gytis

- [X] I have signed the CLA

### CODE REVIEW

**Comment by gytis** [comment]
Seems that the Narayana release I made this morning did not propagate to the Maven central yet.

**Comment by gytis** [comment]
I has synced up and should be OK to retest.

**Comment by wilkinsona** [comment]
Closing and reopening to trigger a new Travis build

**Comment by philwebb** [comment]
Great stuff! Thanks for the very complete contribution.

**Comment by philwebb** [comment]
Fixed in commit 25423e91d5b68a519520124d3d0d3ed939f2b10f

**Comment by philwebb** [comment]
Reopening for  documentation updates

**Comment by gytis** [comment]
Thanks, @philwebb. Was a pleasure.

**Pull request closed without merging**
