### PR TITLE
Add property to enable SPDY or HTTP2 in Undertow

### PR DESCRIPTION
**Pull request by eddumelendez**
See gh-3350

### CODE REVIEW

**Comment by philwebb** [comment]
See #3350

**Comment by wilkinsona** [comment]
I don't like the `server.undertow.option` property that was proposed in `#3350` and implemented here for a couple of reasons:

1. There are a _lot_ of options that could be set, so only supporting `SPDY` or `HTTP2` feels rather strange. Also, some options have configurable values that couldn't be set using this approach.
2. HTTP2 (and SPDY) isn't something that's Undertow-specific. Jetty 9.3 (9.2 is the default at the moment but we do support 9.3 and have a sample for it) also supports HTTP2 and Tomcat will in 9.0.

I think it's worth taking a step back and considering the broader picture for HTTP2 rather than focussing specifically on Undertow and the details of how it's enabled when using Undertow.

**Comment by ofbizbrazil** [comment]
Nowadays SPDY/HTTP2 is a mandatory resource to get applications safer and faster,  having an option by properties is much easier than having a custom EmbeddedFactory to enable it. 

For a long while I am missing this option in Spring Boot and I agree with @wilkinsona this should not  only be able for Undertow as another web servers. 

Opening a property to set any value to web server I agree is dangerous,  but an enum to manage SPDY or HTTP2 is a good option. 

What I meant here is that Spring Boot should go further that only allow coding it.

**Comment by wilkinsona** [comment]
I'm going to close this one is the approach that's been implemented isn't the one that we want to take for enabling HTTP2.

**Comment by herau** [comment]
@wilkinsona any news about this topic ? Did you have a common way to enable HTTP2 ?

**Comment by wilkinsona** [comment]
No news at the moment. https://github.com/spring-projects/spring-boot/issues/3350 is still open.

**Pull request closed without merging**
