### PR TITLE
Upgrade to logback 1.1.6

### PR DESCRIPTION
**Pull request by kazuki43zoo**
The logback has been updated at Feb 29, 2016.
Please review.
I've signed the Spring ICLA.

### CODE REVIEW

**Comment by kazuki43zoo** [comment]
Oh, sorry...
I'll fix a build error.

**Comment by kazuki43zoo** [comment]
I've fixed compile errors caused by method signature changes on `BasicConfigurator`,
For details, refer to http://jira.qos.ch/browse/LOGBACK-1141 and https://github.com/qos-ch/logback/commit/cd0441f993e4da5.

**Comment by wilkinsona** [comment]
Thanks for the PR. The changes are now in 1.3.x and master.

**Comment by kazuki43zoo** [comment]
@wilkinsona  Thanks for merging !!

**Pull request closed without merging**
