### PR TITLE
increases version of git commit plugin to 2.2.5

### PR DESCRIPTION
**Pull request by lkwg82**
see https://github.com/ktoso/maven-git-commit-id-plugin/releases/tag/v2.2.5

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@lkwg82 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=14354)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=14354) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by snicoll** [comment]
Thanks for the PR but we have a semi-automated process that upgrades dependencies and don't accept PRs for dependency upgrades.

**Comment by lkwg82** [comment]
thx for the quick response!

@snicoll can you point me to the procedure?

**Comment by bclozel** [comment]
@lkwg82 We're using [bomr](https://github.com/spring-io/bomr) to update our dependencies.

**Pull request closed without merging**
