### PR TITLE
Update QuartzDataSourceInitializerTests.commentPrefixCanBeCustomized to use a custom prefix that isn't covered by the default

### PR DESCRIPTION
**Pull request by adiohana**
Updated QuartzDataSourceInitializerTests.commentPrefixCanBeCustomized to actually use a custom prefix (**) for comments.

This PR fixes gh-18275

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks very much for the PR, @adiohana. That's pretty much exactly what I had in mind. In addition to the proposed changes, I think it should now be possible to delete the tables_h2.sql file as I believe it's now redundant. Would you like to update your PR to make that change too? No problem if not, we can take care of it (if it's needed) as part of merging this.

**Comment by adiohana** [comment]
@wilkinsona I will update my PR

**Comment by adiohana** [comment]
@wilkinsona ping for merging the PR :]

**Comment by philwebb** [comment]
@adiohana We're all a bit tied up with the upcoming 2.2 RC1 release at the moment. There's no need to ping Andy as the issue has been assigned to the 2.1.x milestone so it shouldn't fall though the cracks. We'll hopefully get to it soon.

**Comment by wilkinsona** [comment]
Thanks very much for making your first contribution to Spring Boot, @adiohana. The proposed changes have been merged into 2.1.x and forwards into master.

**Pull request closed without merging**
