### PR TITLE
Fix system properties override example

### PR DESCRIPTION
**Pull request by ewjmulder**
Fixed the system properties command line override example.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ewjmulder Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15562)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15562) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ewjmulder Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15562)!

**Comment by snicoll** [comment]
@ewjmulder thank you for making your first contribution to Spring Boot. This is now merged in `2.1.x` and `master`.

**Comment by ewjmulder** [comment]
Perfect, thanks for the quick handling and of course the great project!

**Pull request closed without merging**
