### PR TITLE
Log exception before sending to listeners

### PR DESCRIPTION
**Pull request by jadekler**
- Fixes gh-4680

### CODE REVIEW

**Comment by jadekler** [comment]
@anyone - CI failure here seems to be style-related. When I run `./mvnw org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check` locally on a clean master, I get the same error. Is this something anyone else has seen?

**Comment by vpavic** [comment]
@jadekler, check the [code conventions part of contributing guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#code-conventions-and-housekeeping).

Running checkstyle locally should give you relevant error info.
Looking at your diff, [```SpringApplication.java:814```](https://github.com/jadekler/spring-boot/blob/5249a3218760762e236fa86db238d29f7bb85ea4/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L814) seems to have invalid indentation.

**Comment by jadekler** [comment]
@vpavic Aha! Thank you. I actually found out later that my IDE was not set up properly for indentation :/ Thanks for the tip

**Comment by philwebb** [comment]
Thanks @jadekler!

**Comment by jadekler** [comment]
:+1:

**Pull request closed without merging**
