### PR TITLE
Add Gradle Enterprise Maven Extension to 2.1.x

### PR DESCRIPTION
**Pull request by runningcode**
This adds build caching and build scans.

The changes required disabling scans when using the maven invoker plugin in order to not cause duplicate build scans when invoking other maven builds.
There is also an empty `.mvn` folder in the spring-boot-starters project to prevent duplicate build scans as well since there is no way to pass properties to the maven-javadoc-plugin.

The checkstyle plugin was causing a cache miss with the `propertyExpansion` because it contains an absolute path. The absolute path is now ignored and instead the files are added as inputs to the checkstyle plugin.
This only enables the local build cache. The remote cache is not yet enabled.

On my local machine:
`./mvnw clean install` build times go from about 30 minutes to about 10 minutes.
`./mvnw clean install -Pfull` build times go from about 60 minutes to about 13 minutes.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@runningcode Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=22089)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=22089) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@runningcode Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=22089)!

**Comment by wilkinsona** [comment]
Thanks very much for the PR, @runningcode. This is currently blocked on https://github.com/spring-io/gradle-enterprise-conventions/issues/8.

**Comment by wilkinsona** [comment]
The [0.0.5 of the extension is now on Maven Central](https://repo.maven.apache.org/maven2/io/spring/ge/conventions/gradle-enterprise-conventions-maven-extension/0.0.5/) so this is no longer blocked.

**Comment by runningcode** [comment]
@wilkinsona I've updated this PR to use 0.0.5 of the Spring `gradle-enterprise-conventions-maven-extension`.

**Comment by wilkinsona** [comment]
Thanks very much, @runningcode. This has been merged into 2.1.x and forwards in 2.2.x.

**Pull request closed without merging**
