### PR TITLE
Subject and object look reversed based on the following explanation i…

### PR DESCRIPTION
**Pull request by izeye**
…n docs

### CODE REVIEW

**Comment by snicoll** [comment]
No. The external properties override what you'd put in your code using the API. Is the sentence badly written?

**Comment by izeye** [comment]
@snicoll You mean external properties win code using API, am I understanding right?

**Comment by snicoll** [comment]
Yes. Like explained in the example, actually (with the show banner thing).

**Comment by izeye** [comment]
@snicoll Then I think 'not' should be removed from 'The actual application will not show the banner'. Am I missing something?

**Comment by snicoll** [comment]
I meant to write _now_ (and not _not_). It's fixed now, thanks.

**Comment by izeye** [comment]
@snicoll My question is solved _now_ :+1: Thanks for fixing!

**Pull request closed without merging**
