### PR TITLE
Add additional Jackson2ObjectMapperBuilder customization

### PR DESCRIPTION
**Pull request by poznachowski**
- [X] I have signed the CLA

Enables to customize Jackson2ObjectMapperBuilder retaining its default auto-configuration.
Fixes gh-5787

### CODE REVIEW

**Comment by andrewduckett** [comment]
This might be out of scope for what you're proposing but what are your thoughts on making the configuration in `JacksonObjectMapperBuilderConfiguration` be a default `Jackson2ObjectMapperBuilderCustomizer` with a specific order.

Then applications can decide where they'd like to begin customization (before, after, or both)?  If so, `JacksonObjectMapperBuilderConfiguration` should really just ensure a builder exists and run all of the available Customizers.

**Comment by wilkinsona** [comment]
@andrewduckett I like that idea. It's similar to what we've done with `MockMvcBuilderCustomizer` and `SpringBootMockMvcBuilderCustomizer`.

**Comment by poznachowski** [comment]
If @wilkinsona is giving a green light, I'll accomodate this change here.

**Comment by wilkinsona** [comment]
@poznachowski That would be great. Thank you!

**Comment by wilkinsona** [comment]
Thanks for the pr, @poznachowski. I've merged it into master. I made the change that we discussed in 0c2ecb7.

**Comment by poznachowski** [comment]
Thanks and sorry about no activity on the change - I was overwhelmed with work recently.

**Pull request closed without merging**
