### PR TITLE
Autoconfigure RabbitMQ Java Client metrics

### LINKED ISSUE #7498: Autoconfigure RabbitMQ Java Client metrics
RabbitMQ Java Client 4.0 brings support for metrics collection through Dropwizard Metrics. This feature is disabled by default in the client, but it would make sense to enable it automatically in Spring Boot if all the condition are met (RabbitMQ Java Client 4.0 and Dropwizard Metrics on the classpath).

The metrics would also automatically be plugged on the actuator metrics HTTP endpoint.

### PR DESCRIPTION
**Pull request by acogoluegnes**
Enable RabbitMQ Java Client metrics collection if RabbitMQ Java Client 4.0 and Dropwizard Metrics are on the classpath. Configuration flag can also enable/disable (default is to enable).

https://github.com/spring-projects/spring-amqp/pull/507 needs to be merged first.

Fixes #7498

### CODE REVIEW

**Comment by philwebb** [comment]
We'll need to consider the Rabbit client 4.0 upgrade (#7509) before we can do this.

**Comment by philwebb** [comment]
I wonder if we could write our own `MetricsCollector` implementation so that metrics could be added even if coda metrics wasn't being used. That might be a little tricky since we'd need to do it in `spring-boot-actuator` and not in `spring-boot-autoconfiguration`. Perhaps we need a customizer callback for `com.rabbitmq.client.ConnectionFactory`.

**Comment by philwebb** [comment]
@acogoluegnes I'm not sure if you have time, but perhaps you could investigate a Spring Boot specific `MetricsCollector`?

**Comment by acogoluegnes** [comment]
@philwebb Do you mean something based on [Spring Boot's `CounterService`](http://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#production-ready-recording-metrics)? That's certainly doable, but we'd need to refactor the [implementation that ships with RabbitMQ client](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/StandardMetricsCollector.java) to be able to re-use the tricky parts through an abstract class and let sub-classes just increment their metrics. This could be done in 4.0.1. Does that make sense?

**Comment by philwebb** [comment]
>  Does that make sense?

Yeah, that would be ideal. I was thinking we'd need to copy/paste a bunch of that code but an abstract base class would be much better.

**Comment by acogoluegnes** [comment]
I created the [issue in the Java Client](https://github.com/rabbitmq/rabbitmq-java-client/issues/222). How would you like to proceed? Should it be included in the current PR or somewhere else?

**Comment by philwebb** [comment]
The current PR would be best thanks. You can force push and update to the branch.

**Comment by acogoluegnes** [comment]
@philwebb Here is the `CounterService`-based implementation of `MetricsCollector`. Are you OK with the implementation? If yes, I need to release RabbitMQ Java Client 4.1.0 (the PR uses a snapshot) and ask the Spring AMQP folks to use it in Spring AMQP 2.0.

**Comment by acogoluegnes** [comment]
@philwebb Any update on this? Please let me know if you're fine with the implementation (especially the `ConnectionFactoryCustomizer` trick). I'd like to release RabbitMQ Java Client 4.1.0 (which will contain the metrics collector abstract class). No need to merge now, green light is enough. Thanks.

**Comment by acogoluegnes** [comment]
PR is now based on RabbitMQ Java Client 4.1.0 (through Spring AMQP 2.0), not just a snapshot.

**Comment by philwebb** [comment]
Duplicates #10887

**Pull request closed without merging**
