### PR TITLE
Autoconfiguration for embedded Redis.

### PR DESCRIPTION
**Pull request by ameraljovic**
Hi, I added support for embedded Redis server. 

It scans the classpath for the Embedded Redis libraty and if present, starts an embedded Redis server on port specified in `spring.redis.port`.

### CODE REVIEW

**Comment by ameraljovic** [comment]
I have signed and agree to the terms of the SpringSource Individual
Contributor License Agreement.

**Comment by philwebb** [comment]
:+1:

**Comment by philwebb** [comment]
Thanks! Will try to get this into 1.3 (time permitting).

**Comment by fabriciocolombo** [comment]
It would be good to consider the problems that occurred in the spring-session before adding this feature.
See https://github.com/spring-projects/spring-session/issues/248 and https://github.com/spring-projects/spring-session/issues/121#issuecomment-124653443

**Comment by philwebb** [comment]
Thanks for info @fabriciocolombo. It does look like we are likely to get similar issues. @ameraljovic I think we'll have to leave this one for now and take another look around the 1.4 time frame.

Thanks anyway for the PR.

**Comment by philwebb** [comment]
Unfortunately embedded Redis doesn't appear to work that well on Windows or certain Linux distributions. Someone within the Spring team tried to use it and found it caused quite a few stability issues. For that reason I'm afraid we've decided not to merge support at this time.

Thanks anyway for the contribution!

**Pull request closed without merging**
