### PR TITLE
update bright colors in log4j2 and logback

### PR DESCRIPTION
**Pull request by Abhijeetmishr**
#34638 update ColorConverter with bright colors

### CODE REVIEW

**Comment by Abhijeetmishr** [comment]
@wilkinsona @philwebb please review this when available.
one of the above check is failing how to fix that ?

**Comment by wilkinsona** [comment]
Thanks for the PR, @Abhijeetmishr. Ideally, you should run the build locally and fix any problems before opening the pull request.

Looking at the CI logs, your changes have introduced a Checkstyle failure and some test failures:

```
> Task :spring-boot-project:spring-boot:checkstyleTest
[ant:checkstyle] [ERROR] /tmp/build/6da1d659/git-repo/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/logging/logback/ColorConverterTests.java:136: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
```

```
Found test failures in 1 test task:

:spring-boot-project:spring-boot:test
    org.springframework.boot.logging.log4j2.ColorConverterTests > black()
    org.springframework.boot.logging.log4j2.ColorConverterTests > brightblack()
    org.springframework.boot.logging.log4j2.ColorConverterTests > brightblue()
    org.springframework.boot.logging.log4j2.ColorConverterTests > brightcyan()
    org.springframework.boot.logging.log4j2.ColorConverterTests > brightgreen()
    org.springframework.boot.logging.log4j2.ColorConverterTests > brightmagenta()
    org.springframework.boot.logging.log4j2.ColorConverterTests > brightred()
    org.springframework.boot.logging.log4j2.ColorConverterTests > brightwhite()
    org.springframework.boot.logging.log4j2.ColorConverterTests > brightyellow()
    org.springframework.boot.logging.log4j2.ColorConverterTests > white()
    org.springframework.boot.logging.logback.ColorConverterTests > black()
    org.springframework.boot.logging.logback.ColorConverterTests > brightblack()
    org.springframework.boot.logging.logback.ColorConverterTests > brightblue()
    org.springframework.boot.logging.logback.ColorConverterTests > brightcyan()
    org.springframework.boot.logging.logback.ColorConverterTests > brightgreen()
    org.springframework.boot.logging.logback.ColorConverterTests > brightmagenta()
    org.springframework.boot.logging.logback.ColorConverterTests > brightred()
    org.springframework.boot.logging.logback.ColorConverterTests > brightwhite()
    org.springframework.boot.logging.logback.ColorConverterTests > brightyellow()
    org.springframework.boot.logging.logback.ColorConverterTests > white()
```

You should be able to reproduce these failures on your machine by running `./gradlew spring-boot-project:spring-boot:build`.

**Comment by Abhijeetmishr** [comment]
> Thanks for the PR, @Abhijeetmishr. Ideally, you should run the build locally and fix any problems before opening the pull request.
> 
> Looking at the CI logs, your changes have introduced a Checkstyle failure and some test failures:
> 
> ```
> > Task :spring-boot-project:spring-boot:checkstyleTest
> [ant:checkstyle] [ERROR] /tmp/build/6da1d659/git-repo/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/logging/logback/ColorConverterTests.java:136: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
> ```
> 
> ```
> Found test failures in 1 test task:
> 
> :spring-boot-project:spring-boot:test
>     org.springframework.boot.logging.log4j2.ColorConverterTests > black()
>     org.springframework.boot.logging.log4j2.ColorConverterTests > brightblack()
>     org.springframework.boot.logging.log4j2.ColorConverterTests > brightblue()
>     org.springframework.boot.logging.log4j2.ColorConverterTests > brightcyan()
>     org.springframework.boot.logging.log4j2.ColorConverterTests > brightgreen()
>     org.springframework.boot.logging.log4j2.ColorConverterTests > brightmagenta()
>     org.springframework.boot.logging.log4j2.ColorConverterTests > brightred()
>     org.springframework.boot.logging.log4j2.ColorConverterTests > brightwhite()
>     org.springframework.boot.logging.log4j2.ColorConverterTests > brightyellow()
>     org.springframework.boot.logging.log4j2.ColorConverterTests > white()
>     org.springframework.boot.logging.logback.ColorConverterTests > black()
>     org.springframework.boot.logging.logback.ColorConverterTests > brightblack()
>     org.springframework.boot.logging.logback.ColorConverterTests > brightblue()
>     org.springframework.boot.logging.logback.ColorConverterTests > brightcyan()
>     org.springframework.boot.logging.logback.ColorConverterTests > brightgreen()
>     org.springframework.boot.logging.logback.ColorConverterTests > brightmagenta()
>     org.springframework.boot.logging.logback.ColorConverterTests > brightred()
>     org.springframework.boot.logging.logback.ColorConverterTests > brightwhite()
>     org.springframework.boot.logging.logback.ColorConverterTests > brightyellow()
>     org.springframework.boot.logging.logback.ColorConverterTests > white()
> ```
> 
> You should be able to reproduce these failures on your machine by running `./gradlew spring-boot-project:spring-boot:build`.

@wilkinsona okay got it 
Thank you!

**Comment by Abhijeetmishr** [comment]
closing in ref of #34749

**Comment by scottfrederick** [comment]
@Abhijeetmishr You can add more commits to a PR branch to address review comments, there's no need to open a new PR with subsequent changes.

**Comment by Abhijeetmishr** [comment]
> @Abhijeetmishr You can add more commits to a PR branch to address review comments, there's no need to open a new PR with subsequent changes.

@scottfrederick I created another PR because I have messed up with my branch in local. I had created commit without taking pull from main branch.
So I cherry-picked commit and created another branch from main. I thought it will be faster.
Sorry for that 
Thank you!

**Comment by scottfrederick** [comment]
No worries. We appreciate the contribution and just don't want you to create too much work for yourself. We can always take care of rebasing changes when merging.

**Pull request closed without merging**
