### PR TITLE
Disable auto-detection in tests that start Hazelcast

### LINKED ISSUE #31715: Disable auto-detection in tests that start Hazelcast
Programmatically, it's something like:

```java
getAutoDetectionConfig().setEnabled(false)
```

In YAML:

```yaml
hazelcast:
  network:
    join:
      auto-detection:
        enabled: false
```

And in XML:

```xml
<hazelcast>
    ...
    <network>
        <join>
            <auto-detection enabled="false" />
            ...
        </join>
    </network>
    ...
</hazelcast>
```

When configured correctly, the node should log the following:

```
WARNING: [192.168.178.45]:5701 [dev] [4.2.5] No join method is enabled! Starting standalone.
```

We don't want to see this:

```
INFO: [192.168.178.45]:5701 [dev] [4.2.5] Using Multicast discovery
```

### PR DESCRIPTION
**Pull request by adrianbob**
Updated test configs to disable auto-detection for Hazelcast instances

Closes #31715

### CODE REVIEW

**Comment by snicoll** [comment]
Unfortunately, there's no such thing as `auto-detection` in the Hazelcast 4 xsd. There was one for Hazelcast 3 but it's gone in version 4. The programmatic API still has it so I am not sure what's the expected replacement.

**Comment by snicoll** [comment]
Turns out it was an issue with an earlier XSD in the 4.x generation.

**Comment by snicoll** [comment]
Thanks again, @adrianbob. Interesting that GitHub flagged this PR as a first contribution again...

**Comment by adrianbob** [comment]
> Thanks again, @adrianbob. Interesting that GitHub flagged this PR as a first contribution again...

Thanks! The previous commit on SpringBoot was done with my work email so it did not match the one from my personal account.

**Pull request closed without merging**
