### PR TITLE
Add JAVA_OPTS to launcher script.  Resolves #2797

### LINKED ISSUE #2797: Add inlined conf file support to launch.script
https://github.com/spring-projects/spring-boot/commit/ba2ea301f1cc7df7104293bcdf567416c1fda4bb#commitcomment-10652388

### PR DESCRIPTION
**Pull request by JustinKSU**
Resolves #2797

When running Spring Boot as a Linux service, you can now instruct the spring-boot-maven plugin to include JAVA_OPTS in the launcher.script.  A new embeddedLaunchScriptProperties key called "javaOpts" has been created.  Any JVM options specified will be appended to any JAVA_OPTS set by other methods (e.g. environmental variable or .conf file).

This gives the flexibility to specify JAVA_OPTS that are universal across all environments, or in the case you already know the environment, all the JAVA_OPTS in your project.  The end result is the ability to have single artifact deployments even when JVM options are required.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. I added some comments to #2797, but it's probably better to capture them here.

Generally speaking, I am not sure that the extra complexity that this introduces is worth it. As #2797 indicates, using a `.conf` file is our preferred mechanism for this requirement, and it has the advantage of being much more flexible. If we add specific support for `JAVA_OPTS` to the script, why wouldn't we also add support for `RUN_ARGS` for example? It feels like a slippery slope that could lead to more and more properties being added when we already have a general-purpose mechanism in place.

In terms of the actual implementation I don't think that appending the `JAVA_OPTS` baked into the script to those from the environment or the .conf file is a good idea as it makes it impossible for the script's `JAVA_OPTS` to be overridden. I can imagine that some people will want to prepend, some will want to append, and some will want to replace. You can do any of these in the `.conf` file but, without adding more properties, only one with the approach proposed here.

Thanks again for the PR, but for the reasons outlined above, I don't think we should make this change.

**Comment by JustinKSU** [comment]
@wilkinsona Thank you for taking the time to review my comments, pull request, and giving me feedback on both.

I understand the slippery slope argument, but I think changing JAVA_OPTS is much more common than some of the other settings.  I reached out to Rob who reached out to Phil who seemed to agree this would be a useful change.  That said, I can see your points about wanting the build/integration system to take care of generating the .conf file or bundling the .conf file with the jar file.  However, not everyone has the luxury to use these tool.

Would you be open to a compromise?  [embeddedLaunchScriptProperties ](https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html#deployment-script-customization-when-it-written) currently supports a _confFolder_ option, but no _confFile_ option.  If we added it, it would take away the need to have a unique conf file for every release.  This would accomplish my goals without bundling the configuration with the .jar file.

If you agree, I can create a separate feature request for that and would be willing to put in the effort to create the PR.

**Comment by JustinKSU** [comment]
If folks change their mind and we do want to add <javaOpts>, I agree that we should prepend the JAVA_OPTS defined by the build instead of appending it.  I've made these changes in my clone and can create a new pull request or update this one.  Let me know.

**Comment by philwebb** [comment]
I'd like to reopen this to consider what else we can try. When discussing this with Rob the JAVA_OPTS change seemed like the least invasive.

Another option we discussed was a way to embed a default `.conf` file somehow in the script. Something that we could `source` before trying the external one. It would be nice if we could get the `.conf` file to work in the same way as `application.properties`. Something inside the jar that can be overridden by something outside.

**Comment by philwebb** [comment]
PS Sorry for not getting to this one first since I'd already discussed it a little with Rob

**Comment by wilkinsona** [comment]
> we should prepend the JAVA_OPTS defined by the build instead of appending it

I don't think that helps. What happens if you have an option baked into the jar that you want to remove? As I said above, to satisfy everyone, I think it'd be necessary to support appending, prepending, and replacing the JAVA_OPTS that are baked into the jar.

> Another option we discussed was a way to embed a default .conf file somehow in the script. 

That sounds like a better option to me. I wonder if we could look for a separate file at build time and, if it's found, insert it in an appropriate location in the launch script?

**Comment by philwebb** [comment]
> I wonder if we could look for a separate file at build time and, if it's found, insert it in an appropriate location in the launch script?

That sounds like a better option to me. It's a bit more work but it'll probably give the best outcome.

**Comment by wilkinsona** [comment]
If we inlined the file [here](https://github.com/spring-projects/spring-boot/blob/dba6bcc7e191141c92f3ef06d1c58370ee53566a/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script#L42), I think it would then allow an external `.conf` file to change whatever the inlined file has set up. For example it could change `JAVA_OPTS` to whatever it wanted, prepending, appending, or replacing entirely as required. It'd also be analogous to application.properties with an external .conf file taking precedence over the one that's been inlined into the launch script.

**Comment by JustinKSU** [comment]
@wilkinsona Sourcing the file would work.  It would mean in both the CONF file in the project, and the one on the server would need to be aware that JAVA_OPTS might already have values and to prepend, append, or replace as desired.  I would recommend describing the interaction in the documentation, as it's likely someone will unintentionally override options instead of combining them (which might be the more common use case).

**Comment by JustinKSU** [comment]
All,  If we went with allowing a ".conf" file to be included in the project, would we add "embeddedLaunchConfig" or "embeddedLaunchConf" at the same level as "embeddedLaunchScript"?  Or would you see it as another embeddedLaunchScriptProperties?

Either way, procedurally how should we move forward?  A separate issue with a new pull request or edit this one?  I'm happy to do the development, but I'm not sure we would make the next 1.5.x release.

**Comment by wilkinsona** [comment]
> Either way, procedurally how should we move forward? A separate issue with a new pull request or edit this one?

I think we can use #2797 to track the requirement. I then think it's probably best to close this PR as we've agreed that we don't want to take the approach that it is proposing. A new pull request to tackles the new approach would then be most welcome.

> I'm happy to do the development, but I'm not sure we would make the next 1.5.x release.

This feels like it should be a 2.0 change to me so there's plenty of time.

**Pull request closed without merging**
