### PR TITLE
Upgrade to AssertJ 3.15.0

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

this PR upgrades to AssertJ 3.15.0 and already makes use of the new duration assertions (in separate commits though).

Let me know what you think.
Cheers,
Christoph

### CODE REVIEW

**Comment by dreis2211** [comment]
Wait a bit @snicoll . I see one breaking test. Sorry

**Comment by snicoll** [comment]
You know I am actually reviewing before merging right? :-)

**Comment by dreis2211** [comment]
Me too - better that you only need to review the corrected version once ;-)

**Comment by snicoll** [comment]
Cheers Christoph, saw the announcement of the release in my feed yesterday but you beat me to it again :-)

**Comment by dreis2211** [comment]
I saw it because you retweeted it 😆

**Pull request closed without merging**
