### PR TITLE
Add JDBC url to driver-class-name mappings for DB2, Teradata and Firebird

### PR DESCRIPTION
**Pull request by kamilszymanski**

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. Have you [signed the CLA](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#sign-the-contributor-license-agreement)?

Where there's an artifact in Maven Central, can you also please add dependency management to `spring-boot-dependencies/pom.xml` for the relevant JDBC drivers?

**Comment by kamilszymanski** [comment]
I've signed CLA for Spring Framework, shall I also sign it for Spring Boot?

Added JDBC driver for Firebird.

**Comment by wilkinsona** [comment]
Thanks. The CLA covers all projects so no need to sign it again.

**Comment by philwebb** [comment]
We'll probably leave out the "Add Firebird JDBC driver dependency" commit for now. The other one looks good :+1:

**Comment by wilkinsona** [comment]
@philwebb We have dependency management for a number of other JDBC drivers (Postgres, MySQL, Derby, etc) that we use in the same way. Firebird's a bit tricky due to having JDK-specific artifacts, but I think we should provide dependency management for it if we can.

**Comment by philwebb** [comment]
@wilkinsona OK, cool. That makes this easier to merge :)

**Comment by kamilszymanski** [comment]
rebased on master for easier merge

**Comment by wilkinsona** [comment]
@kamilszymanski Thanks. It looks like the dependency management changes got lost when you rebased. Don't worry about it, though; I'll take care of it.

**Comment by wilkinsona** [comment]
Merged. Thanks for the PR, @kamilszymanski.

**Pull request closed without merging**
