### PR TITLE
When virtual threads are enabled, configure Spring Integration's task scheduler to use them

### LINKED ISSUE #41188: When virtual threads are enabled, configure Spring Integration's task scheduler to use them
In the PR below, WebSocketMessagingAutoConfiguration has been modified to use a virtual thread executor
> https://github.com/spring-projects/spring-boot/pull/39611

```java
public class WebSocketMessagingAutoConfiguration {
  // ...
  WebSocketMessageConverterConfiguration(ObjectMapper objectMapper,
    Map<String, AsyncTaskExecutor> taskExecutors) {
    this.objectMapper = objectMapper;
    this.executor = determineAsyncTaskExecutor(taskExecutors);
  }

  private static AsyncTaskExecutor determineAsyncTaskExecutor(Map<String, AsyncTaskExecutor> taskExecutors) {
    if (taskExecutors.size() == 1) {
      return taskExecutors.values().iterator().next();
    }
    return taskExecutors.get(TaskExecutionAutoConfiguration.APPLICATION_TASK_EXECUTOR_BEAN_NAME);
  }

  // ...
}
```

Upon checking the taskExecutors being injected, it is taskScheduler.  
When used with spring-integration, the following Bean is being configured first.   
Is it possible to modify it to allow for auto-configuration?

```java
@Configuration(proxyBeanMethods = false)
@ConditionalOnBean(TaskSchedulerBuilder.class)
@ConditionalOnMissingBean(name = IntegrationContextUtils.TASK_SCHEDULER_BEAN_NAME)
@SuppressWarnings("removal")
public class IntegrationAutoConfiguration {
  // ..
  protected static class IntegrationTaskSchedulerConfiguration {
    @Bean(name = IntegrationContextUtils.TASK_SCHEDULER_BEAN_NAME)
    public ThreadPoolTaskScheduler taskScheduler(TaskSchedulerBuilder taskSchedulerBuilder,
      ObjectProvider<ThreadPoolTaskSchedulerBuilder> threadPoolTaskSchedulerBuilderProvider) {
      // ...
    }
  }
  // ..
}
```

Below is the configuration added without using auto-configuration.

```kotlin
@Configuration
class ExecutorConfig {
  @Bean(
    name = [
      TaskExecutionAutoConfiguration.APPLICATION_TASK_EXECUTOR_BEAN_NAME,
      AsyncAnnotationBeanPostProcessor.DEFAULT_TASK_EXECUTOR_BEAN_NAME
    ]
  )
  fun applicationTaskExecutorVirtualThreads(builder: SimpleAsyncTaskExecutorBuilder): SimpleAsyncTaskExecutor {
    return builder.build()
  }
}
```

Of course, the bottom properties are also set.

```yaml
spring:
  threads:
    virtual:
      enabled: true
```

### PR DESCRIPTION
**Pull request by facewise**
# Motivation

Former `IntegrationAutoConfiguration.IntegrationTaskSchedulerConfiguration` was not aware of virtual threads. It means `ThreadPoolTaskScheduler` was instantiated regardless of capability of virtual threads when you use `spring-boot-starter-integration`.

# Changes

Now `IntegrationAutoConfiguration.IntegrationTaskSchedulerConfiguration` determines a proper `TaskScheduler` bean to be instantiated via `@ConditionalOnThreading`.

If virtual threads is enabled, `SimpleAsyncTaskScheduler` will be instantiated, otherwise works as is.

This can resolve #41188.

### CODE REVIEW

**Comment by mhalbritter** [comment]
Thanks a lot!

**Comment by facewise** [comment]
@mhalbritter Oh, I think I made a broken test. Sorry.
I don't know how to run virtual threads enabled tests with `@EnabledForJreRange(min = JRE.JAVA_21)` on my pc.

**Comment by mhalbritter** [comment]
Don't worry, I'll fix it. The command to run is `gradle test -PtoolchainVersion=21`.

**Comment by facewise** [comment]
Thank you.

**Pull request closed without merging**
