### PR TITLE
Document Custom dependency version in Gradle

### PR DESCRIPTION
**Pull request by rwinch**
This adds documentation on how to leverage Gradle's resolution
strategy to specify dependency versions.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks, @rwinch. While this is good advice for Spring Boot 1.2.x, it isn't for 1.3. Boot 1.3 uses the [dependency management plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin) so the Gradle equivalent of the Maven example becomes:

```
ext['slf4j.version'] = '1.7.5'
```

**Comment by rwinch** [comment]
@wilkinsona Thanks for the information :) I have updated the PR

**Comment by wilkinsona** [comment]
Lovely stuff. Thanks, @rwinch.

**Comment by wilkinsona** [comment]
Merged. Thanks again, @rwinch

**Pull request closed without merging**
