### PR TITLE
Add condition to Cassandra auto-configuration

### PR DESCRIPTION
**Pull request by jeffreye**
Update Cassandra auto-configuration so that beans in `CassandraAutoConfiguration` may be optionally created

### CODE REVIEW

**Comment by snicoll** [comment]
@jeffreye thanks for the PR but we need to take a step back. Rather than offering what you think is a solution to the problem you're experiencing, we'd prefer a description of the problem first. I don't think the cassandra auto-config should be conditional on `spring.cassandra.keyspace-name`.

**Comment by jeffreye** [comment]
1. We would like to use Cassandra driver with our own implementation instead of auto-configured bean. Without configuring spring properties, it will fail the startup currently or we have to exclude the autoconfiguration 
2. CouchbaseAutoConfiguration also has the similar conditions so that it won't create beans unless there is properties

If keyspace name is not a good choice, what is your recommendation?

**Comment by jeffreye** [comment]
Thanks for the info. I'll vote +1 for the issue and hope it could bring more attention to the team.

**Comment by snicoll** [comment]
Indeed, so let's close this one in favor of #11325. Thanks for the suggestion, in any case.

**Pull request closed without merging**
