### PR TITLE
Dump hibernate table schema run with --debug

### PR DESCRIPTION
**Pull request by liujiong1982**
This commit will dump hibernate table schema when run with --debug

Fixed https://github.com/spring-projects/spring-boot/issues/446

### CODE REVIEW

**Comment by scheffield** [comment]
So, how to get the schema exported then?

**Comment by snicoll** [comment]
That's a rejected PR, check #446 for the actual issue which was solved in 1.2 already. Just enable debug (`--debug` or debug=true in your `application.properties`)

**Comment by snicoll** [comment]
@scheffield I've added a note in the documentation (see https://github.com/spring-projects/spring-boot/commit/f0b203f6da5538b0ab3c6655467bfdafcfeb4a8f)

**Comment by scheffield** [comment]
@snicoll Thanks!

**Pull request closed without merging**
