### PR TITLE
Use jws-algorithm config property in ReactiveOAuth2ResourceServerJwkConfiguration

### PR DESCRIPTION
**Pull request by az1a**
**Problem**:  
`spring.security.oauth2.resourceserver.jwt.jws-algorithm` configuration property is ignored in autoconfiguration of reactive application. I've observed this bug during migration of my app to webflux.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@az1a Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20681)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20681) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@az1a Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20681)!

**Comment by mbhave** [comment]
Thanks for the PR @az1a. I think we'd need to do the same for the [public key variant](https://github.com/spring-projects/spring-boot/blob/d8f218d86359557cdfacd2ea756dd40ce7da4d4a/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/reactive/ReactiveOAuth2ResourceServerJwkConfiguration.java#L79) as well. Would you be able to update your PR with that change?

If possible could you also add some tests to verify that the right algorithm is being used in both cases?

**Comment by az1a** [comment]
Hello @mbhave, I've updated the PR. 
I see that Concourse CI build failed but I don't know what's wrong. The project builds successfully on my machine :)

**Comment by mbhave** [comment]
The build failed due to a formatting violation. We can fix that when we merge. Thanks for updating the PR, looks good to me now.

**Comment by mbhave** [comment]
@az1a Thank you for making your first contribution to Spring Boot. This has been merged into `2.2.x` and `master`.

**Pull request closed without merging**
