### PR TITLE
Added Docker client autoConfiguration

### PR DESCRIPTION
**Pull request by hekonsek**
Hi,

I created autoConfiguration for the docker-java [1] Docker client. In the most common scenario, adding docker-java to the classpath will provide `DockerClient` instance connected to the `$DOCKER_HOST` environment variable:

```
@Autowired
DockerClient docker;
...
docker.pullImageCmd("ubuntu").exec();
```

Cheers.

[1] https://github.com/docker-java/docker-java

### CODE REVIEW

**Comment by philwebb** [comment]
I wondering if this is something that we should be considering for the core just yet. It feels like working with the Docker API from a boot application might be quite a specialist use-case at the moment. I'm also concerned about how many dependencies `docker-java` needs.

Perhaps a `docker-java-spring-boot` module that is actually lives under the https://github.com/docker-java organization might be a better approach?

**Comment by hekonsek** [comment]
It's up to you Phil. I created this because of demand for Docker client integration among Camel users. If you don't want to keep this in Boot, I can move that code to the Camel Docker component [1] and maintain it there. I just preferred to keep Boot and non-Camel related code in the Boot so non-Camel folks can benefit from it as well.

Once again - you decide :) .

[1] http://camel.apache.org/docker.html

**Comment by philwebb** [comment]
I've marked the issue as `waiting-for-votes`. I'd be interested to see how many `+1's` we get. Also keen to see what @wilkinsona things since it will indirectly impact the platform POM.

**Comment by philwebb** [comment]
Thanks for PR BTW, I do think it's nice, I'm just worried about supporting it going forward :)

**Comment by wilkinsona** [comment]
Docker's Java client seems to be evolving quite quickly. 1.0 was released in late February with 1.1 then being released in early April. I think I'd prefer to wait until things have settled down a little, or there's overwhelming demand for the auto-configuration

**Comment by hekonsek** [comment]
Sure. I will keep my fork of the code in the Apache Camel until then.

Cheers!

**Comment by pivotal-issuemaster** [comment]
@hekonsek Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=2071) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by trombka** [comment]
Hi, 

It  does not strictly involves this issue, but how about making such Docker autoconfiguration extended with useful containers setup like https://github.com/TouK/dockds ?

**Comment by geditdk** [comment]
Is this still on the radar? 

I'm happy to contribute and update it to support the latest docker-java with defaults, etc.

**Comment by wilkinsona** [comment]
It's on the radar to the extent that the issue is still open. However, it's waiting for votes and there hasn't been much interest. Docker Java also continues to evolve quite rapidly (1.4, 2.x and 3.0) have all be released in the last 12 months. I remain unconvinced that it something that we should add to Spring Boot.

**Comment by philwebb** [comment]
Given the concerns that @wilkinsona has raised, I think this would be better as a third-party starter.

**Pull request closed without merging**
