### PR TITLE
CloudWatch metrics autoconfiguration

### PR DESCRIPTION
**Pull request by dkublik**
Hi,
Two weeks ago I added support for CloudWatch to micrometer.
https://github.com/micrometer-metrics/micrometer/commit/b2b13fb9fcca5ef5170cb9b0bb9ce91f93a2fe27
I thought I will PR for autoconfiguration as well :)

issue: #11275

### CODE REVIEW

**Comment by spencergibb** [comment]
Awesome! This replaces a feature that lived in spring cloud previously.

**Comment by dkublik** [comment]
Well,
Locally I tested it with spring-cloud dependencies, but now it's a problem.

In CloudWatchExportConfiguration I used these classes:
org.springframework.cloud.aws.autoconfigure.context.ContextCredentialsAutoConfiguration;
org.springframework.cloud.aws.context.annotation.ConditionalOnMissingAmazonClient;
org.springframework.cloud.aws.core.config.AmazonWebserviceClientFactoryBean;
org.springframework.cloud.aws.core.region.RegionProvider;

to create AWS client, but they are from
org.springframework.cloud:spring-cloud-aws-autoconfigure
org.springframework.cloud:spring-cloud-aws-context
org.springframework.cloud:spring-cloud-aws-core

I guess I shouldn't make boot depending on cloud (or should I?).
In these case - maybe I should move CloudWatchExportConfiguration to org.springframework.cloud:spring-cloud-aws-autoconfigure (it was there till FINCHELY.M4)?
Then of course it won't be together with other metrics configuration.

**Comment by philwebb** [comment]
> I guess I shouldn't make boot depending on cloud (or should I?).

Definitely not I'm afraid. We shouldn't have a cycle between the projects and Spring Cloud needs to depend on Spring Boot. I'd suggest submitting this PR to `spring-cloud-aws`.

Thanks for code! Sorry we can't take it directly in Boot.

**Comment by dkublik** [comment]
I thought so :).
I'll do that,
thank you!

**Comment by devinsba** [comment]
Any word on the status of this? Both of @dkublik 's PR's got rejected because they felt they should be in the other project. Would be nice to know what the resolution path is/was/will be?

**Comment by wilkinsona** [comment]
There's some CloudWatch support in Micrometer now. There's also some Boot 1.5 [auto-configuration for it](https://github.com/micrometer-metrics/micrometer/commit/3af71a2d2ba033baa8147e98d6ae400d4724d141) but that hasn't made it into Boot for 2.0 yet. Is that intentional, @jkschneider?

**Comment by devinsba** [comment]
I am aware of the support in micrometer, I am using a custom starter wrapping the existing micrometer support for cloudwatch. I'd love to delete that in favor of some official starter

**Comment by jkschneider** [comment]
@wilkinsona I think we had decided that the autoconfiguration needs to go in spring-cloud-aws because the CloudWatch integration involves an AWS SDK dependency, and the AWS SDK evolves way too quickly for Boot.

**Comment by dkublik** [comment]
My follow up Pr - is here
https://github.com/spring-cloud/spring-cloud-aws/pull/283
but was also closed (I guess we have PR cycle :) ),

I'm not sure about @spencergibb 's comment " This should go in boot 2.0 but without references to spring-cloud-aws" - so I asked @jkschneider about it as suggested
(@jkschneider - hope you'll forgive me pasting the conversation here - it will be easier to follow up :) )

pr1
pr2
pr3

One more thing - me and my team use this code from not merged PR in our projects - works like charm :)

aws

**Comment by jkschneider** [comment]
@dkublik Thanks for staying on top of this, and glad you are getting some use out of it in the meantime. Reopened spring-cloud/spring-cloud-aws#283. It really does need to go in spring-cloud-aws because of the AWS SDK dependency. My focus has been on getting Boot 2 squared first, knowing that spring-cloud-aws can be released shortly after Boot 2 is complete.

The problem we had with needing a `micrometer.version` prop in the Spring Cloud BOM should be gone now that Boot 2 includes Micrometer in _its_ BOM. These things just needed a little time to shake out.

There are some other concerns around our CloudWatch integration [here](https://github.com/micrometer-metrics/micrometer/issues/303) that I'd also like to address, but will likely need a follow-up Micrometer 1.1.0, because I can't imagine having the bandwidth to get to it before our 1.0 GA release.

cc / @spencergibb

**Pull request closed without merging**
