### PR TITLE
adding property to disable HiddenHttpMethodFilter

### PR DESCRIPTION
**Pull request by ayudovin**
Adding property to disable HiddenHttpMethodFilter.
this [enhancement](https://github.com/spring-projects/spring-boot/issues/13422).

### CODE REVIEW

**Comment by snicoll** [comment]
@ayudovin thanks again for the PR. This issue was already assigned and it's likely that Brian has started to work on something. To avoid duplicate efforts, it would be nice to double check on such issue (by adding a comment before working on it). Let's wait for Brian to look at this one.

**Comment by ayudovin** [comment]
@snicoll, oh, it's my mistake, I'm so sorry. We could delete this pull request if Brian has started working on this enhancement.

**Comment by snicoll** [comment]
No worries @ayudovin, let's wait for Brian's review.

**Comment by bclozel** [comment]
Thanks @ayudovin !

**Pull request closed without merging**
