### PR TITLE
Consider @Primary annotation when using @MockBean, make @MockBean/@SpyBean behave consistently

### PR DESCRIPTION
**Pull request by neiser**
The discussion in #11066 revealed that the proposed solution is not ideal. Based on @alexandreBaronZnk's work, I created another pull request and tried to honor @philwebb's remarks.

I changed that `getBeanName` respects the `@Primary` annotation (and does not simply fail if more than one candidate is found) and I copied the primary flag from the removed bean to the mocked bean. This makes the tests work again (of course I removed the changes in `findCandidateBeans` first).  

I cannot push to @alexandreBaronZnk's branch, I hope it's okay that I created another pull request.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@neiser Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=11077)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=11077) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@neiser Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=11077)!

**Comment by neiser** [comment]
@philwebb Can you explain why the handling of bean registration is so different for `@MockBean` and `@SpyBean` in `MockitoPostProcessor`? I added some TODO comments in the last commit, as the analogous test where you have a primary bean but want to spy a qualified one does not work. 

Note that I didn't change anything in the current behaviour for `@SpyBean`, so it already had some handling for the `@Primary` annotation in `MockitoPostProcessor.determinePrimaryCandidate`, which is only used when registering spies (and not mocks).

This is all quite mysterious to me. I hope you can shed some light on it.

**Comment by philwebb** [comment]
@neiser Spy beans are quite tricky. With standard mocks we can replace the bean definition early and just create a mock instance when the bean is needed. For spy beans we need to allow the standard instance to be created, then wrap it with a spy.

In `registerSpy` we actually just keep track of the definitions. We then have a `SpyPostProcessor` class that gets called after every bean is created. It delegates back to `MockitoPostProcessor.createSpyIfNecessary` to actually wrap the real bean instance in a spy if we know that's what the user wants.

**Comment by neiser** [comment]
@philwebb Thanks for clarifying that. I did some more work to let `@SpyBean` and `@MockBean` behave consistently as far as bean name finding is concerned in `MockitoPostProcessor`. I created an extra class `MockitoBeanNameFinder` for that purpose.

Now `registerSpy` looks similar to `registerMock` besides this post-injection you mentioned. I hope I got it right with this `beanName` and `transformedBeanName` business. 

All Mockito-related tests run through, even the ones additionally created during this pull request. Let's see if I can get the code formatting style right.

Can you review my changes?

**Comment by neiser** [comment]
@philwebb Just wanted to know what the status is. Is there anything I could add (more documentation what I intend with those changes), or write some more testing? Would be a shame if this work is wasted.

**Comment by snicoll** [comment]
@neiser please bear with us, this is a very busy period and we haven't had a chance to review recent submissions. The PR is here so there's nothing wasted.

**Comment by neiser** [comment]
@snicoll do you have an estimate when you or one of your team has time to review this PR?

**Comment by snicoll** [comment]
Not really but RC1 is scheduled for late Jan so we still have plenty of time to consider it. There's no hurry unless I am missing something.

**Comment by neiser** [comment]
@snicoll Happy new year. Any chance you find some time to review this PR?

**Comment by snicoll** [comment]
@neiser thanks. Sorry but RC1 has been eating all my cycles and I haven't had a chance to get back on this one. It is rather involved too and not particularly in my expertise area.

From a design perspective, I don't like the combination of `@Primary` with `beanName` but I haven't found something satisfactory yet. I am afraid the team will have to spend another round on this one.

**Comment by jfisheratwork** [comment]
Wanted to highlight a specific scenario where this can occur.
When using `<groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-batch</artifactId>` in 1.5.4.RELEASE the BatchAutoConfiguration looks for an unqualified datasource. In my test I am trying to MockBean two different Datasources and with the Primary qualifier not being preserved I get `'javax.sql.DataSource' available: expected single matching bean but found 2`

**Comment by bopfermann** [comment]
Any update on this?

**Comment by neiser** [comment]
@snicoll @philwebb  I'm happy to resolve the merge conflicts which have appeared by now. I'd just like to know if there's any chance an updated PR will be reviewed after some reasonable time.

**Comment by philwebb** [comment]
@neiser Sorry this didn't make it into 2.0, we just ran out of time. I'll add it to the 2.1 backlog. There's no need to rebase, we can do that when we look at merging it.

**Comment by neiser** [comment]
@philwebb any update on this? Is there an estimate when this is reviewed?

**Comment by philwebb** [comment]
@neiser It's on the backlog which means we'd like to include it in the next release but I'm afraid I can't give you an estimate for when it might be reviewed.

**Comment by neiser** [comment]
@philwebb We're approaching now one year that this PR is open. Any chance this gets reviewed soon? I'd also consider this more a bug than an enhancement by the way, as using `@Primary` with `@MockBean` is indeed broken (though I haven't checked the most recent Spring Boot release).

**Comment by philwebb** [comment]
Thanks for bearing with us on this one @neiser! I've now pushed a version of it to master so it should be in 2.1. Unfortunately the PR didn't apply that cleanly so I've chopped it up a bit. The tests from your original PR (with some slight formatting changes) are in a5b3a2646bd90bde4fd9b8fa86a3cddaac7ed844. The main code changes are in c777614d8f3a1072b9e3d03acf6adf2f766f9e48 but they've been made directly to the post processor rather than introducing a new class.

Thanks again!

**Comment by philwebb** [comment]
I realized your `@Author` attribution also got lost in the mix. I've just fixed that in 04710373bf3c1a88cf829f52697750f30aa80c23.

**Comment by neiser** [comment]
@philwebb Thanks a lot for merging it!

**Pull request closed without merging**
