### PR TITLE
Add support for Infinispan

### PR DESCRIPTION
**Pull request by eddumelendez**
Include auto-configuration support for Infinispan. It is possible
to specify the caches to create via `spring.cache.cache-names`.
Provider also allow to set configuration file via `spring.cache.config`.

See gh-2633

### CODE REVIEW

**Comment by snicoll** [comment]
@wilkinsona are you ok to add that dependency to `spring-boot-dependencies`? Thanks!

**Comment by wilkinsona** [comment]
@snicoll Thanks for asking. Can we use 7.2.1.Final instead please? 7.2 on went final earlier this week but, given that we're not releasing till September(ish), I think it'll have sufficient time to bed down before we release.

**Comment by snicoll** [comment]
Alright. @eddumelendez no need to change anything. I'll manage that in the review. Thanks!

**Comment by snicoll** [comment]
Infinispan has also JSR-107 support. Working on that now.

**Comment by snicoll** [comment]
Thanks for the PR, please have a look to the polish commit (https://github.com/spring-projects/spring-boot/commit/0a9b8cbb411142b0c24379f32d41b2071f19a2e4)

**Pull request closed without merging**
