### PR TITLE
Allow TraceWebFilter to capture more details

### PR DESCRIPTION
**Pull request by wwadge**
Changes filter to extend from `AbstractRequestLoggingFilter` instead and adds the following properties:

```
management.trace.max_payload_length
management.trace.include_payload
management.trace.include_payload_response
```

The first two map directly to `AbstractRequestLoggingFilter`, the third controls if response payload should be logged.

### CODE REVIEW

**Comment by wwadge** [comment]
I have signed the CLA

**Comment by nodje** [comment]
Would be useful to also include query parameters names & values while you're at it, woudn't it?

**Comment by wwadge** [comment]
Done. These are the exposed properties:
```
management.dump_requests
		management.trace.include.authType
		management.trace.include.client_info
		management.trace.include.contextPath
		management.trace.include.cookies
		management.trace.include.parameters
		management.trace.include.pathInfo
		management.trace.include.payload
		management.trace.include.payload_response
		management.trace.include.querystring
		management.trace.include.userPrincipal
		management.trace.max_payload_length
```

**Comment by nodje** [comment]
Great, thanks~

**Comment by philwebb** [comment]
I think we'll need to rework this a little before we can include it. I'm a little concerned about changing `WebRequestFilter` to extend `AbstractRequestLoggingFilter` and also by the use of `ContentCachingResponseWrapper`.

We really don't want the `WebRequestTraceFilter` to cache each response, that could cause performance issues and increase memory consumption.

It's probably also worth considering extracting all the `management.trace.*` `@Value` injections into a `@ConfigurationProperties` class.

**Comment by wwadge** [comment]
The reason I extended from AbstractRequestLoggingFilter is that there's quite some overlap (though admittedly the ARLF isn't written in a way that makes this subclass very nice)

Re caching each response, I will guard that by making it optional (with the default set to off). My use case is having a filter like stripe.com does whereby user requests/responses are logged completely.

OK re @ConfigurationProperties - I'll rework.

**Comment by wwadge** [comment]
By the way re performance issue, by default max payload captured is set at 50 bytes (this is coming from AbstractRequestLoggingFilter)

**Comment by wwadge** [comment]
Please advise if you want me to remove the dep on AbstractRequestLoggingFilter completely (it will involve some dupe code though from that class)

**Comment by philwebb** [comment]
@wwadge I think it would be good to try to remove the dependency on `AbstractRequestLoggingFilter`, even if it involves a little duplicate code.

RE: The `ContentCachingResponseWrapper`, [this line was the one I was looking at](https://github.com/wwadge/spring-boot/commit/3004c8c9842387ed9bdf8a2015f0b1391491123d#diff-c9516d271fdc667c74b6f48cf2bd7604R116).

**Comment by wwadge** [comment]
Re ContentCachingResponseWrapper, I fixed that in a later commit: https://github.com/wwadge/spring-boot/commit/fbde7f2821cd3ab12d5325a6a9de9e05ff740f06#diff-c9516d271fdc667c74b6f48cf2bd7604R293

I'll break the  dependency on ARLFilter and report back

**Comment by philwebb** [comment]
Thanks!

**Comment by wwadge** [comment]
Done - it's now much closer in implementation to what was there before.

**Comment by wwadge** [comment]
Remerged and re-sync'ed.

**Comment by philwebb** [comment]
I've rebased the code against master and also made some amendments. Code is available here:
https://github.com/philwebb/spring-boot/tree/gh-3948

The primary changes are:
* TraceProperties is now in the same package as the filter
* Includes are specified using a Set of enum values
* Cookies can no longer be exposed (I don't think Jackson will serialize them correctly)
* There's now only a single property for maximum content length
* Some of the map keys have changed

Unfortunately whilst testing with the `SampleActuatorApplication` I discovered that adding request/response content causes malformed JSON exceptions when you hit the trace endpoint more than once. I'm guessing this is because the content itself is JSON. I think we'll need to find a way to escape nested JSON before we can merge this.

**Comment by philwebb** [comment]
I've merged a variant of your original pull-request that provides additional tracing options but doesn't offer full request/response content tracing. We're not too keen on adding full content tracing for the following reasons:

- Using the `ContentCachingRequestWrapper`/`ContentCachingResponseWrapper` classes can consume a lot of memory, meaning they're not ideal for production.
- Content can itself be JSON which makes marshaling problematic. My previous experiments failed when the trace included previously returned JSON content (i.e. hitting `/trace` more than once breaks things).
- Content could be very sensitive and we don't want someone accidentally exposing passwords/credit cards over `/trace`.
- Servlet containers already offer logging facilities which are arguably a better place to record output.

If you feel strongly that content tracing should be considered please feel free to open another issue.

Thanks for the PR!

**Pull request closed without merging**
