### PR TITLE
Auto configure templated welcome page

### PR DESCRIPTION
**Pull request by bbrouwer**
Auto configure templated welcome page #7931

This differs from the previous pull request in that there are no template specific tests. Since I did not change of the template engine code, I made unit tests just for WebMvcAutoConfiguration.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR, @bbrouwer. I'm guess this was quite tricky to test which led to the mock template availability provider in `spring.factories`?

**Comment by bbrouwer** [comment]
It was getting tricky. Each template provider has a very different setup for testing. I could get some to work, but was having trouble getting all of them to work. Also, since I didn't actually change any code in any individual template provider, I figured this would be a good solution. 

Who knows? Maybe other tests can make use of it that don't rely on any specific template provider, but just depend on there being a template provider. 

Also, I've been waiting for the main Spring Boot build to be fixed before I try to get this to work again. It has been broken for quite a while. Is there any word on when it will be fixed so my pull request will succeed to build?

**Comment by snicoll** [comment]
> It has been broken for quite a while. 

What do you mean by quite a while? It's been broken over the week-end due to change in a SNAPSHOT dependency. We'll get it back asap.

**Comment by bbrouwer** [comment]
Perhaps I'm missing something, then. I tried to make this pull request to be part of Spring Boot 2.0, not 1.5. But when I look at the master branch builds in Travis CI, it has been at least 19 days since the master branch has built successfully. As for Concourse CI, I am unable to log in in order to see any details. 

Can you give me some pointers on how I should proceed.

**Comment by snicoll** [comment]
We don't use Travis anymore (the [last build was 17 days ago](https://travis-ci.org/spring-projects/spring-boot/builds)). See #10693. If you have more questions, please ask on Gitter.

**Comment by bbrouwer** [comment]
Is there any more that you want to see before merging this?

**Comment by wilkinsona** [comment]
@bbrouwer No, I don't think so. Thank you. As shown by the assigned milestone we're planning to merge this in RC1.

**Comment by bbrouwer** [comment]
Do you want me to take a crack at adding some mention of this to the documentation. It looks like section 27.1.5 Static Content would be a good place to mention it.

**Comment by wilkinsona** [comment]
That'd be great. Yes please! 27.1.5 feels like the right place to me as that's where welcome page support is mentioned.

**Comment by wilkinsona** [comment]
Thanks for the PR, @bbrouwer, and for the offer of the documentation changes. There's no need for those now as, having rebased this on top of the changes made for #11094, I've take care of them and done a little polishing in https://github.com/spring-projects/spring-boot/commit/2b1d1cd317636e2e24a10e12f270fc88b1893688.

**Pull request closed without merging**
