### PR TITLE
Update undertow to the last branch 2.0.9

### PR DESCRIPTION
**Pull request by marcomsousa**
Update undertow 2.0.9 the the last banch for Spring Boot 2.1.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@marcomsousa Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=13279)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=13279) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by snicoll** [comment]
@marcomsousa we have a semi-automated process for upgrading dependencies so we usually don't accept PRs that only changes the version.

In this particular case, you're effectively offering to implement #12243  but it needs more than just upgrading the version. Are you willing to rework your PR to fix the build failure and adapt the documentation?

**Comment by wilkinsona** [comment]
Thanks for opening your first Spring Boot PR. There's a little bit more to this to get Tomcat and Undertow using Servlet 4 while Jetty remains on Servlet 3.1. I've got that work in progress in [this branch](https://github.com/wilkinsona/spring-boot/commit/ca55008d2c28210f4b37534796f976dc94241f98) that will be merged once the next Tomcat 9.0.x release happens. Thanks anyway.

**Comment by clemp6r** [comment]
There have been several Tomcat releases since, maybe the bug has been fixed?

**Comment by wilkinsona** [comment]
@clemp6r Which bug are you referring to? This pull request was about upgrading from Undertow 1.4 to 2.0. That's been done as part of a broader piece of work in 2.1 that also upgraded to Tomcat 9.

**Comment by clemp6r** [comment]
The regression you're referring in https://github.com/spring-projects/spring-boot/pull/13342#issuecomment-394282805 that prevented merging your branch.

> Merging it is currently blocked by a regression that'll be fixed in the next Tomcat 9.0.x release.

But as I understand Undertow 2.0 will be available in 2.1, so it's OK.

**Pull request closed without merging**
