### PR TITLE
Added Cassandra support for Spring Boot

### LINKED ISSUE #2064: Add a spring-boot-starter-data-cassandra
Like the spring-boot-starter-data-mongodb but using Spring Data Cassandra.
I could code it and send a PR if that's fine with you.

### PR DESCRIPTION
**Pull request by jdubois**
- Auto-configuration of the Cassandra driver
- Auto-configuration (basic for the moment) of Spring Data Cassandra
- Healthcheck for Cassandra

Fix #2064

### CODE REVIEW

**Comment by philwebb** [comment]
@jdubois I'm sure we've asked before, but could you just confirm that you have signed the CLA?

**Comment by jdubois** [comment]
@philwebb yes, but that was a loooonnng time ago (I'm a former SpringSource employee anyway!). I'm ready to sign it again if needed.

**Comment by philwebb** [comment]
Would you mind. Just to be safe.

**Comment by jdubois** [comment]
I just signed it again and got:
"Hello Julien Dubois
Thank you but our records indicate that you have already accepted the individual contributor agreement..."
So it should be safe!

**Comment by philwebb** [comment]
Great. Thanks!

**Comment by covolution** [comment]
What's the status of this pull request?  It looks like the merge conflicts were just pom issues.

**Comment by wilkinsona** [comment]
It's currently planned for 1.3.0, specifically 1.3.0.RC1.

**Comment by covolution** [comment]
When is 1.3.0.RC1 planned? (I did google for a release schedule but didn't find it).  You are currently on 1.3.0.BUILD-SNAPSHOT but I assume its not available in the snapshot yet?

**Comment by snicoll** [comment]
The current milestones date are [available here](https://github.com/spring-projects/spring-boot/milestones). The issue is open and no related commits are present on this page so you can safely assume it's not available yet. You can try however the fork where this PR was produced.

**Comment by philwebb** [comment]
I've made a start on this (see https://github.com/philwebb/spring-boot/tree/pr/2214 for the changes so far). I think we need to look into adding a sample and some tests before we merge.

Perhaps we can use https://github.com/jsevellec/cassandra-unit

**Comment by jdubois** [comment]
@philwebb we have support for CassandraUnit in JHipster, too -> I'm not sure I have enough time to work on this, but we could also migrate that part of JHipster to Spring Boot

BTW, I will have improvements to add:
- This PR is a bit old, and the code as been greatly improved since (it's in the latest JHipster version)
- For internal projects in my company we have greatly improved CassandraUnit, and this is also something I would like to be easily available for Spring Boot users

**Comment by eddumelendez** [comment]
I didn't notice that this PR already exist. I was working in my own implementation. Would like to update and work on this. /cc @philwebb @jdubois

**Comment by philwebb** [comment]
@eddumelendez Check out https://github.com/philwebb/spring-boot/tree/pr/2214, that's the reworked version of this one.

**Comment by eddumelendez** [comment]
Sorry for the delay I have submitted my branch based on yours @philwebb https://github.com/eddumelendez/spring-boot/commit/31ec950b6c359d9b912b325d960f1deaf173c10b

**Comment by artgo** [comment]
Folks, any plans to merge it any time soon?

**Comment by wilkinsona** [comment]
@artgo That question's already been asked above and there's been no change since then

**Comment by artgo** [comment]
@wilkinsona  got it, sorry for some noise.
@eddumelendez is there a PR for your branch? :)
I'd be happy to vote on it :)

**Comment by eddumelendez** [comment]
@artgo AFAIK @philwebb is merging changes from this PR and my branch based on his (https://github.com/eddumelendez/spring-boot/commit/5a9e39f6160fee956fc7bc635a4ad909aef3cf05) we need to wait till he will finish to review and polish the code.

**Comment by philwebb** [comment]
@eddumelendez @jdubois Thanks for the contribution. I finally found time to tweak the last few bits and merge.

**Pull request closed without merging**
