### PR TITLE
Remove code deprecated in 2.1

### PR DESCRIPTION
**Pull request by Gigaxel**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Gigaxel Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16013)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16013) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Gigaxel Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16013)!

**Comment by snicoll** [comment]
@Gigaxel thank you for opening your first PR. It looks like you're trying to rebase and every attempt sends an email to a large number of users. To avoid further notifications, please wait for a review and we can take care of the rebase ourselves if necessary. Thank you.

**Comment by Gigaxel** [comment]
@snicoll I am sorry, but I've ran into a few issues with my machine. I am sorry for the inconvenience, and I hope it won't happen again.

**Comment by snicoll** [comment]
@Gigaxel thank you very much for making your first contribution to Spring Boot. Your contribution is now merged on `master` with a [polish commit](https://github.com/spring-projects/spring-boot/commit/715db153e35788c91fafb8d191447fcef92933ef).

**Pull request closed without merging**
