### PR TITLE
add nitrite spring boot starter

### PR DESCRIPTION
**Pull request by FunThomas424242**
Hello,

I have read the hints for pull requests - thanks :)

I have only 2 cents for your README.adoc in the subproject spring-boot-starter.
I have added 1 line to the table of third party spring-boot-starters: Nitrite Database
(Its my first starter project, i hope its meet your quality of starter code.)
But, here in the pull request i have only added 2 links to the nitrite-spring-boot-starter project. 

Sorry for my english.

Thanks

Thomas

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@FunThomas424242 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=19196)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=19196) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@FunThomas424242 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=19196)!

**Comment by mbhave** [comment]
I couldn't find a `nitrite-spring-boot-starter` version that's compatible with Spring Boot 2.1.x. I think this should go in the `2.2.x` milestone.

**Comment by mbhave** [comment]
@FunThomas424242 Thank you for making your first contribution to Spring Boot. This has now been merged into 2.2.x and master.

**Comment by FunThomas424242** [comment]
@mbhave Thank you very much.

**Pull request closed without merging**
