### PR TITLE
Support new Micrometer NewRelicConfig eventType properties

### PR DESCRIPTION
**Pull request by neiljpowell**
New categorical `eventType` to publish New Relic metrics and
`meterNameEventTypeEnabled(true)` for compatibility with previous
behavior of publishing an `eventType` per Meter/metric name.

NewRelic's own agents publish metrics to `eventTypes` aligned with broader
categories. To align with their recommendation the default behavior is
to publish metrics under a "SpringBootSample" category. When doing so,
additional context is provided by including "metricName" and "metricType" attributes.
See: https://docs.newrelic.com/docs/insights/insights-data-sources/default-data/insights-default-data-other-new-relic-products

@shakuzen
@breedx-nr

### CODE REVIEW

**Comment by neiljpowell** [comment]
Build failures appear to be issues unrelated to this PR. After merging in master, error is now from the Spring Boot Docs project:
Plugin org.asciidoctor:asciidoctor-maven-plugin:1.6.0 or one of its dependencies could not be resolved: Could not find artifact io.spring.asciidoctor:spring-asciidoctor-extensions-spring-boot:jar:0.3.0.RELEASE in central (https://repo.maven.apache.org/maven2)
@wilkinsona can you confirm?

**Comment by wilkinsona** [comment]
Confirmed. Sorry for the inconvenience. The problem should be fixed in master now. Don't worry about the build failure as the changes proposed here are built before the docs module where the problem is occurring.

**Comment by shakuzen** [comment]
Just for reference, https://github.com/micrometer-metrics/micrometer/pull/1588 is the pull request that added these config properties to Micrometer 1.3. Once these changes are made in Spring Boot, feel free to also send a pull request to Micrometer's `micrometer-spring-legacy` module on the `1.3.x` branch if you're interested @neiljpowell.

**Comment by neiljpowell** [comment]
@wilkinsona Thanks for the quick confirmation and note. I'll still try another rebase from master to see if it will build cleanly.  @shakuzen Thanks for the review and reference to the initiating PR.  I'll be happy to get the legacy project updated.

**Comment by philwebb** [comment]
Thanks very much for the PR @neiljpowell. This has now been merged to master and should be in RC1.

**Pull request closed without merging**
