### PR TITLE
Upgrade to Testcontainers 1.18.3

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks @eddumelendez but, as described in the PR template, we don't need PR for these. Our semi automated tool will pick this up in due course.

**Comment by eddumelendez** [comment]
sorry for the noise with the PR. I didn't see the notification those days so probably it is configured to run every week or so.

**Comment by snicoll** [comment]
It is semi automated so we invoke it manually and double check what it suggests. We usually do this closer from a release so it's going to happen soon.

**Comment by eddumelendez** [comment]
Thank you, @snicoll !

**Pull request closed without merging**
