### PR TITLE
Add access to current trace to be abble to add some information of request execution

### PR DESCRIPTION
**Pull request by gavlyukovskiy**
In our company we are saving some information (performed sqls, time spent on different request stages, etc.) inside of trace, so maybe it will be useful to someone else to have this abbility.

This PR adds unique identifier to each trace, adds trace information when request starts, which can be used if request stucks (maybe we should add status[executing, completed] to the trace info as well). For this reason I have replaced timestamp with two Date fields - started and ended. Also I've looked at https://github.com/spring-projects/spring-boot/pull/6579 and replaced timestamp with date pattern.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gavlyukovskiy Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7512)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7512) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@gavlyukovskiy Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7512)!

**Comment by marcingrzejszczak** [comment]
Hi @gavlyukovskiy are you familiar with the Spring Cloud Sleuth project? It does what you have done in the PR and much, much more. You can check out the docs - cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html and in case of any questions you can ping me on Gitter - https://gitter.im/spring-cloud/spring-cloud-sleuth

**Comment by philwebb** [comment]
Thanks for the PR but I think this overlaps too much with Spring Cloud Sleuth and we're better off recommending the use of that project rather than extending the core of Spring Boot.

**Pull request closed without merging**
