### PR TITLE
add functionality to force stop spring boot application

### PR DESCRIPTION
**Pull request by gauravbrills**
- [X] I have signed the CLA

Add functionality to forces Stop kill Spring boot Application .This is required when the spring boot application is not able to gracefully shutdown .

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. Could you please add some tests for the new functionality? The existing tests can be found in [SysVinitLaunchScriptIT.java](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-integration-tests/spring-boot-launch-script-tests/src/test/java/org/springframework/boot/launchscript/SysVinitLaunchScriptIT.java). Tests for force-stop when the service is stopped and when it's started would be appropriate.

**Comment by gauravbrills** [comment]
sure @wilkinsona let me work on adding those :+1:

**Comment by gauravbrills** [comment]
@wilkinsona added the test cases there and checked in  , running small issues with running the same in docker api 1.24 in windows .But will try to work it out .

**Comment by gauravbrills** [comment]
@wilkinsona I did add the test cases and when running them on windows based docker get the below output in the test cases results for all test  cases old and new .Somehting to do with the test-functions script not found .Not sure the docker-java lib is copying it on the container or not ,Any idea or config I am missing for the test cases .

`
./launch-with-single-command-line-argument.sh: line 1: ./test-functions.sh
: No such file or directory
./launch-with-single-command-line-argument.sh: line 2: install_service
: command not found
./launch-with-single-command-line-argument.sh: line 3: start_service: command not found
./launch-with-single-command-line-argument.sh: line 4: await_app: command not found
`

**Comment by wilkinsona** [comment]
Docker and Windows sounds like a match made in hell to me. Don't worry about getting the tests running. I'll make sure that they're fine as part of merging this. Thanks again for the PR.

**Comment by pivotal-issuemaster** [comment]
@gauravbrills Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=6223) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@gauravbrills Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=6223)!

**Comment by philwebb** [comment]
Need to support timeout property. See https://github.com/spring-projects/spring-boot/commit/509be7474dd53e72e9308c1f0a288cb02bf6d0b4#commitcomment-20326910

**Comment by philwebb** [comment]
Managed to mess up the latest commit and drop the kill args

**Comment by gauravbrills** [comment]
@philwebb has this change been closed and planned for 1.5.0 ?

**Comment by wilkinsona** [comment]
@gauravbrills Yes. It's included in 1.5.0.RC1.

**Pull request closed without merging**
