### PR TITLE
Allow to configure Tomcat/Undertow rotate property

### PR DESCRIPTION
**Pull request by mouminoux**
Add a property to enable or disable tomcat access log rotation.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mouminoux Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7225)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7225) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mouminoux Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7225)!

**Comment by snicoll** [comment]
Thanks for the PR, I've polished it to also add such support to Undertow.

**Comment by mouminoux** [comment]
@snicoll Do you think it's possible to add this enhancement to 1.4.x ?

**Comment by snicoll** [comment]
You've created that PR from the `1.5.x` branch which looks sensible to me.

**Pull request closed without merging**
