### PR TITLE
Prettify the default logging output when log4j2 is used.

### PR DESCRIPTION
**Pull request by tsachev**
Added `WhitespaceThrowablePatternConverter` similar to the one for logback. Configured for both console and file pattern.
  Added ansi styles for log4j2 default console pattern.

Fixes gh-3548

### CODE REVIEW

**Comment by wilkinsona** [comment]
The changes in https://github.com/tsachev/spring-boot/commit/a35eb8b22ff32338796d90f2a765c4d971511e2d result in some unwanted characters appearing in the out put in Eclipse's console. Removing `log4j2.xml` from `spring-boot-sample-actuator-log4j2` and running it produces output like the following:

```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                        

[m2015-07-22 18:07:49.197[m [32m INFO[m [35m11894[m [m---[m [m[           main][m [36ms.a.l.SampleActuatorLog4J2Application   [m [m:[m Starting SampleActuatorLog4J2Application on aw-rmbp.local with PID 11894 (/Users/awilkinson/dev/spring/spring-boot/spring-boot-samples/spring-boot-sample-actuator-log4j2/target/classes started by awilkinson in /Users/awilkinson/dev/spring/spring-boot/spring-boot-samples/spring-boot-sample-actuator-log4j2)
[m2015-07-22 18:07:49.230[m [32m INFO[m [35m11894[m [m---[m [m[           main][m [36mationConfigEmbeddedWebApplicationContext[m [m:[m Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@45f45fa1: startup date [Wed Jul 22 18:07:49 BST 2015]; root of context hierarchy
[m2015-07-22 18:07:49.664[m [32m INFO[m [35m11894[m [m---[m [m[           main][m [36mo.s.b.f.s.DefaultListableBeanFactory    [m [m:[m Overriding bean definition for bean 'beanNameViewResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
[m2015-07-22 18:07:50.176[m [32m INFO[m [35m11894[m [m---[m [m[           main][m [36ms.b.c.e.t.TomcatEmbeddedServletContainer[m [m:[m Tomcat initialized with port(s): 8080 (http)
[m2015-07-22 18:07:50.278[m [32m INFO[m [35m11894[m [m---[m [m[           main][m [36mo.a.c.c.StandardService                 [m [m:[m Starting service Tomcat
[m2015-07-22 18:07:50.279[m [32m INFO[m [35m11894[m [m---[m [m[           main][m [36mo.a.c.c.StandardEngine                  [m [m:[m Starting Servlet Engine: Apache Tomcat/8.0.23
[m2015-07-22 18:07:50.394[m [32m INFO[m [35m11894[m [m---[m [m[ost-startStop-1][m [36mo.a.c.c.C.[.[.[/]                       [m [m:[m Initializing Spring embedded WebApplicationContext
[m2015-07-22 18:07:50.394[m [32m INFO[m [35m11894[m [m---[m [m[ost-startStop-1][m [36mo.s.w.c.ContextLoader                   [m [m:[m Root WebApplicationContext: initialization completed in 1166 ms
```

**Comment by tsachev** [comment]
@wilkinsona I have updated the PR and added noConsoleNoAnsi=true. But in idea `System.console()` returns `null` too.
The console in idea supports ansi.
Idea solves this by passing `--spring.output.ansi.enabled=always` on the command line so I see pretty output even with logback.

Do you think a custom converter should be added that respects the `AnsiOutput` for log4j2 too? (like ColorConverter for logback)

**Comment by wilkinsona** [comment]
@tsachev Looks good now. Thanks!

> Do you think a custom converter should be added that respects the AnsiOutput for log4j2 too? (like ColorConverter for logback)

That sounds good to me. Would you like to tackle it? If so, as part of this PR or as a separate one?

**Comment by tsachev** [comment]
I will do it as part of this PR.

**Comment by tsachev** [comment]
@wilkinsona the PR is updated with color converter instead of `noConsoleNoAnsi`.

**Comment by wilkinsona** [comment]
The output doesn't look right with the latest changes. For example, running the actuator log4j2 sample with `mvn spring-boot:run` produces output like this:

```
%.S.S.S.S.ServletRegistrationBeanlr %.%.%.%.%.ServletRegistrationBeanlr org.springframework.boot.context.embedded.ServletRegistrationBeanlr -.-.-.-.-.ServletRegistrationBeanlr [.s5.b5.c5.e5.ServletRegistrationBeanlr %.spri0.}.}.}.ServletRegistrationBeanlr :.:.:.:.:.ServletRegistrationBeanlr Mapping servlet: 'dispatcherServlet' to [/]
%.S.S.S.S.FilterRegistrationBeanlr %.%.%.%.%.FilterRegistrationBeanlr org.springframework.boot.context.embedded.FilterRegistrationBeanlr -.-.-.-.-.FilterRegistrationBeanlr [.s5.b5.c5.e5.FilterRegistrationBeanlr %.spri0.}.}.}.FilterRegistrationBeanlr :.:.:.:.:.FilterRegistrationBeanlr Mapping filter: 'metricFilter' to: [/*]
%.S.S.S.S.FilterRegistrationBeanlr %.%.%.%.%.FilterRegistrationBeanlr org.springframework.boot.context.embedded.FilterRegistrationBeanlr -.-.-.-.-.FilterRegistrationBeanlr [.s5.b5.c5.e5.FilterRegistrationBeanlr %.spri0.}.}.}.FilterRegistrationBeanlr :.:.:.:.:.FilterRegistrationBeanlr Mapping filter: 'characterEncodingFilter' to: [/*]
%.S.S.S.S.FilterRegistrationBeanlr %.%.%.%.%.FilterRegistrationBeanlr org.springframework.boot.context.embedded.FilterRegistrationBeanlr -.-.-.-.-.FilterRegistrationBeanlr [.s5.b5.c5.e5.FilterRegistrationBeanlr %.spri0.}.}.}.FilterRegistrationBeanlr :.:.:.:.:.FilterRegistrationBeanlr Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
%.S.S.S.S.FilterRegistrationBeanlr %.%.%.%.%.FilterRegistrationBeanlr org.springframework.boot.context.embedded.FilterRegistrationBeanlr -.-.-.-.-.FilterRegistrationBeanlr [.s5.b5.c5.e5.FilterRegistrationBeanlr %.spri0.}.}.}.FilterRegistrationBeanlr :.:.:.:.:.FilterRegistrationBeanlr Mapping filter: 'webRequestLoggingFilter' to: [/*]
%.S.S.S.S.FilterRegistrationBeanlr %.%.%.%.%.FilterRegistrationBeanlr org.springframework.boot.context.embedded.FilterRegistrationBeanlr -.-.-.-.-.FilterRegistrationBeanlr [.s5.b5.c5.e5.FilterRegistrationBeanlr %.spri0.}.}.}.FilterRegistrationBeanlr :.:.:.:.:.FilterRegistrationBeanlr Mapping filter: 'applicationContextIdFilter' to: [/*]
```

**Comment by tsachev** [comment]
I noticed this sometimes too. I think it is because the log4j2 annotation processor is not invoked. If you do mvn compile in the spring-boot module do you see the  same thing?

**Comment by wilkinsona** [comment]
I guess you mean `mvn package` or `mvn test` so that `Log4J2LoggingSystemTests` are run? They produce similar output: 

```
/var/folders/zq/v6xkr2696kv05jbf3bddt9680000gn/T/junit580433562588026725/junit7076080611307915893/tmp.log 2015-08-05 13:44:11.650] service - ????  INFO [main] --- Log4J2LoggingSystemTests: Hello world
%.S.S.S.S.Log4J2LoggingSystemTestslr %.%.%.%.%.Log4J2LoggingSystemTestslr ?.?.?.?.?.Log4J2LoggingSystemTestslr -.-.-.-.-.Log4J2LoggingSystemTestslr [.s5.b5.l5.l5.Log4J2LoggingSystemTestslr %.spri0.}.}.}.Log4J2LoggingSystemTestslr :.:.:.:.:.Log4J2LoggingSystemTestslr Hello world
2015-08-05 13:44:11.689  INFO ???? --- [main] o.s.b.l.l.Log4J2LoggingSystemTests       : Hello world
%.S.S.S.S.Log4J2LoggingSystemTestslr %.%.%.%.%.Log4J2LoggingSystemTestslr ?.?.?.?.?.Log4J2LoggingSystemTestslr -.-.-.-.-.Log4J2LoggingSystemTestslr [.s5.b5.l5.l5.Log4J2LoggingSystemTestslr %.spri0.}.}.}.Log4J2LoggingSystemTestslr :.:.:.:.:.Log4J2LoggingSystemTestslr Hello
```

**Comment by tsachev** [comment]
I have committed wrong converter key (guess I was sleepy when pushing last time). Can you try now?

**Comment by wilkinsona** [comment]
Looks good now. Thanks.

**Comment by wilkinsona** [comment]
Merged in https://github.com/spring-projects/spring-boot/commit/632d78b6fbb84f5a0683c42a8e134054c2b2f873. Thanks for the PR.

**Pull request closed without merging**
