### PR TITLE
Simplify code

### PR DESCRIPTION
**Pull request by 785172550**
as @philwebb suggestion in #18436 ,  improve weakness code submit as another PR

### CODE REVIEW

**Comment by 785172550** [comment]
@philwebb , could you help me solve the build error, it says: `Could not resolve dependencies for project org.springframework.boot:spring-boot-test-support:jar:2.2.0.BUILD-SNAPSHOT` , but I don't change the pom file. what can I do?

**Comment by wilkinsona** [comment]
@785172550 That jar isn't published as it's only used in support of Spring Boot's own tests. You need to build it and install it into your local Maven cache. You can do so with the following command:

```
./mvnw -f spring-boot-project/spring-boot-tools/spring-boot-test-support install
```

**Comment by 785172550** [comment]
hi @wilkinsona , I mean this is error makes Concourse CI build failure, and I want to pass the CI build job

**Comment by wilkinsona** [comment]
Sorry, I misread the error message. The failure is occurring because Spring Data has upgraded to Spring Framework 5.2.0 which has not yet been synced to Maven Central. There's nothing that you need to do as it will sort itself out in due course.

**Comment by philwebb** [comment]
Thanks @785172550 for your first contribution to Spring Boot. This has now been merged into master 👍

**Comment by 785172550** [comment]
@philwebb It isa good start, hope I actually did something for it, and will focus more on Spring Boot

**Comment by 785172550** [comment]
@philwebb how about another PR #16998 what else do Ishould do？

**Comment by philwebb** [comment]
@785172550 We have an [`status: ideal-for-contribution`](https://github.com/spring-projects/spring-boot/labels/status%3A%20ideal-for-contribution) label if you're interested in submitting other PRs.

**Pull request closed without merging**
