### PR TITLE
added structurizr starter

### PR DESCRIPTION
**Pull request by klu2**
No issue, just a link to a new starter-project for spring boot

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@klu2 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=13540)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=13540) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@klu2 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=13540)!

**Comment by klu2** [comment]
Thanks for taking time in reviewing the code - all issues are fixed there. I intentionally linked the sub-module for the spring starter project as the other one is not spring-related (it's a plain kotlin extension), but if you're fine with it, we can also link the root project

**Comment by snicoll** [comment]
Thanks for the feedback @klu2 !

**Pull request closed without merging**
