### PR TITLE
Reduce method visibility in EndpointDiscovererTests

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

this PR fixes the current build.

Cheers,
Christoph

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks a lot @dreis2211

**Comment by wilkinsona** [comment]
Goodness me, I made the same mistake twice in one morning 🤦‍♂. Thanks, @dreis2211!

**Comment by snicoll** [comment]
If that's of any comfort I was about to do it again too for the stuff I've just merged if I didn't notice that PR 😅

**Comment by dreis2211** [comment]
Don't we all introduce checkstyle errors once in a while? Don't worry :)

**Pull request closed without merging**
