### PR TITLE
Inclusing of Hazelcast in starters and samples

### PR DESCRIPTION
**Pull request by neilstevenson**
Hazelcast already has Spring Boot support.

This augments this with a `spring-boot-starter-data-hazelcast`
and a `spring-boot-sample-data-hazelcast` demonstrating the use of this.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@neilstevenson Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7702)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7702) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@neilstevenson Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7702)!

**Comment by snicoll** [comment]
I'd rather wait for this to be part of the official Spring Data release train. @olivergierke any ETA for this?

**Comment by olivergierke** [comment]
Not yet, no. We usually keep projects maintaining the code and releases outside the release train for a while as an inclusion creates quite a bit of additional synchronization efforts for ourselves for the releases. I guess I'd suggest to apply the same strategy to a Boot integration, i.e. shipping that as external Boot integration for now.

**Comment by snicoll** [comment]
@olivergierke thanks. 

@neilstevenson  feel free to submit the idea to Hazelcast and please make sure to review the [naming rules for 3rd party starters](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) first. Thanks for the PR!

**Comment by neilstevenson** [comment]
@snicoll 
Just to confirm, you want `hazelcast-spring-boot-sample-data` instead of `spring-boot-sample-data-hazelcast` ?

Are there plans to rename the existing samples, such as `spring-boot-sample-data-mongodb` so they are consistently named ?

**Comment by snicoll** [comment]
I am not following.

We're not going to include that sample here until Hazelcast joins officially the release train. Feel free to provide one in hazelcast itself in the meantime and, as always, we'd like 3rd party modules do not start with `spring-boot`. Does that answer the question?

**Pull request closed without merging**
