### PR TITLE
CRaSH Web connector support

### LINKED ISSUE #6233: Expose CRaSH web connector
It will be very nice to enable in configuration the CRaSH web UI in the same way as H2 Console.

### PR DESCRIPTION
**Pull request by the-fine**
This is my first pull request to an oss, so please be gentle :)

added web connector to CRaSH auto config
added web connector to shell properties
added crash web connector to actuator sample app

Will resolves #6233 

Still have one issue needed to resolve:
`WebPluginLifeCycle` bean which is needed for `CRaSHConnector` implements `ServletContextListener` and calls `getClassLoader` while `contextInitialized` runs.
This generates the following exception:

```
java.lang.UnsupportedOperationException: Section 4.4 of the Servlet 3.0 specification does not permit this method to be called from a ServletContextListener that was not defined in web.xml, a web-fragment.xml file nor annotated with @WebListener
	at org.apache.catalina.core.StandardContext$NoPluggabilityServletContext.getClassLoader(StandardContext.java:6694)
	at org.crsh.plugin.WebPluginLifeCycle.contextInitialized(WebPluginLifeCycle.java:101)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4714)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5178)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Not sure how to tackle this, will appreciate some assistance.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@the-fine Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=6577)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=6577) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@the-fine Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=6577)!

**Comment by philwebb** [comment]
We might be able to subclass `WebPluginLifeCycle` and add `@WebListener` or more likely we'll need to find a way to trigger it from Spring Boot directly rather than as a `ServletContextListener`.

This looks like it would be a nice addition for 1.5 but it might be a little while before we can get to it. We're currently trying to close out all the bugs we've introduced in 1.4 :)

**Comment by the-fine** [comment]
@philwebb  Subclassing WebPluginLifeCycle won't work, CRaSHConnector(the class that has ServerEndpoint annotation) uses a static method on it.
Can you point me to how can i trigger it directly? Or maybe how to initialize it not as a noPluggabilityListener?
Thanks!

**Comment by philwebb** [comment]
@the-fine Unfortunately it doesn't seem possible to do either of the things that I suggested. It seems that `WebPluginLifeCycle` can never be registered programmatically via the Servlet 3.0 API (the way that Spring Boot currently does things).

Looking at `WebPluginLifeCycle` in a little more detail it seems there might be other problems with that class. It appears to be making a hard assumption that WAR packaging is used (often not the case with Boot).

I'm not too familiar with the internals of CRaSH, but perhaps we need an alternative to `CRaSHConnector` that gets the `PluginContext` from a `PluginLifeCycle` Spring Bean rather than the `WebPluginLifeCycle`. Spring Boot by default will auto-configure its own `CrshBootstrapBean` class (an implementation that's tied to the Spring lifecycle).

Unfortunately `CRaSHConnector` is currently quite tied to `WebPluginLifeCycle`. Perhaps the CRaSH team could extract a `getPluginContext` method that you could then override.

**Comment by wilkinsona** [comment]
>  It appears to be making a hard assumption that WAR packaging is used

CRaSH does that in [other places too](https://github.com/crashub/crash/blob/1.3.2/shell/src/main/java/org/crsh/vfs/spi/url/Node.java#L151-L155):

```java
} else if (f.getName().endsWith(".jar")) {
    mergeEntries(new URL("jar:" + url + "!/"));
} else {
    // WTF ?
}
```

Given that the project seems to be dormant, I think we should seriously consider dropping support for it in 2.0.

**Comment by wilkinsona** [comment]
Thanks for the PR, @the-fine. With some regret, we've decided to remove support for CRaSH in 2.0. See #7006.

**Pull request closed without merging**
