### PR TITLE
Use MessageSource to interpolate bean validation messages

### PR DESCRIPTION
**Pull request by nosan**
see gh-3071

#### Limitation

`MessageSourceInterpolatorDelegate` does not support `\` escape character. The escape character is not supported because there is no way to configure`PropertyPlaceholderHelper` with it.
Is it possible to add escape support in `Spring Framework`? 

Thanks

### CODE REVIEW

**Comment by philwebb** [comment]
I've raise https://github.com/spring-projects/spring-framework/issues/23348 to look at extending `PropertyPlaceholderHelper`

**Comment by nosan** [comment]
Thanks, @philwebb  !

**Comment by nosan** [comment]
Hi @philwebb,

I did some research related to this issue, and my idea to use `PropertyPlaceholderHelper`  was doomed initially.

I thought if `PropertyPlaceholderHelper` had escape support it would be possible to
resolve parameters via `MessageSource`, but it is not possible because [Bean Validation Specification](https://beanvalidation.org/2.0/spec/#validationapi-message)
has quite a specific behavior of interpolating messages and of course, `PropertyPlaceholderHelper` would not be able to support such behavior. 

I made a comparison between `Bean Validation` and `Apache StringSubstitutor`, and of course, they have different behavior and most probably `PropertyPlaceholder` would have something different.

| Message Template  | Bean Validation  |  Apache StringSubstitutor |
|---|---|---
| {foo} |{foo}   |  {foo} |
| \\\\{foo}  |\\{foo}   | \\{foo}  |
|  \\{foo} | \\{foo}  |  {foo} |
|  {foo\\} | {foo\\}  |  {foo\\} |
|  \\{foo\\} | {foo}  |  {foo\\} |

I think https://github.com/spring-projects/spring-framework/issues/23348 should be closed, as it would not help us here.

**Comment by nosan** [comment]
Currently, I'm thinking of another variant of how it could be solved.

**Comment by nosan** [comment]
PR has been updated and ready for the review.
Thanks in advance!

**Comment by wilkinsona** [comment]
Thanks very much, @nosan, both for the PR and for your patience while we found time to process it.

**Comment by nosan** [comment]
No problem at all @wilkinsona
Thanks a lot.

**Pull request closed without merging**
