### PR TITLE
Added support for data source proxying.

### PR DESCRIPTION
**Pull request by gavlyukovskiy**
Autoconfigured to indicate p6spy, datasource-proxy, flexy-pool by default and wrap autoconfigured data source.
Supported to define custom data source proxy or change order of proxying if multimple libraries found using `spring.datasource.proxyType`, disables proxying if empty.
Added ProxyDataSourcePoolMetadataProvider to get metrics from the real data source.

Fixes https://github.com/spring-projects/spring-boot/issues/7863.

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks for the PR. Unfortunately I think that there might be a few problems with the approach.

The first is that the existing datasource beans that get exposed are bound to `@ConfigurationProperties`. If we return proxy variant of those beans then the properties won't get bound correctly.

The second problem is that the `DataSourceBuilder` is now automatically creating proxy `DataSource` instances. I think that this something that the user should opt into at the builder level, rather than it being automatic.

I'm not sure on the best way to fix these issue. Perhaps we can use a `BeanPostProcessor` to replace the `DataSource` bean as late as possible. That would also remove the need for all the additional pool specific `DataSource` auto-configuration.

**Comment by vpavic** [comment]
> Perhaps we can use a BeanPostProcessor to replace the DataSource bean as late as possible. That would also remove the need for all the additional pool specific DataSource auto-configuration.

I've started sketching something along those lines a few weeks ago but didn't have time to round it off into a PR. My approach was to introduce `DataSourceDecorator` contract and provide some implementations out of the box (for proxy-datasource, p6spy, etc) while also allowing users to easily provide their own decorators. Registered decorators would be collected and applied to `DataSource` by a `BeanPostProcessor` which could also support ordering decorators. Thoughts on this @philwebb?

**Comment by gavlyukovskiy** [comment]
Thanks for the answer, @philwebb, @vpavic.

@philwebb I tried to minimize breaking changes so my proposal is based on two conclusions:
1. Keep actual type of data source bean is important, someone might be injecting explicit `HikariDataSource`. For that reason I have rejected approach with `BeanPostProcessor` which also a bit easier.
2. Settings done in data source specific configurations `Dbcp`, `Dbcp2` and `Tomcat` also important.

@vpavic good point about `DataSourceDecorator` it removes the need of worst part - getting real data source using reflection. I tried to keep metrics working, with `DataSourceDecorator` it is easy to get real data source instance, also for user code that may rely on the real data source.

**Comment by gavlyukovskiy** [comment]
@philwebb is not doing automatic proxying related just for `DataSourceBuilder` usage or for autoconfiguration sa well?

**Comment by gavlyukovskiy** [comment]
> existing datasource beans that get exposed are bound to @ConfigurationProperties. If we return proxy variant of those beans then the properties won't get bound correctly.
are you talking about this part?
```
String validationQuery = databaseDriver.getValidationQuery();
if (validationQuery != null) {
	dataSource.setTestOnBorrow(true);
	dataSource.setValidationQuery(validationQuery);
}
```
In my case this will be executed if you use one of "default" proxies.

**Comment by vpavic** [comment]
@gavlyukovskiy `dataSource` bean definitions in `DataSourceConfiguration` are annotated with `@ConfigurationProperties` which binds configuration properties directly to the appropriate `dataSource` bean.

See [`DataSourceConfiguration:53`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration.java#L53), [`DataSourceConfiguration:78`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration.java#L78) and [`DataSourceConfiguration:93`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration.java#L93).

**Comment by gavlyukovskiy** [comment]
@vpavic but parameters can be actually taken from the root prefix `spring.datasource` like `type` or `proxyTypes`. I have noticed it when debugging.

**Comment by gavlyukovskiy** [comment]
Oh, got it, it's about
```
spring.datasource.hikari.allow-pool-suspension
spring.datasource.hikari.auto-commit
spring.datasource.hikari.catalog
...
```
But I don't know when they are assigned to the data source, I can't even find where this metadata is set...

**Comment by gavlyukovskiy** [comment]
I have tried it again now and now I see, very sorry for that dumb comments actually I thought that `@ConfigurationProperties(prefix = "spring.datasource.hikari")` means that `DataSourceProperties` passed into arguments will be taken from prefix `spring.datasource.hikari`, not from `spring.datasource`... But actaully these properties for the `HikariDataSource` and then `ConfigurationPropertiesBindingPostProcessor` injects these properties to the bean itself, now I see the full picture.

**Comment by gavlyukovskiy** [comment]
@philwebb, sould the overriden `DataSource` be proxied in `BeanPostProcessor`?

**Comment by gavlyukovskiy** [comment]
I have changed the code to use decorators instead of direct proxy types. Also I'm using `DecoratedDataSource` to keep both real and decorated data sources for metadata.
BTW I have splited it out to a library - https://github.com/gavlyukovskiy/spring-boot-data-source-decorator and it works fine with existing spring-boot release.

**Comment by wilkinsona** [comment]
Thanks for the PR and thanks, too, for the library that you've split out. Given that you're maintaining the library regularly and that it's included in our third-party starter list, I think that's the best place for this code now. If you disagree, please comment and we can reconsider.

**Pull request closed without merging**
