### PR TITLE
support for additional information parameters

### PR DESCRIPTION
**Pull request by XYUU**
Make access to userinfo support for additional information parameters.
like this:
UserInfoUri: https://api.weibo.com/2/users/show.json?uid={uid}

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@XYUU Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8367)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8367) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@XYUU Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8367)!

**Comment by philwebb** [comment]
@XYUU Can you provide some more background about why you'd like this change? Ideally the pull-request should also include tests.

**Comment by XYUU** [comment]
Some access to user information interface need to pass some of the additional parameters returned when authorized, such as China's Sina WeiBo open API, although not a standard practice, but by simply modifying a few lines of code, you can cover this possible Demand, and does not affect the previous function, I think it is desirable.

**Comment by mbhave** [comment]
@XYUU I don't think always adding the additional information as part of the request to the userinfo endpoint is something we want do. While query parameters are mentioned in the spec, this seems quite specific to your use case. To achieve the same result, you can extend the `UserInfoTokenServices` and override the bits that would let you add the query parameters.

**Comment by XYUU** [comment]
@mbhave In RestTemplate, parameters are not always added to the request endpoint, but as an optional parameter, you can use placeholders to fill when needed. These additional parameters are not exposed when the placeholders are not used. I am currently using a method that extends the UserInfoTokenServices and overwrites the query parameters. As a configurable way to cover more use cases without the need to write code implementations.

**Comment by mbhave** [comment]
@XYUU yes I know that they will only be present if the URI is templated. However, there might be other query parameters that could be added and using additional information from the token is not a standard practice.

**Pull request closed without merging**
