### PR TITLE
Use try-with-resources to ensure resources are closed

### PR DESCRIPTION
**Pull request by oscr**
SonarLint detected an issue where a [FileInputStream](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/java/org/springframework/boot/loader/tools/FileUtils.java#L68) wasn't closed.

### CODE REVIEW

**Comment by philwebb** [comment]
We can't change this until Boot 2.0 since we need to remain compatible with Java 6. I think we'll have a bunch of these type of changes but it's not something we want to handle just just since it'll cause merge conflicts. It's going to be better if we take this on directly when we convert our codebase to Java 8.

**Comment by philwebb** [comment]
Thanks anyway!

**Comment by oscr** [comment]
@philwebb Would a fix using Java 6 syntax be acceptable?

**Comment by spencergibb** [comment]
@oscr isn't that what it does already?
```
finally {		
	inputStream.close();		
}
```

**Comment by oscr** [comment]
@spencergibb That closes the DigestInputStream but the [FileInputStream](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/java/org/springframework/boot/loader/tools/FileUtils.java#L68) isn't closed.

**Comment by spencergibb** [comment]
closing the `DigestInputStream` certainly closes the `FileInputStream` passed in.

**Comment by oscr** [comment]
@spencergibb The [api](https://docs.oracle.com/javase/7/docs/api/java/io/FilterInputStream.html#close()) confirms! Looks like you are right and me and SonarLint is wrong. TIL.

**Pull request closed without merging**
