### PR TITLE
Add reference to quickfixj spring boot starter

### PR DESCRIPTION
**Pull request by gevoulga**
A quickfixj spring boot starter, for the quickfixj library.
Quickfixj implements the FIX message exchange protocol.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gevoulga Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20819)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20819) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@gevoulga Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20819)!

**Comment by snicoll** [comment]
@gevoulga thanks for the suggestion. I had a quick look at the starter and found a number of issues that need to be reviewed before we reference it. Can you please have a look to those?

**Comment by gevoulga** [comment]
> 
> 
> @gevoulga thanks for the suggestion. I had a quick look at the starter and found a number of issues that need to be reviewed before we reference it. Can you please have a look to those?

@snicoll I've addressed the comments raised. Any followup comments are welcome.

**Comment by snicoll** [comment]
Thanks for the quick follow-up @gevoulga and thank you for making your first contribution to Spring Boot.

**Pull request closed without merging**
