### PR TITLE
Add a hint for logging.structured.json.customizer property

### PR DESCRIPTION
**Pull request by nosan**

### CODE REVIEW

**Comment by philwebb** [comment]
I wonder why I didn't make `customizer` a `Class` in `StructuredLoggingJsonProperties`

**Comment by nosan** [comment]
> I wonder why I didn't make `customizer` a `Class` in `StructuredLoggingJsonProperties`

Do you mean in this context? If so, I was also confused about why `java.lang.Class` wasn't simply used here.
```
    {
      "name": "logging.structured.json.customizer",
      "type": "java.lang.String",
      "description": "The fully qualified class name of a StructureLoggingJsonMembersCustomizer"
    },
```

**Comment by philwebb** [comment]
Exactly, I've made that change in #43202 which should remove the need for additional metadata. Thanks for finding it!

**Comment by nosan** [comment]
**additional-spring-configuration-metadata.json** in `spring-boot/spring-boot-project/spring-boot/src/main/resources/META-INF` still contains the following:

```json
    {
      "name": "logging.structured.json.customizer",
      "type": "java.lang.String",
      "description": "The fully qualified class name of a StructuredLoggingJsonMembersCustomizer"
    }
```
Does it need to be updated?

```json
    {
      "name": "logging.structured.json.customizer",
      "type": "java.lang.Class",
      "description": "The fully qualified class name of a StructuredLoggingJsonMembersCustomizer"
    }
```

**Pull request closed without merging**
