### PR TITLE
Skip additional properties null values for spring-boot-maven-plugin

### PR DESCRIPTION
**Pull request by tdanylchuk**
In order to support null values configured in maven.
It solves case when maven property placeholder is used and corresponding property is missed during the build.

Example:
I have different profiles in by maven build configuration and some of them define particular maven parameter which I want to add to /info endpoint.
Problem is that for those profiles which are not define this property, build fails with ```NullAdditionalPropertyValueException```, in this case I think it's better just skip value instead of build fail.
The best solution is to have possibility to define default value, but maven does not support this feature.

### CODE REVIEW

**Comment by philwebb** [comment]
The `NullAdditionalPropertyValueException` is far from ideal, but I'm also not convinced that we should skip unrecognized placeholders.

My concern is that someone could have a typeo in a property and have no indication that it was dropped.

@tdanylchuk Does defining a default property with an empty value and overriding it in profile solve your use-case? Or do you specifically need the property key to disappear from the info endpoint?

**Comment by tdanylchuk** [comment]
@philwebb thx for the quick answer.

Actually I came to the same concern that you described. And originally I was thinking about 2 options:
- Not just skip null values, but log warn message to the build log regarding skipped values (didn't find logs in project, so I assumed that it's not an appropriate approach)
-  Just don't skip null values, return null to /info instead (In this case I need to change dependent project, and for some reason exception is thrown in such case, so I didn't propose that solution)

As for empty value: I have complicated case where this empty property value could override existent property, since I'm using maven mixin plugin for merging two poms (or more). 
But for simple case with one pom with profiles, it should work out (imho this solution requires adding redundant code to my pom.xml)

**Comment by snicoll** [comment]
This looks like a duplicate of #12382 - This is standard behaviour of Maven and I am not keen to deviate from that by implementing something custom in our plugin.

**Comment by tdanylchuk** [comment]
I consider this as not "custom thing", but as "compatibility" with standard Maven behavior, where we cannot define default values for placeholders, and missed values just should not fail the build.

In the end of the day "tools" should help developers, but not force them to add workarounds to their poms imho. It will help at least me and that developer from provided ticket so solve an obstacle and as for me it does not change plugin functionality that much either adds additional complexity.

**Comment by philwebb** [comment]
> I consider this as not "custom thing", but as "compatibility" with standard Maven behavior, where we cannot define default values for placeholders, and missed values just should not fail the build.

Your specific requirement is that missing values don't fail the build, but another user may well prefer that the build fails if they make a typo.

I appreciate that this change makes things better for some users, but on balance I think it's best if we are consistent with our handling of maven properties. This really feels like a limitation of Maven and not something that we should attempt to work-around here.

Regardless, thanks for taking the time to put together the pull-request and I hope you can find a solution that works in your build. I think default value support would be nice addition to Maven, it's a shame they don't yet support it.

**Pull request closed without merging**
