### PR TITLE
configure JRE that is different from compiler target level

### PR DESCRIPTION
**Pull request by martinlippert**

### CODE REVIEW

**Comment by wilkinsona** [comment]
Hey, Martin. Can you explain why this change is necessary please? I haven't noticed any problems either on the command line or in STS.

**Comment by martinlippert** [comment]
If you import a project into STS as existing Maven project, the JRE for the classpath is configured via the compiler target level. This causes issues when the project has references to classes from a higher level JRE/JDK (which is the case for these spring boot projects).

Therefore I added a feature to STS that allows you to specify a different JRE that is then taken into account when importing the project.

**Comment by wilkinsona** [comment]
I see, thanks. Perhaps a bit picky, but I'm not too keen on using a project-wide property to control something that's M2E-specific. Would it be possible to do something that's more isolated? I'm think of something similar to, but ideally less complicated than, what we already do for lifecycle mappings.

**Comment by martinlippert** [comment]
Not picky at all and I am open to all kinds of solutions. Any specific idea? Since I am implementing the project configurator myself anyway, I think I could deal with various ways.

**Comment by wilkinsona** [comment]
Sorry, I don't know enough about Eclipse/M2E to make a specific suggestion. Anything that scopes the configuration to being specific to Eclipse would work for me.

**Comment by martinlippert** [comment]
Added one more commit, but did a stupid rebase in between, therefore I am screwing things up here. Closing this pull request for now, will work on a better way to configure the JRE level, and will create a new one later.

**Pull request closed without merging**
