### PR TITLE
OAuth2 Client documentation still refers to redirect-uri-template

### PR DESCRIPTION
**Pull request by wwjay9**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wwjay9 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18752)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18752) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@wwjay9 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18752)!

**Comment by snicoll** [comment]
Nice catch, thanks @wwjay9

**Comment by wwjay9** [comment]
You're welcome 😄 @snicoll

**Pull request closed without merging**
