### PR TITLE
Elasticsearch autoconfiguration for spring-boot-rest

### PR DESCRIPTION
**Pull request by akonczak**
Hi 

I have added missing beans required in spring-boot-rest to work out of the box with spring-boot-elasticsearch.
Also this change has dependency in spring-date-elasticearch https://jira.spring.io/browse/DATAES-137, commit https://github.com/spring-projects/spring-data-elasticsearch/commit/6cdc765b24bf5c91e012d0ca2b1a1b31e331b03e

### CODE REVIEW

**Comment by snicoll** [comment]
You need to guars the conditional with `@ConditionalOnType` since the extra jar may not be present. And it probably needs to sit in its own config class as well (since you still want the existing support even if the elasticsearch is not present. 

I am not familiar with the elasticsearch integration and since there is no test, I am not sure I get the added value. Can you please clarify?

**Comment by akonczak** [comment]
Hi Stéphane 
You are right, I will move the changes to ElasticsearchDataAutoConfiguration and add necessary tests for it. All new beans are required to create ElasticsearchTemplate.  

To be able to use spring-boot with spring-data-elasticsearch and spring-data-rest, spring-data-elasticsearch needs to expose MappingConnext bean in application context(in our case SimpleElasticsearchMappingContext).

This the fragment from spring-data-rest where they scan application context to find MappingContext for data modules.
```RepositoryRestMvcConfiguration.java
	@Bean
	public PersistentEntities persistentEntities() {

		List<MappingContext<?, ?>> arrayList = new ArrayList<MappingContext<?, ?>>();

		for (MappingContext<?, ?> context : BeanFactoryUtils
				.beansOfTypeIncludingAncestors(applicationContext, MappingContext.class).values()) {
			arrayList.add(context);
		}

		return new PersistentEntities(arrayList);
	}
```

**Comment by mohsinh** [comment]
+1

**Comment by ryl** [comment]
With the exception of some check style errors, this pull request worked for me. Would love to see this pull request merged so I can use Elasticsearch with SDR.

Prior to this pull request, I was able to do GETs but not  POSTs/PUTs. I was receiving the "PersistentEntity must not be null" error mentioned in the JIRA link in the original comment. After pulling this request and installing locally, things worked like a charm.

**Comment by philwebb** [comment]
@akonczak Thanks! Have you signed the CLA?

**Comment by akonczak** [comment]
Hi Phil 

Yes, I have signed it long ago, its not my first pull request for spring boot.

Thanks, 
Artur

**Comment by philwebb** [comment]
Thanks @akonczak, unfortunately our CLA/GitHub integration isn't that great so I often end up asking more than once. Thanks for contributing!

**Comment by akonczak** [comment]
No worries, we have the same problem with Spring Date ElasticSearch.

**Pull request closed without merging**
