### PR TITLE
gh-1826 rollback support for liquibase autoconfiguration

### LINKED ISSUE #1826: SpringBoot Liquibase autoconfiguration and rollbacks
Hi!

As suggested on Twitter I'm pushing the question here.

The question is - with Liqiubase autoconfiguration we can easilly make Liquibase read the changesets and apply all the necessary changes. That's awesome :) 

Now let's assume that we have an application that has already applied one changeset (let's call it "1" and the JAR version is 1.0.0) and we've done a deploy and have applied Liquibase changes comprising of two changesets (let's call them "2" and "3" and the JAR version is 1.1.0 ). Now on production it turned out that our application doesn't work the way it should. We would like to downgrade the application from version 1.1.0 to 1.0.0. That means we would like to rollback the liqubase changes from "3" to "1". Of course it's feasible by using the Liquibase scripts but my question is - is it possible to start our Spring Boot application in such a way to tell JAR version 1.1.0 to rollback the changesets "3" and "2" and then normally deploy version 1.0.0?

### PR DESCRIPTION
**Pull request by gazal-k**
Fixes #1826 

- [X] I have signed the CLA

### CODE REVIEW

**Comment by gazal-k** [comment]
The latest build error is 

`Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (assemble-starter-poms) on project spring-boot-starters: Failed to create assembly: Error creating assembly archive starter-poms: You must set at least one file.`

Not sure how to correct this.

**Comment by wilkinsona** [comment]
I briefly broke master. It was fixed in https://github.com/spring-projects/spring-boot/commit/491ab3dd31000dc94f9c1e7639f72a5642803e30. Could you try rebasing please?

**Comment by gazal-k** [comment]
@wilkinsona should I squash the commits?

**Comment by wilkinsona** [comment]
@gazal-k Yes please

**Comment by philwebb** [comment]
Merged with a few tweaks. Thanks!

**Pull request closed without merging**
