### PR TITLE
Put all custom defined properties in the map with hibernate properties

### PR DESCRIPTION
**Pull request by mdoninger**
fixes gh-2348

### CODE REVIEW

**Comment by philwebb** [comment]
Cheers. Have you signed the CLA?

**Comment by mdoninger** [comment]
Yes, i've signed it last year (on 8/28/14).

**Comment by mdoninger** [comment]
But i used manuel.doninger@gmail.com as mail address. Should i sign it with manuel.doninger@googlemail.com as well, or doesn't that matter?

**Comment by philwebb** [comment]
No that's fine. As long as it has been signed. We don't currently have a good way to track against GitHub IDs to we end up asking with each PR.

**Pull request closed without merging**
