### PR TITLE
Improve RandomValuePropertySource

### PR DESCRIPTION
**Pull request by mbenson**

### CODE REVIEW

**Comment by philwebb** [comment]
I like the javadoc updates but I'm not convinced that we should merge the other items as they are. Specifically:

* We tend not to use `final` for local variable declarations. I find it just adds noise without a lot of benefit.
* I'm not sure that the `localName` variable gives us all that much as it is. Perhaps we could extract a new method just before the `logger.trace` call. Something like `getRandomProperty(name.substring(...))`.
* I agree changing `startsWith("long")` to `equals("long")` but I wonder if it might be better to offer the same `range` support with longs. That way they behave in the same way as `int`.

**Comment by mbenson** [comment]
Fair enough. If you don't hit these before I do I'll take a look at them
tomorrow.

**Comment by mbenson** [comment]
@philwebb: I don't fully grok where you were going with the `getRandomProperty()` suggestion. Can you elaborate there?

**Comment by philwebb** [comment]
Sorry, I wasn't very clear about extracting a new `getRandomProperty` method. I've made that change along with a few other bits and pushed this to master.

If you want to see the individual steps that were made [take a look here](https://github.com/philwebb/spring-boot/commits/pr/3391).

Thanks for the contribution!

**Pull request closed without merging**
