### PR TITLE
Update springloaded version to 1.2.6.RELEASE

### PR DESCRIPTION
**Pull request by michael-simons**
Just a quick improvement to make sure developers use the current version of springloaded.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Re-opening. I missed a commit.

**Comment by wilkinsona** [comment]
Thanks for the PR, @michael-simons

**Comment by michael-simons** [comment]
Not for that @wilkinsona. Sorry I managed to miss one version string.

**Comment by rajadilipkolli** [comment]
@wilkinsona , is there any way to automize these type of version management?? As of now it forces author to manually update the values which becomes tedious

**Comment by wilkinsona** [comment]
@rajadileepkolli There's almost always a way, it's more a matter of time. In this case, a custom Asciidoctor extension could be used to configure all of the versions defined in `spring-boot-dependencies` as attributes that can be referenced something like {{spring-loaded.version}}. I've opened https://github.com/spring-projects/spring-boot/issues/8006.

**Pull request closed without merging**
