### PR TITLE
Remove final from ProblemDetailsExceptionHandler classes to allow proxying

### PR DESCRIPTION
**Pull request by vy**
Removes `final` modifier from `ProblemDetailsExceptionHandler` implementations to allow proxying these beans. See #34426 for the issue.

### CODE REVIEW

**Comment by philwebb** [comment]
I wonder if we should add some tests just to stop `final` sneaking back in the future?

**Comment by philwebb** [comment]
Thanks @vy! Rather than a new dependency we might change this to use standard reflection when we merge it.

**Comment by vy** [comment]
@philwebb, ArchUnit was already used in `TaskConfigurationAvoidanceTests`, hence was my preference for it. But I can replace it with reflection, if that is what you want.

If you prefer reflection, please also let me know if you want to target `ProblemDetailsExceptionHandler` _interfaces_ or `ResponseEntityExceptionHandler` _subclasses_, since the latter will require some stunt to pull.

**Comment by wilkinsona** [comment]
Thanks very much for the PR, @vy. I decided to test the changes by verifying that the exception handlers could be proxied. If you're interested, please see https://github.com/spring-projects/spring-boot/commit/1eb5bbe3ea638e292463a5eca2c3adfc38c4450d for details.

**Comment by vy** [comment]
Thanks so much for the prompt processing of the ticket and keeping me in the loop. :bow: I didn't know about `AopUtils.isCglibProxy`, which makes your tests precisely demonstrative of the bug reported in the first place. :100:

**Comment by sbrannen** [comment]
@wilkinsona, at a glance it appears that those two `assertThat(AopUtils.isCglibProxy(context.getBean(ProblemDetailsExceptionHandler.class)));` assertions are missing `.isTrue()`.

**Pull request closed without merging**
