### PR TITLE
Upgrade to Narayana 5.5.0.Final

### PR DESCRIPTION
**Pull request by tomjenkinson**
Upgrades to the latest bug fix release of Narayana. In particular this release addresses a connection issue:
https://issues.jboss.org/browse/JBTM-2829

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@tomjenkinson Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8063)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8063) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@tomjenkinson Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8063)!

**Comment by snicoll** [comment]
@tomjenkinson `1.4.x` uses `5.3` and we won't upgrade to `5.5.1` in a maintenance release. You can however override the version as described in the doc.

**Comment by snicoll** [comment]
And the bits are not in Maven Central.

**Comment by wilkinsona** [comment]
I'd prefer that we just close this one. We'll pick up 5.5.1 as part of the semi-automated upgrades that I'll do shortly before 1.5.0 is released (if it's in Central by then).

**Pull request closed without merging**
