### PR TITLE
Polish some external documentation links

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

the doc polishing goes on. Sorry for the amount of small PRs. This particular one polishes some external documentation links - namely:

- Point to Jetty documentation of currently supported Jetty version
- Point to Hibernate 5.4 instead of 5.3
- Point to current Gradle docs instead of deprecated 4.2.1 (or any other 4.x) version

Cheers,
Christoph

### CODE REVIEW

**Comment by philwebb** [comment]
> Sorry for the amount of small PRs
No need to apologize, we prefer merging lots of smaller PRs to splitting up large ones :)

Thanks once again!

**Comment by dreis2211** [comment]
I wonder about the force push and the references to the other commits. Could you elaborate?

**Comment by philwebb** [comment]
I rather foolishly managed to commit a heap dump file that was generated when my JVM crashed. Rather than revert it and leave it in the history, I decided to risk an immediate force push.

**Comment by dreis2211** [comment]
I noticed this when syncing my fork as it got ouf sync because of this. I could fix it for mine by resetting master hard to the upstream master. Might happen to some more people.

**Comment by philwebb** [comment]
I managed to really mess it up badly by accidentally deleting a merge commit that I shouldn't have. I tried again to fix it yesterday so you'll probably need to do another `git reset --hard`

**Pull request closed without merging**
