### PR TITLE
Rename Neo4j bean names

### PR DESCRIPTION
**Pull request by nosan**
see gh-19524

Here is the second approach: https://github.com/nosan/spring-boot/commit/9c666b5a06a644a46ce35ff420e534070fbf2d73

I am not sure which way is better. Both variants support back-compatibility.

### CODE REVIEW

**Comment by nosan** [comment]
I think it makes sense to rename`sessionFactory` to **`neo4jSessionFactory`** for `2.3.X` version
with no back-compatibility.

**Comment by snicoll** [comment]
@nosan thanks for the PR. We've discussed it and we'd like to rename the names in `2.2.x` (with no back-compatibility as you indicated). Do you have time to review your PR in that direction?

**Comment by nosan** [comment]
Sure @snicoll,
I let you know

**Comment by nosan** [comment]
@snicoll 
PR has been updated

**Comment by snicoll** [comment]
Thanks for the PR @nosan but looking at what's going on behind the scenes, a change in Spring Data is required. Once we have that in, we'll have to reconsider this from scratch.

**Pull request closed without merging**
