### PR TITLE
Dependency management has unnecessary log4j exclusion for spring-cloud-spring-service-connector

### PR DESCRIPTION
**Pull request by larrywest**
...  spring-cloud-spring-service-connector. 

The dependency on `log4j:log4j` appears to have been removed from spring-cloud-spring-service-connector in late 2014 as part of [spring-cloud-connectors issue #96](https://github.com/spring-cloud/spring-cloud-connectors/issues/96), in commit [f2be5e94305446d4698636a9037bf44185f418ed](https://github.com/spring-cloud/spring-cloud-connectors/commit/f2be5e94305446d4698636a9037bf44185f418ed) (2014-11-24), which was included beginning with spring-cloud-connectors `v1.1.1.RELEASE`.

I did a quick example app using spring-cloud-spring-service-connector `2.0.6.RELEASE` and do not see `log4j:log4j`.

_...and now I see that [Spring Cloud Connectors](https://github.com/spring-cloud/spring-cloud-connectors) is_

>  is in maintenance mode, in favor of the newer Java CFEnv project

_...so perhaps this is moot._  _Or perhaps it's worth removing six unneeded lines from this file._

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@larrywest Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18833)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18833) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@larrywest Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18833)!

**Comment by snicoll** [comment]
Thanks for the PR. Yes, this has been deprecated in `2.2.0`, see https://github.com/spring-projects/spring-boot/issues/17877

**Comment by snicoll** [comment]
@larrywest yep, worth removing unnecessary lines in there indeed. Thank you for making your first contribution to Spring Boot.

**Comment by larrywest** [comment]
(@snicoll FYI, your comment sounds like you intended to merge the PR, but it is "closed with unmerged commits".)

**Comment by wilkinsona** [comment]
That's a GitHub bug that you may want to report to them. Here's your commit in the master branch: https://github.com/spring-projects/spring-boot/commit/82a41a3ed0da32119b35c8d847264386da935ad7.

**Pull request closed without merging**
