### PR TITLE
Add AutoConfiguration for ConversionService

### LINKED ISSUE #758: Offer a way to easily create a ConversionService that matches the one Spring Boot uses internally
I have a use case of adding my own Converters. I was hoping to declare a ConversionService field and have it autowired in based on my implemented Converter's. I notice that the ConfigurationPropertiesBindingPostProcessor.getDefaultConversionService() does a similar thing but it is only for its class. For now I have this:

```
    @Bean
    public ConversionServiceFactoryBean conversionService() {
        ConversionServiceFactoryBean factoryBean = new ConversionServiceFactoryBean();

        @SuppressWarnings("rawtypes")
        Set<Converter> converters = new HashSet<Converter>();
        converters.add(new MyCustomConverter());
        converters.add(new MyOtherCustomConverter());
        factoryBean.setConverters(converters);

        return factoryBean;
    }
```

Thanks

### PR DESCRIPTION
**Pull request by markthemarkest**
- [X] I have signed the CLA

Provide a ConversionService populated with default Spring Converters
and any custom converters registered in the Spring Context.

Does not create a ConversionService if there are no converters
registered with the context.

Does not create a new ConversionService if there is already one
registered with the context.

Fixes #758

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks for the PR, unfortunately we're running out of time for 1.4 so we'll probably need to wait for 1.5 to consider this.

**Comment by pivotal-issuemaster** [comment]
@markthemarkest Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=5920) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by kflorence** [comment]
What about auto registration for `GenericConverter`?

**Comment by snicoll** [comment]
Related to #6222 ?

**Comment by pivotal-issuemaster** [comment]
@markthemarkest Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=5920)!

**Comment by philwebb** [comment]
Thanks for the PR! Having looked into things a little more we think we'll need to solve this another way. There are currently multiple `ConversionService` beans that get used (we've got one for spring-mvc, one for binding, etc). We need to have a think about the best way to allow custom converters to be registered and how people might link them to a specific conversion service.

Thanks anyway.

**Pull request closed without merging**
