### PR TITLE
Make check-location property consistent in Flyway and Liquibase

### PR DESCRIPTION
**Pull request by eddumelendez**
See gh-10464

### CODE REVIEW

**Comment by wilkinsona** [comment]
I'm thinking twice about renaming the properties. While things are now consistent between Flyway and Liquibase, the Liquibase properties for configuring the change log and checking it don't match up any more.

**Comment by philwebb** [comment]
I'm tempted to keep the two properties distinct as well. I think the consistency within the class is more important that consistency between Flyway & Liquibase.

**Comment by wilkinsona** [comment]
@eddumelendez Sorry for changing our mind on this one. Would you like to update your pull request so that it just switches the default value and leaves the property names unchanged?

**Comment by wilkinsona** [comment]
Thank you once again, @eddumelendez

**Pull request closed without merging**
