### PR TITLE
Ldap contextSource base property populating in EmbeddedLdapAutoConfig

### PR DESCRIPTION
**Pull request by pavelda2**
Fix issue spring-projects/spring-boot#10443

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@pavelda2 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=10444)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=10444) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@pavelda2 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=10444)!

**Comment by snicoll** [comment]
Merged, thank you!

**Comment by snicoll** [comment]
This broke [Spring Data's integration tests](https://gist.github.com/olivergierke/430aa42987a04038b164a8bbbbb1c549) and, looking at the error, this change is way more invasive than I thought. Perhaps you could provide a solution that is opt-in instead?

**Comment by pavelda2** [comment]
The problem is in integration test. Somebody sets the `spring.ldap.base=dc=springframework,dc=org` property in test [application.properties](https://github.com/spring-projects/spring-data-examples/blob/master/ldap/example/src/test/resources/application.properties), but this property should have no effect before my improvement.

1. It makes no sense to set whole ldap name `uid=bob,ou=people,dc=springframework,dc=org` in [PersonRepositoryIntegrationTests.java](https://github.com/spring-projects/spring-data-examples/blob/master/ldap/example/src/test/java/example/springdata/ldap/PersonRepositoryIntegrationTests.java#L50) when `spring.ldap.base` is set.
 (fix of `findOneByName` test)

1. It makes no sense to set base in both - `spring.ldap.base` in [application.properties](https://github.com/spring-projects/spring-data-examples/blob/master/ldap/example/src/test/resources/application.properties) and in the [Person](https://github.com/spring-projects/spring-data-examples/blob/master/ldap/example/src/main/java/example/springdata/ldap/Person.java#L32) entity.
(fix of the rest of tests)

From my point of view the test should be repaired.

Possible solutions:

- **Integration tests without base specified:** 
   - Remove base `spring.ldap.base` from [application.properties](https://github.com/spring-projects/spring-data-examples/blob/master/ldap/example/src/test/resources/application.properties)
- **Integration tests with base specified:**  
   - Remove base from [Person](https://github.com/spring-projects/spring-data-examples/blob/master/ldap/example/src/main/java/example/springdata/ldap/Person.java#L32) entity
   - Remove hardcoded base in [PersonRepositoryIntegrationTests.java](https://github.com/spring-projects/spring-data-examples/blob/master/ldap/example/src/test/java/example/springdata/ldap/PersonRepositoryIntegrationTests.java#L50) `findOneByName`.

**Comment by snicoll** [comment]
@pavelda2 thanks for the feedback. Also paging @olivergierke that raised the regression in those tests.

> It makes no sense to set whole ldap name uid=bob,ou=people,dc=springframework,dc=org in PersonRepositoryIntegrationTests.java when spring.ldap.base is set.

That's arguable I suppose, I wonder if there is a clear way to detect such use case. The error I saw was not very informative.

**Comment by vdubus** [comment]
I would suggest to use the value from `spring.ldap.embedded.base-dn` to set correctly the `base` information in `LdapContextSource`.

**Pull request closed without merging**
