### PR TITLE
Update filter method 

### PR DESCRIPTION
**Pull request by Java4ye**
Update filter method for adding isTraceEnabled condition to reduce calls to nanoTime method

### CODE REVIEW

**Comment by mhalbritter** [comment]
What's the problem with `System.nanoTime`?

**Comment by mhalbritter** [comment]
I get that, but why remove the call to `System.nanoTime()`? I mean I get that this variable is only used when logging on trace, but have you observed a performance problem with it?

**Comment by Java4ye** [comment]
@mhalbritter 
I didn't do that, but I found it in the for loop.

**Comment by wilkinsona** [comment]
Until something shows up as a performance bottleneck, I think we should leaves things as they are. It may even be that the `isTraceEnabled()` check is slower than the call to `System.nanoTime()`. Thanks anyway for the proposal.

**Pull request closed without merging**
