### PR TITLE
Define the classloader for FluentConfiguration

### PR DESCRIPTION
**Pull request by Alan-Gomes**
The out of the box support for Flyway currently does not work with a custom class loader defined in `ResourceLoader`. Without this compatibility, Flyway will not be able to load scripts inside the `resources` folder. I experienced this issue when developing a [custom starter](https://github.com/Alan-Gomes/mcspring-boot) which runs inside a personalized class loader.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Alan-Gomes Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16947)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16947) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Alan-Gomes Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16947)!

**Comment by philwebb** [comment]
Thanks for the PR. I think ideally we should also add some tests for this.

**Comment by Alan-Gomes** [comment]
I wrote a test to verify this configuration, it should work now.

**Comment by wilkinsona** [comment]
@Alan-Gomes Thanks very much for making your first contribution to Spring Boot. I have merged your changes into master along with a [polish commit](https://github.com/spring-projects/spring-boot/commit/69a298231c29f193822749c14a6224ddb1765771). The primary reason for the polish was to move away from using a mock ClassLoader as it caused the test to fail due to the mock not being able to find any migration scripts.

**Pull request closed without merging**
