### PR TITLE
Dependency convergence error for nimbus-jose-jwt when depending on spring-boot-starter-oauth2-client

### LINKED ISSUE #22947: Dependency convergence on nimbus-jose-jwt
When I use `spring-boot-starter` 2.3.3.RELEASE as my project's parent and include `org.springframework.boot:spring-boot-starter-oauth2-client:2.3.3.RELEASE` as a dependency, my `dependencyConvergence` rule goes bananas over the version of `com.nimbusds:nimbus-jose-jwt`:

```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (default) @ my-project ---
[WARNING]
Dependency convergence error for com.nimbusds:nimbus-jose-jwt:8.8 paths to dependency are:
+-my.project:my-project:1.0-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-oauth2-client:2.3.3.RELEASE
    +-org.springframework.security:spring-security-oauth2-client:5.3.4.RELEASE
      +-com.nimbusds:oauth2-oidc-sdk:7.1.1
        +-com.nimbusds:nimbus-jose-jwt:8.8
and
+-my.project:my-project:1.0-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-oauth2-client:2.3.3.RELEASE
    +-org.springframework.security:spring-security-oauth2-jose:5.3.4.RELEASE
      +-com.nimbusds:nimbus-jose-jwt:8.19
```

I've been looking around for a bit, and noticed Spring Boot is behind on the `com.nimbusds:oauth2-oidc-sdk` så I bumped it up to 8.18 using the `oauth2-oidc-sdk.version`-property, but still the same issue:

```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (default) @ my-project ---
[WARNING]
Dependency convergence error for com.nimbusds:nimbus-jose-jwt:8.18 paths to dependency are:
+-my.project:my-project:1.0-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-oauth2-client:2.3.3.RELEASE
    +-org.springframework.security:spring-security-oauth2-client:5.3.4.RELEASE
      +-com.nimbusds:oauth2-oidc-sdk:8.18
        +-com.nimbusds:nimbus-jose-jwt:8.18
and
+-my.project:my-project:1.0-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-oauth2-client:2.3.3.RELEASE
    +-org.springframework.security:spring-security-oauth2-jose:5.3.4.RELEASE
      +-com.nimbusds:nimbus-jose-jwt:8.19
```

Another attempt with `oauth2-oidc-sdk.version` = 8.19:

```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (default) @ my-project ---
[WARNING]
Dependency convergence error for com.nimbusds:nimbus-jose-jwt:8.18 paths to dependency are:
+-my.project:my-project:1.0-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-oauth2-client:2.3.3.RELEASE
    +-org.springframework.security:spring-security-oauth2-client:5.3.4.RELEASE
      +-com.nimbusds:oauth2-oidc-sdk:8.19
        +-com.nimbusds:nimbus-jose-jwt:8.18
and
+-my.project:my-project:1.0-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-oauth2-client:2.3.3.RELEASE
    +-org.springframework.security:spring-security-oauth2-jose:5.3.4.RELEASE
      +-com.nimbusds:nimbus-jose-jwt:8.19
```

My point here is really just to show that Spring Security tries to use the most updated version of that artifact, while `oauth2-oidc-sdk` does not (always), effectively making the two artifacts `oauth2-oidc-sdk` and `nimbus-jose-jwt` two separate things.

So my question is - would it make sense to add `com.nimbusds:nimbus-jose-jwt` to Spring Boot's dependency management with its own version property?

I could give it a shot if the team deems it a good idea.

### PR DESCRIPTION
**Pull request by ThomasKasene**
Fixes #22947

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ThomasKasene Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=22996)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=22996) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ThomasKasene Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=22996)!

**Comment by wilkinsona** [comment]
@ThomasKasene Thanks very much for making your first contribution to Spring Boot.

**Comment by dreis2211** [comment]
This breaks quite some tests unfortunately @wilkinsona . Could we revert this for the time being again?

**Comment by wilkinsona** [comment]
So it does. Sorry, @dreis2211. I probably should be pushing changes in my sleep-deprived state…

**Comment by dreis2211** [comment]
We've all been there - no need to be sorry

**Comment by wilkinsona** [comment]
Spring Security 5.3.4 [uses nimbus-jose-jwt 8.19](https://github.com/spring-projects/spring-security/blob/9187a7925ea259d4b686da03f3d68c26cb36c261/oauth2/oauth2-jose/gradle/dependency-locks/compileClasspath.lockfile#L5) so let's align with that.

**Pull request closed without merging**
