### PR TITLE
Add support @LocalServerPort for RSocket Port

### PR DESCRIPTION
**Pull request by veronicavasq**
Currently `@LocalServerPort` does not resolve `spring.rsocket.server.port`
configuration property. This commit allows to set `local.server.port`
when it is used.

See gh-18179

Co-authored-by: Eddú Meléndez <eddu.melendez@gmail.com>

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@veronicavasq Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18287)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18287) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by bclozel** [comment]
Thanks for your help @veronicavasq ! Don't forget to sign the CLA so that we can merge your changes.

**Comment by pivotal-issuemaster** [comment]
@veronicavasq Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18287)!

**Comment by wilkinsona** [comment]
Wondering aloud: should this use a property other than `local.server.port`? Perhaps `local.rsocket.server.port` with a matching `@LocalRSocketServerPort` annotation.

**Comment by eddumelendez** [comment]
@wilkinsona I really like that proposal. we will wait for further news.

**Comment by bclozel** [comment]
@wilkinsona I was also wondering that.

Our current infrastructure allows the following setups:

1. A standalone RSocket server over TCP (`spring.rsocket.server.port=9898`)
2. A standalone RSocket server over websocket (`spring.rsocket.server.port=8443` and `spring.rsocket.server.transport=websocket` and `spring.rsocket.server.mapping-path=/rsocket`)
3. An RSocket websocket server plugged into an existing web server (`spring.rsocket.server.transport=websocket` and `spring.rsocket.server.mapping-path=/rsocket`)

In case 3), the `@LocalServerPort` will be the port of the Reactor Netty Server, as expected.

If we go with this PR, we might have issues with case 1) and 2); the application could start both a web server and a standalone RSocket server (we're allowing this configuration). In that case, both the web server and the RSocket would try and bind to the same environment variable, but with different ports.

Even if I think applications are not very likely to start both servers, this is a valid use case still.
So my vote goes for `local.rsocket.server.port` and `@LocalRSocketServerPort`.

**Comment by wilkinsona** [comment]
Brian's our resident RSocket expert and Stéphane seems to be in agreement too. Let's go for `local.rsocket.server.port` and `@LocalRSocketServerPort` please. @veronicavasq and @eddumelendez, do you have time to update this PR to that effect? Please don't worry if you don't. We can make the amendments as part of merging what you've proposed thus far.

**Comment by eddumelendez** [comment]
We will be working on this on Tuesday (tomorrow)

**Comment by philwebb** [comment]
Thanks very much @veronicavasq for your first contribution to Spring Boot. This has now been merged into master with a small polish commit to relocate the class to the rsocket package.

**Pull request closed without merging**
