### PR TITLE
Security cleanup

### PR DESCRIPTION
**Pull request by rwinch**
My one concern is this seems like the changes I made may impact #1556 but I did not see any tests for that issue, so I'm not sure if I broke anything there.

cc @dsyer

### CODE REVIEW

**Comment by rwinch** [comment]
@dsyer @philwebb I'd really like this to make the next milestone if possible. Any chance you can take a look? 

PS: The build passed for me locally. It looks like Travis said it was taking too long and the build might be hung.

**Comment by philwebb** [comment]
Looks like both commits in this PR have been merged already.

**Comment by mikemosseri** [comment]
This actually broke the ability to not use the default in memory auth. The change on this line from configure to init (https://github.com/spring-projects/spring-boot/commit/e42fa79f7bbec1ed47e234c6825956357bc93f4d#diff-9fddf220548c41d170820f76c509875aR137).

This change causes auth.isConfigured to always be false even when there is another configuration. This is due to the AuthenticationManagerBuilder.performBuild not being called until init is complete. When the method was configure, the user defined security would be used and configured prior.

**Comment by dsyer** [comment]
I'm still using custom user details in a bunch of projects that seem to work. Can you open a new issue, please, anyway, and attach a sample project if possible? The spring-boit-issues project is a good place to send sample projects as pull requests.

**Comment by mikemosseri** [comment]
Yes, will try to. Look at your startup in your projects. You will see that it now shows:

org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration#147 - Using default security password: ad3ece3e-f4bd-4f3f-b71c-403bf510260d

**Comment by rwinch** [comment]
@mikemosseri Thanks for the report. This sounds like a duplicate of #2567

**Comment by mikemosseri** [comment]
@rwinch Yes, it is thanks. I couldn't find something similar earlier.

**Comment by rwinch** [comment]
@michaelbrand Did you see my EDIT? Specifically can you follow up on that ticket as to if both custom and generated credentials work? If so, I can push my fixes and perhaps you can verify against the latest snapshot. Thanks!

**Pull request closed without merging**
