### PR TITLE
fix possible resource leaks

### PR DESCRIPTION
**Pull request by igor-suhorukov**
This pull request is focused on resolving occurrences of Sonar rule [squid:S2095](https://sonarcloud.io/organizations/igor-suhorukov-github/rules#rule_key=squid%3AS2095) - Use try-with-resources or close this 

I inspect Spring Boot code with  [sonarcloud.io](https://sonarcloud.io/dashboard?id=org.springframework.boot%3Aspring-boot-build) and found some issues. Try to fix some blocker issues from #11623

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@igor-suhorukov Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=11624)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=11624) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@igor-suhorukov Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=11624)!

**Comment by snicoll** [comment]
@philwebb looking  at this one, I am a bit surprised about [this polish commit](https://github.com/spring-projects/spring-boot/commit/65b4f61a35eec5f9ae50434409160775fed27f90). Can you expand why you've removed this call to `close`?

**Comment by igor-suhorukov** [comment]
Do you use Continuous Code Quality tools like SonarQube in CI build?

**Comment by philwebb** [comment]
@snicoll No idea 🤷‍♂️  It was 2016

**Comment by philwebb** [comment]
> Do you use Continuous Code Quality tools like SonarQube in CI build?

@igor-suhorukov We have checkstyle rules but we don't have SonarQube. I've raised #11650.

**Pull request closed without merging**
