### PR TITLE
Support for custom repackaging to change loader classes

### PR DESCRIPTION
**Pull request by dsyer**
A layout can also optionally change the loader jar that is unpacked in the
root of the repackaged archive by implementing a new method in Layout.

### CODE REVIEW

**Comment by dsyer** [comment]
Latest commit reverts "layout" in Maven and Gradle config to be an enum again. Users have to provide a `LayoutFactory` explicitly now.

**Comment by philwebb** [comment]
@dsyer I'd like to change this a little so that instead of a custom `Layout` you can use a custom `Repackager`. I think it will give a little bit more flexibility.

Can you take a look at [this branch](https://github.com/philwebb/spring-boot/tree/gh-7263) and let me know if it will work for you? If so I'll merge it next week.

**Comment by dsyer** [comment]
I suppose that is a more liberal approach than what I proposed (something I wasn't trying to achieve). It works, but I'm not sold yet because the `Layout` is still quite a nice abstraction, and I'd like to provide one, so that I don't have to re-write all or most of the `Repackager`. But in the new implementation the layout (if provided by the user) is always injected into the custom `Repackager`. That means I have to override the setter for the `Layout` to prevent it from being overridden by the user-specified value, which feels a bit clunky. Don't you think that the launcher class archive should be part of the "layout" (if it was, as in my proposal, then I probably wouldn't have any complaint about the factory layer)?

**Comment by dsyer** [comment]
Another comment: it's probably good insurance to have a default `RepackagerFactory` that users can choose explicitly if they need it, so they can switch off a custom one that is activated by default.

**Comment by philwebb** [comment]
OK, let me have another go.

**Comment by philwebb** [comment]
@dsyer What about [this version](https://github.com/philwebb/spring-boot/tree/gh-7263-2). The `LayoutFactory` is back and it can return a `Layout` that also implements `CustomLoaderLayout` if custom loader classes need to be written.

The `loadFactory` only kicks in if you don't specify an explicit `layout` (so we don't need to provide a default `LayoutFactory`).

So:
- If the user specifies a `layout` (ZIP, JAR etc) it's always used.
- If the user doesn't specify `layout` and there isn't a `LayoutFactory` on the classpath the layout is based on the file extension.
- If the user doesn't specify `layout` and there's a single `LayoutFactory` on the classpath (and in `spring.factories`) the custom factory is used.
- If the user doesn't specify a `layout` but does specify `layoutFactory` then the factory is used.

**Comment by dsyer** [comment]
That works for me. A default layout factory still seems like a good idea, just in case anyone needs it, but I don't think it's a big deal (they are easy to write).

**Comment by philwebb** [comment]
OK, I'll add a `DefaultLayoutFactory` and get this in.

**Pull request closed without merging**
