### PR TITLE
Improve javadoc of management server port

### LINKED ISSUE #17054: Rectify javadoc for disabling management server port
According to the JavaDoc, setting the `management.server.port` property to `0` should disable the management server.
https://github.com/spring-projects/spring-boot/blob/b5d19b798eca7a6400a97e80d42601e027789aa6/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/web/server/ManagementServerProperties.java#L67-L72

However, according to the [Reference Guide](https://docs.spring.io/spring-boot/docs/2.1.5.RELEASE/reference/htmlsingle/#production-ready-disabling-http-endpoints), setting the value to `-1` is what is used to disable the http management server.

Based on empirical observation, the reference guide is correct. Setting the value of 
 `management.server.port` to `0` actually causes it to use a new random port for the management server, while setting the value to `-1` will disable the management server.

### PR DESCRIPTION
**Pull request by ielatif**
This commit rectifies and improves existing javadoc of management server port.
Closes #17054

### CODE REVIEW

**Comment by ielatif** [comment]
@mbhave the PR is raised against 2.1.x milestone. Can you change it please?

**Comment by philwebb** [comment]
@ielatif Thanks for the offer but there's no need. We'll just cherry-pick the commit.

**Comment by ielatif** [comment]
@philwebb thanks. Fixed checkstyle violations can you please rerun CI build?

**Comment by philwebb** [comment]
@ielatif The build is pending, it should build in a bit.

**Comment by ielatif** [comment]
@philwebb thanks, CI build is successful now

**Pull request closed without merging**
