### PR TITLE
Spring boot server port range support

### PR DESCRIPTION
**Pull request by ishara**
if `server.port` value is set to `0`, the server port will automatically assigned. 
If we need to restrict automatic port to specific  range value such as `8000`-`9000`, the new setting `server.port-range` feature added.  

Please check 
Thank you

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ishara Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9403)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9403) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ishara Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9403)!

**Comment by wilkinsona** [comment]
Thanks for opening your first Spring Boot pull request.

I see that you've used `SocketUtils.findAvailableTcpPort` to find a free port. Our [experience of using it in our own tests is that it's too flakey to use in main code](https://github.com/spring-projects/spring-boot/issues/9382). To consider merging this I think we'd need to use an alternative and, unfortunately, I don't know of a good one. Perhaps you do though?

**Comment by bclozel** [comment]
Could you explain the use case behind that change? Are you using this in production or when running tests on a CI instance?

Just so you know, with #9382 we're trying to limit the use of that `SocketUtils` method because it's not always reliable.

**Comment by ishara** [comment]
This is can not avoid, but if we can retry with until success with another port seems acceptably.
I have just check the code, If we can get the control of port binding for all org.springframework.boot.web.server.WebServer implementation, this can achieve.

**Comment by philwebb** [comment]
Unfortunately the issue we generally find with `SocketUtils.findAvailableTcpPort` isn't that it fails, but rather it thinks it has succeeded but in reality the port is not available. Adding a retry is unlikely so solve that issue I'm afraid.

The way that `SocketUtils.findAvailableTcpPort` works is that it first finds a free port and then it releases it so that it can be used by the real server. After the release happens the OS assumes it's free to dish it out again, so it can be used before the real server actually gets a chance to start.

The only way I can think of to support this would be to dig into the internals of Tomcat/Undertow/Jetty to see if it's possible to obtain and keep the server port directly.

**Comment by philwebb** [comment]
Thanks for the PR, but I think unfortunately we'll need to decline this in its current form for the above reasons. If you manage to find an alternative way to obtain the port please do open a new pull request.

Thanks again!

**Pull request closed without merging**
