### PR TITLE
Adding source line-number info in console log

### PR DESCRIPTION
**Pull request by ralic**
As subject, this will help developer to find where this log comes from.

Log Example  :
````
2018-06-16 13:39:59.956  INFO 39872 --- [ost-startStop-1] o.a.c.c.C.[.[.[/]                        :180 : Initializing Spring embedded WebApplicationContext
2018-06-16 13:39:59.957  INFO 39872 --- [ost-startStop-1] o.s.w.c.ContextLoader                    :87 : Root WebApplicationContext: initialization completed in 2475 ms
2018-06-16 13:40:00.597  INFO 39872 --- [ost-startStop-1] o.s.b.w.s.FilterRegistrationBean         :87 : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-06-16 13:40:00.597  INFO 39872 --- [ost-startStop-1] o.s.b.w.s.FilterRegistrationBean         :87 : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-06-16 13:40:00.597  INFO 39872 --- [ost-startStop-1] o.s.b.w.s.FilterRegistrationBean         :87 : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-06-16 13:40:00.598  INFO 39872 --- [ost-startStop-1] o.s.b.w.s.FilterRegistrationBean         :87 : Mapping filter: 'requestContextFilter' to: [/*]
2018-06-16 13:40:00.599  INFO 39872 --- [ost-startStop-1] .s.DelegatingFilterProxyRegistrationBean :87 : Mapping filter: 'springSecurityFilterChain' to: [/*]
2018-06-16 13:40:00.600  INFO 39872 --- [ost-startStop-1] o.s.b.w.s.FilterRegistrationBean         :87 : Mapping filter: 'httpTraceFilter' to: [/*]
2018-06-16 13:40:00.600  INFO 39872 --- [ost-startStop-1] o.s.b.w.s.FilterRegistrationBean         :87 : Mapping filter: 'webMvcMetricsFilter' to: [/*]
2018-06-16 13:40:00.601  INFO 39872 --- [ost-startStop-1] o.s.b.w.s.ServletRegistrationBean        :87 : Servlet dispatcherServlet mapped to [/]
2018-06-16 13:40:00.681  INFO 39872 --- [  restartedMain] c.z.h.HikariDataSource                   :110 : SpringBootJPAHikariCP - Starting...
2018-06-16 13:40:00.687  WARN 39872 --- [  restartedMain] c.z.h.u.DriverDataSource                 :68 : Registered driver with driverClassName=oracle.jdbc.driver.OracleDriver was not found, trying direct instantiation.
2018-06-16 13:40:00.858  INFO 39872 --- [  restartedMain] c.z.h.p.PoolBase                         :525 : SpringBootJPAHikariCP - Driver does not support get/set network timeout for connections. (null)
2018-06-16 13:40:00.887  INFO 39872 --- [  restartedMain] c.z.h.HikariDataSource                   :123 : SpringBootJPAHikariCP - Start completed.
2018-06-16 13:40:00.922  INFO 39872 --- [  restartedMain] j.LocalContainerEntityManagerFactoryBean :87 : Building JPA container EntityManagerFactory for persistence unit 'default'
2018-06-16 13:40:00.932  INFO 39872 --- [  restartedMain] o.h.j.i.u.LogHelper                      :31 : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2018-06-16 13:40:00.976  INFO 39872 --- [  restartedMain] o.h.Version                              :45 : HHH000412: Hibernate Core {5.2.17.Final}
2018-06-16 13:40:00.977  INFO 39872 --- [  restartedMain] o.h.c.Environment                        :213 : HHH000206: hibernate.properties not found
2018-06-16 13:40:01.007  INFO 39872 --- [  restartedMain] o.h.a.c.Version                          :66 : HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
2018-06-16 13:40:01.099  INFO 39872 --- [  restartedMain] o.h.d.Dialect                            :157 : HHH000400: Using dialect: org.hibernate.dialect.Oracle10gDialect
2018-06-16 13:40:01.109  INFO 39872 --- [  restartedMain] o.h.e.j.e.i.LobCreatorBuilderImpl        :63 : HHH000422: Disabling contextual LOB creation as connection was null
2018-06-16 13:40:01.425  INFO 39872 --- [  restartedMain] j.LocalContainerEntityManagerFactoryBean :87 : Initialized JPA EntityManagerFactory for persistence unit 'default'
2018-06-16 13:40:02.053  WARN 39872 --- [  restartedMain] aWebConfiguration$JpaWebMvcConfiguration :87 : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2018-06-16 13:40:02.117  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/api/inpark/v2/groups/{groupid}/poles/{category}],methods=[GET]}" onto public <T> T com.insynerger.inpark.controllers.LedPoleByCategoryController.findDecentPolesAPIResponse(java.lang.Long,java.lang.String,java.lang.Integer,java.lang.Integer,java.lang.String,java.lang.Boolean)
2018-06-16 13:40:02.119  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/api/inpark/v2/groups/{groupid}/poles],methods=[GET]}" onto public com.insynerger.inpark.responsebodies.poles.PolesAPIResponseBody com.insynerger.inpark.controllers.LedPoleListControllerV2.findDecentPolesAPIResponse(java.lang.Long,java.lang.Integer,java.lang.Integer,java.lang.String,java.lang.Boolean)
2018-06-16 13:40:02.119  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/api/inpark/v2/groups/{groupid}/{category}],methods=[GET]}" onto public <T> java.util.List<T> com.insynerger.inpark.service.category.BaseCategoryResponseServices.findDecentByGroupIDFromCategory(long,java.lang.String,java.lang.Integer,java.lang.Integer,java.lang.String,java.lang.Boolean)
2018-06-16 13:40:02.120  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/api/inpark/v1/categoryJson],methods=[GET]}" onto public java.lang.String com.insynerger.inpark.service.category.CategoryInfoServices.findCategoryJson()
2018-06-16 13:40:02.120  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/api/inpark/v1/category/{category}],methods=[GET]}" onto public java.util.List com.insynerger.inpark.service.category.CategoryInfoServices.findCodeList(java.lang.String)
2018-06-16 13:40:02.121  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/api/inpark/v1/groups/{groupid}/STREET_LIGHT],methods=[GET]}" onto public java.util.List com.insynerger.inpark.service.category.StreeLightResponseServices.findStreeLigthResponse(long,java.lang.String,java.lang.Integer,java.lang.Integer,java.lang.String,java.lang.Boolean)
2018-06-16 13:40:02.121  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/api/inpark/v1/photopath/{photopath}],methods=[GET]}" onto public org.springframework.data.domain.Page<com.insynerger.inpark.entities.AttachedfileEntity> com.insynerger.inpark.service.LedDevicesServices.findPhotoPath(java.lang.String)
2018-06-16 13:40:02.122  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/api/inpark/v1/devices/{poleid}],methods=[GET]}" onto public java.util.List<com.insynerger.inpark.responsebodies.poles.DevicesResponseBody> com.insynerger.inpark.service.LedDevicesServices.findDeviceRespondBodyByPoleId(java.lang.Long)
2018-06-16 13:40:02.122  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/api/inpark/v1/poleplace/{lplId}],methods=[GET]}" onto public <T> java.util.Optional<T> com.insynerger.inpark.service.LedPlaceListServices.findPolePlace(java.lang.Long)
2018-06-16 13:40:02.123  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/api/inpark/v1/groups/{groupid}/poles],methods=[GET]}" onto public <T> org.springframework.data.domain.Page<T> com.insynerger.inpark.service.LedPoleListServices.findPoleList(java.lang.Long,java.lang.Integer,java.lang.Integer,java.lang.String,java.lang.Boolean)
2018-06-16 13:40:02.126  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/swagger-resources]}" onto public org.springframework.http.ResponseEntity<java.util.List<springfox.documentation.swagger.web.SwaggerResource>> springfox.documentation.swagger.web.ApiResourceController.swaggerResources()
2018-06-16 13:40:02.126  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/swagger-resources/configuration/ui]}" onto public org.springframework.http.ResponseEntity<springfox.documentation.swagger.web.UiConfiguration> springfox.documentation.swagger.web.ApiResourceController.uiConfiguration()
2018-06-16 13:40:02.127  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/swagger-resources/configuration/security]}" onto public org.springframework.http.ResponseEntity<springfox.documentation.swagger.web.SecurityConfiguration> springfox.documentation.swagger.web.ApiResourceController.securityConfiguration()
2018-06-16 13:40:02.129  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2018-06-16 13:40:02.129  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerMapping :87 : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2018-06-16 13:40:02.188  INFO 39872 --- [  restartedMain] o.s.b.a.e.w.EndpointLinksResolver        :87 : Exposing 2 endpoint(s) beneath base path '/actuator'
2018-06-16 13:40:02.197  INFO 39872 --- [  restartedMain] s.b.a.e.w.s.WebMvcEndpointHandlerMapping :87 : Mapped "{[/actuator/health],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.String>)
2018-06-16 13:40:02.198  INFO 39872 --- [  restartedMain] s.b.a.e.w.s.WebMvcEndpointHandlerMapping :87 : Mapped "{[/actuator/info],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.String>)
2018-06-16 13:40:02.198  INFO 39872 --- [  restartedMain] s.b.a.e.w.s.WebMvcEndpointHandlerMapping :87 : Mapped "{[/actuator],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto protected java.util.Map<java.lang.String, java.util.Map<java.lang.String, org.springframework.boot.actuate.endpoint.web.Link>> org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping.links(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2018-06-16 13:40:02.312  INFO 39872 --- [  restartedMain] pertySourcedRequestMappingHandlerMapping :87 : Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
2018-06-16 13:40:02.477  INFO 39872 --- [  restartedMain] o.s.w.s.h.SimpleUrlHandlerMapping        :87 : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-06-16 13:40:02.540  INFO 39872 --- [  restartedMain] s.w.s.m.m.a.RequestMappingHandlerAdapter :87 : Looking for @ControllerAdvice: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@6f9ce375: startup date [Sat Jun 16 13:39:57 CST 2018]; root of context hierarchy
2018-06-16 13:40:02.578  INFO 39872 --- [  restartedMain] o.s.w.s.h.SimpleUrlHandlerMapping        :87 : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-06-16 13:40:02.578  INFO 39872 --- [  restartedMain] o.s.w.s.h.SimpleUrlHandlerMapping        :87 : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-06-16 13:40:03.033  INFO 39872 --- [  restartedMain] o.s.s.w.DefaultSecurityFilterChain       :87 : Creating filter chain: org.springframework.security.web.util.matcher.AnyRequestMatcher@1, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@6e60eb6, org.springframework.security.web.context.SecurityContextPersistenceFilter@14711943, org.springframework.security.web.header.HeaderWriterFilter@e05c8ea, org.springframework.security.web.csrf.CsrfFilter@2ed02ef0, org.springframework.security.web.authentication.logout.LogoutFilter@5f5a38ae, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@3c3e0771, org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter@47d86e92, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@5e672eb0, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@6763b149, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@6e0e0e9c, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@29e4b8a4, org.springframework.security.web.session.SessionManagementFilter@4a694644, org.springframework.security.web.access.ExceptionTranslationFilter@3486be97, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@650ca7f]
2018-06-16 13:40:03.125  INFO 39872 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        :87 : Registering beans for JMX exposure on startup
2018-06-16 13:40:03.127  INFO 39872 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        :87 : Bean with name 'dataSource' has been autodetected for JMX exposure
2018-06-16 13:40:03.131  INFO 39872 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        :87 : Located MBean 'dataSource': registering with JMX server as MBean [com.zaxxer.hikari:name=dataSource,type=HikariDataSource]
2018-06-16 13:40:03.136  INFO 39872 --- [  restartedMain] o.s.c.s.DefaultLifecycleProcessor        :87 : Starting beans in phase 2147483647
2018-06-16 13:40:03.136  INFO 39872 --- [  restartedMain] d.s.w.p.DocumentationPluginsBootstrapper :147 : Context refreshed
2018-06-16 13:40:03.147  INFO 39872 --- [  restartedMain] d.s.w.p.DocumentationPluginsBootstrapper :150 : Found 1 custom documentation plugin(s)
2018-06-16 13:40:03.167  INFO 39872 --- [  restartedMain] s.d.s.w.s.ApiListingReferenceScanner     :41 : Scanning for api listing references
2018-06-16 13:40:03.308  INFO 39872 --- [  restartedMain] .d.s.w.r.o.CachingOperationNameGenerator :40 : Generating unique operation named: findDecentPolesAPIResponseUsingGET_1
2018-06-16 13:40:03.318  INFO 39872 --- [  restartedMain] .d.s.w.r.o.CachingOperationNameGenerator :40 : Generating unique operation named: handleUsingGET_1
2018-06-16 13:40:03.346  INFO 39872 --- [  restartedMain] o.a.c.h.Http11NioProtocol                :180 : Starting ProtocolHandler ["https-jsse-nio-192.168.10.59-9908"]
2018-06-16 13:40:03.417  INFO 39872 --- [  restartedMain] o.a.t.u.n.NioSelectorPool                :180 : Using a shared selector for servlet write/read
2018-06-16 13:40:03.428  INFO 39872 --- [  restartedMain] o.s.b.w.e.t.TomcatWebServer              :87 : Tomcat started on port(s): 9908 (https) with context path ''
2018-06-16 13:40:03.431  INFO 39872 --- [  restartedMain] c.i.InPark                               :87 : Started InPark in 6.758 seconds (JVM running for 7.318)
Spring Boot Application Started
2018-06-16 13:40:03.885  INFO 39872 --- [on(2)-127.0.0.1] o.a.c.c.C.[.[.[/]                        :180 : Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-06-16 13:40:03.886  INFO 39872 --- [on(2)-127.0.0.1] o.s.w.s.DispatcherServlet                :87 : FrameworkServlet 'dispatcherServlet': initialization started
2018-06-16 13:40:03.905  INFO 39872 --- [on(2)-127.0.0.1] o.s.w.s.DispatcherServlet                :87 : FrameworkServlet 'dispatcherServlet': initialization completed in 18 
```

<!--
Thanks for contributing to Spring Boot. Please provide a brief description of your pull-request and reference any related issue numbers (prefix references with #).
-->

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ralic Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=13497)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=13497) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ralic Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=13497)!

**Comment by wilkinsona** [comment]
Thanks for the PR. Unfortunately, I don’t think that this change is a suitable default. From Logback’s documentation:

> Generating the line number information is not particularly fast. Thus, its use should be avoided unless execution speed is not an issue.

Thanks anyway.

**Comment by ralic** [comment]
I was using the same pattern on log4j2. Talking about performance, many test reports showed that Log4j2 is significantly faster than logback. Particularly in the asynchronous logging. Would there be a plan to migrate default spring-start-logging to use log4j2?
https://logging.apache.org/log4j/2.x/performance.html

**Comment by wilkinsona** [comment]
> Would there be a plan to migrate default spring-start-logging to use log4j2?

No, not at the moment anyway. In our experience the performance difference isn't as large as those tests suggest and, in terms of startup, Logback is actually faster. For example, an app that starts in approximately 4 seconds with Logback takes 4.1 seconds with Log4j2.

**Pull request closed without merging**
