### PR TITLE
Make intermediate classes in type hierarchy of public class public

### PR DESCRIPTION
**Pull request by izeye**
Based on https://github.com/spring-projects/spring-boot/issues/11929#issuecomment-363548571, there are a few classes which don't align with it. This PR tries to align them with it.

### CODE REVIEW

**Comment by philwebb** [comment]
Not sure I totally agree that a package private class shouldn't be part of the hierarchy. I've flagged this one for team discussion.

**Comment by wilkinsona** [comment]
My reasoning is that if you indirectly extend a package-private class then you are inheriting from and are exposed to Boot's internals. I don't think we should inflict that exposure on people. Gradle's API has a number of classes where internals leak out in this manner and it's been the main source of compatibility problems with both Boot's plugin and the dependency management plugin.

**Comment by izeye** [comment]
For example, `AbstractNestedCondition` is package-private but has a protected method and a protected nested class, so it's open for its children's inheritance unless its all children are final: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/AbstractNestedCondition.java#L68-L102

And also the protected nested class, `AbstractNestedCondition.MemberMatchOutcomes` is exposed in "Nested Class Summary" section in Javadoc as a broken link: https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/api/org/springframework/boot/autoconfigure/condition/AllNestedConditions.html

**Comment by snicoll** [comment]
I felt the same way as @philwebb initially but @wilkinsona shared that compelling argument previously. I think it would be more consistent to make them public.

**Comment by philwebb** [comment]
We discussed this on our call today and I've been convinced. Will merge this in 2.0.x.

**Comment by philwebb** [comment]
We need to check the `@since` tags when we merge.

**Comment by snicoll** [comment]
@philwebb `@since` tags look good. Thanks again @izeye!

**Pull request closed without merging**
