### PR TITLE
Add support for configuring missingQueuesFatal property

### PR DESCRIPTION
**Pull request by nosan**
see [gh-14122](https://github.com/spring-projects/spring-boot/issues/14122)

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks again @nosan, please review the [polish commit](https://github.com/spring-projects/spring-boot/commit/c1322a543ce426f1daa71c9a9f30d051347b6e46) if you can.

**Comment by nosan** [comment]
@snicoll I wanted to do the same way, but I haven't done because of the javadoc meanings. Could you please check one more time the difference between simple/direct  `missing-queues-fatal`, just to make everything is ok :)

[Simple ](https://docs.spring.io/spring-amqp/api/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.html#setMissingQueuesFatal-boolean-) , [Direct](https://docs.spring.io/spring-amqp/api/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.html#setMissingQueuesFatal-boolean-)


Thanks in advance.

**Comment by garyrussell** [comment]
>When true, if the queues are removed while the container is running, the containeris stopped.

This difference is because of the internal design of the containers.

With the SMLC, each consumer instance can listen to multiple queues; if any one of those queues is deleted from the broker; the consumer is killed by the broker.
With the new container (Direct), there is a consumer for each queue, so deleting one queue doesn’t affect the other consumer(s).

**Comment by snicoll** [comment]
Alright, let's document that as two keys. I'll push another polish later today

**Comment by snicoll** [comment]
@nosan thank you very much for drawing my attention to this. I thought that the properties were common since it was calling the abstract factory but it turns out that there is a subtle semantic difference the we have to explain. I took the opportunity to revisit this a bit further by exposing the difference in default values (rather than keeping `Boolean).

**Pull request closed without merging**
