### PR TITLE
Upgrade to Spring Cloud Connectors 1.2.0.RELEASE

### PR DESCRIPTION
**Pull request by royclarkson**

### CODE REVIEW

**Comment by snicoll** [comment]
See #3443

**Comment by wilkinsona** [comment]
The release isn't in Maven Central yet so on putting this on hold for now. /cc @royclarkson @scottfrederick

**Comment by scottfrederick** [comment]
Spring Cloud Connectors 1.2.0.RELEASE is now in Maven Central.

**Comment by royclarkson** [comment]
ping @wilkinsona

**Pull request closed without merging**
