### PR TITLE
Add ConnectionDetails and ServiceConnection support to Pulsar

### PR DESCRIPTION
**Pull request by onobc**
1. Add connection details to Pulsar auto-configuration.
2. Add service connection details impl to Pulsar for testcontainers support
3. Update Pulsar smoke tests to use `@ServiceConnection`
4. Add docker compose connection details impl (Docker Compose support)

cc: @eddumelendez @philwebb

### CODE REVIEW

**Comment by mhalbritter** [comment]
Hey Chris,

thank you for that PR! Do you know if there's a suitable docker image for Apache Pulsar so that we could add Docker Compose support for Pulsar, too? Ideally we want to have both Testcontainers and Docker Compose support.

**Comment by onobc** [comment]
@mhalbritter I already have another commit already queued up to add Docker compose support but wanted to keep this PR smaller. Shall I add the other commit here in this PR? I am ok w/ that and it will take me only a couple mins. Lmk.

**Comment by mhalbritter** [comment]
Ah, cool! Yes, please add this commit to this PR too. Then we have the whole `ConnectionDetails` story for Pulsar in one PR. Thanks!

**Comment by philwebb** [comment]
Thanks @onobc!

**Pull request closed without merging**
