### PR TITLE
Add spring.mvc.view-controller.* property

### PR DESCRIPTION
**Pull request by making**
Add `spring.mvc.view-controller.*` allowing users to configure the map for the given URL path (or pattern) and pre-configured view.

This commit eliminates creating trivial controllers like the following:

``` java
@Contoller
public class HelloController {
  @RequestMapping("/hello/**")
  public String hello() {
    return "hello";
  }
}
```
by configuring
``` properties
spring.mvc.view-controller./hello/**=hello
```
in `application.properites`

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR, but this feels a little too much like programming via properties to me and Spring MVC already provides an API that lets you do this in a single line per view:

```java
static class MvcConfiguration extends WebMvcConfigurerAdapter {
	@Override
	public void addViewControllers(ViewControllerRegistry registry) {
		registry.addViewController("/hello/**").setViewName("hello");
	}
}
```

I also worry that a properties-based approach may trip people up when they want to include a `.` in the path of the request mapping.

**Comment by snicoll** [comment]
I concur.

Also, I don't like the idea of having a path as the key of a map. This feels a bit unnatural to me.

**Comment by making** [comment]
Thank you for your comments.

Of course, I know `WebMvcConfigurerAdapter#addViewControllers`.
I don't think it's a convenient way because I feel creating `HelloController` is easier and straightforward.

If I could configure in properties, I feel convenient because there is no need to write code.
Moreover, IDE suggests how to configure it.

This property would be useful in some case, e.g. welcome page, login form page.

I feel it is a matter of practice. Actually, some properties like `spring.jpa.properties.aaa.bbb` and `logging.level.aaa.bbb` already allow including `.` in their key and can have `/` or others in principal.

**Comment by making** [comment]
If you still feel unnatural, how about the following idea?

``` properties
spring.mvc.view-controller[0].urlPath=/hello/**
spring.mvc.view-controller[0].viewName=hello
spring.mvc.view-controller[0].statusCode=200
```

**Comment by wilkinsona** [comment]
Sorry, I'm still not keen for a couple of reasons:

- I can't see much benefit in externalising this configuration
- It's less concise than the Java API

In short, I think it's adding the cost of there being another way to achieve something without any benefit.

**Comment by making** [comment]
OK. Thank for your comment.

**Pull request closed without merging**
