### PR TITLE
Polish Pivotal GemFire starter and sample.

### PR DESCRIPTION
**Pull request by jxblum**
Closes gh-5439.

### CODE REVIEW

**Comment by snicoll** [comment]
Merged with [a polish commit](https://github.com/spring-projects/spring-boot/commit/d4a1365a2a551e2caf34d37bb41d27828507f5a0). Thanks!

**Comment by wilkinsona** [comment]
Reopening as we need to get rid of the dependency management for Spring Shell

**Comment by wilkinsona** [comment]
Reopening once again. The dependency management for Gemfire needs to be reinstated. We shouldn't rely on the transitive dependency pulling in the right version as it's then possible that another dependency would down or upgrade the version to one that isn't supported.

**Comment by jxblum** [comment]
@wilkinsona 

> We shouldn't rely on the transitive dependency pulling in the right version as it's then possible that another dependency would down or upgrade the version to one that isn't supported.

Understood; that makes sense.  However, I fail to see any reason why an explicit dependency declaration is needed in the [spring-boot-starter-data-gemfire/pom.xml](https://github.com/spring-projects/spring-boot/blob/v1.4.0.M1/spring-boot-starters/spring-boot-starter-data-gemfire/pom.xml#L25-L34) at all if...

1. GemFire is appropriately managed in the `spring-boot-dependencies/pom.xml`, as it was [here](https://github.com/spring-projects/spring-boot/blob/v1.4.0.M1/spring-boot-dependencies/pom.xml#L70) and [here](https://github.com/spring-projects/spring-boot/blob/v1.4.0.M1/spring-boot-dependencies/pom.xml#L616-L626).

2. Regardless if _Spring Data GemFire_ (using the [starter](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-starters/spring-boot-starter-data-gemfire/pom.xml#L26-L35)), or another _Spring Boot Starter_ (e.g. _integration_) or even say, an application dependency, pulls in GemFire transitively, as long as the starter, or possibly the application POM, (indirectly) inherits from the `spring-boot-dependencies/pom.xml`, such as through the `spring-boot-parent` (for the `spring-boot-starter-data-gemfire`, the hierarchy is `spring-boot-starters` -> `spring-boot-parent` -> `spring-boot-dependencies`), then the explicit **GemFire** dependency declaration should not be needed, yet the right version of **GemFire** for _Spring Boot_, and specifically SDG or any other module (e.g. integration) will be used.

I would also caution that **Spring Data GemFire** has a very [specific requirement](https://github.com/spring-projects/spring-data-gemfire/wiki/Spring-Data-GemFire-to-GemFire-Version-Compatibility) on the **version** of **GemFire** used.  It was both a mistake and naive that SDG supported multiple simultaneous versions of GemFire at once in the past, something I have corrected since then.

So, it is absolutely paramount that the `gemfire.version` managed by _Spring Boot_ is kept in-sync with the version that _Spring Data GemFire_ expects, which determined by the _Spring Data Release Train_ version pulled in by _Spring Boot_.  Not that this is not managable, but will require a bit of extra care and attention.

**Comment by wilkinsona** [comment]
> However, I fail to see any reason why an explicit dependency declaration is needed in the spring-boot-starter-data-gemfire/pom.xml at all

You've linked to the starter from M1. As things stand, there's no such dependency in the starter.

> I would also caution that Spring Data GemFire has a very specific requirement on the version of GemFire used.

Thanks. We understand that. It's no different to several other dependencies for which we also provide dependency management.

**Comment by jxblum** [comment]
> As things stand, there's no such dependency in the starter.

I saw that, actually (I only referenced M1 assuming we wanted tor revert back to how it was).

So is there anything that needs to be done with this PR, or that I should redo?

**Comment by wilkinsona** [comment]
Nothing more needs to be done. I took care of the last two niggles in the two commits that are referenced above (https://github.com/spring-projects/spring-boot/commit/e0f9da5afe6584fed9d25c88893b895d5db4990e and https://github.com/spring-projects/spring-boot/commit/b4ea90c2ccc740f608a7b15120788eae37c31bc7)

**Comment by jxblum** [comment]
Thanks @wilkinsona!

**Pull request closed without merging**
