### PR TITLE
Upgrade to Jackson 2.12.0

### PR DESCRIPTION
**Pull request by valfirst**

### CODE REVIEW

**Comment by philwebb** [comment]
Interesting that some classes have been renamed. I wonder if we should try to tolerate older Jackson versions as well?

**Comment by dreis2211** [comment]
@philwebb See https://github.com/FasterXML/jackson-databind/issues/2715 for the reason behind the renaming.

**Comment by snicoll** [comment]
@valfirst thank you for making your first contribution to Spring Boot. I've polished to tolerate older Jackson versions.

**Comment by wilkinsona** [comment]
We subsequently upgraded to 2.12.1 (https://github.com/spring-projects/spring-boot/commit/7b39cfb06133c287994483c3ab90fc521a8217a4). I've retitled this PR so that the release notes are accurate and @valfirst is still credited for their contribution.

**Pull request closed without merging**
