### PR TITLE
Fix default value for `spring.mobile.devicedelegatingviewresolver.ena…

### PR DESCRIPTION
**Pull request by izeye**
…bled`

### CODE REVIEW

**Comment by snicoll** [comment]
Well, this is similar to other PRs in that area. Default value and sample value are both used in the documentation in a interchangeable way. I'd rather have one PR that would fix it all rather than changing things individually. 

For instance, the default for the batch schema script is not "nice" (maybe that's not the proper place to put that value). And the sample value for the "devicedelegatingviewresolver' is unfortunate indeed (says the contrary of the default).

**Comment by izeye** [comment]
@snicoll Sorry. I just thought the place only for default.

Feel free to close my PRs that are inappropriate.

Thanks for the feedback :)

**Comment by snicoll** [comment]
I do think it's appropriate but splitting that conversation in multiple PRs isn't great. Could you please submit one PR where this is fixed instead?

**Comment by izeye** [comment]
@snicoll I understand and I can

but if the place is not only for default, my PRs don't seem to have any value.

**Comment by snicoll** [comment]
That's the discussion we're having now. I think both are useful but if there is no way to distinguish one of the other it probably does more harm than it helps.

@wilkinsona, @philwebb thoughts?

**Comment by wilkinsona** [comment]
My understanding was that the convention was for the default value for each property to be shown in the appendix, but I'm not sure where that understanding came from. I think that showing the default value in the documentation's a good idea. If others agree I think we should update the preamble in the appendix to document it and then apply the convention consistently.

**Comment by snicoll** [comment]
I have created #3230 to discuss/track this one. Based on what we decide to do we'll either merge this one or work on the harmonization instead.

**Pull request closed without merging**
