### PR TITLE
Add HTTP header fields to the error attributes

### PR DESCRIPTION
**Pull request by mnhock**

### CODE REVIEW

**Comment by wilkinsona** [comment]
See #4741 (also raised by @mnhock) which is part of the same theme

**Comment by pivotal-issuemaster** [comment]
@mnhock Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=4744) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mnhock Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=4744)!

**Comment by philwebb** [comment]
We're not keen to do this out of the box since it's possible we might end up echoing something sensitive.  It's relatively easy to this yourself by providing a different `errorAttributes` bean.

**Comment by mengchengfeng** [comment]
@philwebb I understand the desire to avoid echoing sensitive information, but it's only "easy" to find out the headers ourselves in a custom `errorAttributes` if the Throwable contains header information. For errors such as HttpRequestMethodNotSupportedException, it didn't seem like there was a way for me to retrieve request header information using the information available to ErrorAttributes. 

Any advice on retrieving header attributes for _all_ errors?

**Pull request closed without merging**
