### PR TITLE
Upgrade to Jackson 2.8.6 and replace Jackson manual dependency management by the import of its bom

### PR DESCRIPTION
**Pull request by eddumelendez**
Before this commit, Jackson's dependency management have been managed by
spring-boot. This commit, remove the manual dependency management in
favor of jackson's bom.

See gh-7432

### CODE REVIEW

**Comment by eddumelendez** [comment]
@wilkinsona regarding jackson's dependency management, the only missing dependency in the BOM is `com.fasterxml.jackson.jaxrs:jackson-jaxrs-base` which is transitive dependency of `jackson-jaxrs-json-provider`. I think that should be ok for now. isn't it?

**Comment by wilkinsona** [comment]
Thanks, @eddumelendez. I see you've opened https://github.com/FasterXML/jackson-bom/issues/2. Thank you for that. I think we should wait for that to be fixed before we adopt the bom otherwise there's a possibility that someone will end up with Jackson modules with a mixture of versions on the classpath.

**Comment by snicoll** [comment]
We need a Jackson 2.8.6 release.

**Comment by eddumelendez** [comment]
jackson-bom 2.8.6 was released days ago. PR is updated :)

**Comment by wilkinsona** [comment]
Thanks for the PR, @eddumelendez!

**Comment by lucamartellucci** [comment]
Hi to all,
i've a problem with the configuration for java 6.
as explained in the documentation http://docs.spring.io/spring-boot/docs/1.5.1.RELEASE/reference/htmlsingle/#howto-use-java-6-jackson i've downgraded the version of jackson to 2.6.x but during the build, maven fails because it needs the jackson-bom version 2.6.x but it doesn't exist! i've checked here https://github.com/FasterXML/jackson-bom

i'm a bit confused, can you help me!
Thank you!

**Comment by wilkinsona** [comment]
@lucamartellucci Ah, that's an unwanted side-effect that we'd overlooked. Can you open a new issue please? We'll either need to update the docs or drop the use of the bom till 2.0

**Pull request closed without merging**
