### PR TITLE
Allow custom repo-locations for InstallCommand

### PR DESCRIPTION
**Pull request by joshiste**
specify with  --remoteRepositories &lt;id&gt;::&lt;url&gt;
e.g. --remoteRepositories spring-ms::http://repo.spring.io/milestone

closes gh-2659

CLA 93620140928055712

### CODE REVIEW

**Comment by joshiste** [comment]
Is there a chance to get this into 1.2.3?

**Comment by philwebb** [comment]
We'll do our best. @dsyer / @wilkinsona  any concerns about this PR since you've both touched that code in the past?

**Comment by wilkinsona** [comment]
There's some overlap here with `settings.xml` which the CLI already reads for configuring mirrors, proxies, etc. We should consider expanding that to also look at profiles as a means of configuring the repositories that are used for dependency resolution.

If we end up going with the route suggested in this PR, then I don't think the switch should be called `remoteRepositories`. "remote" is unnecessary and I also think the switch should be singular with support for specifying it multiple times to configure multiple repositories. This would align more closely with Unix conventions. I'd call it `--repository`

**Comment by joshiste** [comment]
Hmm,  is it possible that respecting settings.xml is only implemented for
grab- and not for install-command?

**Comment by wilkinsona** [comment]
No, I don't think so. The install command is implemented as a `@Grab` under the covers so it should be using the exact same logic. What makes you think that install may be ignoring `settings.xml`?

**Comment by philwebb** [comment]
I think we'll need to push this back to 1.3.0 I'm afraid. It seems like there are still decisions to iron out.

**Comment by joshiste** [comment]
K.  I must give it a second try to get the settings.xml being used. On my
first try I could not make it work... Is there any docs on this? Couldn't
really find one...

**Comment by wilkinsona** [comment]
@joshiste Did you see my earlier question "What makes you think that install may be ignoring settings.xml?" Note that, at the moment, we won't find any extra repositories in profiles in your settings.xml, just proxies, mirrors, etc.

I've opened #2703 to document the CLI's support for reading some configuration from `settings.xml`

**Comment by joshiste** [comment]
> Note that, at the moment, we won't find any extra repositories in profiles in your settings.xml

ah ok. that what was i thought, without a deeper look into the XmlSettings code. And so I assumed setting.xml is ignored

**Comment by wilkinsona** [comment]
@joshiste Thanks for the PR. We discussed this again today and have decided that we'd prefer to tackle this by enhancing the existing code that looks at settings.xml to also honour the repositories that are configured there. Would you like to take a look at that in another PR?

**Comment by joshiste** [comment]
I'll have a look at it in anther PR.
I would simply add all repositories from the active profiles.
Am I allowed to pass the repository list into `RepositorySystemSessionAutoConfiguration#apply()` for modification?

**Pull request closed without merging**
