### PR TITLE
Add disk space health indicator's path to its details and log message

### PR DESCRIPTION
**Pull request by rreich**
Directly seeing the path would make it easier for developers and administrators to find and fix a configuration issue.

### CODE REVIEW

**Comment by snicoll** [comment]
@rreich thanks for the PR we can proceed until you've signed the CLA.

**Comment by rreich** [comment]
@snicoll Thanks for looking at the PR and for the hint. I hoped this might be considered an ["obvious fix"](https://cla.pivotal.io/about#obvious-fixes). I signed the CLA now.

**Comment by wilkinsona** [comment]
@rreich Thanks very much for making your first contribution to Spring Boot.

**Comment by rreich** [comment]
Thanks  @wilkinsona !
Unfortunately I just noticed that you seem to integrate fixes upwards, so I should have probably created this PR against 2.6.x (The version we are using currently).
I created a new PR for that now by cherry-picking from main: https://github.com/spring-projects/spring-boot/pull/32234
Sorry for my misunderstanding - I should have checked beforehand. If it is too much of an inconvenience, feel free to close the new PR.

**Comment by wilkinsona** [comment]
No problem. As Brian explained on #32234, this isn't the sort of change that we'd make in a maintenance release anyway. It's not fixing a bug so it belong in the next major or minor release. That's 3.0 at this time.

**Pull request closed without merging**
