### PR TITLE
Quartz may attempt to use the DataSource before migrations have been run

### PR DESCRIPTION
**Pull request by nosan**
see gh-17528

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks yet again @nosan! This has now been merged into 2.1 and forward-ported to 2.2. I changed things slightly in 75a1a2491453ae609749fb46dfff7aea64b1e927 so `@Bean` methods are used in favor of multiple `@Configuration` classes.

**Comment by nosan** [comment]
Thank you very much, @philwebb

Just to make sure, I see that `@ConditionalOnClass` annotations have been removed. Did you really want to remove them or it was done accidentally?

**Comment by philwebb** [comment]
Hi @nosan, That was intentional and `@ConditionalOnBean` should deal with any `ClassNotFoundException`.

**Comment by sausageRoll** [comment]
Hello @philwebb 

I'm facing this issue right now. Could you take a look please?

**Comment by wilkinsona** [comment]
@sausageRoll AFAIK, this problem's been fixed since 2.1.8 and shouldn't occur with 2.3.1. If you are seeing it with 2.3.1, please open a new issue and provide a minimal sample that reproduces the problem.

**Pull request closed without merging**
