### PR TITLE
Enable ApplicationPidFileWriter by setting application.properties

### PR DESCRIPTION
**Pull request by lbdx**
Enable ApplicationPidFileWriter by application.properties. #2201

### CODE REVIEW

**Comment by lbdx** [comment]
Enable ApplicationPidFileWriter by application.properties. #2201

**Comment by philwebb** [comment]
Thanks! Have you signed the CLA?

**Comment by izeye** [comment]
@lbdx @philwebb Is it possible to work?

I tried to register `ApplicationPidFileWriter` by bean before but it didn't work.

I thought it's too late to catch `ApplicationPreparedEvent`

when `ApplicationPidFileWriter` is registered by bean instead of adding to `SpringApplication`.

I made a sample project:
https://github.com/izeye/samples-spring-boot-branches/tree/pid

**Comment by lbdx** [comment]
@philwebb  I have signed the cla.
@izeye I will try to run your sample project.

**Comment by philwebb** [comment]
@izeye I haven't review the pull-request yet.

**Comment by philwebb** [comment]
This could probably be reworked to use `setTriggerEventType` on the `ApplicationPidFileWriter` bean rather than needing to convert the event.

**Comment by philwebb** [comment]
Leaving this for now due to the reasons discussed in https://github.com/spring-projects/spring-boot/issues/2201#issuecomment-120490927

**Comment by izeye** [comment]
@philwebb I guess this should be closed because this is labeled as `wontfix`.

**Pull request closed without merging**
