### PR TITLE
Polymorphic where clause

### PR DESCRIPTION
**Pull request by thapabhanu**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@thapabhanu Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7116)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7116) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by snicoll** [comment]
@thapabhanu before we act on this PR, please push force an update with a single commit that only changes what you intended to change. The code format of your IDE changed too many lines, please check [the contributing page](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc) for more details.

The type in the doc is typically not part of this, we'll fix it separately. Thanks!

**Comment by philwebb** [comment]
I'm going to close this one for now because it's not clear if the pull-request is from @thapabhanu or @eneveu. We really need the person that's writing the code to submit the pull-request so that the CLA is signed correctly.

If you do resubmit this, please provide some more background about why you want the change.

**Comment by eneveu** [comment]
Sorry guys, just saw this notification... I have no idea why @thapabhanu created this pull request. Maybe he misclicked and created a pull request by mistake?

I had originally cloned your repository and added a few commits, to create a test case for this StackOverflow question: http://stackoverflow.com/questions/29277094/polymorphic-where-clause-using-querydsl

There is nothing to merge here.

**Pull request closed without merging**
