### PR TITLE
Add support for AWS Redshift JDBC driver

### PR DESCRIPTION
**Pull request by hekonsek**
Hi,

Nothing fancy here - just added AWS Redshift JDBC driver definition to DatabaseDriver enum, so it could be auto-detected by `DataSourceBuilder`.

Thanks!

### CODE REVIEW

**Comment by philwebb** [comment]
Nice, thanks!

**Comment by snicoll** [comment]
Thanks @hekonsek!

**Comment by hekonsek** [comment]
Thank you for merging!

**Comment by wilkinsona** [comment]
Re-opening as the change has broken the build. It causes `DatabaseDriverClassNameTests` to fail as `com.amazon.redshift.jdbc.Driver` isn't on the classpath. Redshift needs to be excluded from the tests.

**Comment by dreis2211** [comment]
I was already working on a fix, while you reopened this @wilkinsona . See gh-16905.

**Pull request closed without merging**
