### PR TITLE
Adds loadOnStartup property to EndpointServlet

### LINKED ISSUE #15672: Allow to set loadOnStartup on actuator EndpointServlet's
https://github.com/spring-projects/spring-boot/blob/badccc083e1e3b24aee684fb306845f48c1f7147/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/web/ServletEndpointRegistrar.java#L73-L78

Why is setting loadOnStartup not allowed in ServletEndpointRegistrar?
In my specific use case I need that the invocation of 'init' method in wrapped Servlet instance be on startup, not in the first http invocation.
Is there a reason to not provide this option for EndPointServlet's?

To provide it, org.springframework.boot.actuate.endpoint.web.EndpointServlet should contain a property 'loadOnStartup' in addition to already present 'initParameters' property. If there is no reason to not do it, I can provide a PR.

Thanks for answering.

### PR DESCRIPTION
**Pull request by juliojgd**
loadOnStartup property was missing from EndpointServlet and cannot
be set inside ServletEndpointRegistrar. Now it can be set and register
a Servlet with that integer property ready to act upon registration

Fixes #15672

### CODE REVIEW

**Comment by juliojgd** [comment]
I removed an unused import in EndpointServlet.

**Comment by juliojgd** [comment]
@wilkinsona It seems that the concourse build failed because of changes in hateoas module  (not made by my commits). It will be marked OK in following builds or is any further action required by me?

**Comment by wilkinsona** [comment]
There were some breaking API changes in recent HATEOAS snapshots. We've adapted to them on master now. No need for you to take any further action. We'll rebase your changes prior to merging them. Thanks for asking.

**Comment by snicoll** [comment]
@juliojgd thank you very much for making your first contribution to Spring Boot. This work is now merged in `master`.

**Comment by juliojgd** [comment]
@snicoll Thank you very much for your review. I hope I will be contributing again. :)

**Pull request closed without merging**
