### PR TITLE
Update Readme.adoc

### PR DESCRIPTION
**Pull request by charlie-harvey**
Added spring-boot-starter-nifty - a Spring Boot Starter for Facebook's Nifty service.

### CODE REVIEW

**Comment by spencergibb** [comment]
[Here](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) is the naming convention for third party starter.

**Comment by charlie-harvey** [comment]
Oh. Mah. Gahd.

Ok. So, renaming all the things. Will re-submit.

**Comment by spencergibb** [comment]
@charlie-harvey :stuck_out_tongue_winking_eye:

**Comment by snicoll** [comment]
Thank you @spencergibb !

**Comment by wilkinsona** [comment]
Merged into master. Thanks for the PR.

**Pull request closed without merging**
