### PR TITLE
Use more specific AssertJ MapAssert for return of JsonContentAssert#extractingJsonPathMapValue

### PR DESCRIPTION
**Pull request by mihhail-lapushkin**
Fixed this: https://github.com/spring-projects/spring-boot/issues/9650
[ sorry for typo in the commit message :( ]

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mihhail-lapushkin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9675)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9675) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mihhail-lapushkin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9675)!

**Comment by philwebb** [comment]
That's for the PR. No worries about the commit message, we'll fix that when we merge.

**Comment by filiphr** [comment]
@philwebb I don't know your policy on this things, but I would propose that you align the returns of AssertJ with the returns of the `JsonContentAssert`.  The same problem happens for `JsonContentAssert#extractingJsonPathArrayValue`.  Sorry that I didn't mention it in the initial ticket, I could open another one if you want to.

**Comment by philwebb** [comment]
Thanks @filiphr, no need for a new ticket as it's all related to the same underling issue. 

@mihhail-lapushkin if you're able to update the PR with the addition methods, that would be fantastic. Otherwise we'll do it when we merge.

**Comment by mihhail-lapushkin** [comment]
Fixed `JsonContentAssert#extractingJsonPathArrayValue`. Not sure if others need fixing / could be fixed.

**Comment by filiphr** [comment]
I think that the others are OK. 

Theoretically what could be done if it is needed on spring boot side is to have a test that will check the signatures between `AssertJ` and `JsonContentAssert`, but that might be an overkill...

**Comment by wilkinsona** [comment]
Thanks very much for the PR, @mihhail-lapushkin. I've merged it into 1.5.x and master with [some minor polishing](https://github.com/spring-projects/spring-boot/commit/f6727e786a2c50fd54d7387e1f4e94f78dc0dc3a).

**Pull request closed without merging**
