### PR TITLE
Provide dependency management for MariaDB Java client.

### PR DESCRIPTION
**Pull request by izeye**
I would be good to provide dependency management for MariaDB Java client.

### CODE REVIEW

**Comment by philwebb** [comment]
One for @wilkinsona to decided I think. I'm not sure that this wouldn't be better off in the platform since we don't directly provide any support for MariaDB in Boot.

**Comment by wilkinsona** [comment]
We (sort of) do support MariaDB as it's one of the driver's listed in `DatabaseDriver`. MySQL is also supported in `DatabaseDriver` and we provide dependency management for it. I'm happy for it to go in Boot.

**Comment by philwebb** [comment]
Sounds good to me

**Comment by izeye** [comment]
Thanks!

**Comment by wilkinsona** [comment]
@izeye Thanks for the PR, I've merged it into master (1.3)

**Pull request closed without merging**
