### PR TITLE
HEAD request for heapdump endpoint without dumping

### PR DESCRIPTION
**Pull request by joshiste**
When doing a HEAD request to the heapdump endpoint (for testing availability) currently the heap gets dumped. With this commit the heap only gets dumped for GET requests.

- [X] I have signed the CLA

### CODE REVIEW

**Comment by bclozel** [comment]
According to the [HTTP RFC](https://tools.ietf.org/html/rfc7231#section-4.3.2):

>    The HEAD method is identical to GET except that the server MUST NOT
   send a message body in the response (i.e., the response terminates at
   the end of the header section).  The server SHOULD send the same
   header fields in response to a HEAD request as it would have sent if
   the request had been a GET

Currently, sending a HEAD request does the following:

```
➜  tmp curl -vvv -X HEAD localhost:8080/heapdump
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> HEAD /heapdump HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200
< X-Application-Context: application
< Content-Disposition: attachment; filename="heapdump2016-07-11-11-25-live8160655066236663150.hprof.gz"
< Content-Type: application/octet-stream
< Content-Length: 7562485
< Date: Mon, 11 Jul 2016 09:25:28 GMT
<
```

I think your PR is bypassing completely that mechanism (i.e. not dumping the heap at all, not writing response headers).

Even though the validity of that information is very short-lived (since the next call to that endpoint will yield different results), I believe this behavior is correct since it sets the `Content-Disposition` and `Content-Length` headers, which are both very useful to HEAD requests.

If anything, we could add `Cache-Control: no-store` to responses to make sure nothing is caching those dumps - but I think this PR should be denied since it breaks the HTTP contract.

**Comment by bclozel** [comment]
I'm closing this PR now, let me know if I've missed something.
Thanks for your contribution.

**Comment by joshiste** [comment]
In my opinion the benefit of being able to do a fast head request overweights the drawbacks of breaking the contract. (As you pointed out they are very small since the headers are short lived).

**Comment by joshiste** [comment]
And as the RFC says the same headers **should** be returned by the server. Imho it is allowed not to do so and this is a recommendation and not a requirement.

**Comment by wilkinsona** [comment]
@joshiste What's your use case for making a `HEAD` request? You said above that you want to test availability of the endpoint. You _could_ use `GET` for that. I'm guessing it's for Spring Boot Admin where you want to customise the UI depending on whether or not the endpoint's enabled?

**Comment by joshiste** [comment]
>  I'm guessing it's for Spring Boot Admin where you want to customise the UI depending on whether or not the endpoint's enabled?

Correct.

**Comment by wilkinsona** [comment]
You can use an `OPTIONS` request to determine the availability of a resource. For example:

```
$ curl -i -X OPTIONS http://localhost:8080/heapdump
HTTP/1.1 200
X-Application-Context: application
Allow: GET,HEAD
Content-Length: 0
Date: Wed, 13 Jul 2016 16:08:39 GMT
```

You'll get a 404 if the resource does not exist:

```
curl -i -X OPTIONS http://localhost:8080/whatever
HTTP/1.1 404
X-Application-Context: application
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 13 Jul 2016 16:09:54 GMT

{"timestamp":"2016-07-13T16:09:54.399+0000","status":404,"error":"Not Found","message":"No message available","path":"/whatever"}
```

**Comment by joshiste** [comment]
Seems resonable. The onyl problem I'm facing is that I access the endpoint via spring cloud zuul and currently the options request doesn't get forwarded, it's handled by the `ServletWrappingController` in front....

**Comment by wilkinsona** [comment]
Sounds like a (Spring Cloud) Zuul issue might be in order

**Comment by joshiste** [comment]
more a spring framework issue for let the AbstractController dispatch the OPTIONS request. I've already commented on a jira issue related to that.

**Pull request closed without merging**
