### PR TITLE
Added inlinedConfScript property #2797

### PR DESCRIPTION
**Pull request by JustinKSU**
Added inlinedConfScript which can reference a file path or a File
object.  This property can be used to add additional commands (e.g.
setting JAVA_OPTS) to the default launcher script.

Utilizes FileCopyUtils now.  Added missing JavaDoc.

Feature requested in #2797

### CODE REVIEW

**Comment by JustinKSU** [comment]
Need to fix the unit test.  inlinedConfScriptCanBeReplaced() can be removed because it's covered by inlinedConfScriptFileLoad

**Comment by JustinKSU** [comment]
Latest error is unrelated to changes in this pull request:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project spring-boot-autoconfigure: Compilation failure
[ERROR] /home/travis/build/spring-projects/spring-boot/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/AbstractRepositoryConfigurationSourceSupport.java:[67,24] constructor AnnotationRepositoryConfigurationSource in class org.springframework.data.repository.config.AnnotationRepositoryConfigurationSource cannot be applied to given types;

**Comment by wilkinsona** [comment]
@JustinKSU Yep, don't worry about that. It should have been fixed by https://github.com/spring-projects/spring-boot/commit/5a4ef50ef1d71f1a42edaee309b3e04fb754b13a.

**Comment by wilkinsona** [comment]
Thanks for the PR. I've merged the changes into master. I [polished things a little bit](https://github.com/spring-projects/spring-boot/commit/1e4e64aa8c8f5705d7f894af76e6f6698fec8a3b), most notably reverting the move to `FileCopyUtils`. While not necessarily a bad thing to do, I'd prefer to keep the changes focussed on adding the inlined conf script support.

**Pull request closed without merging**
