### PR TITLE
Add GitHub link for Azure Spring Boot Starters

### PR DESCRIPTION
**Pull request by ZhijunZhao**
@snicoll 

Also at @yungez @aovechki @selvasingh @Matthew-Dong for awareness.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ZhijunZhao Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9633)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9633) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by ZhijunZhao** [comment]
Now that signing the Contributor License Agreement is needed, let me fork the repo under Microsoft org. Close this PR and will send a new PR later.

**Comment by snicoll** [comment]
@pivotal-issuemaster this is a trivial change

**Comment by snicoll** [comment]
@ZhijunZhao no need to sign the CLA for such trivial change. Thanks for the PR, it has been merged.

**Pull request closed without merging**
