### PR TITLE
added ANSI color support for banners

### PR DESCRIPTION
**Pull request by sailorgeoffrey**

### CODE REVIEW

**Comment by philwebb** [comment]
I think this would still be a nice feature. Have you signed the CLA?

**Comment by sailorgeoffrey** [comment]
Yes, my CLA confirmation is *112420150316064025.*

**Comment by sailorgeoffrey** [comment]
it looks pretty though :)
sc

**Comment by spencergibb** [comment]
:+1:

**Comment by sailorgeoffrey** [comment]
I took a much better approach with this pull request:
https://github.com/spring-projects/spring-boot/pull/2704
closing this because it's a duplicate

**Pull request closed without merging**
