### PR TITLE
#12678: Add address setting for DLQ and ExpiryQueue for all managed destinations

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@graben Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=12680)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=12680) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@graben Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=12680)!

**Comment by snicoll** [comment]
@graben can you please add some tests?

**Comment by graben** [comment]
Tests added

**Pull request closed without merging**
