### PR TITLE
skip GrabCommandIntegrationTests if local Maven settings override the repository location

### PR DESCRIPTION
**Pull request by mbenson**

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. If possible, rather than skipping the tests, I'd prefer to fix the implementation to cope with a custom local repository location. I'm curious if you already tried that and hit a problem which led you to skipping the tests instead.

**Comment by wilkinsona** [comment]
I've investigated this some more and convinced myself that the implementation is lacking. We should fix it, rather than skipped the tests. See #3274.

**Comment by mbenson** [comment]
Actually, grab command does seem to work properly with a local Maven repository defined, but in this case the `grape.root` property is never even accessed. The tests depend on the `joda-time` dependency first being absent (`#deleteLocalRepository`), a "Downloading: file:" message showing up in the log, and the dependency later being present. That is the whole basis of the problem: the `localRepository` defined in one's `settings.xml` pre-empts the `grape.root` property and invalidates the assumptions made by the setup of the test  case. The defined repository location is used, and at least after the first time the test is run the `joda-time` dependency is already present, *and* no "Downloading" log message will be found because there will be no need to download anything.

**Comment by wilkinsona** [comment]
@mbenson Take a look at the changes I've made in 5e743fb. Among other things, you'll see that `grape.root` now takes priority over a custom local repository location. This means that `grab` will now copy files from that custom local repository to the desired output location and the `Downloading: file:` message is now logged as expected.

**Comment by mbenson** [comment]
Taking into account your fix for the tests on Windows, I am satisfied with your changes to spring-boot-cli/grape/localRepository. Thanks!

**Comment by mbenson** [comment]
I'm not sure what has changed since my last comment, but today I am not receiving any more test failures in the `master` branch. Thanks!

**Comment by wilkinsona** [comment]
@mbenson We see the same failures in CI from time to time and haven't been able to get to the bottom of them, although I'm almost certain that they're not directly related to the problem described by this issue. The current best guess is that the failure's down to a corrupted download. Clearing the local Maven cache, or running a new build that picks up a more recent Spring Framework snapshot seems to fix the problem.

**Pull request closed without merging**
