### PR TITLE
Note about spring-boot:run disabling automatic Maven expansion (Issue #980)

### PR DESCRIPTION
**Pull request by StevenGeens**
I ran into the problem described in #980.

I've updated the docs with the information mentioned in that issue.

PS: I am a Github newbie, so excuse any formatting/etiquette mistakes I am bound to make.

### CODE REVIEW

**Comment by snicoll** [comment]
I'd rather have that move to the [plugin documentation](http://docs.spring.io/spring-boot/docs/current/maven-plugin/)

**Comment by StevenGeens** [comment]
The plugin documentation is already very close to covering it in it's [usage](http://docs.spring.io/spring-boot/docs/1.2.1.RELEASE/maven-plugin/usage.html) section (heading "Running the application").

But I'd like at least some kind of hint here that the cause of the issue is related to the `spring-boot:run` target. If you're like me and use `spring-boot:run` exclusively to test, you'll have no idea that it's due to to your Maven target (and thus the plugin) and not some other potential pitfall. (I assumed it was not working at all until I found issue #980.)

Maybe I could remove the pom.xml code example and link to the documentation? (Although not being able to link directly to the usage heading is kind of annoying.)

**Comment by snicoll** [comment]
alright. Yes please remove the sample and redirect to the page. I can manage the heading problem. Just rebase and push force on your  branch to update this PR

(note: you shouldn't create PR from master but from a local branch)

**Comment by snicoll** [comment]
Also, please sign the CLA if you haven't done so (link in README)

**Comment by StevenGeens** [comment]
I've signed the CLA.

I've also removed code example and replaced by a link. I am not familiar with how the docs are build so I just copied the link from [howto.adoc](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/howto.adoc#create-an-executable-jar-with-maven). It's not built, so it might be incorrect, but I doubt it.

I als squashed it into a single commit, I assume this is the preferred from for such a small change.

**Comment by snicoll** [comment]
indeed, thanks!

**Comment by snicoll** [comment]
Merged with a few updates. Thanks!

**Comment by ricard0javier** [comment]
Excellent, I was looking for it today! just in time!

**Comment by snicoll** [comment]
Cheers. I did try to add some anchors but it didn't look good so I'll have to revisit that at some point.

**Pull request closed without merging**
