### PR TITLE
add protocol to MailProperties

### PR DESCRIPTION
**Pull request by josefhernandez**
add protocol to MailProperties.
The protocol is needed, for example, if you're using gmail that uses smtps

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks. Have you signed the CLA?

**Comment by josefhernandez** [comment]
Yes, for project spring cloud.
must i sign again for sprint boot ?
do you need the confirmation number ?

**Comment by snicoll** [comment]
Yes, Please. I don't need the number. Please drop a line when you've signed it. Thanks!

**Comment by josefhernandez** [comment]
Signed

**Comment by snicoll** [comment]
Merged, thanks! I've polished your PR in https://github.com/spring-projects/spring-boot/commit/7669e888cb763ecbdd25e4a794ce91f47be8200f (in particular, the indents in your PR were broken). 

Thanks!

**Pull request closed without merging**
