### PR TITLE
Only link to the two alternative formats from each format of the reference documentation

### PR DESCRIPTION
**Pull request by Buzzardo**
And some small editing changes.

### CODE REVIEW

**Comment by philwebb** [comment]
We should double check the condition works because I'm not sure if the new backend sets the same property name.

**Comment by wilkinsona** [comment]
@Buzzardo For future reference, we try to keep individual commits focussed on a single change. This PR's mixing improvements to the links to the other forms of the documentation with some general editing of the multi-page documentation's index. I'll split things up while merging this and have happened https://github.com/spring-projects/spring-boot/issues/27805 to track the editorial changes.

**Comment by wilkinsona** [comment]
> We should double check the condition works because I'm not sure if the new backend sets the same property name.

Good catch, Phil. As proposed, the changes remove the sentence beginning "This document is also available as …" from both the single-page documentation and from the PDF.

**Comment by wilkinsona** [comment]
Thanks, @Buzzardo. I've merged these changes into main.

For future reference, it'd be greatly appreciated if you could build your changes (`./gradlew spring-boot-project:spring-boot-docs:build` should do the trick) before submitting them and double-check that they're rendered as expected.

**Pull request closed without merging**
