### PR TITLE
Updates prefix match in BufferCounterService

### LINKED ISSUE #10145: BufferCounterService should check for the "counter." prefix like it is done in the DefaultCounterService
The `DefaultCounterService` has the code:
```
if (metricName.startsWith("counter.") || metricName.startsWith("meter.")) {
	return metricName;
}
```
Meanwhile `BufferCounterService`:
```
if (metricName.startsWith("counter") || metricName.startsWith("meter")) {
	return metricName;
}
```
That doesn't look consistent and breaks our project when we switch from Java 7 to Java 8. Just because we can't read `spring.metrics.counter.*` from the Redis properly any more.

See https://github.com/spring-cloud-stream-app-starters/counter/issues/3 for more info.

### PR DESCRIPTION
**Pull request by venilnoronha**
This PR updates the prefix match in `BufferCounterService`. Fixes #10145.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. Could you please consider also adding a test that verifies that the prefix is correct now?

**Comment by venilnoronha** [comment]
Seems like `BufferCounterService` was dropped by introducing `micrometer` metrics.

**Comment by wilkinsona** [comment]
Thanks

**Comment by wilkinsona** [comment]
Thanks again. I've merged the change and tests into 1.5.x. As you noted, the code in question has been replaced with Micrometer in master.

**Comment by venilnoronha** [comment]
I see. Thanks for merging!

**Pull request closed without merging**
