### PR TITLE
GitProperties, BuildProperties support unicode string.

### PR DESCRIPTION
**Pull request by hengyunabc**

### CODE REVIEW

**Comment by wilkinsona** [comment]
I'm not sure about this one as the default for a `.properties` file is ISO-8859-1 and there have been problems in the past when we've deviated from that default (see https://github.com/spring-projects/spring-boot/issues/5361, for example). There's also the fact that Java 9 will move for UTF-8 by default to consider. This will make this change redundant while also providing consistent use of UTF, avoiding the problem reported in #5361.

Considering the above, I think we should leave this as it is. Any characters that don't fit in ISO-8859-1 should be escaped.

**Comment by hengyunabc** [comment]
@wilkinsona 
Add a key like `spring.info.git.encoding=utf-8` to support unicode string?

A lots of applications will run under java8.

**Comment by wilkinsona** [comment]
That's an interesting suggestion, thanks. I'm quite tempted to support this as you've proposed. I'll re-open this and let's see what the rest of the team thinks.

**Comment by wilkinsona** [comment]
Oh, GitHub won't let me reopen it as "the master branch was force-pushed or recreated". That's a shame. Sorry for the hassle, but can you please open a new PR with your updated proposal?

**Pull request closed without merging**
