### PR TITLE
Auto-configuration for SendGrid's Java client

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
Pull for #2160. **SendGrid** gets auto-configured if:

- `com.sendgrid.SendGrid` is on classpath
- property: `sendgrid.username` is defined
- additionally auto-configures proxy when `sendgrid.proxy.host` and `sendgrid.proxy.port` is defined

**Documentation** - only *Appendix A. Common application properties* section has been updated with new properties.

**Unit tests** - testing proxy creation could be improved if I could set up some mock HTTP server (for example with [Jadler](https://github.com/jadler-mocking/jadler/wiki)) and see if there are requests coming in. At the moment there is a check if `SendGrid` bean is created but there is no really a way to check if it's created with proxy or not.

### CODE REVIEW

**Comment by philwebb** [comment]
Nice, we'll take a look at this when we switch master to 1.3.

**Comment by snicoll** [comment]
This may sound a bit repetitive but could we please avoid using root context unless we really have to? `spring.sendgrid` is a bit longer admittedly but it avoids taking yet another root namespace.

**Comment by philwebb** [comment]
+1 for the property name change

**Comment by wilkinsona** [comment]
Thanks for the PR. I've made one notable change: the properties are now `spring.sendgrid.*` rather than `sendgrid.*`

**Comment by maciejwalkowiak** [comment]
Cool, thanks!

**Comment by snicoll** [comment]
:+1:

**Comment by patrickbray** [comment]
This is great are there any plans to extend this to support SendGrid API keys as well?

**Comment by wilkinsona** [comment]
I don't believe so. Please open a new issue or, even better, a pull request if that's an enhancement that you would like to be made.

**Comment by patrickbray** [comment]
:+1: will do

**Pull request closed without merging**
