### PR TITLE
Finishes issue #3690 - offline actuator docs

### PR DESCRIPTION
**Pull request by jadekler**
Some notes:

- Asciidoctor gives a (reasonable-ish) way of replacing font-awesome, but not at all a good solution for google fonts (which is that you need to provide it manually). So google fonts live in `asciidoctor.css`. If I missed something in searching through documentation regarding this - please let me know and I'll be happy to amend
- Google fonts doesn't seem to give any way of downloading the files for a custom fontset (which [of course asciidoctor uses](https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400)). There are 71 fonts to download in google's css file. After 20 minutes of downloading I wrote [a script to do it instead](https://gist.github.com/jadekler/96f326ea0ff828e472c3) and dumped google's css into `asciidoctor.css`. Again, let me know if there's a better way to do this

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks. Have you signed the CLA?

**Comment by jadekler** [comment]
@philwebb Done!

**Comment by philwebb** [comment]
See #3690

**Comment by philwebb** [comment]
I think the suggested change will unfortunately add too much weight. Perhaps we can find a way to create a Asciidoctor style that doesn't rely on webfonts.

Another option might be to try and get these assets during the build rather than adding them directly to git.

**Comment by jadekler** [comment]
@philwebb Makes sense. I was also reluctant about the solution.

**Pull request closed without merging**
