### PR TITLE
PatternSyntaxException may be thrown when looking for an environment entry or metric with a name that looks a bit like a regular expression

### PR DESCRIPTION
**Pull request by DylianBEGO**
Sometimes, Spring detects a string as a regex because it contains regex parts. The problem is this string is not a regex and a PatternSyntaxException is raised when pattern try to compile it.

This modification checks if the regex compilation is possible, else we consider it is just a simple string.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Interesting. Thanks for the PR. Just to help us understand the nature of the problem, can you please share an example of an endpoint call you were making where the current behaviour is inadequate?

**Comment by DylianBEGO** [comment]
For example, `/admin/env/*`  throw a `PatternSyntaxException` with the current method, this path is considered to be a regex while not

**Comment by wilkinsona** [comment]
I get that something like `*` would break. I was more interested in a real-world use case for such a call. Do you have a `*` key in the environment?

**Comment by DylianBEGO** [comment]
No, i don't have a key like this. 

I think it's more robust to not throw an exception when someone makes a mistake. For example, if we put `*` by mistake instead of `.*` or `.something*` or even for any other invalid regex.

What do you think ?

**Comment by wilkinsona** [comment]
It's a little bit tricky. On the one hand, if you pass in something that was intended to be a regex but you mess up the syntax, a bad request response would be helpful. On the other hand, we don't want to prevent people from searching for keys that look a bit like a regular expression…

**Comment by jebeaudet** [comment]
While I agree with the helpfulness of the bad request response, I don't see how this is possible without breaking the api. If we had a specific query param for the regex, we could then be sure of the intentions of the user and return an error in the case of an invalid regex. But with the path param syntax serving as a filter on keys with a `contains()` and a regex, I don't see how we could know if the user meant the key named `foo*bar` of the equivalent regex.

IMO, this PR is the best we can do without breaking the api, we won't support my example but at least it won't throw expressions that look like a regex but are not. We could introduce a new query param for a regex on top of the existing behaviour I guess, although I'm not a fan of this solution as I think it's cumbersome when searching (having to put a query param instead of a path param).

**Comment by wilkinsona** [comment]
Thanks. In the course of some work on the Actuator for 2.0, it's become apparent that we really need to move to a query parameter for the pattern. Please see #9796 for more details on that. For 1.5.x, I agree that what you're proposing here is the best we can do.

**Comment by jebeaudet** [comment]
Glad to hear that! Any change to get it merged in the 1.4.x branch as well? We're not planning on updating to 1.5 in the near future and I'd like to see that fix :)

**Comment by wilkinsona** [comment]
No, sorry. As mentioned when it [was announced](https://spring.io/blog/2017/06/08/spring-boot-1-4-7-available-now) 1.4.7 was the last 1.4.x release.

**Comment by jebeaudet** [comment]
Oh, that's too bad... Thanks for answer, I've missed this detail.

**Comment by wilkinsona** [comment]
Thanks for the PR, @DylianBEGO. I've merged it into 1.5.x and master with [some minor polishing](https://github.com/spring-projects/spring-boot/commit/bbc34a676cb7e59b1898f3caa84a86a51b28a7cd).

**Pull request closed without merging**
