### PR TITLE
Avoid string concatenation inside StringBuilder append()

### PR DESCRIPTION
**Pull request by igor-suhorukov**

### CODE REVIEW

**Comment by snicoll** [comment]
@igor-suhorukov thanks but I am going to hold on this one (see https://github.com/spring-projects/spring-boot/pull/14254#issuecomment-417435441).

**Comment by dreis2211** [comment]
@snicoll If I may provide a test benchmark:

```
    @Benchmark
    public String testNew(TestState testState) {
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.append("This is a test (");
		stringBuilder.append(testState);
		stringBuilder.append(")");
		return stringBuilder.toString();
    }

    @Benchmark
    public String testOld(TestState testState) {
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.append("This is a test (" + testState + ")");
		return stringBuilder.toString();
    }
```
```
Benchmark             Mode  Cnt        Score       Error  Units
MyBenchmark.testNew  thrpt   10  3376165,616 ± 31221,896  ops/s
MyBenchmark.testOld  thrpt   10  2555779,678 ± 59353,058  ops/s
```

The comment in #14254 is about changing concatenations with + to a StringBuilder. Here we already have a StringBuilder available, so it should be quite natural to use it. In fact, IDEA is producing a warning about such places :
grafik

Cheers,
Christoph

**Comment by snicoll** [comment]
@dreis2211 thanks for the feedback. I know about the potential speed difference and I am using IntelliJ IDEA myself so I know about the warning as well. We've declined somewhat related changes in the past and I'd like to double check with the team before merging.

**Comment by snicoll** [comment]
We've had a look to this one during our last team call and decided to go for it. Thanks for the PR!

**Comment by wilkinsona** [comment]
> I wonder is there a reason why these kinds of changes were denied in the past

Yes. We've denied them in the past when, in our opinion, they make the code harder to read and when the changes are not in a performance-criticial code path.

**Pull request closed without merging**
