### PR TITLE
Add an option to log the banner instead of printing to std out

### PR DESCRIPTION
**Pull request by jrrickard**
Adds option to log banner message

This commit adds the option to output the banner using the logger 
instead of Standard Out. Default behavior will remain printing the
banner to standard out, but now Spring Boot users can specify a property
to emit the banner to the log:

```
spring.main.show_banner_in_log=true
```

This is accomplished by:

* Addition of a new boolean attribute to SpringBootApplication
* Addition of a new method on the Banner interface (and implementations)

Fixes gh-4001

### CODE REVIEW

**Comment by jrrickard** [comment]
I have previously signed the CLA.

**Comment by wilkinsona** [comment]
I wonder if people will be confused by the behaviour of this configuration:

```
spring.main.show-banner: false
spring.main.show-banner-in-log: true
```

The banner won't be shown in either location as `show-banner: false` switches it off completely. Perhaps an enum would be better with `OFF`, `CONSOLE`, and `LOG` as supported values?

I'm also not 100% sure about changing the `Banner` interface. It looks as if it would be possible to call the existing `printBanner` method with a `PrintStream` that writes to a `String`. That `String` could then be post-processed and logged.

What says you, @philwebb?

**Comment by jrrickard** [comment]
Good feedback, I agree with everything you said. Let me update my PR.

**Comment by philwebb** [comment]
+1 on not changing the `Banner` interface.

**Comment by wilkinsona** [comment]
Thanks for the updates, @jrrickard.

I just tried adding an overload of `setShowBanner` to continue supporting the use of a `boolean` to switch it on or off. It doesn't work and I think that's reasonable.

@philwebb We've made incompatible changes to some other properties in 1.3. Are you happy to add `spring.main.showBanner` to the list?

**Pull request closed without merging**
