### PR TITLE
Improve logging for HikariCheckpointRestoreLifecycle

### PR DESCRIPTION
**Pull request by deki**
Adressing #42906, open to change it to an exception instead of the warning message as it won't work as expected without `allow-pool-suspension=true`.

### CODE REVIEW

**Comment by sdeleuze** [comment]
Will the warning be also printed when doing a regular shutdown of the application?

**Comment by wilkinsona** [comment]
Yes, I believe so. If `org.crac.Resource` is on the classpath then `HikariCheckpointRestoreLifecycle` will be auto-configured. The log message will then be output irrespective of the type of shutdown that's being performed.

**Comment by christophstrobl** [comment]
Adding the shutdown time is a nice addition, though I think it should be formatted with a reasonable time unit. 
Not so sure about the warning log message for suspension. Thought the requirement for pool suspension had been documented/is easy to find.

**Comment by deki** [comment]
I don't see it in https://docs.spring.io/spring-boot/reference/packaging/checkpoint-restore.html, where could I have read about it?
I think as long as crac is on classpath, users will consider using checkpoints at some point and the warning message would point them in the right direction.

**Comment by christophstrobl** [comment]
the link in the docs seem to be broken.
> ... resources such as socket, files and thread pools [on a limited scope](https://github.com/spring-projects/spring-lifecycle-smoke-tests/blob/main/STATUS.adoc).

...so the [info](https://github.com/spring-projects/spring-lifecycle-smoke-tests/tree/main/data/data-jpa#jvm-checkpoint-restore) is not as easy to be found as I had assumed.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/issues/42938 should have fixed the link to the status page.

**Pull request closed without merging**
