### PR TITLE
Support '/' in endpoint names

### PR DESCRIPTION
**Pull request by Ivan97**
Update the `EndpointId` constraints to allow '/' in names.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Ivan97 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=14894)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=14894) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Ivan97 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=14894)!

**Comment by wilkinsona** [comment]
Thanks for the PR. Given the ID's use in the path of the endpoint and also in the prefix of its configuration properties, I'm quite reluctant to support `/`. Can you please explain why you need it?

**Comment by Ivan97** [comment]
Thanks for your reply.Here is the reason.In my project,I have this configuration `@Endpoint(id = "verticles/deploy")` to set endpoint url as `/actuator/verticles/deploy`.This configuration works just ok before the version 2.0.6.RELEASE.When I update to the latest version,something went wrong.I think the endpoint url contains '/' may be a common sense.Or maybe I’m using this annotation improperly?

**Comment by wilkinsona** [comment]
We never intended `/` to be used in an endpoint id and 2.0.6 has formalised the rules with the introduction of a new `EndpointId` class.

Mapping an endpoint to `/actuator/verticles/deploy` feels a little strange to me. I would expect that to be a `verticles` endpoint that then uses a `@Selector` on a read operation to handle `deploy` in the same way the Boot's `HealthEndpoint` allows you to [request the health of an individual component](https://github.com/spring-projects/spring-boot/blob/22e722d9f9f885d7fc67d51d16d68d55db6d6efc/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/HealthEndpoint.java#L60).

**Comment by wilkinsona** [comment]
If you really want your endpoint to be mapped to `verticles/deploy` you could use `verticles-deploy` as its ID and then customise its path mapping:

```
management.endpoints.web.path-mapping.verticles-deploy=verticles/deploy
```

**Comment by Ivan97** [comment]
Thank you for your patient.I think I understand what you mean.😃😃😃

**Comment by wilkinsona** [comment]
Great, I'll close this one then as it sounds like you have a way forward and we really don't want to allow `/` in the ID of an endpoint.

**Pull request closed without merging**
