### PR TITLE
Netty connection timeouts of 0 or -1 are not applied correctly

### PR DESCRIPTION
**Pull request by ayudovin**
Fix for #16497

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks once again @ayudovin !

**Comment by snicoll** [comment]
@ayudovin can you please remove the merge commit from the PR? (and not use merge commits in general). Rebasing your changes from master and push force the result on your existing branch (`fix-connection-timeout-netty`) is what I'd like to see. Thank you.

**Comment by ayudovin** [comment]
@snicoll, I tried to follow your suggestion. Can you check that it's alright?

**Comment by snicoll** [comment]
Perfect, thank you very much!

**Comment by ayudovin** [comment]
@snicoll, Do I need to rebase again my changes?
As I see, failed tests are not related to my changes

**Comment by philwebb** [comment]
@ayudovin There's no need for an additional rebase, we'll take care of that when merging.

**Comment by ayudovin** [comment]
@philwebb Do you have updates about this pull request?

**Comment by snicoll** [comment]
@ayudovin the PR is triage with an assigned milestone. All that's left is a review and merge. We have a lot of things going on at the moment so we'll get to it as soon as we can.

**Comment by philwebb** [comment]
Thanks for the fix @ayudovin, and for discovering and fixing the bug in `PropertyMapper`!

**Pull request closed without merging**
