### PR TITLE
Remove possible null pointer dereference of beanFactory

### PR DESCRIPTION
**Pull request by mnhock**
There is a possible null pointer dereference of beanFactory in the line `BeanExpressionResolver resolver = beanFactory.getBeanExpressionResolver();`

### CODE REVIEW

**Comment by wilkinsona** [comment]
I'm not sure that this should have been merged. As I understand it, the contract of `ConfigurableApplicationContext.getBeanFactory()` is that it will never return `null`. If it breaks that contract, I'd rather that it fails fast with a `NullPointerException` than limps on with unexpected behaviour.

**Comment by mnhock** [comment]
So the null check below the line would be unnecessary as well?

`BeanExpressionContext expressionContext = (beanFactory != null)		 		BeanExpressionContext expressionContext = (beanFactory != null)
 				? new BeanExpressionContext(beanFactory, null) : null;`

**Comment by wilkinsona** [comment]
IMO, yes (assuming that my understanding of the contract for `getBeanFactory` is correct).

**Comment by wilkinsona** [comment]
That said, at least things are consistent now which is a definite improvement.

**Comment by mnhock** [comment]
From the javadoc it can be null.

```java
/**
 * Return the {@link ConfigurableListableBeanFactory} that will hold the bean
 * definition should the condition match or {@code null} if the bean factory
 * is not available.
 * @return the bean factory or {@code null}
 */
```

**Comment by snicoll** [comment]
I was about to say that.

**Comment by wilkinsona** [comment]
Oops, sorry. I was referring to the contract for `ConfigurableApplicationContext.getBeanFactory()`, not `ConditionContext.getBeanFactory()`. Please ignore me :)

**Comment by mnhock** [comment]
Thanks for the great discussion!

**Pull request closed without merging**
