### PR TITLE
Read application.properties using ISO 8859-1

### PR DESCRIPTION
**Pull request by thiagohirata**
Fixes gh-10564

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@thiagohirata Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=10565)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=10565) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@thiagohirata Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=10565)!

**Comment by philwebb** [comment]
Thanks!

**Comment by Bai-Jie** [comment]
Note that the default charset of properties file in JDK 9 is UTF-8.

see
- JDK 9 Release Notes: http://www.oracle.com/technetwork/java/javase/9-new-features-3745613.html#JDK-8027607
- JEP 226: http://openjdk.java.net/jeps/226

**Comment by philwebb** [comment]
@Bai-Jie Thanks for the info. It looks to me like that change may be limited to `ResourceBundle` handling or properties files. I think `Properties.load` [still uses ISO 8859-1](http://download.java.net/java/jdk9/docs/api/java/util/Properties.html#load-java.io.InputStream-).

**Comment by Bai-Jie** [comment]
@philwebb Yes, you are right. Sorry for my misunderstanding.

**Comment by philwebb** [comment]
@thiagohirata Thanks for the contribution! This has now been merged into master (with a few minor formatting changes)

**Pull request closed without merging**
