### PR TITLE
Consider inverting equals, equalsIgnoreCase to avoid potential NPE

### PR DESCRIPTION
**Pull request by mnhock**

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR.

Some of these look like good changes to make, but others appear to be harmless but unnecessary. For example `File.getName` and `Method.getName` will never return `null`. I also spotted at least one case where the proceeding line makes it impossible that a value will be `null`.

I think it's probably best if we (the Spring Boot team) discuss this issue and decide how many of the changes we want to make.

**Comment by mnhock** [comment]
Thanks for considering to make some of this changes! Your are right some of this changes are unnecessary, because in practice there can not be a NPE.

**Comment by philwebb** [comment]
After some careful consideration we're not sure that we want to switch current checks to use this style. Although switching the order does protect against NPEs we feel that it doesn't really help with the readability of the code. It's also going to introduce a lot of changes will make `git --blame` and merge conflicts harder to handler.

Thanks anyway for the pull-request.

**Comment by mnhock** [comment]
Thanks for the time you investigated in this PR!

**Pull request closed without merging**
