### PR TITLE
Add autoconfiguration for kohsuke:github-api

### PR DESCRIPTION
**Pull request by Shredder121**
I figured I'd start on this myself, but don't know whether I'm going in the right direction or not.

### CODE REVIEW

**Comment by Shredder121** [comment]
So, need someone familiar with autoconfiguration to chip in.

Let me know what you think as well.

**Comment by wilkinsona** [comment]
Thanks for the PR. This auto-configuration doesn't feel like a natural fit for inclusion in Spring Boot. IMO, it would be better as a third-party starter. We could then add it to the [list of such starters](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters#community-contributions)

**Comment by snicoll** [comment]
+1, please review [the documentation as well](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-developing-auto-configuration) (in particular the [naming convention](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming))

**Comment by Shredder121** [comment]
@wilkinsona @snicoll Thanks for your views, much appreciated.
Good that I brought this up, before it was fully done.
I'll see if I can continue that path.
Shall I close this, or do any of you want to punch the button?

**Comment by wilkinsona** [comment]
@Shredder121 Thanks. I've closed this PR. Please do open another as and when your third-party starter is available so that it gets added to the list.

**Pull request closed without merging**
