### PR TITLE
Add support for AstraDB

### PR DESCRIPTION
**Pull request by michaelsembwever**
autoconfigure properties for a CassandraVectorStore cql connection to AstraDB

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the proposal. Please note that as this would be a new feature it cannot be added to a 3.2.x maintenance release. The earliest that it could be added would now be Spring Boot 3.4 as we've just started the RC phase for 3.3 and the feature set is frozen.

If we want a configuration property for the cloud secure connect bundle then, rather than introducing new `spring.astra.*` properties for it, I think it would be better for it to sit alongside existing properties that are applied to the `CqlSessionBuilder` that we already auto-configure. For example, `spring.cassandra.keyspace-name` is applied to the `CqlSessionBuilder` using `withKeyspace`. Similarly, a new `spring.cassandra.cloud-secure-connect-bundle` property could be applied to the `CqlSessionBuilder` using `withCloudSecureConnectBundle`.

**Comment by michaelsembwever** [comment]
> Thanks for the proposal. Please note that as this would be a new feature it cannot be added to a 3.2.x maintenance release. The earliest that it could be added would now be Spring Boot 3.4 as we've just started the RC phase for 3.3 and the feature set is frozen.

This is your decision, but it's a trivial addition… 🤷 

> If we want a configuration property for the cloud secure connect bundle then, rather than introducing new spring.astra.* properties for it, I think it would be better for it to sit alongside existing properties that are applied to the CqlSessionBuilder that we already auto-configure. For example, spring.cassandra.keyspace-name is applied to the CqlSessionBuilder using withKeyspace. Similarly, a new spring.cassandra.cloud-secure-connect-bundle property could be applied to the CqlSessionBuilder using withCloudSecureConnectBundle.

It can't be part of the existing Cassandra connections.  This only works with AstraDB.  AstraDB is CQL compatible with Cassandra, but not vice versa.

I've no objection to putting the classes into the `org.springframework.boot.autoconfigure.cassandra` package.
But a property `spring.cassandra.cloud-secure-connect-bundle` definitely implies the wrong thing.
What about ` spring.cassandra.astra.cloud-secure-connect-bundle` instead ?

**Comment by wilkinsona** [comment]
> I've no objection to putting the classes into the `org.springframework.boot.autoconfigure.cassandra` package.
But a property `spring.cassandra.cloud-secure-connect-bundle` definitely implies the wrong thing.

Generally speaking, when naming and structuring properties, we try to take our lead from the names and structure of the API that the properties are configuring. In this case the Astra-specific `withCloudSecureConnectBundle` method's on `SessionBuilder` alongside several other general Cassandra methods. Why does the API of `SessionBuilder` not also imply the wrong thing? If there were several Astra properties, grouping them together beneath `spring.cassandra.astra` would be quite compelling. With only one, deviating from the structure of the API we're using is less appealing.

**Comment by wilkinsona** [comment]
> Putting it alongside the other cassandra options would be very confusing (and likely create errors) for cassandra users.

Then why has the API of `SessionBuilder`/`CqlSessionBuilder` been modelled as it has? Is it not very confusing for the general purpose `CqlSessionBuilder` API to contain a method that's Astra specific? If not, what is it about Spring Boot that would make a similarly structured property name confusing?

What I'm trying to understand is why the structure of our properties should different from the structure of the API in the Cassandra Driver's Java API.

**Comment by michaelsembwever** [comment]
The secureConnectBundle works as part of existing cql connections and drivers. 

This information does go into the `CqlSessionBuilder`, but it breaks a vanilla cql connection.

> What I'm trying to understand is why the structure of our properties should different from the structure of the API in the Cassandra Driver's Java API.

The java-driver was only recently donated to the ASF.  When it was at DataStax then proprietary features like this could be put directly into it.  Now it's at the ASF these features will be removed over time – and then you'll see a `AstraCqlSessionBuilder` (i'd envision this would eventuate as most of the `org.springframework.boot.autoconfigure.cassandra` package being copied to `org.springframework.boot.autoconfigure.astra` – and that explains my original preference to that latter package :) )

**Comment by philwebb** [comment]
> Now it's at the ASF these features will be removed over time – and then you'll see a AstraCqlSessionBuilder.

Given this fact, I think we should hold off on adding direct support to Spring Boot at this time. It looks like the existing `org.springframework.boot.autoconfigure.cassandra.CqlSessionBuilderCustomizer` should suffice for now.

I think we should consider adding support when the `AstraCqlSessionBuilder` has been added.

Thanks anyway for the PR @michaelsembwever

**Comment by michaelsembwever** [comment]
>  I think we should hold off on adding direct support to Spring Boot at this time.

That could be years away.

Take a look at this PR in action here:  https://github.com/datastax/ai-agent-java

With the application.properties it is very easy to switch from using Apache Cassandra to using AstraDB, just by adding a few properties.

https://github.com/datastax/ai-agent-java/blob/workshop-step-1/src/main/resources/application.properties 

This layout of property name spaces makes sense to me.

**Comment by philwebb** [comment]
Thanks for the additional info @michaelsembwever.  We discussed this again but still feel like it's a little early to consider adding support directly in Spring Boot. It looks like most folks should be able to use the `CqlSessionBuilderCustomizer` with a relatively small amount of code to get AstraDB working.

We'd like to wait a while to see how things play out and how much demand there is.

**Comment by michaelsembwever** [comment]
FTR, the aligned the suggested patch as closely to the feedback provided and to my understanding of how you would want it here: 
https://github.com/spring-projects/spring-boot/compare/main...michaelsembwever:spring-boot:mck/astradb-autoconfigure-0 

That puts it under the same package as cassandra, i.e. `org.springframework.boot.autoconfigure.cassandra`
 and puts the property under `spring.cassandra.astra` so that it's aligned and a subset of `spring.cassandra`.


>  It looks like most folks should be able to use the CqlSessionBuilderCustomizer with a relatively small amount of code to get AstraDB working.

From our experience spring-boot users have absolutely no idea where to start.  Spring boot autoconfigure and the existing cassandra classes in it are not in the slightest intuitive.  I'd be surprised if you're not getting the feedback from this demographic of users…

**Pull request closed without merging**
