### PR TITLE
[#3711] Update UserInfoTokenServices.java

### PR DESCRIPTION
**Pull request by tgsoverly**
Brought over the code that was proposed there by @ncastilho

### CODE REVIEW

**Comment by tgsoverly** [comment]
Corresponds to https://github.com/spring-projects/spring-boot/issues/3711

**Comment by tgsoverly** [comment]
This code certainly needs tests if anyone could give me a quick "where to stick it" I would be happy to write it if you think this is desired functionality.  I wont bother if you don't want this.

**Comment by dsyer** [comment]
The only problem with this is that it makes quite specific assumptions about the form of the data coming from the user info endpoint. If there is no such field as "authorities" for instance, or if it is not a list of maps, then the whole thing will blow up.

If you re-write it to be more robust, unit tests would certainly be appropriate. It should be obvious where to put them.

**Comment by tgsoverly** [comment]
I agree with the statements.  I just didn't want to spend time adding it properly if the whole concept was not acceptable.

**Pull request closed without merging**
