### PR TITLE
Migrate spring-boot-sample-web-ui to Bootstrap v4

### PR DESCRIPTION
**Pull request by krudolph**
Migrates the Thymeleaf example to the current Bootstrap version. 
Although the v4.0.0-beta version is not final, it is not EOL like the currently used v2.0.4.

The jQuery dependencies were never used and are now removed.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@krudolph Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=10653)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=10653) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@krudolph Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=10653)!

**Comment by wilkinsona** [comment]
Thanks for the PR. Do you know when Bootstrap 4.0 is expected to go final?

**Comment by krudolph** [comment]
No, I don't think that there is a release date yet. It looks like there will be several beta Versions (https://github.com/twbs/bootstrap/projects).

**Comment by wilkinsona** [comment]
Thanks. In that case I think we'd better wait a while. I'm not keen on the idea of us shipping a release of Spring Boot that depends on a Bootstrap beta, even if that's only in a sample.

**Comment by slachiewicz** [comment]
So today Bootstrap 4 was relased https://blog.getbootstrap.com/2018/01/18/bootstrap-4/

**Comment by wilkinsona** [comment]
Thanks, @slachiewicz. @krudolph Would you like to update your PR accordingly?

**Comment by krudolph** [comment]
I have updated the Bootstrap version.

**Comment by wilkinsona** [comment]
Thanks very much. I've merged this into master.

**Pull request closed without merging**
