### PR TITLE
Add Neo4J auto-configuration

### PR DESCRIPTION
**Pull request by jexp**
Added Spring Boot auto-configuration for Spring Data Neo4j

There is a

* `Neo4jProperties` (spring.data.neo4j.{host,port,url,protocol,username,password})
* `Neo4jDataAutoConfiguration`,
* `Neo4jRepositoryAutoConfiguration`
* `Neo4jStarter`

And `spring-boot-samples-data-neo4j`

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks Michael! Have you already signed a copy of the Spring CLA?

**Comment by jexp** [comment]
Ya numerous times ;)
I'm spring data neo4j project lead

**Comment by philwebb** [comment]
I felt a bit stupid asking, but I gotta cover my ass :)

**Comment by jexp** [comment]
Which is perfectly fine :) Thanks for asking.

**Comment by jexp** [comment]
Sdn 4.0.0.release is out I update the dependency when I'm back at a computer

**Comment by jexp** [comment]
Updated PR to SDN 4.0.0.RELEASE

**Comment by jexp** [comment]
ping @philwebb ?

**Comment by philwebb** [comment]
Thanks! Will hopefully get to this after SpringOne.

**Comment by jexp** [comment]
ping @philwebb  :)

**Comment by philwebb** [comment]
@jexp SpringOne has literally just ended!!! As soon as the alcohol leaves my system I'll get on it :)

**Comment by jexp** [comment]
Sorry ;) i saw Josh already in LA again. But he's no measure

**Comment by philwebb** [comment]
I drink way less coffee than him and I try not to work at weekends.

**Comment by philwebb** [comment]
@jexp Is there any way to start an embedded server so that we can integration test the sample? I've found some documentation in the Neo4J user guide but it seems at odds with the `org.neo4j.ogm.session.Session` interface used by `spring-data-neo4j`.

I've also found the `CommunityNeoServer` class but it's deprecated with the following message:

> This class is for internal use only and will be moved to an internal package in a future release.
> Please use Neo4j Server and plugins or un-managed extensions for bespoke solutions.

Do you know what that means?

**Comment by philwebb** [comment]
I've updated the pull request a little and tried to simplify things where possible. There are still quite a few things to sort out before we can merge, namely:

- There are `FIXME` items in the code and several `@Ignored` tests
- The Neo4J `ConversionService` causes problems when named `conversionService` as it prevents the configuration properties from being autowired. I've renamed the bean for now but I don't understand what it does or why we need it.
- The sample tests will fail if Neo4J server isn't running and I've found no sensible way to start and embeded version.

Changes from the original PR are:
- I've dropped the method that created the properties object from an `Environment`. The `ConversionService` was the root cause of injection not working.
- There are less properties now. No `host`/`port`, just use the `url`.
- There is no support for `local.neo4j.port`. Since we don't have an embedded story it makes little sense to support it.
- Formatting and author tags etc.

**Comment by philwebb** [comment]
I need to move on to some of the more pressing bugs so this might need to take a back seat for a while. I'm still hoping that we can get it in to 1.3.

**Comment by jexp** [comment]
Hi @philwebb sorry for the radio silence, just a crazy week. 

I hope that @vince-bickers can take over from me as he knows more about the bells and whistles involved in some of these things.

For the in-memory testing server - it exists, but I was not sure where to put the dependencies in spring-boot, as it depends on a number of things from the neo4j/ogm/sdn4 testing packages. So I would have to have a place where to add those dependencies with scope `test`.

**Comment by jexp** [comment]
@philwebb where can I find your updates?

Some of the tests that I `@Ignored`, I just didn't know how they were intended to be used.

**Comment by philwebb** [comment]
@jexp Sorry, I forgot to add the link. My updates are https://github.com/philwebb/spring-boot/tree/gh-3899

**Comment by vince-bickers** [comment]
@philwebb What do you need from me to get this working? I've just picked this up from @jexp, glad to help in any way.

Michael said that one thing you need are the dependencies for using the inProcess test-harness. This is what the SDN documentation defines:

        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-neo4j</artifactId>
            <version>${sdn.version}</version>
            <type>test-jar</type>
        </dependency>

        <dependency>
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j-kernel</artifactId>
            <version>${neo4j.version}</version>
            <type>test-jar</type>
        </dependency>

        <dependency>
            <groupId>org.neo4j.app</groupId>
            <artifactId>neo4j-server</artifactId>
            <version>${neo4j.version}</version>
            <type>test-jar</type>
        </dependency>

       <dependency>
          <groupId>org.neo4j</groupId>
          <artifactId>neo4j-ogm</artifactId>
          <version>${neo4j-ogm.version}</version>
          <type>test-jar</type>
          <scope>test</scope>
      </dependency>

      <dependency>
          <groupId>org.neo4j.test</groupId>
          <artifactId>neo4j-harness</artifactId>
          <version>${neo4j.version}</version>
          <scope>test</scope>
      </dependency> 

 Let me know if this is what you're after, or if you need anything else.

**Comment by philwebb** [comment]
>  Michael said that one thing you need are the dependencies for using the inProcess test-harness. This is what the SDN documentation defines...

@vince-bickers Do you have any more documentation or sample code that shows how to actually start a temporary Neo4J instance so that we can run integration tests against it? Ideally I want to just spin up Neo4J on a random port then test that our basic configuration works.

**Comment by jexp** [comment]
Hey @philwebb I just spoke with @snicoll

He said that there might be an issue when our testing dependencies (which use embedded neo4j) is GPL licensed.

Otherwise I'd add it to spring-boot-parent's additional dependencies.

**Comment by wilkinsona** [comment]
Moving to 1.4.0. Unfortunately it's a bit late to be tackling this in 1.3.0.

**Comment by snicoll** [comment]
@jexp I understand that the licensing issue has been fixed recently. Is there a way to update this PR with those changes and rebase from master?

**Comment by jexp** [comment]
@snicoll yes we're working on it. We were just waiting for SDN 4.1.RC1 as part of the Hopper release train.

@vince-bickers has a working branch/PR here: https://github.com/spring-projects/spring-boot/pull/5458

Please have a look and let us know what you think.

Todos for after Spring-Data-Hopper goes GA:

* [ ] Remove Neo4j M2 repository declaration
* [ ] Remove explicit neo4j-lucene dependency

**Comment by snicoll** [comment]
@jexp Hopper RC1 has been released and we're using it. Isn't that enough to submit an updated PR? Please push force on this branch if you can to keep the history.

**Comment by snicoll** [comment]
> Please push force on this branch if you can to keep the history.

Ah, too late :(

**Comment by snicoll** [comment]
Duplicates #5458

**Pull request closed without merging**
