### PR TITLE
Reuse ObjectMappers in JacksonJsonParser & ConfigurationPropertiesReportEndpoint

### PR DESCRIPTION
**Pull request by dpaq**
Since ObjectMappers are expensive allow them to be reused

### CODE REVIEW

**Comment by dpaq** [comment]
Removed the modifications to MBean endpoints that was already completed and re-targetted to master

**Comment by wilkinsona** [comment]
Thanks for the updated PR.

Can you please explain the rationale for the `ObjectMapperProvider` abstraction? In `ConfigurationPropertiesReportEndpoint` would it not be sufficient to inject the auto-configured `Jackson2ObjectMapperBuilder` and then use it to create the `ObjectMapper` that's then customised? This would allow the user's `spring.jackson.*` configuration to be reused with the necessary customisations on top.

You've updated `JacksonJsonParser` to allow more control over its `ObjectMapper`, but you haven't made a corresponding change to `JsonParserFactory` which is, I believe, the only class that instantiates a `JacksonJsonParser` at the moment.

**Comment by dpaq** [comment]
Somehow it all made sense a few weeks ago when I wrote it; but I don't disagree with your comments now. That's what I get for coding on vacation instead of relaxing!

What do you think about eliminating the JsonParserFactory entirely? It only seems to be used by the BeansEndpoint and VcapApplicationListener. The BeansEndpoint could use the auto-configured Jackson2ObjectMapperBuilder (just like how you suggest for the ConfigurationPropertiesReportEndpoint). Not sure I can inject it into the VcapApplicationListener or not; but if not it feels like ObjectMapper is already everywhere in the code would it really be a big deal to just use it directly and eliminate a static factory method.

**Comment by wilkinsona** [comment]
I don't think we can get rid of `JsonParserFactory` as it prevents its users from being tied to a particular JSON parser implementation.

We don't want to inject dependencies into `VcapApplicationListener` so it'll have to continue creating its own parser instance one way or the other.

`BeansEndpoint` is a little more interesting as it is a bean. Ideally, it'd be able to use a shared `ObjectMapper` or `Gson` instance, or fallback to the other options that `JsonParserFactory` supports. That's potentially quite a big change, though.

**Comment by dpaq** [comment]
Seems like there is a lot of options here beyond the original request (such as the other feature request to do pretty printing); let's just reject this and start over.

Is there something I'm doing that's causing the build to fail? I'm doing a full clean build with tests before submitting.

**Comment by wilkinsona** [comment]
> Is there something I'm doing that's causing the build to fail? I'm doing a full clean build with tests before submitting.

Hard to tell without know what the failure is. I build using `mvn install` using Maven 3.2.3 and Java 8.

**Comment by dpaq** [comment]
Sorry I meant the Travis CI build; mvn install locally finishes successfully with Maven 3.3.1 and Java 8 prefectly.

It's fine though - we'll cross that bridge when it matters. Doesn't matter now. Thanks - have a good day.

**Pull request closed without merging**
