### PR TITLE
Auto-configure Flyway with any JavaMigration beans

### LINKED ISSUE #15446: Transparently integrate Flyway 6.0's support JavaMigration instances created by DI frameworks
Starting with Flyway 6.0 (due out in Q1 2019), Spring users can use this to automatically use all `JavaMigration` Spring beans with Flyway:

```java
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.migration.JavaMigration;
import org.springframework.context.ApplicationContext;

...
ApplicationContext applicationContext = ...; // obtain a reference to Spring's ApplicationContext.

Flyway flyway = Flyway.configure()
    .dataSource(url, user, password)
    // Add all Spring-instantiated JavaMigration beans
    .javaMigrations(applicationContext.getBeansOfType(JavaMigration.class).values().toArray(new JavaMigration[0]))
    .load();
flyway.migrate();
```

Spring Boot is most certainly able to make this fully transparent for its users.

References:
- https://github.com/flyway/flyway/issues/1062#issuecomment-446279678
- https://twitter.com/snicoll/status/1072755676923998208

### PR DESCRIPTION
**Pull request by SammyVimes**
This pull request fixes #15446. Added java migration autoconfiguration.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@SammyVimes Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=17993)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=17993) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@SammyVimes Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=17993)!

**Comment by wilkinsona** [comment]
Thanks very much for the pull request, @SammyVimes. Would you mind splitting it into two, one for each commit? I'd like the closed issues and pull requests to shows the upgrade to Flyway 6 and the addition of support for auto-configuring Java migrations as two separate things.

**Comment by SammyVimes** [comment]
Of course, I'll do it right away

**Comment by SammyVimes** [comment]
Created new pull request (with flyway 6 only) https://github.com/spring-projects/spring-boot/pull/17997.

**Comment by SammyVimes** [comment]
I fixed tests related to flyway, but It looks like some tests are unstable in master, so the build is not passing :(

**Comment by philwebb** [comment]
@SammyVimes Sorry about that, our CI box ran out of diskspace.

**Comment by wilkinsona** [comment]
Thanks again, @SammyVimes.

**Comment by happygrizzly** [comment]
How do I get these changes into my project? I'm using 2.1.7 RELEASE version.

**Comment by wilkinsona** [comment]
You'll have to upgrade to 2.2. The changes are in 2.2.0 snapshots and will be in 2.2.0.M6 which is scheduled for early next month.

**Comment by happygrizzly** [comment]
> You'll have to upgrade to 2.2. The changes are in 2.2.0 snapshots and will be in 2.2.0.M6 which is scheduled for early next month.

Does this mean I'll have to wait for M6 to be done?

**Comment by happygrizzly** [comment]
Well, I think I can temporarily downgrade the flyway dependency. Thank you!

> You'll have to upgrade to 2.2. The changes are in 2.2.0 snapshots and will be in 2.2.0.M6 which is scheduled for early next month.

Well, I think I can temporarily downgrade the flyway dependency. Thank you!

**Pull request closed without merging**
