### PR TITLE
conversionService used for Actuator endpoints should be configurable

### PR DESCRIPTION
**Pull request by ayudovin**
I'm not sure that I absolutely understand goal of this [enhancement](https://github.com/spring-projects/spring-boot/issues/11013), but maybe such solution will be satisfactory.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR, @ayudovin. Judging by [this comment](
https://github.com/spring-projects/spring-boot/issues/11013#issuecomment-344173992), I'm not sure this is quite what @snicoll had in mind. He's only holiday at the moment so we'll have to wait a week or so to get his input.

**Comment by snicoll** [comment]
Thanks for the PR. Andy is right, that's not really what I have in mind. I remember that looking for `Converter` beans in the context would have been an effective way to make sure this works properly but it's been a while and maybe I am wrong. Perhaps you could start with a test that fails the use case described in the related issue and try to associate converters from the context? I'd rather do this in a generic manner rather than focusing on a particular converter.

**Comment by ayudovin** [comment]
@snicoll, i'm not sure I understand how i can help you. Do you what I begin to work on fails tests in this pull request ?

**Comment by ayudovin** [comment]
@snicoll, ok, i just close this pull request on current moment if you don't mind

**Pull request closed without merging**
