### PR TITLE
Use `bytes.length` instead of `encoded.length` in Base64Encoder

### PR DESCRIPTION
**Pull request by izeye**

### CODE REVIEW

**Comment by philwebb** [comment]
Any specific reason for this change?

**Comment by izeye** [comment]
@philwebb I thought `bytes.length` is more appropriate for the place. Am I missing something?

**Comment by philwebb** [comment]
Oh yeah, I must have been half asleep when I wrote that :)  I've also port this to the copy in devtools.

**Comment by izeye** [comment]
@philwebb :) BTW, is there any specific reason for using its own Base64 encoder, not using `java.util.Base64.Encoder`?

**Comment by philwebb** [comment]
@izeye Java 6 compatibility

**Comment by izeye** [comment]
@philwebb Oh, sorry. I didn't see the `since` part. Thanks for the answer :)

**Pull request closed without merging**
