### PR TITLE
Update server.context properties

### PR DESCRIPTION
**Pull request by afaulconbridge**
The documentation is out of date for `server.context-path` and `server.context-parameters.*`  and should be updated to `server.servlet.context-path` and `server.servlet.context-parameters.*` respectively.

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks for the PR. There are a bunch of keys that have been relocated for the WebFlux support and we are still reviewing them. That's why the documentation hasn't been updated yet.

**Comment by pivotal-issuemaster** [comment]
@afaulconbridge Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8527)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8527) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@afaulconbridge Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8527)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8527) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@afaulconbridge Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8527)!

**Comment by snicoll** [comment]
Thanks for the PR, this was fixed as part of https://github.com/spring-projects/spring-boot/commit/eeed3a841cbe2de0b37ae118ea4fae55f5ca5598

**Pull request closed without merging**
