### PR TITLE
Redis Metrics Exporter needs afterPropertiesSet()

### PR DESCRIPTION
**Pull request by jmkgreen**
On my system I get an NPE without this change.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jmkgreen Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7195)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7195) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jmkgreen Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7195)!

**Comment by wilkinsona** [comment]
As far as I can see, there's no `afterPropertiesSet` method on `RedisMetricRepository`. As a result, your suggested change doesn't compile. Have I misunderstood?

**Comment by jmkgreen** [comment]
Whoops, coded the fix my side immediately after the bit taken from the documentation - which has nothing to do with the fragment in the documentation at all.  Disregard!

**Pull request closed without merging**
