### PR TITLE
Add new ssl properties in RabbitAutoConfiguration

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by eddumelendez** [comment]
Looks like `com.rabbitmq:http-client` is not in the maven central but it is at https://repo.spring.io/libs-release/com/rabbitmq/http-client/1.0.0.RELEASE/. Sync is pending.

**Comment by wilkinsona** [comment]
@eddumelendez What's the relationship between `com.rabbitmq:http-client` and this PR?

**Comment by wilkinsona** [comment]
@artembilan @garyrussell We can't upgrade Boot to Spring AMQP RC1 until `com.rabbitmq:http-client` is published to Maven Central. Do you know if there are any plans to do so?

**Comment by snicoll** [comment]
Thanks @eddumelendez but I didn't want to implement the `propertiesLocation` thing. The point of the way we configure SSL support in Spring Boot is to avoid several ways of doing the same thing (as the 4 properties can always be located in a `secret` profile.

**Pull request closed without merging**
