### PR TITLE
Fix readme at neo4j sample project

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by snicoll** [comment]
thanks @eddumelendez but I'd like to first understand why that's necessary. This wasn't the case when the sample was built and I don't want to hardcode the neo4j version for that artifact unless I really have to.

**Comment by mangrish** [comment]
@eddumelendez @snicoll: The embedded driver is now no longer shipped automatically with the OGM and hence SDN. It is up to the end user to specify the dependency and version of neo4j (as per OGM and SDN docs). You could go either way here but if you want to lean more towards "it just works" then you would need to add the dependency.

**Comment by snicoll** [comment]
@mangrish thanks for the quick reply. Do you have a link in your doc that explains that

Team, I am leaning towards removing any reference to the embedded driver in our sample and replace that with that link.

**Comment by mangrish** [comment]
@snicoll There is an info box a little further down from each link:

OGM: http://neo4j.com/docs/ogm-manual/current/reference/#reference:configuration:driver:embedded

SDN: http://docs.spring.io/spring-data/neo4j/docs/4.2.x/reference/html/#reference.getting_started.driver

**Comment by eddumelendez** [comment]
Thanks @mangrish to provide this information!

**Comment by philwebb** [comment]
> Team, I am leaning towards removing any reference to the embedded driver in our sample and replace that with that link.

I wonder if we should add `org.neo4j:neo4j` as a managed dependency?

**Comment by snicoll** [comment]
There's really no reason for us to do that. It's a different version and we'll have to manage the mapping for the sole purpose of that example. Not worth it at all IMO.

**Comment by eddumelendez** [comment]
@mangrish I was looking at `spring-data-neo4j` repository and seems that adding the following dependency the example will work. Do you think this would be fine or the original PR is the right approach to handle the neo4j version's server.

```
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm-test</artifactId>
    <version>${neo4j-ogm.version}</version>
    <scope>test</scope>
    <exclusions>
        <exclusion>
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j-security-enterprise</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Pull request closed without merging**
