### PR TITLE
#7711 - Make testRestTemplate bean name unique enough as to not cause…

### PR DESCRIPTION
**Pull request by dustinschultz**
… conflicts with user defined beans

### CODE REVIEW

**Comment by philwebb** [comment]
See #7711 for background

**Comment by philwebb** [comment]
I wonder if we can just back off if an existing `testRestTemplate` bean is registered?

**Comment by snicoll** [comment]
that would be pretty bad (if you refer the name). I could register a `RestTemplate` with name `testRestTemplate` in my own config and still want a `TestRestTemplate` provided to me. IMO, the name we use should have some sort of unique qualifier. I wouldn't use the one @dustinschultz has suggested but something of the kind.

**Comment by philwebb** [comment]
Thanks for the PR, we've got a similar fix lined up that uses the fully qualified class name as the bean name. Will be pushing it shortly.

**Comment by dustinschultz** [comment]
Great - thanks guys!

**Pull request closed without merging**
