### PR TITLE
Upgrade Maven WAR Plugin to 3.2.2

### PR DESCRIPTION
**Pull request by khmarbaise**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@khmarbaise Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=13564)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=13564) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@khmarbaise Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=13564)!

**Comment by wilkinsona** [comment]
Thanks for the PR, but we can't upgrade to a new minor version of the war plugin in a maintenance release of Spring Boot. We could consider merging this into master (for Boot 2.1) though. Would you like to update the PR to use master as its base branch?

**Comment by khmarbaise** [comment]
Hi @wilkinsona have closed this one an open a new PR #13629

**Pull request closed without merging**
