### PR TITLE
Simplify ArrayList calling addAll() Immediately

### PR DESCRIPTION
**Pull request by Nooheat**
I just simplified ArrayList construction.
```java
	private static <E> Set<E> asUnmodifiableOrderedSet(Collection<E> elements) {
		List<E> list = new ArrayList<>();
		list.addAll(elements);
		list.sort(AnnotationAwareOrderComparator.INSTANCE);
		return new LinkedHashSet<>(list);
	}
```
it can be
```java
	private static <E> Set<E> asUnmodifiableOrderedSet(Collection<E> elements) {
		List<E> list = new ArrayList<>(elements);
		list.sort(AnnotationAwareOrderComparator.INSTANCE);
		return new LinkedHashSet<>(list);
	}
```
And this change has a little profit to allocate memory
- See: https://stackoverflow.com/a/4238693

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Nooheat Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15033)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15033) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Nooheat Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15033)!

**Comment by Nooheat** [comment]
whut??? I'm sorry to make failure.. :(
I don't know what to do.

**Comment by snicoll** [comment]
@nooheat don’t you worry, this looks unrelated. Thanks for the PR!

**Comment by snicoll** [comment]
@Nooheat thank you for making your first contribution to Spring Boot. This is now merged in `2.0.x` and `master`.

**Pull request closed without merging**
