### PR TITLE
Add tests for CompressionConnectorCustomizer

### PR DESCRIPTION
**Pull request by za-rudeboy**
CompressionConnectorCustomizer currently does not have any associated tests. Added CompressionConnectorCustomizerTest for it

### CODE REVIEW

**Comment by philwebb** [comment]
Thank you!

**Comment by wilkinsona** [comment]
The new class should be renamed to `…Tests` as part of merging this.

**Comment by za-rudeboy** [comment]
> The new class should be renamed to `…Tests` as part of merging this.

Done

**Comment by wilkinsona** [comment]
Thanks!

**Comment by mbhave** [comment]
@za-rudeboy Thank you for making your first contribution to Spring Boot. This is now on master.

**Pull request closed without merging**
