### PR TITLE
Simplify retrieval of Narayana XARecoveryModule

### PR DESCRIPTION
**Pull request by gytis**
Simplify code by using XARecoveryModule.getRegisteredXARecoveryModule() instead of iterating the list to retrieve XARecoveryModule.

### CODE REVIEW

**Comment by gytis** [comment]
CI failure doesn't seem to be related.

**Comment by wilkinsona** [comment]
@gytis Thanks. What versions of Narayana is this applicable to? Should the change go in 1.5 or only in master?

**Comment by gytis** [comment]
master and 1.5.x would be great to keep consistent.

**Comment by wilkinsona** [comment]
@gytis I've cherry-picked this into 1.5.x and merged it into master. For future reference, if you want a fix to go in 1.5.x, please create the pull request against 1.5.x rather than master.

**Pull request closed without merging**
