### PR TITLE
Remove `Nullable` annotation

### PR DESCRIPTION
**Pull request by wonwoo**

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. The intent of the proposed changes isn't clear to me. Can you please describe what you are aiming to harmonise? Note that we have an [issue](
https://github.com/spring-projects/spring-boot/issues/10712) open to add `@Nullable` across Spring Boot's API. It is something that we want to do, but we want to do it in one go across the entire API.

**Comment by wonwoo** [comment]
nullable annotation is declared another convert method. in harmony with them..

But if you change the entire api at once, this pr is closed.

**Comment by wilkinsona** [comment]
Thanks for the clarification. The existing usages of `@Nullable` on a `Converter` are only in some test code. I'm also not sure why it's there and think I could probably be removed.

@snicoll, can you recall why we have `@Nullable` here:

https://github.com/spring-projects/spring-boot/blob/e8fef9733520a7bd40813931c311a7cc46075f2d/spring-boot-project/spring-boot-test-autoconfigure/src/test/java/org/springframework/boot/test/autoconfigure/web/reactive/webclient/ExampleIdConverter.java#L42-L50

**Comment by snicoll** [comment]
It is probably a mistake, IntelliJ IDEA can add the annotation automatically when you override a method.

**Comment by wonwoo** [comment]
https://github.com/spring-projects/spring-boot/blob/ca0de4385c01cbbd120e96ec9f83427fb48c9a15/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/convert/ArrayToDelimitedStringConverter.java#L53-L59

`ArrayToDelimitedStringConverter`, `DelimitedStringToArrayConverter`, `DelimitedStringToCollectionConverter` 

Nullable Annotations are declared in the class

**Comment by wilkinsona** [comment]
Well spotted. They shouldn't be there in either (and are providing no benefit as it's a package-private class). Would you like to repurpose this PR to remove them? The only place where `@Nullable` should be used is to allow actuator endpoint operations to indicate that an input is optional.

**Comment by wilkinsona** [comment]
Thanks very much for making your first contribution to Spring Boot, @wonwoo. The proposed changes have been merged into 2.1.x and forwards into master.

**Pull request closed without merging**
