### PR TITLE
Fix typo in TomcatWebServer Javadoc

### PR DESCRIPTION
**Pull request by joca-bt**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@joca-bt Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=24245)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=24245) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by joca-bt** [comment]
"If you are submitting an obvious fix, then you do not need to sign the CLA."

**Comment by snicoll** [comment]
@pivotal-issuemaster this is an obvious fix.

**Comment by pivotal-issuemaster** [comment]
@joca-bt This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by snicoll** [comment]
@joca-bt good catch and thank you for making your first contribution to Spring Boot.

**Pull request closed without merging**
