### PR TITLE
Migrate UndertowCustomizer, TomcatCustomizer and JettyCustomizer to PropertyMapper

### PR DESCRIPTION
**Pull request by qinnnyul**
Added unit tests for UndertowCustomizer, TomcatCustomizer and JettyCustomizer, meanwhile, adapted PropertyMapper into these classes, please refer to #11688

### CODE REVIEW

**Comment by snicoll** [comment]
@qinnnyul please do not create PRs from `master`  that last commit is unrelated  to this issue.

**Comment by qinnnyul** [comment]
@snicoll sure thing, I will keep it in mind, thanks for reminder

**Comment by snicoll** [comment]
@qinnnyul thanks for the PR. I've polished it in 1c195f5. I've also removed the tests as we do not write tests like this (no need to mock the environment and the properties object for instance) and refactoring them turn out to be a major work (also considering they were duplicating other existing tests). If you want to contribute them back in a format that is more compliant with what we do, let us know if you need guidance.

**Comment by qinnnyul** [comment]
@snicoll very nice, thanks.

**Pull request closed without merging**
