### PR TITLE
Enable custom Reservoir in DropwizardMetricServices metrics

### LINKED ISSUE #5199: Support overriding Reservoir for DropWizard timers and histograms
Spring Boot out of the box collects various metrics and if DropWizard is on the classpath those metrics are available in DropWizard MetricRegistry. Currently, Spring Boot 1.3.2, Timer and Histogram metrics get registered in registry with default Reservoir implementation.

It would be nice to be able to override Reservoir per metric, or at least for a start to be able to override global one.

If it's possible already, please have it documented. If it's not possible, please support it and have it documented.

One different Reservoir I'd like to use is HdrHistogramResetOnSnapshotReservoir, see more details on the use case and that reservoir implementation in https://github.com/dropwizard/metrics/issues/143#issuecomment-85428445 and in https://bitbucket.org/marshallpierce/hdrhistogram-metrics-reservoir/

### PR DESCRIPTION
**Pull request by lucassaldanha**
Uses the ReservoirFactory to customize the implementation of
the Reservoir that will be used when creating Timer and Histogram
in the DropwizardMetricServices.

Fixes #5199

### CODE REVIEW

**Comment by johnrengelman** [comment]
Yay!

**Comment by lucassaldanha** [comment]
@philwebb you've added the 1.5.0 milestone to this PR. Shall I open another PR specific to merge on 1.5.x or will you guys just use the same one across the branches?

**Comment by snicoll** [comment]
@lucassaldanha one PR and we merge forward. We usually appreciate if the PR is built off the right branch but we'll manage this one, don't worry.

**Comment by lucassaldanha** [comment]
@snicoll I can see that the code quality tool is complaining about the default package private level. Is that a rule that you guys follow in the project or we can ignore that warning? I'm using the protected level so I can inject a mock dependency for the unit tests. I don't think it should be a public method.

From Codacy:

`Use explicit scoping instead of the default package private level. What this means it that you should do is make all the fields within your classes private to enforce better encapsulation.`

**Comment by philwebb** [comment]
@lucassaldanha We don't use `Codacy` so you can ignore that. We use package scope for classes quite often but not so much for methods. It's not uncommon for us to polish up commits when they're merged so don't worry too much about things like the scope.

**Comment by philwebb** [comment]
Thanks for the PR. I've reworked things a little bit in commit 06a7ab0cd5f3036e7ece4edf7c80428874afc362. The main change I've made is to simplify `ReservoirFactory` and pass it the name of the metric. If you get a chance, please let me know if the updated code still works for you.

Thanks again!

**Pull request closed without merging**
