### PR TITLE
Add javax-websocket-client-impl in bom #9988

### PR DESCRIPTION
**Pull request by blasd**
Add missing javax-websocket-client-impl artifactid in bom

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@blasd Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9990)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9990) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by wilkinsona** [comment]
Duplicate of #9989

**Comment by blasd** [comment]
Hello. https://github.com/spring-projects/spring-boot/pull/9989 goes only into 1.5.x. Shouldn't this be kept to pr into master?

**Comment by wilkinsona** [comment]
Thanks, but no. We'll merge the change forwards from 1.5.x to master as needed.

**Pull request closed without merging**
