### PR TITLE
Add support for SSL in `InfluxDbAutoconfiguration`

### PR DESCRIPTION
**Pull request by alimate**
`spring.influx.ssl.enabled` property determines whether or not we're going to use SSL to interact with InfluxDB. If enabled, then the `spring.influx.ssl.certificate` represents the path to X509 formatted public key.

Fixes gh-9502

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@alimate Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=11157)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=11157) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by wilkinsona** [comment]
I'm not sure that we should merge this, at least not in its current form.

#9502 was about allowing the client to use HTTPS to talk to the InfluxDB server. #9669 has already given the auto-configuration for support for using a custom `OkHttpClient.Builder` which can be used to enable that.

The proposal here seems to be specifically about connecting to an InfluxDB server that's using a certificate that's self-signed or otherwise not trusted by default. In this proposal, if you enable SSL it requires that you also provide a certificate to populate the client's trust store. For cases where the server's certificate is already trusted, that's unnecessary.

Also, the way that the certificate is provided is different to how we do things for configuring the web server's SSL. In this proposal, a bare certificate is provided and it's the wrapped up in a `KeyStore`. In the web server case, a key store is provided which simplifies the implementation.

My inclination is to decline this. The current custom `OkHttpClient.Builder` approach seems to be sufficient for most cases. If we want to do something to simplify the SSL case, I think it should be more closely modelled on what we've done for configuring web server SSL.

**Comment by snicoll** [comment]
> My inclination is to decline this. The current custom OkHttpClient.Builder approach seems to be sufficient for most cases.

+1

**Comment by wilkinsona** [comment]
Ok, given the reactions from @alimate and @snicoll's agreement, I'm going to close this one. Thank you anyway for the contribution.

**Pull request closed without merging**
