### PR TITLE
Add missing dots in cache auto-configurations.

### PR DESCRIPTION
**Pull request by izeye**

### CODE REVIEW

**Comment by snicoll** [comment]
Oh crap. Thanks for that but since this was the second source of error that wasn't detected I went for https://github.com/spring-projects/spring-boot/commit/961350735b1b3986add11a65774e0be171c21066 instead (testing the condition directly). It's still not 100% perfect though.

**Comment by izeye** [comment]
@snicoll Is there any way I can get any snapshot including the commit?

I tried to refresh Gradle in IntelliJ but I couldn't see the commit yet.

**Comment by snicoll** [comment]
The build [completed 23 minutes ago](https://build.spring.io/browse/BOOT-PUB) can you try again please?

**Comment by izeye** [comment]
@snicoll I installed in my local Maven repository

and I confirmed the commit worked with my sample.

Thanks for fixing!

**Comment by snicoll** [comment]
:+1:

**Comment by izeye** [comment]
@snicoll It's weird...

I cleared my local Maven repository and Gradle cache

but I'm still getting a snapshot which doesn't include the commit.

I'm not sure what I did wrong.

**Pull request closed without merging**
