### PR TITLE
Add support for enum default values in configuration processor

### PR DESCRIPTION
**Pull request by qerub**
Pull request for #7562.

I'd like to see a merge into 1.4.x if possible.

If approved, can I get my name added to at least `ExpressionTree`'s `@author` list? :)

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks for the PR. I'm afraid this one definitely falls under the "enhancement" category and as such I don't think we should apply it to 1.4.x.

**Comment by philwebb** [comment]
Just looking at the code, what happens if you have a constant that refers to a value that isn't an enum?

For example:

```java
private String value = MyClass.SOME_STATIC;
```

**Comment by qerub** [comment]
> Thanks for the PR. I'm afraid this one definitely falls under the "enhancement" category and as such I don't think we should apply it to 1.4.x.

I don't think it would be a stretch to call it a bug fix, but your call. :)

> Just looking at the code, what happens if you have a constant that refers to a value that isn't an enum?

It will treat it as if it were an enum (i.e. reporting the default value "some-static" for your example).

If this is not OK, do you have any tips on how to detect enum-ness?

**Comment by philwebb** [comment]
@qerub 

> It will treat it as if it were an enum (i.e. reporting the default value "some-static" for your example). If this is not OK, do you have any tips on how to detect enum-ness?

I think that will be a problem, it's going to be a little confusing to have that happen. I'm not sure how to detect if the type actually refers to an enum or not.

**Comment by qerub** [comment]
OK, I'll try to figure out a solution!

**Comment by snicoll** [comment]
One way to mitigate this is to check that the "selected" part of the expression is the same as the type of property (i.e. checking the left side match the right one). But even we did that, we could end up in a situation where `MyClass` refers to some "instance" of the property and we would use the name of the static field as the default value. 

There isn't a way here unfortunately. We should go the manual metadata route for those (#7890). 

@qerub I am afraid I don't see a way out here. Feel free to reopen if you found one.

**Pull request closed without merging**
