### PR TITLE
Document spring.main.register-shutdown-hook

### PR DESCRIPTION
**Pull request by polarbear567**

### CODE REVIEW

**Comment by polarbear567** [comment]
Hi, @wilkinsona now I put this description in howto document, and I don't know if it's right, do you have some suggestion?

**Comment by wilkinsona** [comment]
Thanks for the pull request, @polarbear567.

All I had in mind for this one was to add an entry in spring-boot-project/spring-boot/src/main/resources/META-INF/additional-spring-configuration-metadata.json and the appendix in the documentation (only necessary in 2.1.x).

Do you have time to update your changes along those lines?

**Comment by polarbear567** [comment]
@wilkinsona , sure, I'd love to do this, just a question, do you want me to pull a branch from 2.1.x and submit it to 2.1.x?

**Comment by polarbear567** [comment]
the new PR is https://github.com/spring-projects/spring-boot/pull/18581

**Comment by snicoll** [comment]
Closing in favour of PR #18581

**Pull request closed without merging**
