### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by wambugucoder**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wambugucoder Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=24610)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=24610) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@wambugucoder Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=24610)!

**Comment by pivotal-issuemaster** [comment]
@wambugucoder Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=24610)!

**Comment by snicoll** [comment]
@wambugucoder I assume this was opened by mistake. Please use your own fork for experiments.

**Pull request closed without merging**
