### PR TITLE
Adjust to changes in Spring AMQP 2.2 snapshots

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

this PR should fix the current build caused by a number of changes in the newest AMQP snapshots.

Cheers,
Christoph

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thank you, @dreis2211. I had been looking at this too and have a slightly different take on it [here](https://github.com/wilkinsona/spring-boot/commit/344b9bce19a160d3ab335b63020cb7a3041b0d98).

**Comment by wilkinsona** [comment]
Thanks, @dreis2211. @snicoll seems to like a mix of the two :)

**Comment by dreis2211** [comment]
Teamwork 💪

**Comment by snicoll** [comment]
I agree, this Community rocks. Thank you so much again Christoph.

**Pull request closed without merging**
