### PR TITLE
Fix anchors in links to Maven and Gradle plugin docs

### LINKED ISSUE #21019: Documentation on Layering Docker Images has a broken link to the Maven Plugin doc
Broken link

In this section of the docs:
https://docs.spring.io/spring-boot/docs/2.3.0.M4/reference/htmlsingle/#layering-docker-images

The last sentence has two links, one for Maven and one for Gradle. The Maven link is broken (returns 404 Not Found). Instead of:

https://docs.spring.io/spring-boot/docs/2.3.0.M4/maven-plugin/html//#repackage-layered-jars

It should be:

https://docs.spring.io/spring-boot/docs/2.3.0.M4/maven-plugin/reference/html//#repackage-layered-jars

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

this PR fixes #21019. While doing so, I noticed another broken anchor that I fixed alongside. Hope that's okay.

Cheers,
Christoph

### CODE REVIEW

**Comment by dreis2211** [comment]
Test failures seem unrelated.

**Comment by wilkinsona** [comment]
The test failures look like https://github.com/spring-projects/spring-boot/issues/20900.

**Comment by dreis2211** [comment]
Jep, and a consecutive docker failure (no space on device)

**Comment by wilkinsona** [comment]
Thanks very much, @dreis2211, particularly for spotting and fixing the other broken anchor.

**Pull request closed without merging**
