### PR TITLE
Spring Boot Starter for Spring Social Google

### PR DESCRIPTION
**Pull request by jiwhiz**
I'm using [Spring Social Google](https://github.com/GabiAxel/spring-social-google) in my project, and would like to have a spring boot starter for that.

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks, have you signed the CLA?

**Comment by jiwhiz** [comment]
Yes, did that long time ago when I worked with spring social security.

**Comment by philwebb** [comment]
@jiwhiz Thanks, but could you also sign the Spring Boot CLA. I think they are the same but I'd like to make sure that we have all bases covered.

**Comment by jiwhiz** [comment]
@philwebb Signed the Spring Boot CLA. Got response:

>Hello Yuan Ji
>
>Thank you but our records indicate that you have already accepted the individual 
>contributor agreement. If you are interested in participating in an additional 
>Spring project, please contact the appropriate project lead and indicate that 
>you have already signed the Spring Contributor Agreement. Once signed
>agreement covers participating in as many Spring projects as you need.
>
>Your confirmation number is: 40020121213084106

**Comment by philwebb** [comment]
OK, Thanks. My mistake, it looks like the CLA covers all projects.

**Comment by wilkinsona** [comment]
As things stand, I'm not sure that we should merge this.

The project's group id is `org.springframework.social` but, AFAIK, it isn't an official Spring project. It isn't listed in the [Spring Social README](https://github.com/spring-projects/spring-social#spring-social-modules) and isn't in the Spring Projects GitHub organisation. I'm wary of creating the wrong impression regarding the Spring team's involvement with the project. I'd be more comfortable if the project wasn't being published in "our" group id.

/cc @habuma

**Comment by jiwhiz** [comment]
Hmm... Spring Social Google is already under group id of "org.springframework.social". Since it is so important, is it possible to move it into spring-projects? I think it will benefit all of us.

/cc @GabiAxel @habuma

**Comment by jiwhiz** [comment]
So @GabiAxel is OK to move spring-social-google to spring-projects. Is it @habuma 's call now?

**Comment by wilkinsona** [comment]
Thanks for the PR. We've discussed this and decided that we don't want to add support for `spring-social-google` to Spring Boot. As an alternative, you may want to consider contributing the auto-configuration to the `spring-social-google` project.

**Pull request closed without merging**
