### PR TITLE
Adapt Javadoc to reflect the removal of deprecated code.

### PR DESCRIPTION
**Pull request by cosminhume**
A trivial update of the documentation, removing references to methods that were first deprecated and then removed.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cosminhume Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18668)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18668) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by cosminhume** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@cosminhume This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by wilkinsona** [comment]
Thanks for the suggestion but the javadoc is correct as it is. You can use a long value that is interpreted as data size in bytes or use something like 1MB which is a data size in megabytes.

**Comment by snicoll** [comment]
@wilkinsona Actually we used to have methods in there that takes a `long` and `a `DataSize`. We removed the former so I think this update to the Javadoc in this context makes sense. Thoughts?

**Comment by wilkinsona** [comment]
I don't think it makes sense as proposed as, IMO, too much context is lost. Specifically, it's not clear that you can specify a value without a unit and that it will be treated as bytes. If we feel it's necessary to describe how things can be set, I think the javadoc should remain unchanged. Alternatively, I'd remove the whole sentence about how things can be set as we don't provide such a description for any other class that I can recall.

**Comment by snicoll** [comment]
Good point on losing the context and I like your idea of removing the last sentence altogether. @cosminhume would you be willing to rework your PR in that direction?

**Comment by cosminhume** [comment]
@snicoll I removed the last sentence altogether, please see #18755

**Pull request closed without merging**
