### PR TITLE
HealthMvcEndpoint's cache is not thread-safe

### PR DESCRIPTION
**Pull request by utkuozdemir**
Used an atomic reference and its `updateAndGet` method introduced with Java 8 to make the health cache thread-safe.

### CODE REVIEW

**Comment by wilkinsona** [comment]
When this was [originally implemented](https://github.com/spring-projects/spring-boot/commit/24e71e868f0599eb041b80d32f7cd3e17977c897) a comment was added:

```
// Not too worried about concurrent access here, the worst that can happen is the
// odd extra call to delegate.invoke()
```

On closer inspection, that's not the case. The worst that can happen is that two requests for health are made concurrently. The first thread identifies that the cache is stale and updates `lastAccess`. The second thread sees the updated `lastAccess` and incorrectly identifies that the cache is fresh and returns the stale value. The first thread then updates the cache and returns the fresh health.

I think we should consider fixing this in 1.5 which will require a different approach to the one proposed here as we can't use `AtomicReference.updateAndGet` there.

**Comment by utkuozdemir** [comment]
> The second thread sees the updated lastAccess and incorrectly identifies that the cache is fresh and returns the stale health.

As far as I know, there is no guarantee for, let's say, after a certain period of time, another thread will start to read the updated value even if the field is not `volatile`/atomic. It can be in some extreme cases the stale reference is read indefinitely (however I don't know the interrnals deeply).

After I implemented this solution, I realized that this means a locking on each and every health call, which can actually be avoided. So, a solution would be to either implement a double-checked locking mechanism which checks the last access for stale cache, or to use a `ReentrantReadWriteLock` to avoid locking for reads.

I can implement one of the solutions above for 1.5 using Java 7 APIs if you think it makes sense.

**Comment by wilkinsona** [comment]
I don't mind too much about locking as any lock is unlikely to be highly contented and the cost of an uncontended lock is low enough to not be a concern. That said, given that we only really care about stale responses and don't care too much about a small number of duplicate calls to the delegate, storing your new `HealthCheck` class in a `volatile` field would probably be sufficient.

**Comment by wilkinsona** [comment]
Thanks for the PR, @utkuozdemir. I've fixed this in 1.5.x [using a volatile field](https://github.com/spring-projects/spring-boot/commit/7a04708c41f54fe6f2307e3bd607b9bb7c103090). In the interests of making any future changes easy to merge forwards, we'd prefer to keep the solutions in 1.5.x and master as similar as possible. To that end, we'll stick with the volatile field approach rather than using `AtomicReference` and `updateAndGet`. Thanks anyway, and thanks, too, for bringing the problem to our attention.

**Comment by utkuozdemir** [comment]
Thank you for the solution @wilkinsona. I couldn't find the chance to implement the necessary change after the initial PR, good to see it got solved.

**Pull request closed without merging**
