### PR TITLE
Provide logfile via MvcEndpoint

### LINKED ISSUE #2137: An endpoint for logging
Accessing current log file of server is crucial in case an error. An endpoint for logging would be great and handy.

### PR DESCRIPTION
**Pull request by joshiste**
closes #2137

### CODE REVIEW

**Comment by philwebb** [comment]
Cool. We'll take a look at this for 1.3. I wonder if we should disable the endpoint if the `logging.file` property is not set?

**Comment by joshiste** [comment]
Now the Logfile-Endpoint is only added when logging.file or loggin.path is set.
BTW CLA is 93620140928055712

**Comment by joshiste** [comment]
I'm curious wether you gonna merge this into 1.3.0?

**Comment by wilkinsona** [comment]
That's the plan – it's currently assigned to the 1.3.0.RC1 milestone.

**Comment by philwebb** [comment]
Merged with a few tweaks. Primarily removing the "file download" prompt when hitting the endpoint.

Thanks!

**Pull request closed without merging**
