### PR TITLE
Polish ResourceProperties.Cache.Cachecontrol.toHttpCacheControl()

### PR DESCRIPTION
**Pull request by izeye**
I'm not sure there's any benefit in using the functional style here but IMHO, this simple style looks more readable and consistent with the other parts.

### CODE REVIEW

**Comment by bclozel** [comment]
This has been partially polished the other way around in e01c92a38a4a.
Marking this as `for:team-attention` to decide what's best here; I prefer the imperative style.

**Comment by snicoll** [comment]
I've seen the current style in a few other places (OAuth2 comes to mind) and I prefer the imperative style as well.

**Comment by wilkinsona** [comment]
I prefer the fewer logic branches of the code in its current form. I am not in favour of merging this.

**Comment by bclozel** [comment]
Sorry @izeye, the team decided to expand that style in other places of the project so we'll keep it that way.

Thanks for your contribution!

**Comment by izeye** [comment]
@bclozel Thanks for the information!

**Comment by philwebb** [comment]
We have an open enhancement ticket to improve this pattern across the codebase. See #9018.

**Pull request closed without merging**
