### PR TITLE
Added spring boot starter for GraphQL project

### PR DESCRIPTION
**Pull request by janfockaert**
Added new starter project for GraphQL. This is a simple but powerful project to get started with GraphQL.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@janfockaert Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8026)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8026) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@janfockaert Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8026)!

**Comment by snicoll** [comment]
@janfockaert any insight about the linked issue?

**Comment by janfockaert** [comment]
@snicoll This is still on the planning for next release

**Comment by janfockaert** [comment]
There is a typo in the title -> [GrahQL] should be [GrahpQL]. Can you correct this?

**Comment by snicoll** [comment]
I can, will do. Thanks for reporting it

**Comment by janfockaert** [comment]
Thanks

**Pull request closed without merging**
