### PR TITLE
Add Firebird specific health query

### PR DESCRIPTION
**Pull request by kaliy**
I've added firebird support for datasource check. It uses system table [RDB$DATABASE](http://ibexpert.net/ibe/index.php?n=Doc.SystemObjects).
Although the more convenient way is to use MON$DATABASE table which was made specifically for this purpose, it was introduced only in firebird 2.1.

### CODE REVIEW

**Comment by kaliy** [comment]
I've closed it because I wanted to reopen it to trigger travis build again

**Comment by wilkinsona** [comment]
Thanks for the PR. Have you [signed the CLA](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#sign-the-contributor-license-agreement)?

**Comment by kaliy** [comment]
just did it

**Comment by snicoll** [comment]
Merged, thanks!

**Pull request closed without merging**
