### PR TITLE
Use CollectionUtils.isEmpty() and StringUtils.hasLength()

### PR DESCRIPTION
**Pull request by quaff**
search `(\w+) != null && !(\1).isEmpty\(\)`

### CODE REVIEW

**Comment by mhalbritter** [comment]
Hey @quaff, thanks for the PR. If I use this regex to search our `main` codebase, I still find some which haven't been replaced, like `org.springframework.boot.actuate.autoconfigure.health.HealthProperties.Status#setOrder` or `org.springframework.boot.autoconfigure.condition.ConditionMessage.ItemsBuilder#items(org.springframework.boot.autoconfigure.condition.ConditionMessage.Style, java.util.Collection<?>)`. Is there a particular reason that those haven't been replaced?

**Comment by quaff** [comment]
> Hey @quaff, thanks for the PR. If I use this regex to search our `main` codebase, I still find some which haven't been replaced, like `org.springframework.boot.actuate.autoconfigure.health.HealthProperties.Status#setOrder` or `org.springframework.boot.autoconfigure.condition.ConditionMessage.ItemsBuilder#items(org.springframework.boot.autoconfigure.condition.ConditionMessage.Style, java.util.Collection<?>)`. Is there a particular reason that those haven't been replaced?

They are included in this PR, please check.

**Comment by mhalbritter** [comment]
Hey @quaff, of course you're right, that was a mistake on my part :)

**Comment by mhalbritter** [comment]
Thanks!

**Pull request closed without merging**
