### PR TITLE
[WIP] Add compatibility for both flyway 9 and 10 for 38923

### PR DESCRIPTION
**Pull request by MazizEsa**
In summary added compatibility with flyway 10 and 9 by using reflection when initializing flyway scanner.
Add mechanism to check the dependency based on the mentioned flyway versions.

### CODE REVIEW

**Comment by MazizEsa** [comment]
@wilkinsona can you have a look. This is a draft, WIP. 
Im wanna check first whether it's in the right direction.
Still need to add checks / conditions on dependency part to cater the different dependencies and package structure when importing (postgres and hsql).

**Comment by wilkinsona** [comment]
Thanks, @MazizEsa. For the default case (Flyway 9), please don't use reflection. Instead, just directly call the Flyway API that we compile against. Only when Flyway 10's detected should reflection be used.

Also, if you can, please build your changes (`./gradlew build` or `./gradlew spring-boot-project:spring-boot-autoconfigure:build`) and fix any problems before pushing.

**Comment by MazizEsa** [comment]
Sure. I'm working from the main branch. Hence flyway 10 is the default. Is
it fine? Or should I work from other branch?

**Comment by wilkinsona** [comment]
As I [said a couple of weeks ago](https://github.com/spring-projects/spring-boot/issues/38923#issuecomment-2081392373), the change is only needed in the `3.2.x` branch. As you've noticed, we've already upgraded to Flyway 10 in the main branch so nothing's needed there. Please use `3.2.x` as the base branch for your changes.

**Comment by MazizEsa** [comment]
Thanks @wilkinsona . My bad. I was old either branch was fine. Will make the changes soon.

**Pull request closed without merging**
