### PR TITLE
added support for setPreferFileSystemAccess on FreeMarkerConfigurationFa...

### PR DESCRIPTION
**Pull request by creactiviti**
added support for configurable setPreferFileSystemAccess -- like we have on the Velocity implementation.

### CODE REVIEW

**Comment by philwebb** [comment]
We should also update the appendix docs when this is merged

**Comment by philwebb** [comment]
@creactiviti Haves you signed the CLA?

**Comment by creactiviti** [comment]
I don't believe I did. How do I do that?

**Comment by philwebb** [comment]
@creactiviti Details are here: https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc

**Comment by creactiviti** [comment]
@philwebb done. confirmation number: 127020150620020224.

**Comment by philwebb** [comment]
@creactiviti Thanks!

**Pull request closed without merging**
