### PR TITLE
Merge pull request #1 from spring-projects/master

### PR DESCRIPTION
**Pull request by xieguanliang**
Update upstream

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@xieguanliang Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=17239)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=17239) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by philwebb** [comment]
@xieguanliang Please use your own repository if you want to experiment with GitHub's pull-request features.

**Comment by xieguanliang** [comment]
I am sorry,  I do it wrong ,I just want to update spring-boot of my repository with pulling request.


发自我的iPhone

------------------ Original ------------------

**Comment by philwebb** [comment]
@xieguanliang No problem, you can usually do that on the command line, e.g:

```
$ git clone https://github.com/xieguanliang/spring-boot.git
$ cd spring-boot
$ git remote add upstream https://github.com/spring-projects/spring-boot.git
$ git rebase upstream/master
$ git push -f origin master
```

For more help try https://guides.github.com

**Comment by xieguanliang** [comment]
Thanks, I do it , and it works！


发自我的iPhone

------------------ Original ------------------

**Pull request closed without merging**
