### PR TITLE
MetricsFilter doesn't consider path variables when using Jersey

### PR DESCRIPTION
**Pull request by isopov**
#5875 - fix for this problem that will be fixed in other ways in 2.0.x and further

### CODE REVIEW

**Comment by isopov** [comment]
@wilkinsona we discussed this is gitter and I don't want you to miss it (especially if this PR is not good enough), so tagging - it is really similar to #5875 and the main good part here is test.

**Comment by wilkinsona** [comment]
Thanks for the PR, @isopov. My feeling is that we shouldn't try to patch this for Jersey. As pointed out in #5875, it would still leave us with a problem for web frameworks other than Spring MVC and Jersey.

As things stand, my preference is to fall back to `unmapped` for a request-response that does not have the best matching pattern attribute. I've implemented that in [this branch](https://github.com/wilkinsona/spring-boot/tree/gh-5875). They are the 1.5.x equivalent of the changes that have been made in 2.0.3 for https://github.com/spring-projects/spring-boot/issues/12447.  The longer term approach (2.1) is to make the metrics filter general purpose and call out to pluggable strategies that provide the necessary information. This would allow us to solve it for Jersey while also providing a documented, supported, plug point for other Frameworks and use cases to be plugged in as well.

**Comment by wilkinsona** [comment]
Having just discussed this with @philwebb, we're going to align 1.5 with 2.0's current behaviour and fall back to `unmapped` when we can get a pattern from Spring MVC. Thanks anyway, @isopov.

**Comment by isopov** [comment]
So this means that for Jersey in 1.5.x all urls will be one and the same "unmapped" even if there are not path veriables in them? Than we'll need to use some workaround...

**Pull request closed without merging**
