### PR TITLE
Feature: Undertow access log configuration by properties

### PR DESCRIPTION
**Pull request by marcosbarbero**
Providing access_log configuration for Undertow at application.yml(properties) like the configuration available for Tomcat.
```
server.undertow.access-log-enabled: true
server.undertow.access-log-pattern: common #default
server.undertow.basedir:  #default /tmp
```

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. Have you [signed the CLA](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#sign-the-contributor-license-agreement)?

The series of separate commits and the non-functional changes (reordering of imports, introduction of wildcard imports, reordering of fields and methods, etc) make the changes harder to review than they could be. Can you please squash the changes into a single commit and remove the non-functional changes so that the diff just shows what's necessary to add access log support?

**Comment by marcosbarbero** [comment]
Sure, can you close this pull request?  I'll submit new one with those changes.

**Comment by wilkinsona** [comment]
I can, but there's no need; you can force a push to the branch for this one instead.

**Comment by marcosbarbero** [comment]
@wilkinsona I'm signing the CLA and I don't know who is the spring-boot project lead, could you help me please?

**Comment by wilkinsona** [comment]
As [noted here](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc), you can use Dave Syer or Phillip Webb.

**Comment by marcosbarbero** [comment]
@wilkinsona Thank you!
About the pull request, I've deleted my forked copy so I'll close this and send a new one right now.

**Pull request closed without merging**
