### PR TITLE
Use start-stop-daemon in lauch.script rather than su.

### PR DESCRIPTION
**Pull request by bedge**
This was not legal shell syntax.

### CODE REVIEW

**Comment by bedge** [comment]
This change will use start-stop-daemon if present. Another option would be to set a flag in ${jarfolder}/${configfile} to configure which start mechanism to use.
eg:
in ${jarfolder}/${configfile}:
```
export USE_START_STOP_DAEMON=1
``` 
Then, rather than just checking the existence of start-stop-daemon, do:
```
if [ "$USE_START_STOP_DAEMON" ] ; then
    use it
else
    use current su
fi
```
If this is preferable, let me know and I'll refactor to support this.

**Comment by bedge** [comment]
Resolves https://github.com/spring-projects/spring-boot/issues/3742

**Comment by wilkinsona** [comment]
@bedge Thanks for the PR. Your current approach looks good to me

**Comment by wilkinsona** [comment]
Testing on Ubuntu 14.04 the pid's now written correctly but the app fails to start, logging the following:

```
start-stop-daemon: unable to start java (No such file or directory)
```

**Comment by wilkinsona** [comment]
Looks like `start-stop-daemon` needs the executable's path to be absolute. Using the output of `type -p java`, rather than just `java` fixes the problem.

**Comment by wilkinsona** [comment]
@bedge Have you [signed the CLA](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#sign-the-contributor-license-agreement)?

**Comment by bedge** [comment]
@wilkinsona Yes, just signed the CLA, online & emailed PDF just to be safe.
Will update to use `type-p java`

**Comment by philwebb** [comment]
Thanks for signing the CLA! Now merged.

**Comment by bedge** [comment]
WooHoo!, thanks for merging. This makes my life much easier. Next is log rotation...

**Pull request closed without merging**
