### PR TITLE
More defensive about logging system home

### PR DESCRIPTION
**Pull request by dsyer**
We can afford to catch Throwable here. It doesn't affect the flow
and it makes it work with AOT.

### CODE REVIEW

**Comment by snicoll** [comment]
What exception do we have with GraalVM? Do we have reported an issue on their tracker?

**Comment by dsyer** [comment]
I think it's the same as this one: https://github.com/oracle/graal/issues/564. Anyway, `ProtectionDomain` doesn't make much sense in a native image, and it's completely optional in Boot as far as I can tell, so it shouldn't really matter much.

**Comment by dsyer** [comment]
See also #14168

**Comment by snicoll** [comment]
Thanks but we prefer the issue on the GraalVM to be taken care of. It it turns out it can't, we can reopen this issue and investigate how this can be tested.

**Comment by philwebb** [comment]
I've raised #14216 to see if we can setup a CI in the longer term

**Pull request closed without merging**
