### PR TITLE
Fix stack-trace line breaks in whitelabel error views

### PR DESCRIPTION
**Pull request by up-to-you**
Fix stack-trace line break inside div for DefaultErrorWebExceptionHandler

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@up-to-you Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15075)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15075) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by bclozel** [comment]
@up-to-you Could you sign the CLA so that I can merge your pull-request please?

**Comment by snicoll** [comment]
@up-to-you indeed, thank you.

**Comment by wilkinsona** [comment]
This still needs to be merged. Brian backed it out when he realised the CLA had not be signed.

**Comment by bclozel** [comment]
Thanks for your first contribution @up-to-you !

**Pull request closed without merging**
