### PR TITLE
Automatic detection of jansi in DefaultLogbackConfiguration.

### PR DESCRIPTION
**Pull request by Nowheresly**
Fixes gh-2331

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks, you've already signed the CLA right?

**Comment by Nowheresly** [comment]
Right !

**Comment by Nowheresly** [comment]
It seems the use of jansi may not work with some windows versions.
See bug report here: http://jira.qos.ch/browse/LOGBACK-762
and it seems this bug report won't be fixed in a near future...
Maybe auto-enabling jansi (ie: what my PR is doing) is not the right thing to do.
Any suggestions ?

**Comment by philwebb** [comment]
Hmm, that is a little concerning but it looks like your code only kicks in when jansi is on the classpath. Perhaps we need to offer a way to opt-out in case the user had jansi but doesn't want it for logback. 

I would have thought that generally, if the user has a jansi dependency then configuring it would be what they want.

**Comment by Nowheresly** [comment]
> it looks like your code only kicks in when jansi is on the classpath. 

Right !

> Perhaps we need to offer a way to opt-out in case the user had jansi but doesn't want it for logback.

Precisely what I thought. Now how ? With yet another environment variable ? Any name to suggest ? Or some other approach ?

**Comment by Nowheresly** [comment]
I added a system property that is checked during the detect jansi process. When system property `spring.logback.jansi.deactivated` is set to true, jansi won't be used with logback even if it is in the classpath.
I added as well a unit test `DefaultLogbackConfigurationTest`.

**Comment by philwebb** [comment]
I'm still in two minds about this one. I'm worried about the `LOGBACK-762` issue that you referenced. Going to discuss with the team.

**Comment by philwebb** [comment]
After further review we've decided no to merge at this time. Since color output is really just a "nice to have" feature we'd rather leave things as they are and not risk breaking apps. As suggested in  LOGBACK-762 using ansicon or conemu is probably a preferable solution.

**Comment by Nowheresly** [comment]
All right 
Makes sense indeed...

**Pull request closed without merging**
