### PR TITLE
Include unconditional classes in auto-config endpoint

### PR DESCRIPTION
**Pull request by rokii**
https://github.com/spring-projects/spring-boot/issues/9226

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rokii Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9227)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9227) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rokii Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9227)!

**Comment by wilkinsona** [comment]
@rokii Thank you for opening your first contribution to Spring Boot

**Comment by wilkinsona** [comment]
This is a follow-on from https://github.com/spring-projects/spring-boot/issues/2209 which added the unconditional classes to the logged report.

**Comment by snicoll** [comment]
Merged, thanks!

**Pull request closed without merging**
