### PR TITLE
Rename HCP to SAP_CLOUD_PLATFORM, as it is the official name.

### PR DESCRIPTION
**Pull request by ihrigb**
Rename HCP to SAP_CLOUD_PLATFORM, as this is the official name of the platform.

### CODE REVIEW

**Comment by snicoll** [comment]
What changed your mind since you opened the original pull request?  I appreciate the use of official name but `SAP_CLOUD_PLATFORM` is rather long so I'd like to avoid that if we can.

**Comment by ihrigb** [comment]
@snicoll Hana Cloud Platform (HCP) is not the official name anylonger, so I wanted to adopt this here, as this is still in milestone state (and not released). Any suggestions for a shorter name?

**Comment by snicoll** [comment]
`SAP` ?

**Comment by ihrigb** [comment]
Sounds reasonable, I will update the PR.

**Comment by snicoll** [comment]
@ihrigb if you do, please only change that then. Your PR has a lot of unrelated changes. Thank you.

**Comment by ihrigb** [comment]
Damn, used the wrong formatter... I will try to fix it.

**Comment by snicoll** [comment]
That was better but still too much unrelated changes. I've polished them myself.

**Pull request closed without merging**
