### PR TITLE
Support 'spring.jdbc.template.*' for customizing JdbcTemplate

### PR DESCRIPTION
**Pull request by kazuki43zoo**
I want to support some useful properties for customizing a `JdbcTemplate` that creating on auto configure.

* `fetchSize`
* `queryTimeout`
* `maxRows`

What do you think ?

### CODE REVIEW

**Comment by philwebb** [comment]
I'm slightly worried that we're verging into programming by properties here. You can do this relatively easily already by defining your own `JdbcTemplate` bean. Let's see what the rest of the team think.

**Comment by kazuki43zoo** [comment]
Hi @philwebb, thanks for review comments.
I see. My opinion is .... Since I think there are many cases that specify the `fetchSize` and `queryTimeout`, it is convenient if it can specify using property provided by Spring Boot.

Thanks.

**Comment by snicoll** [comment]
This is subtle but I am +1 with Phil on that one. We've done it for JmsTemplate but it was more involved with existing auto config for The destination resolver and message converter. Creating the template is dead easy so I wouldn't go that far either.

**Comment by wilkinsona** [comment]
I am in favour of merging this. It's just setting three, simple scalar values. It doesn't feel like programming by properties to me.

**Comment by snicoll** [comment]
If we merge this, we need to fix the named template vs. plain template situation first IMO.

**Comment by snicoll** [comment]
#7954 but it looks like it was declined (so we should probably close #4945 as well then? (confused)

**Comment by wilkinsona** [comment]
#7954 was declined because we don't like the solution. The preference is to use `@ConditionalOnSingleCandidate` as suggested in #4594

**Comment by kazuki43zoo** [comment]
I think it is better to specify using  a property because the `fetchSize` and `queryTimeout` are possibility for tuning(customizing) for each execution environments (local, test, production, etc...)

**Comment by snicoll** [comment]
@kazuki43zoo thanks for the PR, I've polished your contribution in 5ea3ab4

**Comment by kazuki43zoo** [comment]
@snicoll Thanks for polishing and merging !!

**Pull request closed without merging**
