### PR TITLE
Relax Logback loadConfiguration to allow missing resources without failing.

### LINKED ISSUE #6000: Logback "loadConfiguration" too strict with errors (on resources/files)
Hi,

Currently in Spring Boot 1.4.0M3, in `LogbackLoggingSystem` within the method "loadConfiguration", the check for Status.ERRORS is too strict when it comes to missing property resources/files. Under normal logback conditions, Logback logs the error but continues onwards. In Spring Boot, the startup is aborted. 

For example, in a logback-spring.xml configuration:

```xml
<property resource="blahblah.properties">
<property file="/a/directory/blahblah.properties"/>
```

Would cause the bootup to fail. Without using Spring Boot the error is echoed to the appender but ignored. It is quite often the case that this missing resources/files are fine, it doesn't affect the system and logback defaults to using the set values configured within the configuration file. So, being too strict here, IMHO, is too much.

In my view, if it is a `Status.ERROR` *and* if the `Status.getOrigin == PropertyAction` *and* if the message contains "Could not find" we should just skip onwards...

If I have some time, I'll put together a patch (and test if appropriate) for this.

-=david=-

### PR DESCRIPTION
**Pull request by dharrigan**
Hi,

A simple patch to fix issue #6000. 
- [X] I have signed the CLA

property resources to be ignored, without aborting with and ERROR.

Fixes #6000.

### CODE REVIEW

**Comment by dharrigan** [comment]
How Bizarre,

I ran maven checkstyle:checkstyle locally without any issues!

`
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Logging Starter 1.4.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:checkstyle (default-cli) @ spring-boot-starter-logging ---
[INFO]   
`

-=david=-

**Comment by snicoll** [comment]
Try `mvn compile` :)

**Comment by pivotal-issuemaster** [comment]
@dharrigan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=6002) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dharrigan Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=6002)!

**Comment by wilkinsona** [comment]
Closing per the [comment on #6000](https://github.com/spring-projects/spring-boot/issues/6000#issuecomment-225599185).

**Pull request closed without merging**
