### PR TITLE
Update MyUserHandler.java

### PR DESCRIPTION
**Pull request by ritzykey**
markdown error

### CODE REVIEW

**Comment by snicoll** [comment]
@ritzykey what do you mean by "markdown error"? As far as I understand it, the purpose of `/**/` is to [replace irrelevant body with `...`](https://docs.spring.io/spring-boot/reference/web/reactive.html#web.reactive.webflux)

**Comment by snicoll** [comment]
@ritzykey what browser and what link is that? This is what I have on Firefox for https://docs.spring.io/spring-boot/reference/web/reactive.html#web.reactive.webflux

image

**Comment by wilkinsona** [comment]
Thanks, @ritzykey. The code that you have changed is for https://docs.spring.io/spring-boot/reference/web/reactive.html where the problem does not occur. The code for https://docs.spring.io/spring-boot/reference/web/servlet.html is 

https://github.com/spring-projects/spring-boot/blob/06c008832254b955b2c7318abe4678b7160700c6/spring-boot-project/spring-boot-docs/src/main/java/org/springframework/boot/docs/web/servlet/springmvc/MyUserHandler.java#L24-L39

Would you like to update this class instead? The fix is to remove the newlines between `/**/` and the `return` statement so that everything's on one line as it is in the reactive variant:

https://github.com/spring-projects/spring-boot/blob/06c008832254b955b2c7318abe4678b7160700c6/spring-boot-project/spring-boot-docs/src/main/java/org/springframework/boot/docs/web/reactive/webflux/MyUserHandler.java#L26-L38

**Comment by snicoll** [comment]
superseded by #41948

**Pull request closed without merging**
