### PR TITLE
Add a command line option for image.cleanCache when building with Maven

### PR DESCRIPTION
**Pull request by kedar-joshi**
Exposed `image.cleanCache` as command line option for cache cleanup when building with Maven.

Closes gh-23202.

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks @kedar-joshi but this issue is currently assigned to @Bhanu-Latha. Let's hear from the first.

**Comment by snicoll** [comment]
We haven't heard back from the original assignee so we'll process with this PR.

**Comment by kedar-joshi** [comment]
> We haven't heard back from the original assignee so we'll process with this PR.

Sure. Let me rebase my branch.

**Comment by kedar-joshi** [comment]
> Sure. Let me rebase my branch.

Done.

**Comment by snicoll** [comment]
Unfortunately, I mixed up the GitHub issue ID when I polished. Fixed by 142a38f350

Thanks @kedar-joshi

**Pull request closed without merging**
