### PR TITLE
ImportsContextCustomizer does not support AliasFor

### PR DESCRIPTION
**Pull request by lmartelli**
Fixes https://github.com/spring-projects/spring-boot/issues/34854

Use `MergedAnnotations` in order to support `@AliasFor`.

I used plain `Predicate` instead of `AnnotationFilter` because it is much simpler and generic.

### CODE REVIEW

**Review by wilkinsona — CHANGES_REQUESTED** [review]
Thanks for the proposal, @lmartelli. We try to minimise the scope of changes that we make, particularly in maintenance releases. With this in mind, these changes are too broad. For example, the move from `AnnotationFilter` to `Predicate` is not necessary to fix the problem. We also don't use `var` in Spring Boot's code. Would you like to rework your proposal so that it only makes the changes that are required to fix the problem and nothing more?

**Comment by lmartelli** [comment]
> > Would you like to rework your proposal so that it only makes the changes that are required to fix the problem and nothing more?
> 
> Sure, I'll do that.

@wilkinsona But note that we still have to remove `ImportsContextCustomizer.AnnotationFilter` and use the one from `org.springframework.core.annotation.AnnotationFilter` instead since that's what `org.springframework.core.annotation.MergedAnnotations.Search#withAnnotationFilter()` wants.

**Comment by lmartelli** [comment]
@wilkinsona is the new version OK ?

**Comment by snicoll** [comment]
This still looks quite a large change to me and I am not sure the use of `stream` and `reduce` is something we want. The `MergedAnnotations` API you've used doesn't exist in `2.7.x` and we need to be able to rebase the change there. Can you please limit your change to support aliases and only that? We can refine the code further as a separate step.

**Comment by philwebb** [comment]
Thanks very much @lmartelli, I've taken the tests from this commit and merged them into 2.7 along with a [minimal fix](https://github.com/spring-projects/spring-boot/commit/5d0640a35636368d149ea35b3e3c7017f1ddab5d). I've also taken the changes you made to `ImportsContextCustomizer` and applied them [with a little polish](https://github.com/spring-projects/spring-boot/commit/7c942679ad85f254acaa0318cf07753c65a21716) to `main` (see #36211).

Thanks again!

**Pull request closed without merging**
