### PR TITLE
Polish

### PR DESCRIPTION
**Pull request by arefbehboudi**
- Removed @SuppressWarnings as it was no longer needed.
- Used pattern matching.
- Replace the while loop with string repeat

### CODE REVIEW

**Comment by mhalbritter** [comment]
Thanks!

**Comment by arefbehboudi** [comment]
thank you @mhalbritter , Can I ask why my pull request build is getting errors?

**Comment by mhalbritter** [comment]
On the CI, you mean? There's something wrong in the infrastructure I think.

**Comment by arefbehboudi** [comment]
Thank you, so the issue is not with my pull request.

**Pull request closed without merging**
