### PR TITLE
upgrade to Maven 3.5.0

### PR DESCRIPTION
**Pull request by rajadilipkolli**
With 3.5.0 we will have output coloring, this change will implement the same in spring-boot project

### CODE REVIEW

**Comment by snicoll** [comment]
Looks sensible but we need to upgrade our CI pipeline to it as well. I am looking into it.

**Comment by snicoll** [comment]
Bamboo build switched to Maven 3.5

**Comment by rajadilipkolli** [comment]
Is it possible for us to view bamboo CI??

**Comment by philwebb** [comment]
@rajadileepkolli Not the Bamboo settings I'm afraid. They're all locked down.

**Comment by snicoll** [comment]
@rajadileepkolli the build is here: https://build.spring.io/browse/BOOT-PUB - It went fine so I'll go ahead and merge this one.

**Comment by ton3r** [comment]
I've tested to set up JSF (Mojarra) with the currently Spring-Boot (1.5.6.RELEASE) and try to create an executable .war file with spring-boot-maven-plugin and the repackage goal.

The problem is that the application within this .war starts up but got problem to initialze. After some days of tests and tests and debug, I finally switch down the Spring-Boot Releases and the last working Version for "executable .war Files" is 1.5.2.

May be the change to Maven 3.5 brings this behavior. Currently I can't find the final _error/bug/reason_ for this behavior.

Easiest way to test is to check out this example (and disable the theme in pom and JSFConfiguration.class)

https://github.com/cenobyte321/Spring-Boot-JSF-Example

https://stackoverflow.com/questions/46079645/spring-boot-with-jsf-in-a-executable-war-java-io-filenotfoundexception-jar-e/46101210#46101210

execute 

```
mvn -Dmaven.test.skip=true clean install spring-boot:repackage
java -jar target/application-0.0.1-SNAPSHOT.war
```

everything works fine, it starts and one can call it in the browser

Then change the spring-boot parent dependency to something `>= 1.5.3.RELEASE` and do the same. You will find the exception during startup.

`"java.util.concurrent.ExecutionException: javax.faces.FacesException: java.io.FileNotFoundException: JAR entry META-INF/ not found in /var/folders/gj/...."`

**Comment by wilkinsona** [comment]
@ton3r The version of Maven with which Boot is built will have no effect here. Your example will be using whatever version of Maven you have installed. If you believe you've found a bug, please open a new issue with a minimal sample that we can easily run to reproduce the problem. Unfortunately we don't have time to take a sample and change it, particularly as there's no guarantee that we'll make the exact changes that are necessary to reproduce the behaviour you're seeing.

**Pull request closed without merging**
