### PR TITLE
Update list of default internal proxies in Web Server howto

### PR DESCRIPTION
**Pull request by dalbani**
The documentation lags a bit behind the code in terms of default internal proxies.
I was using IPv6 and it took me some time to figure out what was going on.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Rather than updating the list of internal proxies here, which may get out of sync again, I think it would be better to link to [the documentation for `server.tomcat.remoteip.internal-proxies`](https://docs.spring.io/spring-boot/docs/2.5.x/reference/htmlsingle/#application-properties.server.server.tomcat.remoteip.internal-proxies) which lists its default value. While the regular expression isn't quite as easy to read, I think that's outweighed by the fact that it'll always be accurate. If you agree, would you like to update your proposal to make that change?

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Rather than updating the list of internal proxies here, which may get out of sync again, I think it would be better to link to [the documentation for `server.tomcat.remoteip.internal-proxies`](https://docs.spring.io/spring-boot/docs/2.5.x/reference/htmlsingle/#application-properties.server.server.tomcat.remoteip.internal-proxies) which lists its default value. While the regular expression isn't quite as easy to read, I think that's outweighed by the fact that it'll always be accurate. If you agree, would you like to update your proposal to make that change?

**Comment by dalbani** [comment]
Yes, sure, I will do as you suggested. I agree that it's a better to link to the reference documentation.

**Comment by dalbani** [comment]
I have now provided a link to the "Server Properties" section and the name of the property to look for.
I'd have preferred providing a direct link to the property, but I couldn't find out how to do it.  
I tried a reference like `<<application-properties#appendix.application-properties.server.server.tomcat.remoteip.internal-proxies>>` but it couldn't be resolved.  
Probably related to the fact that AsciiDoc sections in `appendix.application-properties` are dynamically generated??

**Comment by dalbani** [comment]
Good to see how you implemented it in the end, thanks for the tip! 👍

**Pull request closed without merging**
