### PR TITLE
Fix Assert isDirectory in addSourceFolder()

### PR DESCRIPTION
**Pull request by herrminni**
Fix Assert for checking if added source folder is a directory.

Can be reproduced if one adds an additional path in application.properties, for example:
spring.devtools.restart.additional-paths=src/main/webapps

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. Can you please explain what problem you're trying to fix? The change you have made looks wrong to me as it will cause `addSourceFolder` to only accept a `folder` that is not a directory.

**Comment by wilkinsona** [comment]
The Travis build also shows test failures as a result of your change. Did you run the build prior to submitting this PR?

**Comment by herrminni** [comment]
Hi wilkinsona,

in general I tried to add external sources like a "webapps" folder, that is not an the classpath to be detected for changes for the "LiveReload" Server.

The problem occurred when I added the following line in application.properties:
`spring.devtools.restart.additional-paths=src/main/webapps`

While I was in the debugger, the problem seemed to be trival, that the assert check was the opposite of what wanted to be checked. 
So I tried to fix it quickly on github directly (as it seemed trivial)

I'm now checking out the complete project into eclipse and try to reproduce and fix the issue

**Comment by herrminni** [comment]
Hi wilkinsona,
sorry, that was my fault!

I tried to add a folder that did not exist.
As the error said, that the given folder was not a directory, I misunderstood the assert.

I would like to suggest to add an additional assert _before_ the `folder.isDirectory()`check:
`Assert.isTrue(folder.exists(), "Folder does not exist");`

Maybe this additional check helps if someone mistyped the directory name, like me :)

Sorry for the inconvenience!
Should I add an other pull request with this `folder.exists()`  assert?

**Comment by wilkinsona** [comment]
Another PR, or a forced push to this one, would be much appreciated. I'd keep the single `folder.isDirectory()` check (it checks that the `File` exists _and_ that it's a directory) and reword the assertion message to make it clear that `folder` must exist and must be a directory.

**Pull request closed without merging**
