### PR TITLE
Fix MustacheEnvironmentCollector to not ignore native fetcher

### PR DESCRIPTION
**Pull request by dsyer**
When the context is a map (as it is in a web View for instance) you can't
assume a non-null fetcher actually contains the property you are searching
for. This change alters the logic so that the native fetcher is always
consulted if it exists, but there is always a fallback.

Fixes gh-21045

### CODE REVIEW

**Comment by dsyer** [comment]
CI failures look unrelated to me?

**Comment by wilkinsona** [comment]
> CI failures look unrelated to me?

Confirmed. The latest Micrometer 1.5 snapshots have broken our build.

**Comment by dsyer** [comment]
UPDATE: this patch is not complete. It fails to resolve `_csrf.token` in a basic Spring Security app. I'll try and fix that.

**Comment by philwebb** [comment]
I'm tempted to just apply this to 2.3.x rather than the older branches. Any objections @dsyer?

**Comment by dsyer** [comment]
No, I don’t think so.

**Comment by snicoll** [comment]
There is an unrelated change in `.gitignore` that should be removed.

**Comment by dsyer** [comment]
I left it as a separate commit so you can leave it out easily if you want.

**Comment by philwebb** [comment]
Thanks @dsyer! I pulled the ignore commit out and applied it to 2.1.x onwards. The Mustache fix is just on 2.3.x+.

**Pull request closed without merging**
