### PR TITLE
Add configuration properties for remaining Undertow server options

### PR DESCRIPTION
**Pull request by rhamedy**
Added remaining Undertow's server configuration parameters. See the issue for ongoing discussion.

Fixes gh-16077

### CODE REVIEW

**Comment by rhamedy** [comment]
Resolved the `conflict` caused by `2.1.x` release! Rebased, and resolved the conflicts 👍

**Comment by wilkinsona** [comment]
@rhamedy Thank you very much for making your first contribution to Spring Boot. I have merged to proposed changes in to master along with a [polish commit](https://github.com/spring-projects/spring-boot/commit/ca1a666f58ac3587a6ad67d0a27c5ab6c93be910). The polish addressed three main things:

1. Updated the javadoc of the new properties to match the style of the rest of the codebase
2. Switched to primitives and provided default values for the new properties where appropriate. This means that the default values are available in the configuration property metadata
3. Improve the test coverage as I noticed that you'd [accidentally configured the max header size using the max post size](https://github.com/spring-projects/spring-boot/pull/16278/files#diff-f236831a196e857440aa8081583e4691R98) but our existing tests hadn't caught it

**Comment by rhamedy** [comment]
@wilkinsona thanks for the polish and for describing your changes. The tests and changes look much better. The PR was definitely not `final` version and in my mind I thought there will be a `review/feedback` of some sort which would give me another opportunity to improve my changes. I am happy with my first contribution 🙂

**Comment by wilkinsona** [comment]
Sorry for not giving you another opportunity to improve your changes. I hope you'll contribute again and, if you do, please feel free to remind us that you'd like another opportunity to improve things if needed rather than us polishing and merging. You could use GitHub's new support for [draft pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to give us another reminder.

**Pull request closed without merging**
