### PR TITLE
Fix escaping of pipe character in reference tables

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

while working on #18371 I noticed that there are some issues with the handling of `|` inside tables in the reference docs. Here's a list of issues that I found, but there might be more:

- The default value of `server.tomcat.internal-proxies` shows `{vbar}` in both HTML and PDF reference instead of `|`
- The description of `server.tomcat.relaxed-path-chars` breaks the table formatting completely in the PDF version
- The description of `server.tomcat.relaxed-query-chars` breaks the table yet another time ;-)

It seems that neither of the escaping strategies work for both HTML and PDF. Luckily, the docs under https://asciidoctor.org/docs/user-manual/#escaping-the-cell-separator provide a third option.

> The cell separator is controlled using the separator attribute on the table block. You’ll want to select a character that will never be used for content. A good candidate is the broken bar, or ¦

Applying this seems to fix the issues mentioned above.

Let me know what you think.
Cheers,
Christoph

### CODE REVIEW

**Comment by snicoll** [comment]
> breaks the table formatting completely in the PDF version

@dreis2211 just to make sure I understand this one. I've generated a PDF from `master` (with your latest fix to include the appendices) and I don't see an obvious problem for the two keys you've mentioned. I can see the `{vbar}` though.

What have I missed?

**Comment by dreis2211** [comment]
Interesting. Now I can't reproduce this either anymore. I should have taken a screenshot. Maybe an error on my side by not (re-)compiling `spring-boot-configuration-docs` properly beforehand. Sorry for the confusion.

"At least" the `{vbar}` problem remains. But this gets me thinking if a simple escaping with `\|` might work after all. Give me a minute to try this.

**Comment by dreis2211** [comment]
@snicoll The simpler escaping with `\|` seems to work indeed. Could you give it another try whenever you have a spare minute, please?

**Comment by dreis2211** [comment]
Test failure seems unrelated

**Pull request closed without merging**
