### PR TITLE
Add Thymeleaf sample

### PR DESCRIPTION
**Pull request by Lisanaaa**
Thymeleaf is a modern server-side Java template engine for both web and standalone environments.
I develop a very starting-based guide to implement Thymeleaf in Spring Boot Web as a sample. 
This is the first time I contribute to Spring, so if there is any layout or typesetting problems, please let me know. Thanks for all the contributors and maintainers of Spring Boot!

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Lisanaaa Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=13536)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=13536) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Lisanaaa Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=13536)!

**Comment by wilkinsona** [comment]
Thanks for opening your first Spring Boot pull request. We already have a number of samples that use Thymeleaf, but their names don't make it clear that they do. Of those samples, `spring-boot-sample-web-ui` is the one that's most focussed on Thymeleaf. Rather than adding another sample, I think we could just rename that one.

Labeling for team attention to see what the rest of the team think.

**Comment by Lisanaaa** [comment]
I download the `spring-boot-sample-web-ui` and run it. But I got some thing wrong, 

`org.thymeleaf.exceptions.TemplateProcessingException: Could not parse as fragment selection: "fragments :: head(title=~{::title/text()})" (messages/list:3)
	at org.thymeleaf.standard.expression.FragmentSelectionUtils.parseFragmentSelection(FragmentSelectionUtils.java:106)
	at org.thymeleaf.standard.fragment.StandardFragmentProcessor.computeStandardFragmentSpec(StandardFragmentProcessor.java:73)
	at org.thymeleaf.standard.processor.attr.AbstractStandardFragmentHandlingAttrProcessor.computeFragment(AbstractStandardFragmentHandlingAttrProcessor.java:68)
	at `
And I think a more clear and easier guide is better for the newbies. No matter what's the next step, I will still contribute. Be in this Spring family.

**Comment by philwebb** [comment]
> And I think a more clear and easier guide is better for the newbies

Our samples are somewhat misnamed, we mainly use them to test the integrity of the release. Perhaps we should look at assing a dedicated Thymeleaf sample to spring.io/guides. The repo for that project is https://github.com/spring-guides

**Comment by wilkinsona** [comment]
There's an [existing Spring MVC and Thymeleaf guide](https://spring.io/guides/gs/serving-web-content/).

**Comment by wilkinsona** [comment]
We discussed this yesterday, and decided that what's being proposed here is already covered by the existing guide. I've opened https://github.com/spring-guides/gs-serving-web-content/issues/24 to hopefully make it a bit clearer that the guide uses Thymeleaf. We've decided not to rename our existing web UI sample as it doesn't focus specifically on Thymeleaf but also uses Bootstrap etc.

**Pull request closed without merging**
