### PR TITLE
Upgrade to Hibernate Validator 6.0.2.Final

### PR DESCRIPTION
**Pull request by rajadilipkolli**
Hibernate Validator 6.0 Final comes with Bean Validation 2.0 support, this PR updates Hibernate Validator to latest version

### CODE REVIEW

**Comment by rajadilipkolli** [comment]
@spring-issuemaster travis build failure is not related to this PR, can you restart it?

**Comment by wilkinsona** [comment]
Thanks for the PR. I'm going to put this one on hold for now as there are still some decisions to be made about Hibernate Validator 6 that are being tracked by #9784.

**Comment by rajadilipkolli** [comment]
Once 6.0.2 is in maven repository we need to upgrade to [this](http://in.relation.to/2017/08/22/hibernate-validator-602-final-out/) version

**Comment by wilkinsona** [comment]
@rajadileepkolli Thanks again for the PR. It looks like we can proceed with the upgrade to Hibernate Validator 6 in M5. To make sure that no Hibernate Validator 5 or earlier dependencies creep in, can you please update the [configuration of the enforcer plugin's excluded dependencies](https://github.com/spring-projects/spring-boot/blob/26b93e9454cdd8c7a49765e5a0e42ff0e4fa4a00/spring-boot-starters/pom.xml#L94-L96)?

**Comment by snicoll** [comment]
That broke the build, I am looking at it

**Comment by wilkinsona** [comment]
The build is still broken. The Glassfish deployment test is failing because it's using the Validation API from the container rather than the deployed war. There's the first app server deployment test that runs. The others may well be broken too.

**Pull request closed without merging**
