### PR TITLE
Add InfluxDB exporter to Actuator

### PR DESCRIPTION
**Pull request by mklimasz**
Since 5688 issue wasn't done for a while, I decided to make my first contribution since I'm working on such configuration anyway.

Configurable implementation of gauge writer to export metrics into InfluxDB.

Fixes gh-5688

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks!

**Comment by philwebb** [comment]
I polished this a little [here](https://github.com/philwebb/spring-boot/tree/gh-7351). I'm wondering if we should strip out the `Builder`. It seems a little unnecessary since you can just configure `InfluxDB` directly. It's also not really a builder since it modifies the existing `InfluxDB` instance and doesn't create a new one.

**Comment by mklimasz** [comment]
My goal was to make clean configuration wrapper to avoid working on pure influxdb-java library.
But I guess, Builder isn't mandatory and can be removed or InfluxDB instance can be created inside builder.

**Comment by philwebb** [comment]
Unfortunately I need to de-scope some issues targeted for Spring Boot 1.5. I'd like to push this back since we want to review metrics in general.

**Comment by mklimasz** [comment]
When you finish review metrics and you will find consensus, you can ping me here and I can remake this in correct way.

**Comment by izeye** [comment]
This looks superseded by #9970 as this is for #5688 which has been already superseded.

**Comment by snicoll** [comment]
Indeed, thanks @izeye !

**Pull request closed without merging**
