### PR TITLE
Add a ConcurrentCompositeHealthIndicator

### PR DESCRIPTION
**Pull request by RikEnde**
See https://github.com/spring-projects/spring-boot/issues/2652

I submitted a PR for this issue before, but it wasn't very good. I hope this one is better. 

**Problem:** 
Right now, invoking the health endpoint lead to a synchronous invocation of all underlying HealthIndicator instance(s) that have been configured. It would be nice to offer an option to run these in parallel instead.

**Real world example:**
I have a number of HealtIndicator components that poll remote systems and report on latency and status, and the latency really adds up, especially if there are time-outs involved.

**Solution:**
This PR adds a ConcurrentCompositeHealthIndicator that can run the HealthIndicator instances on the  ThreadPoolTaskExecutor. 

Usage in code:
```
    @Bean
    public HealthEndpoint healthEndpoint(HealthAggregator healthAggregator,
                                         HealthIndicatorRegistry registry,
                                         ThreadPoolTaskExecutor executor
                                         ) {
        return new HealthEndpoint(
            new ConcurrentCompositeHealthIndicator(healthAggregator, registry, executor, Duration.ofMillis(1100)));
    }
```

### CODE REVIEW

**Comment by snicoll** [comment]
@rikende did you mean to close this PR?

**Comment by RikEnde** [comment]
While working on this, I found it could be solved at the application level once we move to spring boot 2.1.x

**Comment by CLOUGH** [comment]
@RikEnde  could you share the workaround that you found.

**Comment by RikEnde** [comment]
> @RikEnde could you share the workaround that you found.

Sure, but keep in mind this hasn't been touched in 2 years, it probably won't work for the latest version of spring boot https://github.com/RikEnde/concurrent-actuator-test.git

**Comment by RikEnde** [comment]
> @RikEnde could you share the workaround that you found.



> @RikEnde could you share the workaround that you found.

The code from this PR could be implemented entirely in domain code, requiring no framework changes. However, this was 2 years old. It doesn't even compile against the current version.

**Pull request closed without merging**
