### PR TITLE
Handle StepRegistry connect/read timeout deprecation

### PR DESCRIPTION
**Pull request by ayudovin**
this [enhancement](https://github.com/spring-projects/spring-boot/issues/14855)

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. It looks like you've implemented the second of the [two options that @snicoll listed](https://github.com/spring-projects/spring-boot/issues/14855#issuecomment-430282929) but haven't addressed the mapping of the deprecated properties. I'm [not yet sure](
https://github.com/spring-projects/spring-boot/issues/14855#issuecomment-431038614) what to do about that. Will need to figure that out before we can proceed here.

**Comment by ayudovin** [comment]
@wilkinsona , hi, do you have any updates about this pull request ?

**Comment by wilkinsona** [comment]
@ayudovin We've decided to remove the mappings of the deprecated properties from Boot's various config adapters. Time is tight with 2.1.0.RELEASE due tomorrow. Do you have time to update your PR today? No problem at all if not, we can take care of the additional changes as part of merging this.

**Comment by ayudovin** [comment]
@wilkinsona,  I updated pull request, I hope that I understood your suggestion correct.

**Comment by wilkinsona** [comment]
Thank you for your work on this, @ayudovin. I've merged the changes into master with a [polish commit](https://github.com/spring-projects/spring-boot/commit/290e8886c92b75c50cfd986ef79ffb512164d5e7) that changes the auto-configurations so that their properties are injected once into the class rather than twice into two separate `@Bean` methods.

**Comment by ayudovin** [comment]
@wilkinsona, thank you,I absolutely agree with your polish commit.

**Pull request closed without merging**
