### PR TITLE
Reintroduce support for ActiveMQ

### LINKED ISSUE #34011: Reintroduce support for Active MQ
ActiveMQ developer Jean-Baptiste Onofré says:

> FYI, we will include jakarta/JMS2 client in ActiveMQ 5.18.x (currently
> in preparation).

When this is released, please restore an activemq starter for Spring boot 3.0.

In our case, "move to artemis" is not an option as we use Amazon MQ which is currently ActiveMQ classic/RabbitMQ only.

Matt Pavlovich on the activemq users list has produced a jakarta based build from the 5.18.x branch

[activemq-client-jakarta](https://github.com/hyteio/activemq-client-jakarta)

[AMQ-9170](https://issues.apache.org/jira/browse/AMQ-9170)

### PR DESCRIPTION
**Pull request by bendiscz**
Adds ActiveMQ starter using the new `activemq-client-jakarta:5.18.1` ActiveMQ client library that supports JMS 3.0.

Most of this patch is based on reverting commit 63492507b437d1d5a14bbbb4056b27d4166120ce and removing embedded in-memory broker support. The embedded broker support is being worked on for ActiveMQ 5.19.x.

Partially fixes #34011.

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks again @bendiscz. I restored the smoke test using Testcontainers.

**Comment by spencergibb** [comment]
It is here, at least: https://github.com/spring-projects/spring-boot/releases/tag/v3.1.0-RC1

**Comment by scottfrederick** [comment]
It looks like we missed this in the Spring Boot 3.1.0-RC1 release notes, so it wasn't included in the consolidated 3.0 release notes. I've added it here: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1-Release-Notes#activemq-support

**Comment by wilkinsona** [comment]
I've opened https://github.com/spring-io/start.spring.io/issues/1194 to update start.spring.io.

**Comment by r0main** [comment]
Hi,

Thanks a lot all for your reactivity. Looking at @wilkinsona comment here spring-io/start.spring.io#1194 I understand that the support for ActiveMQ is only partial ? Or am I wrong ? 

From the comment I understand that this PR reintroduced support of ActiveMQ for applications connecting to a remote ActiveMQ ? Does this mean that if I have a Spring Boot 2.7 application instantiating an embedded ActiveMQ I can't migrate to Spring Boot 3.1 ? 

Thanks for the clarification !

Best regards,
Romain

**Comment by wilkinsona** [comment]
>  Does this mean that if I have a Spring Boot 2.7 application instantiating an embedded ActiveMQ I can't migrate to Spring Boot 3.1 ?

Yes. ActiveMQ only supports the jakarta.jms APIs in its client APIs at this time. The embedded broker still uses javax.jms so it isn't Jakarta EE 9+ compatible. As @bendiscz said above, the embedded broker side of things is being worked on for ActiveMQ 5.19.x.

**Comment by r0main** [comment]
Oh yes you're right I missed this part ! Thanks a lot again for reactivity.

**Comment by sukanth** [comment]
@snicoll do you know when activemq-broker 5.19.x is going to be released with activemq broker support with jakarta ?

**Comment by philwebb** [comment]
@sukanth We have no insight into the ActiveMQ project, you would need to ask them.

**Comment by r0main** [comment]
@sukanth FYI I found this on ActiveMQ mailing list : https://lists.apache.org/list?users@activemq.apache.org:lte=1M:wildfly

image

@snicoll if ActiveMQ Classic 5.19.X is released in September. Do you think Spring Boot could reintroduce the support of the ActiveMQ broker in Spring Boot 3.2 ?

**Comment by r0main** [comment]
Hi,

Ok sorry about the screenshot. I'm commenting on this issue because Spring Boot 3.1 only reintroduced the support of ActiveMQ client. Support of ActiveMQ broker is still missing waiting for the 5.19.X release of ActiveMQ (which will support Jakarta).

**Comment by snicoll** [comment]
I think "embedded" is quite crucial to understand what you were talking about. This issue is closed, ActiveMQ 5.19 isn't released yet so there isn't anything actionable at this time. We'll do our best based on what's available when it'll be.

**Comment by kedaniilakis** [comment]
Is spring going to support ActiveMQ "classic" longterm or is there a tendency towards ActiveMQ-Artemis? This information would be helpful to decide if we want to remove activeMQ-classic in favor of artemis which already supports the jakarta migration.

**Comment by snicoll** [comment]
@kedaniilakis The answer should be provided by the ActiveMQ team, not us. As long as ActiveMQ classic is supported and we can support it consistently with our dependency management, I don't see a reason to drop support. The indication that we've restored support once they complete the Jakarta migration should be a good indicator of that.

**Comment by mattrpav** [comment]
Hi- @kedaniilakis @snicoll I'm leading the Jakarta support for ActiveMQ 5.x. 

The short answer is 'yes'. ActiveMQ 5.x will support Jakarta and be able to be fully brought back into Spring 6. The PR for broker support is code complete and in-review. We are targeting a September release for ActiveMQ 5.19.0 with Jakarta support.

ref: [ActiveMQ server-side Jakarta support PR](https://github.com/apache/activemq/pull/996)

**Comment by kedaniilakis** [comment]
@mattrpav Is there a release plan about the 5.19? You are targeting a September release, do you know if it is the beginning-mid-end of September? Thank you for your answers

**Comment by mattrpav** [comment]
@kedaniilakis the big Jakarta PR is in final review with tentative plans to merge next week. After that 1-2 weeks to do any minor clean-up tasks and cut release. Mid-September is a reasonable estimate.

**Comment by kedaniilakis** [comment]
Is there any news regarding this? I read here https://activemq.apache.org/new-features-in-60 that 
Once Artemis reaches a sufficient level of feature parity with the 5.x code-base it will become ActiveMQ 6. Initial migration documentation is available.

Will the 5.19 actually be released or is the 6.x.x the new version?

**Comment by snicoll** [comment]
Can you please stop asking here about the release plan of another project. Direct this discussion to the ActiveMQ team. I know @mattrpav is watching but this discussion does not belong here.

**Comment by mattrpav** [comment]
@kedaniilakis the release for Jakarta-based ActiveMQ 5.x is planned to be avail shortly. Next 1-2 weeks. All the Jakarta work is code complete.

**Pull request closed without merging**
