### PR TITLE
Upgrade to Elasticsearch 2.3.3

### PR DESCRIPTION
**Pull request by jloisel**
- [X] I have signed the CLA

Elasticsearch 2.3.3 is the latest available version:
https://www.elastic.co/guide/en/elasticsearch/reference/2.3/es-release-notes.html

### CODE REVIEW

**Comment by snicoll** [comment]
I think @wilkinsona prefers to use whatever Spring Data brings and I can see it's 2.2.0 for now (which is not what we use) so maybe I misunderstood that statement.

**Comment by jloisel** [comment]
Maybe Spring data should be updated then? It shouldn't be difficult, there are just minor API changes between 2.2.0 and 2.3.3.

**Comment by wilkinsona** [comment]
Generally speaking we stick to the same minor version as Spring Data uses. In this case, that means sticking with 2.2.x unless the Spring Data team indicate that 2.3 is supported as well.

@olivergierke @mohsinh Is Spring Data Elasticsearch compatible with Elasticsearch 2.3? Should we move to 2.3.x in Boot 1.4?

**Comment by mohsinh** [comment]
Hello, 

We have upgraded the elasticsearch library to 2.3.3. 

This will be available in Hopper SR2 release. And Ingalls M1.

More information can be found at [DATAES-262](https://jira.spring.io/browse/DATAES-262)

**Comment by jloisel** [comment]
:+1:

**Comment by olivergierke** [comment]
I'd like to revert the commit for the maintenance branch as upgrading a minor version within service releases contradicts our dependency version policy. I suggest we rather create a build profile for 2.3 to make sure Spring Data Elasticsearch is generally compatible with 2.3 so that Boot can actually use it by default.

**Comment by mohsinh** [comment]
@olivergierke It seems like you have already removed it from the maintenance branch, Thanks !

**Comment by akonczak** [comment]
Hi All
 
The current code in master and SR2 is compatible with elasticsearch 2.3.3 as default(I have test that against 1.4.M3).
You will need only to change ES library version.

We need only remember that ES can use modules for embedded server and modules are compatible per version of ES(we are shipping Spring Data Elasticsearch without any modules so we are save).
The changes in the master are to ensure that tests are passing for groovy scripting language for 2.3.3.

**Comment by wilkinsona** [comment]
>  I suggest we rather create a build profile for 2.3 to make sure Spring Data Elasticsearch is generally compatible with 2.3 so that Boot can actually use it by default.

I like this idea a lot. Has it happened?

**Comment by akonczak** [comment]
I'm not sure if this will work for us. 
Spring Data Elasticsearch - master is already using 2.3.3 ES.

SR is using ES 2.2.0, I can add profile but that require changes in the code directly to ensure that tests are using proper path to version of plugins designed for ES 2.3.3(base on selected profile).

@olivergierke 
Do you think that we can add this into SR and its worth it ?

**Comment by olivergierke** [comment]
I was thinking of a build profile to add to the `pom.xml` that just tweaks the dependency version to a recent 2.3.x. Even if that's just maintained in the maintenance branch for Hopper, it would allow us to run CI builds with that profile.

**Comment by snicoll** [comment]
@wilkinsona and I discussed this and we're ok to use that version for 1.4. Having that build profile would be very nice!

**Comment by akonczak** [comment]
@olivergierke , @wilkinsona

I have modified SR branch and added profile 'es2.3.3' to build Spring Data Elasticsearch with ES 2.3.3.

**Pull request closed without merging**
