### PR TITLE
Polish reference documentation

### PR DESCRIPTION
**Pull request by 724thomas**
This pull request addresses a series of minor typos and phrasing inconsistencies identified in few sections of documentation. Primary objective is to enhance overall clarity and readability of documentation, enhancing the user experience for developers and contributors.

The modification encompasses the following documentation files:
- batch.adoc
- data-initialization.adoc
- docker-compose.adoc
- logging.adoc
- nosql.adoc
- security.adoc
- testing.adoc

I have reviewed and updated these files so that the language is precise, clear and consistent.

Impact Assessment:
These changes are confined exclusively to documentation content.
There is no impact on the functional aspects of the code.

### CODE REVIEW

**Comment by philwebb** [comment]
@724thomas Did you mean to close this one?

**Comment by 724thomas** [comment]
> @724thomas Did you mean to close this one?

yes. It's been 2weeks and thought that I might've done something wrong..?

**Comment by philwebb** [comment]
If you can reopen it that would be great. There's nothing wrong, we just haven't got around to merging it yet.

**Comment by 724thomas** [comment]
> If you can reopen it that would be great. There's nothing wrong, we just haven't got around to merging it yet.

oh, good to know :) I will be patient.
I reopened the pr request

**Comment by philwebb** [comment]
Thanks very much @724thomas, I've merged this to 3.2.x and forward. I did change "in the classpath" back to "on the classpath" since that's the common phasing in my experience.

**Comment by 724thomas** [comment]
> Thanks very much @724thomas, I've merged this to 3.2.x and forward. I did change "in the classpath" back to "on the classpath" since that's the common phasing in my experience.

Thank you for the review @philwebb

**Pull request closed without merging**
