### PR TITLE
Update the Debugging Documentation of the Spring Boot Maven Plugin 

### PR DESCRIPTION
**Pull request by lukasdo**
Replaced the old JVM Argument -Xdebug (which does nothing according to documentation) with newer ones as described in  #39388.

### CODE REVIEW

**Comment by wanger26** [comment]
Should we update the test for [parseDebugFlags](https://github.com/spring-projects/spring-boot/blob/d4affd7f851c318decd7da1eee71e12ec9c0e6d3/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/test/java/org/springframework/boot/maven/RunArgumentsTests.java#L65-L71) as well as the [running-your-application](https://github.com/spring-projects/spring-boot/blob/c416c17fe85507e82ea172d43b54086a1a8d02a4/spring-boot-project/spring-boot-docs/src/docs/asciidoc/using/running-your-application.adoc#L38-L45) doc to reflect this change?

**Comment by lukasdo** [comment]
I added another commit for the [running-your-application](https://github.com/spring-projects/spring-boot/blob/c416c17fe85507e82ea172d43b54086a1a8d02a4/spring-boot-project/spring-boot-docs/src/docs/asciidoc/using/running-your-application.adoc#L38-L45) documentation. 

An updated `parseDebugsFlags` test could look like this:
```	@Test
	void parseDebugFlag() {
		String[] args = parseArgs("-agentlib:jdwp=server=y,transport=dt_socket,address=8000,suspend=n");
		assertThat(args).hasSize(1);
		assertThat(args[0]).isEqualTo("-agentlib:jdwp=server=y,transport=dt_socket,address=8000,suspend=n");
	}
```

I am not really sure if that would make sense as it would be just testing if one argument is parsed correctly which is also tested in e.g. `parseWithExtraSpaces`. If desired I could update this test or delete it completely.

**Comment by wanger26** [comment]
Excellent, thank you 💯  It might be worth updating the test to ensure that the parsing works as expected in cases changes are made in the parser in the future.

**Review by wanger26 — COMMENTED** [review]
LGTM 🚀

**Comment by mhalbritter** [comment]
Thank you very much and congratulations on your first contribution :tada:!

**Pull request closed without merging**
