### PR TITLE
#2805 Improved configuration options for node client

### PR DESCRIPTION
**Pull request by akonczak**
For more information please check issue #2805

### CODE REVIEW

**Comment by rreitmann** [comment]
When will this be merged? I would like to run a non-local elasticsearch node and this change would make this possible for me without disabling auto configuration.

**Comment by philwebb** [comment]
We discussed this today and plan to merge before we release M2

**Comment by rreitmann** [comment]
Thx! That is great news for me :+1:

**Comment by philwebb** [comment]
Thanks, I reworked the code a little to keep the previous defaults if override properties aren't provided.

**Comment by philwebb** [comment]
@akonczak could you sign the CLA if you haven't already.

**Comment by akonczak** [comment]
@philwebb I did that long time ago.

**Comment by philwebb** [comment]
Thanks.

**Pull request closed without merging**
