### PR TITLE
Issue 3136: maven plug-in to create output directory if does not exist

### PR DESCRIPTION
**Pull request by lcardito**
Hi guys,

just wrote those 2 lines to provide the enhancement describe in [issue 3136](https://github.com/spring-projects/spring-boot/issues/3136).
 
I had a quick think about unit testing the method but to do so I'd like to change the modifier from private to protected so that I can call it from the test class. Is it something that might help or you prefer a more integration approach?

Cheers,
Luigi

### CODE REVIEW

**Comment by snicoll** [comment]
That PR looks weird :) You should have created a branch from a clean update of master (looks like you tried to merge our master instead of rebasing it). 

That being said, I have the commit with the change and if you've tested that and you're happy it's already a lot. Have you signed [the CLA](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)? Thanks!

**Comment by snicoll** [comment]
Actually, I take it back. Your commit is hidden behind the merge commit. It's a two liner so I could just add that by myself but I'd prefer that you keep your contribution. Could you please create a branch in your fork from a clean master copy and then push force on this branch? This will update the PR automatically. Let me know when you're done. Thanks.

**Comment by lcardito** [comment]
Oh ok! Apologies for that. I'll do it this evening and let you know. 

Thanks!

**Comment by lcardito** [comment]
Hi @snicoll ,
This should be done now. Let me know if it looks better :)
Thank you very much for your help!

**Comment by snicoll** [comment]
Yup, it does. Thanks a lot, I'll process it tomorrow.

**Comment by snicoll** [comment]
Merged with some modifications, thanks!

**Pull request closed without merging**
