### PR TITLE
Fix a range check when extracting a virtual host in `RabbitProperties`

### PR DESCRIPTION
**Pull request by izeye**

### CODE REVIEW

**Comment by philwebb** [comment]
We could also do with a test when we merge this

**Comment by wilkinsona** [comment]
@izeye. Thanks for the PR, but I don't think the range check isn't a problem. If the address ends with `/` the substring call successfully produces an empty string. With the change proposed here, the substring never happens and the `/` is left on the end of the address. This can result in a `NumberFormatException` when attempting to parse the port.

I think what needs to happen is for the empty string to be mapped to a `/`. This would make the behaviour consistent with `setVirtualHost`. I've opened #3304.

**Comment by garyrussell** [comment]
@wilkinsona @philwebb  Please note that, since https://github.com/spring-projects/spring-boot/commit/e3a124d0f9c8a819b9148dcdfb4f5ce5a6efd31f , it's no longer necessary for boot to parse the URI - since the `RabbitConnectionFactoryBean` exposes a `setUri()` method, the URI can be passed directly to Rabbit and he will parse it. cc/ @snicoll

**Comment by wilkinsona** [comment]
Thanks for the tip, @garyrussell. I've opened https://github.com/spring-projects/spring-boot/issues/3328.

**Pull request closed without merging**
