### PR TITLE
Added helpful logging for people running into IntelliJ bug IDEA-107048, see https://youtrack.jetbrains.com/issue/IDEA-107048

### PR DESCRIPTION
**Pull request by rolfchess**
Added helpful logging for people running into IntelliJ bug IDEA-107048, see https://youtrack.jetbrains.com/issue/IDEA-107048

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks. Have you [signed the CLA](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#sign-the-contributor-license-agreement)?

**Comment by rolfchess** [comment]
I signed it just now.

**Comment by philwebb** [comment]
Cool. Thanks!

**Comment by wilkinsona** [comment]
The proposed log message isn't 100% accurate. The bug that's referenced is still open so the problem also applies to all 15.0.2+, not just 15.0.1 and earlier (and the 16 EAP, AFAIK).

More generally speaking, I'm not keen on adding the message at all. Why is this particular problem with IDEA receiving special treatment? There are, I'm sure, many bugs in third-party code that we could add special message for. Where should we draw the line?

**Comment by snicoll** [comment]
I am not keen on adding it either. I think the problem is that it's hard to track the problem is in the tools and not in Spring Boot itself. Maybe we could fix the exception message instead?

**Comment by rolfchess** [comment]
It is indeed not a defect of spring-boot. The logging in this pull request is intended to help IntelliJ users who start out with spring-boot until Jetbrains fixes the actual problem. A clearer exception message may be a better and more future-proof fix, I'm open to suggestions.

**Comment by philwebb** [comment]
After some consideration we've decided that we'd rather not add product specific log messages. Although it seems like a good idea, there are lots of other reasons why this exception could be thrown and adding a specific message could be confusing in those cases. We also don't really want to start adding specific code paths for issues that should ultimately be fixed upstream.

Hopefully people searching for the problem will find this issue, or the [stackoverflow answer](http://stackoverflow.com/a/30241983/1526192) until [IDEA-107048](https://youtrack.jetbrains.com/issue/IDEA-107048) gets fixed.

**Pull request closed without merging**
