### PR TITLE
Added information about Infinispan Starter

### PR DESCRIPTION
**Pull request by slaskawi**
Hey!

This is just a minor tip for the users looking for more information about Infinispan integration bits.

For more information, please have a look at https://github.com/infinispan/infinispan-spring-boot/issues/17

Thanks,
Sebastian

### CODE REVIEW

**Comment by slaskawi** [comment]
Hey @snicoll!

Thanks for bringing this up!

I think we have similar implementation to some extend [[1](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/cache/InfinispanCacheConfiguration.java)][[2](https://github.com/infinispan/infinispan-spring-boot/blob/master/infinispan-spring-boot-starter-autoconfigure/src/main/java/infinispan/autoconfigure/embedded/InfinispanEmbeddedAutoConfiguration.java)]. Looking at [InfinispanCacheConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/cache/InfinispanCacheConfiguration.java) I can see that you're using only the embedded mode (`@ConditionalOnClass(SpringEmbeddedCacheManager.class)`). This is absolutely fine but Infinispan supports also Client/Server mode (which is the default for [Infinispan Spring Boot Starters](https://github.com/infinispan/infinispan-spring-boot/blob/master/infinispan-spring-boot-starter/pom.xml#L22)). Finally, it is even more complicated - you can use both in a single project (e.g. caching data locally and connect to a remote Infinispan cluster and treat it as a NoSQL datastore)!

Having said that I think we have a couple of options:

1. Leave it as is. A developer always have a choice. One can use the approach from Spring Boot or just add  yet another dependency. 
2. Add a dependency to Infinispan Spring Boot Starters and remove some bits from Spring Boot. This sounds like an easy thing to do but it would introduce some changes in Spring Boot dependencies. 
3. We also could do it another way around - put our starter into your codebase. But from historical perspective, we've never done this (all Spring integration bits have always been hosted in our repositories and unless there are some ground breaking arguments, we'd like to keep it this way). 

I would personally vote for option `#2`. You are already using a dependency to [Infinispan Core and Infinispan Spring modules](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/pom.xml#L299), so it shouldn't make any difference.

**Comment by slaskawi** [comment]
@snicoll Any update?

**Comment by snicoll** [comment]
I think we are considering removing our code and rely on your support instead. We can't have dependency management for your code, that would create a cycle. 

But maybe you can improve your auto config to react to the spring.config.type property? If you do and order your auto-configuration before ours you'd be covered i think.

**Comment by slaskawi** [comment]
That sounds sensible.

I created https://github.com/infinispan/infinispan-spring-boot/issues/23 to implement this. The only thing I would kindly ask to add on your side is some documentation which would guide users to our repository.

**Comment by snicoll** [comment]
Of course, we want to make sure our users can still use Infinispan. So we'll give the reference to your starter and links to your doc. What is the timeline for this? I'd like to flip the switch to Spring Boot 2.0. An early milestone would be ideal (first part of this year).

**Comment by slaskawi** [comment]
I would prefer to implement this for `2.0.0.Alpha1` (since `1.0.0` is in CR phase). 

I think it should be ready in a week or two. The timing seems to fit (I can see that [2.0 is scheduled](https://github.com/spring-projects/spring-boot/milestone/53) for the release in a week or two (assuming some slip)). I think it might be a good idea to align the starter to `2.0.0.M1`.

**Comment by snicoll** [comment]
@slaskawi in the end we decided to keep our code for users that are happy with that. I'll update the documentation to refer to your starter. 

Regardless, reacting to the type is a good thing (if a user has defined a dedicated cache type, you shouldn't configure Infinispan). I'll rework that PR, thanks!

**Comment by slaskawi** [comment]
Sounds good. Thanks!

**Comment by slaskawi** [comment]
Thank you @snicoll !

**Pull request closed without merging**
