### PR TITLE
Use default schema in actuator Liquibase endpoint

### PR DESCRIPTION
**Pull request by candrews**
The Actuator Liquibase endpoint should use the configured schema

Without this change, the endpoint won't work correctly if the application.properties configuration options `liquibase.defaultSchema` is used. An error such as:
>  org.h2.jdbc.JdbcSQLException: Table "DATABASECHANGELOG" not found; SQL statement:
> SELECT * FROM PUBLIC.DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC

will result.

### CODE REVIEW

**Comment by candrews** [comment]
@snicoll I've updated this PR with a test that passes with this change and fails without it.

**Comment by snicoll** [comment]
That test broke another test due to the change of configuration to `DataSourceAutoConfiguration`

**Comment by cforce** [comment]
will that move into sprig cloud Dalston.SR5 (spring boot 1.5.7)?

**Comment by philwebb** [comment]
@cforce 

> Will that move into spring cloud Dalston.SR5 (spring boot 1.5.7)?

Yes, this was merged into Spring Boot 1.5.7 (see the milestone label above)

> What will the default value for liquibase.default-schema be?

It's `null` [see this line](https://github.com/spring-projects/spring-boot/blob/c68173082d9b53fc64773bdbb8370c091fb8ebc9/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase/LiquibaseProperties.java#L54). 

> Will "public" work in cloud environment like PCF for mysql / postgresql with on demand service binding?

I don't know. You're best to ask this type of question on stackoverflow.com

**Pull request closed without merging**
