### PR TITLE
Add Spring Content Boot Starters

### PR DESCRIPTION
**Pull request by paulcwarren**
The DellEMC Dojo team would like to add our Spring Content project, that has boot-starters for its fs, s3, jpa, mongo and REST modules, to your README.

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks for the PR, I've created https://github.com/paulcwarren/spring-content/issues/8

**Comment by snicoll** [comment]
@paulcwarren any news about this?

**Comment by paulcwarren** [comment]
Since this would affect Customers the suggestion made here was to duplicate the boot-starter projects and update the documentation accordingly (to point at the correctly named set).  We'll deprecate the others but leave them for a release, or two.  

Would that be acceptable @snicoll?

**Comment by snicoll** [comment]
@paulcwarren it is your project so I really don't have a say. IMO, if you decide to change the name, you should determine when you're doing the change (a new major release perhaps?). Having them both at the same time feels weird though. We're happy to promote it when that's the case.

**Comment by snicoll** [comment]
Let's keep the discussion on paulcwarren/spring-content#8 for now then. Thanks!

**Comment by paulcwarren** [comment]
Sounds good.  I will re-raise once we rename our projects.

**Pull request closed without merging**
