### PR TITLE
Polish and refactor to java 7 and 8 idioms

### PR DESCRIPTION
**Pull request by emacampolo**

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. May I ask how you identified the place where Java 7 and 8 idioms could be applied? I'd really like to make sure that, for example, the diamond operator is used everywhere rather than a partial migration.

**Comment by emacampolo** [comment]
I found them using IntelliJ's inspection tool. As you already noticed, I only refactored that module since I did not know if such changes would be welcomed.
If you want, I can do the same thing with the other modules.

**Comment by emacampolo** [comment]
Most changes were done manually so if that is your concern. I carefully analysed if there was a test covering non trivial changes.

**Comment by wilkinsona** [comment]
Thanks. I'm not concerned about the changes being made manually, just that they're being made consistently across the codebase. Using IntelliJ's inspections should achieve the nicely.

To keep each commit relatively small, my preference would be to use a separate commit for each type of change. For example, a single commit that moves to using the diamond operator across all modules. Where appropriate, it would also be good to update the IDE metadata for Eclipse to enforce things. As you don't appear to be an Eclipse user, we can take care of that as part of a merge though.

**Comment by emacampolo** [comment]
Ok, thanks for the feedback. I will do the following:

I will decline this PR and I will submit a new branch with one commit per refactor/idiom for every module so you can review each commit:

eg. 
Apply Java 7 idioms (diamond operator and try catch with resources)
Apply Java 8 idioms (replaced inner classes for lambdas, ...)
Favor StringBuilder over strings concatenation
...

**Comment by wilkinsona** [comment]
Thanks. FWIW, I'd go even further and split each idiom into a single commit:

- Diamond operation
- Try-with-resources (I think we've done this one already)
- Multi-catch
- Lamdas
- Etc

To avoid wasted effort, it might be worth doing one and seeing how easy it is for us to merge. To avoid merge conflicts, broad changes such as these may be better done at a time when we know not many other changes are going to be made.

> Favor StringBuilder over strings concatenation

Generally speaking, I'm not so keen on this one. My understanding is that the compiler will take care of this for us (unless it's a really complicated string) and I prefer the more concise nature of concatenation.

**Comment by emacampolo** [comment]
Ok then , I will include one commit with java 7 and 8 idioms only and see how it goes ;) With favoring StringBuilder over string I meant the following:

```java
for (Entry<Object, Object> name : this.objectNameStaticProperties.entrySet()) {
    builder.append("," + name.getKey() + "=" + name.getValue());
}
```
with

```java
for (Entry<Object, Object> name : this.objectNameStaticProperties.entrySet()) {
    builder.append(",").append(name.getKey()).append("=").append(name.getValue());
}
```
IMHO we benefit a little more from readability than in performance as you mentioned.
But, I will keep the first commit as simple as possible.

**Comment by philwebb** [comment]
@emacampolo FWIW I find the top style easier to read than multiple `.append` calls. I'd suggest starting with the other changes first we're less keen on the `StringBuilder` changes.

Thanks.

**Comment by emacampolo** [comment]
Will do. Thank you for the review Phil.

**Pull request closed without merging**
