### PR TITLE
Remove  unused class

### PR DESCRIPTION
**Pull request by dubu**
remove unused html class properties.

### CODE REVIEW

**Comment by philwebb** [comment]
I'd quite like to go the other way and add some additional CSS styles. I think the HTML snippets are quite useful for people.

**Comment by snicoll** [comment]
+1

**Comment by dubu** [comment]
HTML snippets are good idea :+1:
would you tell me a similar example ? well-suited HTML snippets example

**Comment by dubu** [comment]
@philwebb

**Pull request closed without merging**
