### PR TITLE
Manage Tomcat queued connections

### LINKED ISSUE #6433: Tomcat acceptCount
Enhancement:
Add additional tomcat parameter: accept-count. This is incredibly useful parameter when implementing throttles to protect resources from heavy activity spikes. It is the best friend of max-threads which is already supported. Otherwise you end up with hundreds of sockets sitting in blocked state, rather then sending a 503 - try again later.

```
server:
  port: 8080
  tomcat:
    max-threads: 10
    accept-count: notImplemented
```

### PR DESCRIPTION
**Pull request by herau**
Adding two tomcat server properties:
- server.tomcat.accept-count
- server.tomcat.max-connections

Fixes #6433

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@herau Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=6571)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=6571) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@herau Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=6571)!

**Comment by philwebb** [comment]
Thanks. I'll target this to 1.5. We should also look to see if Jetty/Undertow have similar options that mean this could be a top level property.

**Comment by herau** [comment]
Ok i will check it.

**Comment by herau** [comment]
@philwebb 
**Tomcat** has an `acceptCount`option

> The maximum queue length for incoming connection requests when all possible request processing threads are in use. Any requests received when the queue is full will be refused. The default value is 100.

and a `maxConnections	` option
> The maximum number of connections that the server will accept and process at any given time. When this number has been reached, the server will accept, but not process, one further connection. This additional connection be blocked until the number of connections being processed falls below maxConnections at which point the server will start accepting and processing new connections again. Note that once the limit has been reached, the operating system may still accept connections based on the acceptCount setting.

**Jetty** has an `acceptQueueSize`option:

> The size of the pending connection backlog. The exact interpretation is JVM and operating system specific and you can ignore it. Higher values allow more connections to wait pending an acceptor thread. Because the exact interpretation is deployment dependent, it is best to keep this value as the default unless there is a specific connection issue for a specific OS that you need to address.

But i don't find any option for the limitation of connections number :-(

**Undertow** provide a [RequestLimitingHandler](https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/handlers/RequestLimitingHandler.java) which allow to define the `maximum concurrent requests` and the the `maximum number of requests to queue`

So you could use a generic option to set the maxime number of requests to queue with a key like `server.max-requests-queue-size`

**Comment by philwebb** [comment]
@herau Thanks for the detailed analysis. It looks like the different implementations are probably different enough that a uniform property isn't the best approach after all. We're just merge your PR as it is and keep it Tomcat specific.

Thanks!

**Pull request closed without merging**
