### PR TITLE
Dependency management for micrometer-registry-cloudwatch is missing

### PR DESCRIPTION
**Pull request by cmakinen**
Added `micrometer-registry-cloudwatch` to spring-boot dependencyManagement section.

Refers to issue: #13981

### CODE REVIEW

**Comment by snicoll** [comment]
@cmakinen thanks for the PR but before we add this to the dependency management, I'd like to understand why we don't have auto-configuration at all for this (in the current state adding the version in the two other modules is useless).

paging @jkschneider

**Comment by spencergibb** [comment]
It is in spring cloud aws

**Comment by snicoll** [comment]
Thanks Spencer, some [more info in this comment](https://github.com/spring-projects/spring-boot/pull/11276#issuecomment-364199576).

@cmakinen can you please rework your PR to remove the inclusion of that library in the `autoconfigure` and `docs` modules?

**Comment by snicoll** [comment]
@cmakinen thank you very much for your first contribution to Spring Boot. This has been merged in `2.0.x` and `master`.

**Comment by cmakinen** [comment]
Thanks @snicoll Really appreciate it!! Happy to contribute :)

**Comment by jkschneider** [comment]
If we dependency manage `micrometer-registry-cloudwatch` in Spring Boot, we are effectively dependency managing the AWS SDK which iterates quite a bit faster than Spring Boot.

That’s why we left this to `spring-cloud-aws`.

**Comment by snicoll** [comment]
Reopening to double check we didn’t do this on purpose

**Comment by wilkinsona** [comment]
> If we dependency manage micrometer-registry-cloudwatch in Spring Boot, we are effectively dependency managing the AWS SDK

I don't think we are. The dependency management of `micrometer-registry-cloudwatch` will have no direct effect on the version of the AWS SDK. The version of the AWS SDK would only be affected if the user adds a dependency on `micrometer-registry-cloudwatch` and then, in the absence of any other dependency on the AWS SDK, they'll get whatever version of the AWS SDK is pulled in transitively. In terms of the version of the AWS SDK, this is no different to the user manually specifying the version of `micrometer-registry-cloudwatch`.

**Pull request closed without merging**
