### PR TITLE
If Spring Security OAuth2 is detected on the classpath, automatically configure it

### PR DESCRIPTION
**Pull request by gregturn**
* Automatically spin up Authorization Server and Resource Server
* Automatically configures method level security included OAuth2Expression handler
* Wrote extensive unit tests verifying default behavior as well as the auto-configuration backing off when custom Authorization/Resource servers are included
* Created org.springframework.boot.security.oauth2 subpackage to contain it

### CODE REVIEW

**Comment by gregturn** [comment]
@philwebb My bad.I thought you were talking about star imports auto-added by CLI, not star imports in the Java code OF Spring Boot CLI. I need to to tune my IntelliJ setup. In Spring Data we use star imports ONLY for Spring Test static imports. I have a separate configuration for Spring Boot and need to fine tune that aspect so you don't have to keep polishing my commits.

**Comment by dsyer** [comment]
I've made some more changes on my fork. I think this is turning in to a 1.3.0 feature (getting to be quite a lot of moving parts).

**Comment by gregturn** [comment]
@dsyer @philwebb I've rebased against master, merged Dave's latest batch of edits, resolved the conflicts, and fixed one lingering test case.

**Comment by dsyer** [comment]
Merged (finally).

**Pull request closed without merging**
