### PR TITLE
LiquibaseEndpoint does not report change sets from ancestor contexts

### LINKED ISSUE #22680: Use loop variable ApplicationContext to determine all Liquibase beans
https://github.com/spring-projects/spring-boot/blob/d2926e02222f942948637bd5bb6972379eb094c8/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/liquibase/LiquibaseEndpoint.java#L65

should be replaced with `target.getBeansOfType(SpringLiquibase.class)`

### PR DESCRIPTION
**Pull request by biergit**
Fix traversal of ApplicationContext hierarchy to resolve potential Liquibase beans
Fixes #22680

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@biergit Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=22681)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=22681) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@biergit This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by wilkinsona** [comment]
@biergit Thanks for the pull request. Can you please sign the CLA? The proposal will result in a change in functionality which means it is not considered to be an obvious fix.

**Comment by pivotal-issuemaster** [comment]
@biergit Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=22681)!

**Comment by biergit** [comment]
Ok @wilkinsona that wasn't obvious to me ;) I'm part of the closer family now.

**Comment by wilkinsona** [comment]
Thanks very much for making your first contribution to Spring Boot, @biergit. This has been fixed in 2.2, 2.3, and 2.4.

**Pull request closed without merging**
