### PR TITLE
Document requirement for Maven 3.6.3 or later

### LINKED ISSUE #34694: Document requirement for Maven 3.6.3 or later
The latest version of the Maven Help Plugin (https://github.com/spring-projects/spring-boot/issues/34687) requires Maven 3.6.3. We should update our supported versions of Maven accordingly.

### PR DESCRIPTION
**Pull request by isabek**
resolves #34694

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks, @isabek. Could you please update the version in [the "Build Tool Plugins" section](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/index.html#build-tool-plugins.maven) as well?

**Comment by isabek** [comment]
@wilkinsona sure. Also, I found another [occurrence](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/index.html#getting-started.system-requirements) of `Maven 3.5+`. Should I change it as well?

Also, is forcing existing commit okay?

**Comment by wilkinsona** [comment]
> Should I change it as well?

Yes, please.

> Also, is forcing existing commit okay?

Absolutely. We'd prefer all the changes in a single commit but we can squash them as part of merging if you like.

**Comment by isabek** [comment]
@wilkinsona I've added the requested changes

**Review by wilkinsona — APPROVED** [review]

**Comment by wilkinsona** [comment]
@isabek Thank you very much for making your first contribution to Spring Boot.

**Pull request closed without merging**
