### PR TITLE
fix SonarCube issues  "Local variables should not shadow class fields"(squid:HiddenFieldCheck)

### PR DESCRIPTION
**Pull request by igor-suhorukov**
To get rid confusing to know whether the field or the local variable is being used. This pull request fix [171 issues](https://sonarcloud.io/project/issues?id=org.springframework.boot%3Aspring-boot-build&resolved=false&rules=squid%3AHiddenFieldCheck) with "local variables overriding class field names"( [squid:HiddenFieldCheck](https://sonarcloud.io/organizations/igor-suhorukov-github/rules#rule_key=squid%3AHiddenFieldCheck))

This pull request is related issues described in ticket #11650

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR but I disagree with this one. We prefix all field access with `this` so, IMO, there’s no confusion.

**Comment by igor-suhorukov** [comment]
@wilkinsona ok, it is my mistake maybe

**Comment by philwebb** [comment]
I'm with Andy on this one I'm afraid. We have a checkstyle rule to enforce the `this.` prefix so I think there's limited value in enforcing different local variable names. In fact, I often prefer the simpler names you get when you aren't forced to choose something different.

**Comment by philwebb** [comment]
> what do you think about Utility classes should not have public constructors

Generally agree and we [have a checkstyle rule](https://github.com/philwebb/spring-boot/blob/0ca3a8d7ade7b319e48d46ad51ae32f36f4f747d/spring-boot-parent/src/checkstyle/checkstyle.xml#L40) for this. The problem with [the Sonar results](https://sonarcloud.io/project/issues?id=org.springframework.boot%3Aspring-boot-build&resolved=false&rules=squid%3AS1118&types=CODE_SMELL) here is that is' picking things like `CacheMeterBinderProvidersConfiguration` that I don't consider utility classes. In fact, we've generally tried to avoid util classes altogether in Boot.

> Generic wildcard types should not be used in return parameters

This one is very subjective as well. I generally try not to return them for public APIs, but it can be difficult to always do this without causing a lot of problems. Take [this one](https://sonarcloud.io/component?id=org.springframework.boot%3Aspring-boot-actuator%3Asrc%2Fmain%2Fjava%2Forg%2Fspringframework%2Fboot%2Factuate%2Finfo%2FInfoPropertiesInfoContributor.java&line=75) for example. We could return a `PropertySource<Object>` I guess, but really what's the point? We're really saying you can return a property source of any generic here and we'll deal with it. I'm not sure always enforcing the rule makes for better code, although it may well be worth a review of some APIs.

**Pull request closed without merging**
