### PR TITLE
Upgrade to gson 2.4

### PR DESCRIPTION
**Pull request by zhanhb**

### CODE REVIEW

**Comment by wilkinsona** [comment]
IMO, this should wait till 1.4. Post-RC1 is too late to move to a new minor version of a dependency

**Comment by zhanhb** [comment]
I can't find document about the difference 2.3.1 and 2.4. I compare the source from github.com/google/gson. The most difference which may cause compatibility issues is the method toJson changed from
`public final String toJson(T value) throws IOException {...}`
to
`public final String toJson(T value) {...}`
in source file com/google/gson/TypeAdapter.
The second one is method `hashCode` and `equals` added in com/google/gson/internal/LazilyParsedNumber. Other changes are not considerable.

**Comment by zhanhb** [comment]
In my opinion, minor version change of google code can be applied to the project.

**Comment by jhoeller** [comment]
FWIW, we compile Spring Framework 4.2.3 against GSON 2.4 and haven't run into a problem yet. It seems to be a safe upgrade. But then, we're still compatible with GSON 2.3, of course; it's just the version that we compile against at this point in order to eagerly find API incompatibilities etc.

**Comment by zhanhb** [comment]
OK, I see. And should I keep this PR?

**Comment by wilkinsona** [comment]
Our rule of thumb is that we don't change a minor version in a maintenance release and I consider the move from RC1 to RELEASE to be a maintenance release

**Comment by zhanhb** [comment]
gson 2.5 has been released.

**Comment by snicoll** [comment]
Thanks for the PR, I've upgrade to gson 2.5 in 24b953e

**Pull request closed without merging**
