### PR TITLE
Upgrade flyway and liquibase samples

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by snicoll** [comment]
What are those unrelated changes Eddu? What do you intend with the repository changes?

**Comment by eddumelendez** [comment]
Adding `PersonController ` in order to replace the `CommandLineRunner::run` where repository.findAll() is called. `PersonRepository` no need change I have updated the PR.

**Comment by snicoll** [comment]
And why do you want to replace the command line runner? What's the link with actuator endpoint ?

**Comment by eddumelendez** [comment]
My mistake, forgot that if `spring-boot-starter-web` is a dependency `CommandLineRunner::run` is executed by the application is still running. 

About the actuator endpoint, I will add a README file. It is ok?

**Comment by snicoll** [comment]
Let's not add a read me for just one thing. Feel free to add one in your pr though.

**Comment by snicoll** [comment]
Merged, thanks!

**Pull request closed without merging**
