### PR TITLE
Dependency management for REST Assured is incomplete

### PR DESCRIPTION
**Pull request by it-ony**
Added dependency of spring-mock-mvc with the same version as rest-assured.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@it-ony Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=11866)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=11866) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@it-ony Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=11866)!

**Comment by wilkinsona** [comment]
Thanks. In the interests of keeping the versions of all of REST Assured's modules in sync, we should add dependency management for the other missing modules too. I believe those are the following:

- `json-path`
- `json-schema-validator`
- `scala-support`
- `xml-path`

**Comment by wilkinsona** [comment]
Thank you very much for making your first contribution to Spring Boot. This change has now been merged into master.

**Pull request closed without merging**
