### PR TITLE
Add actuator endpoint to retrieve audit events

### PR DESCRIPTION
**Pull request by vpavic**
This PR introduces `AuditEventsEndpoint` to retrieve audit events from `AuditEventRepository`. Both HTTP and JMX endpoints are available.

By default, the endpoint retrieves latest events as indicated by `endpoints.auditevents.default-max-age` configuration property, which itself defaults to 60 minutes. Endpoint also exposes `AuditEventRepository` operations to find audit events using custom criteria.

TODOs:
- [x] complete Actuator docs on this endpoint

### CODE REVIEW

**Comment by vpavic** [comment]
PR updated to resolve conflicts and complete the Actuator docs.

**Comment by vpavic** [comment]
Just a thought, maybe the `AuditEventsEndpoint` itself isn't needed and the MVC and JMX endpoints could simply wrap the `AuditEventRepository` and expose its operations. This would remove the need for the configuration property introduced by the PR, due to the need to somehow handle the default invocation of the endpoint.

WDYT @philwebb?

**Comment by philwebb** [comment]
@vpavic That sounds like it might be a good idea. Since we'd be adding direct JMX and MVC support the `Endpoint` itself doesn't add that much.

**Comment by vpavic** [comment]
Great, this will simplify things quite a bit. I'll update the PR mid-next week.

**Comment by vpavic** [comment]
@philwebb I've updated the PR. As suggested, both MVC and JMX endpoints now simply wrap `AuditEventRepository` and expose its operations.

Since there was no existing support for JMX endpoint implementations without a backing `Endpoint` (like with `AbstractMvcEndpoint`), I've decomposed the existing `EndpointMBean` to support such use case. That effort is extracted into a separate commit.

**Comment by philwebb** [comment]
@vpavic Thanks! I should hopefully get to merging this soon.

**Comment by vpavic** [comment]
I've updated the PR to ensure consistent formatting of `AuditEvent#timestamp`.

@philwebb I forgot to mention one problematic bit about `AuditEventsMBean` registration - since it's no longer backed by an `Endpoint` it does not use existing `EndpointMBeanExporter` based registration mechanism and ATM it does not respect the `EndpointMBeanExportProperties`.

**Comment by snicoll** [comment]
@philwebb while polishing the configuration meta-data appendix I noticed that you removed `endpoints.auditevents.sensitive`. That property exists and is mapped so I've added again

https://github.com/spring-projects/spring-boot/commit/615804ff34cc220397d6a84417f67a649a262f37

If that property is ignored, we need a way to reflect that in the documentation (it will still show up in IDE support).

**Comment by philwebb** [comment]
@snicoll Thanks. It's ignored for JMX but not for MVC.

**Pull request closed without merging**
