### PR TITLE
Added Infinispan starter reference

### PR DESCRIPTION
**Pull request by slaskawi**
Hey,

I added a community-based Spring Boot Starter for Infinispan.

Thanks,
Sebastian

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@slaskawi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7997)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7997) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by snicoll** [comment]
@pivotal-issuemaster this is a trivial change

**Comment by pivotal-issuemaster** [comment]
@slaskawi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7997)!

**Comment by pivotal-issuemaster** [comment]
@slaskawi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7997)!

**Comment by pivotal-issuemaster** [comment]
@slaskawi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7997)!

**Comment by pivotal-issuemaster** [comment]
@slaskawi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7997)!

**Comment by snicoll** [comment]
Thanks Sebastian, this should have been on the list  for quite a while already!

**Comment by slaskawi** [comment]
No problem! My pleasure!

**Pull request closed without merging**
