### PR TITLE
Document how to configure Maven's Failsafe plugin when not using spring-boot-starter-parent

### PR DESCRIPTION
**Pull request by robert-smith-911**
A documentation fix for #25473 to document how to configure maven's failsafe plugin when not using spring boot starter parent pom.

### CODE REVIEW

**Comment by robert-smith-911** [comment]
Aha sure @wilkinsona no problem!

**Comment by snicoll** [comment]
@robert-smith-911 how is it going? Would you have time to update this PR?

**Comment by robert-smith-911** [comment]
@snicoll Yes sir just got busy at work, doing it today thanks for the reminder

**Comment by robert-smith-911** [comment]
@snicoll @wilkinsona How's this?

**Comment by robert-smith-911** [comment]
@wilkinsona sure!

**Pull request closed without merging**
