### PR TITLE
Use AssertJ facilities for expected exceptions

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

I just noticed some usages of `@Test(expected = SomeException.class)` that could probably benefit from using AssertJ facilities. E.g. by making clear what is expected to fail in a test.

Let me know what you think.
Cheers,
Christoph

### CODE REVIEW

**Comment by mbhave** [comment]
Thanks @dreis2211. They might have been missed in #16066.

**Comment by dreis2211** [comment]
@mbhave I wonder if you mean #14336?

**Comment by mbhave** [comment]
Oops, sorry I did mean that. I don't know why I pasted the same issue number 🤦‍♀️

**Comment by dreis2211** [comment]
Test failure seems unrelated.

**Comment by snicoll** [comment]
@dreis2211 good catch again, thanks.

**Comment by dreis2211** [comment]
Sorry I missed the 3 copyright updates :/

**Comment by snicoll** [comment]
No need to be sorry, Christoph. Thanks for all the hard work.

**Pull request closed without merging**
