### PR TITLE
Added support for debug option as goal for maven plugin

### PR DESCRIPTION
**Pull request by RishikeshDarandale**
This 'debug' goal of maven plugin will allow a better option to start
the underlying container in 'debug' mode. The debuggee process can
join debugger on default port '5005' or the specified one.

Thus by providing this goal, user will have an option to start the
container in normal or debug mode for the development process. This
is just nice to have feature for the convenience.

Port can be configured by specifing the 'debug.port' as command line
parameter.

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks @RishikeshDarandale. Have you signed the CLA?

**Comment by philwebb** [comment]
@snicoll any thoughts on this?

**Comment by RishikeshDarandale** [comment]
@philwebb, I have signed ICLA.

**Comment by snicoll** [comment]
It feels that a dedicated goal for that is a bit too much. After all, it's a one liner that has an explicit section in the documentation. I'd rather keep what  we have than brining a separate goal for it.

**Comment by philwebb** [comment]
Thanks for the feedback @snicoll. I think we'll leave this out for now.

Thanks anyway for the contribution @RishikeshDarandale :+1:

**Comment by RishikeshDarandale** [comment]
Thanks @philwebb , @snicoll for the feedback. :-)

**Pull request closed without merging**
