### PR TITLE
Add explanation for @SpringBootTest on externalized configuration.

### PR DESCRIPTION
**Pull request by kazuki43zoo**
I've added explanation that can specify properties for testing at the `@SpringBootTest` annotation.
Please review.

### CODE REVIEW

**Comment by snicoll** [comment]
Thank you for the PR. Actually `@TestPropertySource` takes precedence over `@SpringBootTest#properties `so I've added a separate entry to make that more explicit.

**Comment by kazuki43zoo** [comment]
Hi @snicoll , thanks for resolve. But I've added [some comments on your commit](https://github.com/spring-projects/spring-boot/commit/878a0525670aa190fd6d42486bce9de5b2457b87#commitcomment-19019689).

**Comment by snicoll** [comment]
Good catch, I've fixed that in 5d3ac53

**Comment by kazuki43zoo** [comment]
Thanks for fix :+1:

**Pull request closed without merging**
