### PR TITLE
Remove deprecated ZipkinSender

### LINKED ISSUE #42589: Make ZipkinHttpClientSender the default BytesMessageSender
Right now, org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinConfigurations.SenderConfiguration imports `UrlConnectionSenderConfiguration` before `HttpClientSenderConfiguration`. We should switch that around. Also we should think about removing support for `URLConnectionSender` altogether.

### PR DESCRIPTION
**Pull request by wickdynex**
## Description

This PR have removed three `SenderConfiguration` also its `Sender`: `UrlConnectionSenderConfiguration`, `RestTemplateSenderConfiguration` and `WebClientSenderConfiguration` in file `ZipkinConfigurations`. Remove the related test cases about these `SenderConfiguration` class in file `ZipkinConfigurationsSenderConfigurationTests`.

---

## Related Issue
Fixed #42589, #43047, #43048 

---

## Type of Change

- [X] Remove feature
- [X] Remove related tests
- [ ] Add new test cases
- [ ] Documentation update

---

## Checklist

- [X] I have reviewed the code for any potential issues or improvements.
- [X] I have run tests locally and they are passing.
- [X] I have followed the coding style and conventions of the project.

---

## Screenshots 

image

---

## Additional Notes

I does remove the other `Senders` and its `SenderConfiguration` class, and also remove the test class related to these deprecated🥰. But do I need refactor `ZipkinConfiguration` structure, and write some test case to integrate test this modified class.🤨 Also update the documents about this related Sender🤔. Please give me some advice if this PR can't be merged🥹, and I will try my best to fix it up. Looking forward to your reply❤️~

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR, @wickdynex. Unfortunately, this is changing too many different things for a single PR. Please just focus on the changes for #42589 as already described by @mhalbritter:

> In the scope of this issue, you should just reorder the configurations, like you said in https://github.com/spring-projects/spring-boot/issues/42589#issuecomment-2450330858. And I guess some tests needs to be adapted.

**Comment by wickdynex** [comment]
> Thanks for the PR, @wickdynex. Unfortunately, this is changing too many different things for a single PR. Please just focus on the changes for #42589 as already described by @mhalbritter:
> 
> > In the scope of this issue, you should just reorder the configurations, like you said in [#42589 (comment)](https://github.com/spring-projects/spring-boot/issues/42589#issuecomment-2450330858). And I guess some tests needs to be adapted.

Alright, maybe I should split this PR into 3 pieces for 3 issues🤔? emmm, and how to deal with this PR, close or continually commit on this branch? do u have any idea?🥰 And also assign the issue #43047, #43048 to me? If I can fix it🥳.

**Comment by snicoll** [comment]
I can see you created a new PR. closing this one

**Comment by wickdynex** [comment]
> I can see you created a new PR. closing this one

Yeah, thanks for your help🥳.

**Pull request closed without merging**
