### PR TITLE
Provide dependency management for JUnit Jupiter

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by snicoll** [comment]
Now that's GA, perhaps we can promote that to `spring-boot-dependencies`. What do you think @wilkinsona?

**Comment by wilkinsona** [comment]
Good idea. Given that we have a sample and that Framework has first-class support for it, providing dependency management feels right to me.

**Comment by snicoll** [comment]
@eddumelendez are you willing to rework the PR?

**Comment by eddumelendez** [comment]
@snicoll Sure! it's done 😃

**Comment by kazuki43zoo** [comment]
Hi @snicoll and @wilkinsona,

I have one question.
Have you plan to change the default dependency artifact to the Junit Jupiter instead of the Junit 4 on the spring-boot-starter-test?

**Comment by philwebb** [comment]
@kazuki43zoo Most probably not in Spring Boot 2.0.

**Comment by snicoll** [comment]
@kazuki43zoo please watch #6402

**Comment by kazuki43zoo** [comment]
@philwebb @snicoll 

Thanks for your reply! I will watch #6402 .

**Comment by sbrannen** [comment]
Why would you include dependency management for the `Launcher` API if you're only focusing on the JUnit Jupiter API?

Most users won't need the `Launcher` API: it's typically only needed by build tools (e.g., Gradle and Maven) and IDEs.

I'm not saying you should necessarily remove the `Launcher`, but users _will_ likely need the `junit-vintage-engine` in order to be able to run existing JUnit 4 and JUnit 3 tests alongside JUnit Jupiter tests (or alongside any other testing framework running on the JUnit Platform).

Plus, why not include a dependency on `junit-jupiter-params` as well (even if it's technically _experimental_)?

Food for thought...

\- Sam

**Comment by wilkinsona** [comment]
IMO, the dependency management is incomplete. The rule of thumb is that we manage all dependencies that are released together. In this case, I believe we should have dependency management for all of the Platform and all of Jupiter too.

**Comment by snicoll** [comment]
I agree it is incomplete and was expecting @wilkinsona to report that. However, I did remove `params` on purpose as it is marked experimental in JUnit's documentation. Not sure we should include such labeled artifact.

@wilkinsona some of those dependencies are used by plugins only so adding them to `dependencyManagement` would be actually useless.

**Comment by sbrannen** [comment]
@snicoll, thanks for the explanation regarding `params`.

I looked at your latest commit, and I understand the rationale for the changes. 👍

**Pull request closed without merging**
