### PR TITLE
Stop TestRestTemplate from overriding custom error handler

### LINKED ISSUE #7265: Make is easier to use TestRestTemplate with a custom ResponseErrorHandler
Custom error handler set using `RestTemplateBuilder` bean or using the configuration `TestRestTemplateConfiguration` from [Spring Boot Reference Guide](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-with-spock) is overriden by `TestRestTemplate.NoOpResponseErrorHandler`.

Specifically, when using the following class:
````
class CustomResponseErrorHandler extends DefaultResponseErrorHandler {
    // implementation
}
````
in the configuration of the builder:
````
ResponseErrorHandler customErrorHandler = new CustomResponseErrorHandler();
RestTemplateBuilder builder = builderProvider.getIfAvailable()
                                             .errorHandler(customErrorHandler);
````
The following line is false:
````
new TestRestTemplate(builder.build()).getRestTemplate().getErrorHandler().equals(customErrorHandler)
````

### PR DESCRIPTION
**Pull request by MateuszRasinski**
Fixes #7265

### CODE REVIEW

**Comment by wilkinsona** [comment]
I'm not sure about this. It's part of `TestRestTemplate`'s contract that it's fault tolerant and this potentially changes that. We may have users who are customising the error handler for "normal" rest templates, but that have tests that rely on it being replaced and becoming fault tolerant when they use `TestRestTemplate`.

**Comment by MateuszRasinski** [comment]
Consider the tests that expect specific exceptions to be thrown in some situations. This is how my team works using the Spock Framework. For now, we have to fallback to setup `TestRestTemplate` each time we execute a test method:
````
def setup() {
    testRestTemplate.getRestTemplate().setErrorHandler(customErrorHandler);
}
````
IMO it is a bit _hackish_.

What is more, the javadoc of `TestRestTemplate` says:

> If you need customizations (for example to adding additional message converters) use a RestTemplateBuilder `@Bean`.

It is then misleading, because not all customizations are working at the moment, or as you suggest not all customizations are available to the client. Either way, something is wrong.

**Comment by zdanek** [comment]
+1 for this PR

**Comment by wilkinsona** [comment]
We'd like to do something to support your use case, but we don't think this is the right way to tackle it. Thanks anyway for the PR.

**Pull request closed without merging**
