### PR TITLE
Update and rename LICENSE.txt to LICENSE

### PR DESCRIPTION
**Pull request by thomasturrell**
* Remove boilerplate from license.
* Rename to LICENSE, which is the current default name for a LICENSE in a GitHub repository.

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks for the PR but most Spring projects use `LICENSE.txt` which is still recognized by GitHub. I think we should also leave the appendix section.

**Comment by thomasturrell** [comment]
@philwebb thank you for taking the time to review my pull request.

An additional issue that I resolved in this pull request replacing the template: 

`Copyright {yyyy} {name of copyright owner}`

with:

`Copyright 2002-2022 Pivotal, Inc.`

Do you think it is worth me opening another pull request with just this (minor) change?

**Comment by thomasturrell** [comment]
> `Copyright 2002-2022 Pivotal, Inc.`

Although I believe that this should now be

`Copyright 2002-2023 Pivotal, Inc.

**Comment by philwebb** [comment]
@thomasturrell I think we usually leave that template information as it is in the `LICENCE.txt` file. For example, [here is the one from Spring Framework](https://github.com/spring-projects/spring-framework/blob/88cac6a4a3a84ff9891d226d7ad47d2707af6d96/LICENSE.txt#L190).

We do update the copyright in source files that we change. For example, [here's](https://github.com/spring-projects/spring-boot/commit/f588793445dee905335625ba946674ed3a771db0) a recent commit where I updated the date. We use "the original author or authors" rather than "Pivotal" or any specific company.

**Pull request closed without merging**
