### PR TITLE
Upgrade to Asciidoctor Gradle JVM 3.0.0

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

this PR upgrades to `org.asciidoctor:asciidoctor-gradle-jvm:3.0.0` and fixes related issues that prevented building the docs on that new version. This seems to overlap with #19785 so I've split the necessary commits.

Let me know what you think.
Cheers,
Christoph

### CODE REVIEW

**Comment by dreis2211** [comment]
The current errors should be fixed with #19952 already

**Comment by wilkinsona** [comment]
We should check if we need to tackle https://github.com/spring-io/spring-asciidoctor-extensions/issues/21 before merging this. That issue was opened as a placeholder so it may be that the extension is already AsciidoctorJ 2.0 compatible.

**Comment by dreis2211** [comment]
Is there anything I can help with, @wilkinsona ?

**Comment by wilkinsona** [comment]
Thanks for the offer, @dreis2211. I think it's been taken care of thanks to @rwinch. I just need to double-check that I didn't break it when merging and then cut a release of the extensions.

**Comment by wilkinsona** [comment]
The extensions have been released and Boot's now using them. I think we should now be good-to-go on this one.

**Comment by wilkinsona** [comment]
The PDF generation [failed](https://ge.spring.io/s/vx4qqz2lkhajs/console-log?task=:spring-boot-project:spring-boot-docs:asciidoctorPdf) when built locally. I think that's because we're using the configuration property JSON to generate the Asciidoc source. This makes the changes to use, for example, `&lt;` rather than `<` have no effect. The `&lt;` has been replaced with `<` again by the time the Asciidoctor processing is performed. I think we may need to do some escaping of the description in `SingleConfigurationTableEntry` instead.

**Comment by dreis2211** [comment]
Interesting....I wonder why this didn't fail for me locally?

**Comment by dreis2211** [comment]
Pushed an updated version

**Pull request closed without merging**
