### PR TITLE
Add support for actuator kafka client metrics

### PR DESCRIPTION
**Pull request by ssouris**
Add metrics for kafka clients, providing a PublicMetrics implementation

Fixes gh-8756

### CODE REVIEW

**Comment by ssouris** [comment]
In this PR the following naming convention is used

`<beanName>.<kafka_metric_group>.<kafka_metric_name>`

`KafkaMetric` also provides 
* description and 
* tags e.x. `clientId: client-1`

e.x. in prometheus TSDB it could look like
```
io_wait_ratio{group='producer-metrics', client_id='client-1'}

or

producer_metrics_io_wait_ratio{client_id='client-1'}
```

Is the naming convention used in the PR good enough? Or should another one be considered?

Thanks in advance

**Comment by philwebb** [comment]
Thanks for the PR. We're planning some changes to the metrics subsystem so it might be a while before we can get to merge this.

**Comment by tsachev** [comment]
Just a heads up that the new versions of spring-kafka `1.3.x` and `2.0.x` will also expose the api for consumer(s) metrics spring-projects/spring-kafka@d545fe506113d564307b8a35409ad14ccf84090a (this PR is only for producer(s))

**Comment by wilkinsona** [comment]
Unfortunately, the change to using Micrometer for metrics means that this pull request is no longer usable. @ssouris If you'd like to open another PR that provides the same functionality using Micrometer, we'd be happy to take a look at it. Thanks anyway.

**Comment by ssouris** [comment]
Thanks I'll try doing that :)

**Comment by ST-DDT** [comment]
@ssouris Any progress on this one?

**Pull request closed without merging**
