### PR TITLE
Add official Gradle Wrapper Validation GitHub Action

### PR DESCRIPTION
**Pull request by JLLeitschuh**
See: https://github.com/gradle/wrapper-validation-action

### CODE REVIEW

**Comment by snicoll** [comment]
@JLLeitschuh thank you for making your first contribution to Spring Boot.

**Comment by JLLeitschuh** [comment]
Looks like you may be on the same legacy billing plan as some other companies I've contributed to. 😢 That's unfortunate.

https://github.com/spring-projects/spring-boot/runs/407247777

**Comment by snicoll** [comment]
Yep, saw that and investigating internally what we could do.

**Comment by wilkinsona** [comment]
It looks like it's going to take longer than we'd like to sort out the billing plan. Let's revert this for now so that PRs aren't affected in the meantime.

**Comment by snicoll** [comment]
Looks like we have access to actions now.

**Comment by JLLeitschuh** [comment]
Woot!!

**Pull request closed without merging**
