### PR TITLE
support WebServer args in H2ConsoleAutoConfiguration

### LINKED ISSUE #5232: H2ConsoleAutoConfiguration should support WebServer args
H2's `WebServlet` allows passing init args to `WebServer` via servlet init params. There should be a new property added to `H2ConsoleProperties` to pass these args to the servlet

### PR DESCRIPTION
**Pull request by sfussenegger**
added support for [H2 console settings](http://www.h2database.com/html/tutorial.html#console_settings) via `spring.h2.console.settings`

### CODE REVIEW

**Comment by sfussenegger** [comment]
btw, I've already signed the contributors agreement for my contributions to [spring-social](https://github.com/spring-projects/spring-social/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Asfussenegger) and [spring-cloud-aws](https://github.com/spring-cloud/spring-cloud-aws/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Asfussenegger)

**Comment by sfussenegger** [comment]
@philwebb will this be merged into 1.3.x too? does it make sense to create a PR for it?

**Comment by philwebb** [comment]
@sfussenegger It feels like an enhancement rather than a bug so I'd rather not backport it to 1.3.

**Comment by snicoll** [comment]
Thanks for the PR but I am not keen on configuring the console with a comma separated list of init parameters. An init parameter can have a value and we tend to have dedicated key per configuration item anyway. @mdeinum submitted a similar PR that I am reviewing right now. See #5417

**Comment by sfussenegger** [comment]
@snicoll fair enough. #5417 looks good

**Pull request closed without merging**
