### PR TITLE
Fix ordering of Math.abs() call

### PR DESCRIPTION
**Pull request by Shredder121**
Currently, when the random source returns Long.MIN_VALUE, the sign bit can't be unset.
So the random value stays negative.

I take it that I will have to sign the CLA if you want to incorporate this?

### CODE REVIEW

**Comment by wilkinsona** [comment]
@Shredder121 Yes, please. Details are [here](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#sign-the-contributor-license-agreement).

**Comment by Shredder121** [comment]
I have just completed it.

**Comment by Shredder121** [comment]
Nice.

**Comment by philwebb** [comment]
Thanks for the fix! Much appreciated.

**Pull request closed without merging**
