### PR TITLE
Documenting AWS Elastic Beanstalk deployment

### PR DESCRIPTION
**Pull request by szantopeter**
As discussed with @snicoll in this https://github.com/spring-projects/spring-boot/issues/7935 issue, here is my description

### CODE REVIEW

**Comment by philwebb** [comment]
Nice! Thank you.

**Comment by wilkinsona** [comment]
There's quite a lot to the documentation, and little of it is specific to Spring Boot. As such, I'm not sure that it belongs in our reference documentation. My main concern is that it's likely to get out of sync with current version of Elastic Beanstalk. If we want to mention deployment to Elastic Beanstalk, I'd prefer that we just link to [their documentation for deploying Java application](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_Java.html), perhaps with some additional Spring Boot-specific guidance.

**Comment by szantopeter** [comment]
@philwebb based on your suggestions I made the description much shorter, only outlining the differences compared to the official AWS Java guide.

**Comment by philwebb** [comment]
Thanks for the update

**Pull request closed without merging**
