### PR TITLE
Bug fix -9519 Deprecate JsonContent.assertThat method

### PR DESCRIPTION
**Pull request by blossoms**
Resolved issue #9519 
Deprecate JsonContent.assertThat method

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@blossoms Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9678)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9678) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@blossoms Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9678)!

**Comment by pivotal-issuemaster** [comment]
@blossoms Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=9678)!

**Comment by philwebb** [comment]
Thanks for the PR. I think we also need some Javadoc to explain what the preferred way of calling the method is.

**Comment by blossoms** [comment]
Hi Philwebb, Thanks for review. This is my first commit and starting up on this. 
Please guide me what should be the content of javadoc. 
We have deprecated this function to discourage its use as we have other function with same functionality.

**Comment by philwebb** [comment]
Probably something like `use {@link org.assertj.core.api.Assertions#assertThat AspectJ's assertThat} instead"

**Comment by wilkinsona** [comment]
@philwebb Shouldn't we deprecate this in 1.5.x and remove it in 2.0?

**Comment by wilkinsona** [comment]
Ignore the remove it part, I was being daft. I still wonder if we should add the deprecation in 1.5 though.

**Comment by philwebb** [comment]
Yeah, 1.5 makes sense. I've changed the milestone target.

**Comment by wilkinsona** [comment]
@blossoms Thank you for your first contribution to Spring Boot. I've merged your changes into 1.5.x and master.

**Pull request closed without merging**
