### PR TITLE
Add option to initialise SendGrid from ApiKey

### PR DESCRIPTION
**Pull request by patrickbray**
Add option to initialise SendGrid from ApiKey rather then user credentials

### CODE REVIEW

**Comment by patrickbray** [comment]
Build seems to be failing due to checkstyle attempting to run locally I get the following error from both this branch and master: 

```
[INFO] [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.3.1.BUILD-SNAPSHOT:start (pre-integration-test) on project start-stop-fork: Could not figure out if the application has started: Failed to connect to MBean server at port 63986: Spring application did not start before the configured timeout (30000ms -> [Help 1]
```

Unsure how to debug that failure, checking the build.log file does not yield much more info: 

```
The build exited with code 1. See /Users/pbray/Development/spring-boot/spring-boot-tools/spring-boot-maven-plugin/target/it/start-stop-fork/build.log for details.
```

**Comment by wilkinsona** [comment]
@patrickbray Thanks for the PR. I haven't seen the problem with the Maven plugin before. You should be able to diagnose the checkstyle problems by running `mvn -DskipTests clean install`.

Looking at the code, the lack of javadoc on `SendGridPropertyCondition` will be at least part of the problem. I'd avoid that by making it package-private. There's also a precedent for such classes being an inner-class of the auto-configuration class where it's used.

**Comment by patrickbray** [comment]
Thanks @wilkinsona. I found my maven issue and have cleaned up the formatting. Please let me know if there is anything else which I need to do.

**Comment by wilkinsona** [comment]
Looks good now. Thanks, @patrickbray

**Comment by patrickbray** [comment]
@wilkinsona any reason why this didn't make the release is there anything more you need me to do?

**Comment by wilkinsona** [comment]
@patrickbray Which release are you referring to? This PR was opened after 1.3.0 was released so, given that it's an enhancement, the natural target for it is 1.4.

**Comment by patrickbray** [comment]
Sorry for the confusion I was thinking 1.3.1 but it makes sense if that only includes fixes for this to be targeted at 1.4. Just wanted to make sure there was nothing else that needed to be done :)

**Comment by snicoll** [comment]
@patrickbray I haven't seen any indication that you've signed the CLA. Can you please confirm you did?

**Comment by patrickbray** [comment]
@snicoll, sorry no I hadn't but I have now do you need my confirmation number?

**Comment by snicoll** [comment]
Nope, thanks for the feedback.

**Comment by snicoll** [comment]
Thanks for the PR! I polished it in https://github.com/spring-projects/spring-boot/commit/3562026e9a2aa6a970b2acf83bb7632a151a6b97

**Pull request closed without merging**
