### PR TITLE
Fix typo in Spring Session documentation (obvious fix)

### PR DESCRIPTION
**Pull request by PascalSchumacher**
Fix typo in Spring Session documentation (obvious fix)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@PascalSchumacher Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=24020)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=24020) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by PascalSchumacher** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@PascalSchumacher This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by wilkinsona** [comment]
Thanks very much, @PascalSchumacher.

**Pull request closed without merging**
