### PR TITLE
Scopes filtering to jar added in the spring boot jar

### PR DESCRIPTION
**Pull request by olamy**
I'd like to filter the jar included in the spring boot one based on the scope.

``` xml
            <configuration>
              <scopes>
                <scope>compile</scope>
                <scope>runtime</scope>
              </scopes>
            </configuration>
```

### CODE REVIEW

**Comment by gordon00** [comment]
Too bad, it would have been useful in GWT context.
When you use GWT, you have to add GWT dependencies that are needed only by the maven-gwt-plugin to procuce some javascript files. (They have to be project dependencies, not plugin dependencies)
In classic maven war project , you just set provided scope to few "root" gwt dependencies and that's it.
Here, you have to browse all gwt dependency branch to add them into "excludes" xml element. So boring... that does not match maven provided scope spirit... don't you agree ?

**Comment by philwebb** [comment]
@gordon00 This issue has been closed for over a year, please raise a new request if you think things can be improved.

We need to include provided scope dependencies to make fully executable wars. If you're happy deploying to tomcat you could just set `skip` to `true` on `spring-boot:repackage`. You can also use the `excludeGroupIds` property if all the GWT artifacts have a common group.

**Comment by gordon00** [comment]
No, I really want to use the plugin to generate a standalone jar including tomcat.
Google gin, google guice, google guava for gwt don't have the same groupId... And there's a lot of others GWT libs like gwt-dispatch...
Exemple : gin include guice. But gin and guice-assist dont have same groupId. (thanks google)
If I exclude parent dependency gin, guice-assist and others sublibs are still included in jar.
Would you think it is possible to exclude a dependency and all his subdependencies transitively ?
The config would look like this : 
<excludes>
  <eclude>
    <groupId>com.google.gwt.inject</groupId>
    <artifactId>gin</artifactId>
    <excludeTransitively>true</excludeTransitively>
</excludes>

**Comment by gordon00** [comment]
Oops XML failed, let's try flat representation : 
excludes.exclude.groupId=com.google.gwt.inject
excludes.exclude.artifactId=gin
excludes.exclude.transitively=true

**Comment by philwebb** [comment]
@gordon00 This is just adding noise to the closed issue. Please open a new one. Use [three backticks](https://help.github.com/articles/markdown-basics/#multiple-lines) to escape XML .

**Pull request closed without merging**
