### PR TITLE
#4665 Extracted "banner.location" property and value into public cons…

### PR DESCRIPTION
**Pull request by anandshah123**

### CODE REVIEW

**Comment by philwebb** [comment]
See #4665

**Comment by snicoll** [comment]
Thanks, have you [signed the CLA](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#sign-the-contributor-license-agreement)?

**Comment by anandshah123** [comment]
Yes

**Comment by snicoll** [comment]
Thanks for the PR!

**Pull request closed without merging**
