### PR TITLE
JSON parser consistency

### PR DESCRIPTION
**Pull request by jadekler**
- Consistently handle nulls and empty strings for parseList and parseMap
- Tests for the aforementioned
- AbstractJsonParserTests test methods renamed to JUnit 4 convention (testFoo() -> @Test foo())

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR.

I agree that the JSONParser contract needs to be tightened up and the implementations made consistent, but I'm not sure if this is the right way to go about it. Rather than making all of the implementations tolerate null and empty strings, we might want to throw an exception. If we do go with making the implementations more tolerant then the callers within Spring Boot should be updated accordingly.

**Comment by wilkinsona** [comment]
Having discussed this, our current feeling is that we're happy with this as it is. However, we'd like to know if you encountered a problem that was caused by the code in its current form? That would probably change our opinion.

**Comment by jadekler** [comment]
@wilkinsona Nope, just looking around for test opportunities. I noticed that the basic parser has some handling that the others don't, so adding tests for it to the abstract tests triggered a consistency update to the other parsers.

If you'd like to keep the parsers as-is, how would you feel about adding some tests around that null handling to the basic parser tests (its specific tests, not the abstract test) (don't have the code up atm, sorry for the vague class names).

**Comment by wilkinsona** [comment]
Thanks, @jadekler. I think our team discussion was based on a faulty assumption. Our goal was simply to have all of the parsers thrown an exception with bad input. We don't really mind exactly what exception they throw, as long as they throw one. However, that's not the case at the moment. Consider these 6 tests:

```
	@Test
	public void mapWithNullThrowsARuntimeException() {
		this.thrown.expect(RuntimeException.class);
		this.parser.parseMap(null);
	}

	@Test
	public void listWithNullThrowsARuntimeException() {
		this.thrown.expect(RuntimeException.class);
		this.parser.parseList(null);
	}

	@Test
	public void mapWithEmptyStringThrowsARuntimeException() {
		this.thrown.expect(RuntimeException.class);
		this.parser.parseMap("");
	}

	@Test
	public void listWithEmptyStringThrowsARuntimeException() {
		this.thrown.expect(RuntimeException.class);
		this.parser.parseList("");
	}

	@Test
	public void mapWithListThrowsARuntimeException() {
		this.thrown.expect(RuntimeException.class);
		this.parser.parseMap("[]");
	}

	@Test
	public void listWithMapThrowsARuntimeException() {
		this.thrown.expect(RuntimeException.class);
		this.parser.parseList("{}");
	}
```

They all pass with the JacksonParser, JsonJsonParser, JsonSimpleJsonParser, but one or more fails with BasicJsonParser, GsonJsonParser, and YamlJsonParser. Gson seems particularly broken: it returns an empty map when given an empty list.

An update to this pull request (force push to your branch) that updates BasicJsonParser, GsonJsonParser, and YamlJsonParser to reject bad input in the same way as the other parsers would be most welcome.

**Comment by jadekler** [comment]
Great - I'm on it.

**Comment by philwebb** [comment]
:+1:

**Comment by jadekler** [comment]
@wilkinsona Updated with your tests, and added a little bit of cleanup. Esp wondering if you had feedback on the refactor to JsonSimpleJsonParser for simplicity (not sure if there was an original reason for the `.addAll` stuff it had going on - happy to revert and add a test if so) and the json checking in the form of:

```
if (json == null || json.equals("") || json.startsWith("[")) {
	throw new IllegalArgumentException("Cannot parse JSON");
}
```

**Comment by jadekler** [comment]
Also, random question; how do I run `mvn checkstyle:check` with `src/checkstyle/checkstyle.xml`? I'd like to see the errors that travis CI is giving me but when running checkstyle locally I'm getting hundreds of errors (presumedly because I don't know how to point it at the aforementioned `checkstyle.xml`)

**Comment by snicoll** [comment]
checkstyle is ran as part of the build, "mvn package" should show them...

**Comment by wilkinsona** [comment]
Thanks, @jadekler.

The check style warnings are 99% due to spaces instead of tabs in `AbstractJsonParserTests`. There's also a single unused import in `BasicJsonParser`.

> feedback on the refactor to JsonSimpleJsonParser for simplicity

I like those changes. I'm not sure of the historical reasons for the code being the way it was, but there's less code now and the tests all pass.

>  and the json checking

In wondering about this, I realised there were a few cases that we hadn't considered with leading whitespace:

	@Test
	public void listWithLeadingWhitespace() {
		List<Object> list = this.parser.parseList("\n\t[\"foo\"]");
		assertEquals(1, list.size());
		assertEquals("foo", list.get(0));
	}

	@Test
	public void mapWithLeadingWhitespace() {
		Map<String, Object> map = this.parser.parseMap("\n\t{\"foo\":\"bar\"}");
		assertEquals(1, map.size());
		assertEquals("bar", map.get("foo"));
	}

	@Test
	public void mapWithLeadingWhitespaceListThrowsARuntimeException() {
		this.thrown.expect(RuntimeException.class);
		this.parser.parseMap("\n\t[]");
	}

	@Test
	public void listWithLeadingWhitespaceMapThrowsARuntimeException() {
		this.thrown.expect(RuntimeException.class);
		this.parser.parseList("\n\t{}");
	}

I think fixing these leads, at least in some cases, to the JSON checking logic being inverted to accommodate the call to `trim()`:

    	if (json != null) {
		json = json.trim();
		if (json.startsWith("{")) {
			return new Yaml().loadAs(json, Map.class);
		}
	}
	throw new IllegalArgumentException("Cannot parse JSON");

Let me know if you'd like to make these changes, or if you'd like me to do so as part of merging this. Thanks again.

**Comment by jadekler** [comment]
@wilkinsona Gotcha, that makes sense. I'm happy to make these changes as long as you're in the patient mood for dumb things like spacing problems =) I'm trying to make IntelliJ work for spring PRs but it's not going well heh. Let me pop in this tests and clean up the formatting stuff quickly.

**Comment by jadekler** [comment]
@wilkinsona Donezo - let me know your thoughts. It's basically what you wrote, though =) Much nicer way of doing it.

**Comment by wilkinsona** [comment]
Thanks for your perseverance, @jadekler. I've merged this into master.

**Comment by snicoll** [comment]
:+1:

**Comment by philwebb** [comment]
+1

**Comment by jadekler** [comment]
:+1:

**Pull request closed without merging**
