### PR TITLE
Improvements for the init script

### PR DESCRIPTION
**Pull request by joshiste**
Two separate commits with the following improvements:

1) if present source ${identity}.conf (next to the jar-file) before building the command using JAVA_OPTS and RUN_ARGS. So the .conf file can be used to specify JVM-options and default run-arguments

2) Add LSB-Header to the init-script. Though specifiying spring-boot-application as provides / short descriptions seems a bit odd.

CLA is signed,

### CODE REVIEW

**Comment by philwebb** [comment]
Nice nice nice! :+1: 

One quick question, do you think `/etc` is the best place for `{$identity}.conf` or should we look for it next to the `.jar` file. I'm primarily thinking about parity with `application.properties`.

**Comment by joshiste** [comment]
/etc is the place where our sysadmins would expect the service config. But
when I think of it, it would be reasonable to look for the conf next to the
jar and sym link it in /etc

**Comment by joshiste** [comment]
Updated the PR to look for the .conf file next to the jar

**Comment by philwebb** [comment]
Cool. Thanks

**Comment by bedge** [comment]
+1 vote for this. 
I just submitted a patch for almost the exact same thing :-)
https://github.com/bedge/spring-boot/issues/1

**Comment by philwebb** [comment]
Thanks, I've squashed the commits together and reworked the ordering to follow @bedge's suggestion.

**Pull request closed without merging**
