### PR TITLE
Fix link to Spring Data JPA in docs

### PR DESCRIPTION
**Pull request by cristiangreco**
Fix asciidoc link.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cristiangreco Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=12342)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=12342) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@cristiangreco Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=12342)!

**Comment by wilkinsona** [comment]
Thanks for the PR. Am I right in thinking that the link isn't currently broken? You're just polishing it to use the `spring-data-jpa` attribute?

**Comment by wilkinsona** [comment]
Sorry, ignore that. On closer inspection I can see that it is indeed broken.

**Comment by wilkinsona** [comment]
Thanks again for the PR, @cristiangreco. The proposed change is now in master.

**Pull request closed without merging**
