### PR TITLE
Alternative implementation of PropertyNamePatternsMatcher

### PR DESCRIPTION
**Pull request by dsyer**
When I was trying to understand this stuff again for gh-3385 I found
a few things that seemed unnecessarily complex. This seems more 
straightforward to me.

### CODE REVIEW

**Comment by philwebb** [comment]
We should probably do this in RC1. Do the `psbt` prefixes need to be added in the tests? Just wondering if the old tests work fine with the change?

**Comment by dsyer** [comment]
IIRC the old tests were fine, but I added some more and needed the prefix to get a better separation between tests.

**Comment by philwebb** [comment]
I'm not sure that we should merge the changes to `DefaultPropertyNamePatternsMatcher`. The implementation is a bit odd but it's because of #1823

**Comment by dsyer** [comment]
Do you have some tests we could use to measure it. I see a tiny bit of regex matching in the new implementation, but that could easily be factored out without changing the logic (I think). I don't see anything else that looks dangerous, but only by measuring it would we know.

**Comment by philwebb** [comment]
I think I originally optimized that class following some manual profiling of the pet clinic sample, I can't find any individual performance tests. I've tried adding one [here](https://github.com/philwebb/spring-boot/tree/gh-3402) but I'm not sure how accurately it's simulating real apps.

If memory serves I think the refactoring saved in the region of 50-100ms.

**Comment by dsyer** [comment]
As mentioned in #3515 I think this change is a (potentially significant) optimization for other reasons so we should merge it (maybe change the regex matching bit if you're still worried by it, but since they will be called 30-40 times less often in a PetStore app it seems like we can maybe live with it).

**Comment by philwebb** [comment]
There appears to be quite a large performance hit with this (running timing tests that I added) so I think we need some refactoring.

```
StopWatch '': running time (millis) = 159
-----------------------------------------
ms     %     Task name
-----------------------------------------
00159  100%  

StopWatch '': running time (millis) = 16
-----------------------------------------
ms     %     Task name
-----------------------------------------
00016  100%  




StopWatch '': running time (millis) = 164
-----------------------------------------
ms     %     Task name
-----------------------------------------
00164  100%  

StopWatch '': running time (millis) = 68486
-----------------------------------------
ms     %     Task name
-----------------------------------------
68486  100%  
```

It seems like the significant part of the code that effects #3515 might be `processEnumerablePropertySource`:

Can we just change

```java
if (PropertySourcesPropertyValues.PATTERN_MATCHED_PROPERTY_SOURCES
		.contains(source.getName()) && !includes.matches(propertyName)) {
	continue;
}
```

to

```java
if (!includes.matches(propertyName)) {
	continue;
}
```

Would that be enough? Why did we have the `PATTERN_MATCHED_PROPERTY_SOURCES`? Seems like 94c5203de60cb5755aeb3ca3fbbadc47b9a2e92c was the initial commit that added it.

**Comment by dsyer** [comment]
Do you have those tests somewhere we can share?

**Comment by philwebb** [comment]
There a bit rough around the edges... https://github.com/philwebb/spring-boot/commit/c4fee0c251a46cab78644a15beaf16acc038e69c

**Comment by dsyer** [comment]
I think that test is useful, but it's at the wrong level in the stack to really attack the overall user experience. I think we need a performance test at the level of the `PropertiesConfigurationFactory` because that's the thing that really uses the `PropertySourcesPropertyValues`, which is in turn where the `PropertyNamePatternMatcher` is used. The change in this PR reduces significantly the number of candidate "names" that are plugged into the `PropertyValues`, so it can improve performance from the user's point of view even if the `PropertyNamePatternMatcher` is less efficient.

Here's a test I was using:

```
@RunWith(Theories.class)
public class PropertiesConfigurationFactoryPerformanceTests {

	@DataPoints
	public static String[] values = new String[1000];

	private PropertiesConfigurationFactory<Foo> factory;

	private Validator validator;

	private boolean ignoreUnknownFields = true;

	private String targetName = null;

	private static StandardEnvironment environment = new StandardEnvironment();

	@BeforeClass
	public static void init() {
		EnvironmentTestUtils.addEnvironment(environment, "name: blah", "bar: blah");
	}

	@Theory
	public void testValidProperties(String value) throws Exception {
		Foo foo = createFoo();
		assertEquals("blah", foo.bar);
		assertEquals("blah", foo.name);
	}

	private Foo createFoo() throws Exception {
		setupFactory();
		this.factory.setPropertySources(environment.getPropertySources());
		this.factory.afterPropertiesSet();
		return this.factory.getObject();
	}

	private void setupFactory() throws IOException {
		this.factory = new PropertiesConfigurationFactory<Foo>(Foo.class);
		this.factory.setValidator(this.validator);
		this.factory.setTargetName(this.targetName);
		this.factory.setIgnoreUnknownFields(this.ignoreUnknownFields);
		this.factory.setMessageSource(new StaticMessageSource());
	}

	// Foo needs to be public and to have setters for all properties
	public static class Foo {
		@NotNull
		private String name;

		private String bar;

		public String getName() {
			return this.name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public String getBar() {
			return this.bar;
		}

		public void setBar(String bar) {
			this.bar = bar;
		}

	}

}
```

Without any further optimization this test runs about 5 times slower here than in master (while the pattern matcher is about 1000 times slower). Optimizing a bit I got it to 2 times slower. Maybe if we chip away a bit more we could level them up?

Anyway, the approach here of reducing the number of match candidates seems like it will solve other problems like #3515, so it's worth spending a bit more energy on it.

**Comment by dsyer** [comment]
`PropertiesConfigurationFactoryPerformanceTests` is now in master and in this branch. It runs in 1.6s in master and 2.2s here on my laptop, so fairly comparable. That's binding 1000 `@ConfigurationProperties` beans (so each one takes only a couple of milliseconds, and a typical JPA application would use up 34*2=70ms on startup).

**Comment by philwebb** [comment]
Somethings off with the new `matchWithSeparator` method. Calling it with `targetName=spring.main.bean_name_generator` and `propertyName=java.vm.specification.name` returns `true`.

**Comment by philwebb** [comment]
Fixing `matchWithSeparator` causes `ConfigurationPropertiesBindingPostProcessorTests.notWritablePropertyException` to fail. Probably due to the fact that `test.madeup` never makes it into the `PropertyValues` so `ignoreUnknownFields` isn't aware of it.

**Comment by philwebb** [comment]
Wow, there's a lot of edge cases with the relaxed binding!

I've had another go [here](https://github.com/philwebb/spring-boot/tree/gh-3515) if you want to have a look. The tests pass but I'm still not confident it's correct. I can't to anything on this tomorrow so I'll have another look on Wednesday. I've also found a bug in `DefaultPropertyNamePatternsMatcher` which should probably be fixed in 1.2.x.

**Comment by dsyer** [comment]
I have a fix. I smell a compromise though (e.g. we support "FOO_BAR_SPAM" binding to "foo.barSpam" but not "foo.BAR_SPAM").

**Comment by dsyer** [comment]
Your implementation looks good to me. I can't say for sure we have a test that verifies it, but it seems to fix #3515 as well (in a different way), so that's also good. I would also like to have an explicit test for binding "FOO_BAR_SPAM" to "foo.barSpam".

**Comment by snicoll** [comment]
I second that because that's how I tried to bind an OS env variable and I had to do `FOO_BAR-SPAM` to make it work.

**Comment by philwebb** [comment]
OK, I'll add some tests and also merge in the extra test parts of this PR. Probably tomorrow.

**Pull request closed without merging**
