### PR TITLE
Fix issue #1668: Added support for custom system class loader to enable loading of various classes that are packaged inside nested jars at the system level

### PR DESCRIPTION
**Pull request by aantono**
Added support for custom system class loader to enable loading of various classes that are packaged inside nested jars at the system level

### CODE REVIEW

**Comment by btiernay** [comment]
Just hit an issue in Spark where this would be extremely useful. @philwebb is adding this out of the question?

**Comment by btiernay** [comment]
FYI:

*Storm*
For Storm this is possible with `worker.childopts`:
https://storm.apache.org/apidocs/backtype/storm/Config.html#WORKER_CHILDOPTS

*Spark*
For Spark this is possible with `spark.executorEnv.[EnvironmentVariableName]`:
http://spark.apache.org/docs/1.2.0/configuration.html#runtime-environment

*Hadoop Map Reduce*
For Hadoop this is possible with `mapred.child.java.opts`:
http://hadoop.apache.org/docs/stable/hadoop-mapreduce-client/hadoop-mapreduce-client-core/mapred-default.xml

**Comment by btiernay** [comment]
@aantono Does this implementation work? I can't get it to run without throwing `java.lang.ClassNotFoundException`s. Do you have a sample project I can look at?

**Comment by aantono** [comment]
@btiernay it sure does.  I'll try to whip up a test project to share.  What exact CNFE are you getting?  How is the class being attempted to be loaded?

**Comment by wilkinsona** [comment]
We've discussed this today and have decided that this is an edge case that won't be of use to the vast majority of Boot users. As such, we don't want to take on the burden of maintaining the custom class loader. Instead, we think that those that need this functionality should implement it themselves. If changes are required to the launcher to allow such functionality to be plugged in then we are happy to make them.

**Comment by mooreds** [comment]
Oh bummer.  Would have been nice to have this rolled in so that it was easier to run spring boot under a different security manager.  See my issue linked above.  

Oh well, thanks for considering it.

**Comment by oleksiimiroshnyk** [comment]
Hi @aantono @wilkinsona sorry for rising this old thread, but do you have a solution to share ?
I'm trying to solve pretty much the same issue - define my custom protocol handler.
The issue is that in JDK classes there is code that attempts to load my handler with Classloader.getSystemClassloader(). And of course my classloader is packaged in jar that's inside "uber" jar.
@wilkinsona what changes to launcher do think needs to be done ? Can you outline steps of how to plug in custom classloader to work smooth with spring boot loader etc ?

**Comment by aantono** [comment]
The workaround I've done was to create an implementation of `SpringApplicationRunListener` with an ugly static block hack, as we use Tomcat, and it happen to have its own Handler Factory, which we can take advantage of:

```
private static final String TOMCAT_FACTORY = "org.apache.catalina.webresources.TomcatURLStreamHandlerFactory";

static {
        // Bootstrap handler, before SpringBoot kicks in
        Handler.initialize();
        // This is an UGLY JVM-Spring Boot Hack to work-around the issue of Protocol Handlers only loadable from System Classloader
        //  Since in Spring Boot uber jar the only classes that are loaded directly from System Classloader are the launcher
        //      We will attempt to register ourselves to the Tomcat's TomcatURLStreamHandlerFactory user handler.
        registerWithTomcatIfExists();
}

private static void registerWithTomcatIfExists() {
        try {
            if (ClassUtils.isPresent(TOMCAT_FACTORY, null)) {
                Class<?> clazz = ClassUtils.forName(TOMCAT_FACTORY, null);
                Method register = ReflectionUtils.findMethod(clazz, "register");
                ReflectionUtils.invokeMethod(register, clazz);
                Method getInstance = ReflectionUtils.findMethod(clazz, "getInstance");
                Object handler = ReflectionUtils.invokeMethod(getInstance, clazz);
                Method addUserFactory = ReflectionUtils.findMethod(clazz, "addUserFactory", URLStreamHandlerFactory.class);
                URLStreamHandlerFactory customFactory = new Handler.CustomURLStreamHandlerFactory();
                ReflectionUtils.invokeMethod(addUserFactory, handler, customFactory);
            }
        } catch (ClassNotFoundException e) {
            // Guess something went wrong... :(
            throw new RuntimeException("Unable to add custom protocol Handler to " + TOMCAT_FACTORY, e);
        }
}
```

**Pull request closed without merging**
