### PR TITLE
HTTP response format details for health endpoint.

### PR DESCRIPTION
**Pull request by luispollo**
When going through the Spring Boot documentation for production-ready endpoints, I missed having details about how the health endpoint responses look like, especially the HTTP status codes and response body format. I hope to contribute to improve that area of the document with this small change.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@luispollo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8703)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8703) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@luispollo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8703)!

**Comment by wilkinsona** [comment]
Thanks for the PR. We may merge this as a temporary step in the right direction, but I think that the long-term fix for this should be https://github.com/spring-projects/spring-boot/issues/8042.

**Comment by luispollo** [comment]
Thanks for the feedback @wilkinsona. I agree. I noticed the separate actuator docs -- which is where I got the samples from :) -- but was unaware of #8042. Up to you to merge if you think it's worth it.

**Comment by philwebb** [comment]
I think it's worth merging this to 1.4.x since we probably won't get to #8042 in a maintenance release. Thanks for the contribution.

**Comment by luispollo** [comment]
Thanks @philwebb. My pleasure.

**Pull request closed without merging**
