### PR TITLE
Fix typo in howto.adoc

### PR DESCRIPTION
**Pull request by YooInKeun**
I think there are some typo in `spring-boot-docs/src/docs/asciidoc/howto.adoc`.
Thank you for reading my PR.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@YooInKeun Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20313)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20313) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@YooInKeun Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20313)!

**Comment by snicoll** [comment]
Well spotted @YooInKeun and thank you for making your first contribution to Spring Boot.

**Comment by YooInKeun** [comment]
Thank you!

**Pull request closed without merging**
