### PR TITLE
Create tests for gh-11367

### PR DESCRIPTION
**Pull request by mederly**
Tests that illustrate #11367 (second try).

### CODE REVIEW

**Comment by wilkinsona** [comment]
@rwinch Can you please help us out here? As noted in #11367, @mederly has signed the CLA but the check continues to fail.

**Comment by wilkinsona** [comment]
@mederly I think the email address you used to sign the CLA may have to match the email address you used for the commit included in the PR (@rwinch, please correct me if I am mistaken). Can you please confirm that's the case?

**Comment by mederly** [comment]
@wilkinsona The email address used in the commit is "mederly@evolveum.com". In my github account I have two email addresses: a gmail one (marked as Primary, Public, Notifications) and mederly@evolveum.com. Maybe that's the problem ... I can make the evolveum one to be primary and public.

As for the CLA, it was signed by our company, Evolveum. I am a publicly-visible member of it.

So, I am going to mark mederly@evolveum.com address to be Primary and Public.

**Comment by mederly** [comment]
@wilkinsona I no longer see "manually synchronize" link on this PR, so I am going to close it and create new one. I am sorry for that mess. Hope it will work.

**Pull request closed without merging**
