### PR TITLE
Add MongoClientFactoryBean as a ConditionalClass

### PR DESCRIPTION
**Pull request by julien-may**
The class EmbeddedMongoAutoConfiguration.EmbeddedMongoDependencyConfiguration extends
MongoClientDependsOnBeanFactoryPostProcessor that uses MongoClientFactoryBean to ensure
that MongoClient beans depend on the embeddedMongoServer bean.

To prevent a MongoClientFactoryBean ClassNotFoundException, the MongoClientFactoryBean was
added to the ConditionalOnClass to prevent creating the Post Processort in case it is missing,
e.g. using the EmbeddedMongoAutoConfiguration without spring data mongo

- [X] I have signed the CLA

### CODE REVIEW

**Comment by snicoll** [comment]
Can you please make that change from the `1.3.x` branch? We'll merge it forward to master. You can push force on your existing branch, please do not create another PR.

**Comment by julien-may** [comment]
I made the changes on the `1.3.x` branch and then non fast forwarded the changes also to the master branch.

still if you want me to only do the change in the branch, i have to create a new PR, as i cannot change the source/target (`spring-projects:master` from `julien-may:master`)

**Comment by snicoll** [comment]
oh well, that's why PR are better made of a dedicated branch.

**Comment by julien-may** [comment]
https://github.com/spring-projects/spring-boot/pull/6203

**Pull request closed without merging**
