### PR TITLE
Make it easier to override FILE_LOG_PATTERN

### PR DESCRIPTION
**Pull request by sangwook**
Make it easier to override FILE_LOG_PATTERN.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sangwook Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=6782)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=6782) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sangwook Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=6782)!

**Comment by wilkinsona** [comment]
@sangwook Thanks for the PR, I've merged it into 1.5.x.

**Comment by joshuawhite929** [comment]
Given that the same feature is available for overriding the CONSOLE_LOG_PATTERN in 1.4.3, can we consider pulling this into the 1.4.x pipeline instead of waiting for 1.5?  Right now, you can override CONSOLE_LOG_PATTERN but can't override FILE_LOG_PATTERN which is inconsistent.  Thoughts?

**Comment by wilkinsona** [comment]
1.5.0.RELEASE is scheduled for tomorrow so you don't have long to wait. I am not in favour of back porting enhancements into a 1.4.x maintenance release.

**Comment by joshuawhite929** [comment]
This works out well.  I didn't know the 1.5 release was so close

**Pull request closed without merging**
