### PR TITLE
Use StandardCharsets where possible

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

this PR replaces `Charset.forName(...)` with its StandardCharsets counterparts if possible,

Cheers,
Christoph

### CODE REVIEW

**Comment by dreis2211** [comment]
Tests seem to be failing - will take a look. Sorry for the inconveniences.

**Comment by izeye** [comment]
@dreis2211 I deliberately leaved them as is in https://github.com/spring-projects/spring-boot/pull/10972 because it looked like a limitation of collecting initial values in configuration metadata annotation processor as you could see in https://ci.spring.io/builds/16769.

**Comment by dreis2211** [comment]
@izeye I'm seeing the same limitation, though reverting to the previous state doesn't seem to help at the moment. The test won't run anymore.

**Comment by dreis2211** [comment]
@izeye & @snicoll  I think I got it working with extending the well-known static finals in `JavaCompilerFieldValuesParser` by some of the more default StandardCharsets (omitting the special UTF-16 ones).

**Pull request closed without merging**
