### PR TITLE
Upgrade to Testcontainers 1.14.1

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

this PR upgrades to Testcontainers 1.14.1.

Cheers,
Christoph

### CODE REVIEW

**Comment by snicoll** [comment]
We are still discussing whether we want to accept certain "only version" upgrades PR, see #20707. I am going to put this one on-hold until we get a chance to finalize this discussion.

**Comment by dreis2211** [comment]
Sure thing. I kept myself quite for a bit as the version was released two weeks ago already, I think. If that contributes to the discussion a bit.

**Comment by philwebb** [comment]
We should upgrade this anyway, regardless of #20707. I'm not sure if BOMR will pick it up so I'll drop it in 2.3.0 just so we don't forget.

**Comment by dreis2211** [comment]
Bomr won't pick it up. That's part of the discussion: if one-liner upgrades should be rejected even though they're not picked up by bomr (which is essentially only stuff spring-boot-dependencies)

**Comment by snicoll** [comment]
Thanks for that @dreis2211.

> I kept myself quite for a bit as the version was released two weeks ago already, I think.

As I've indicated [in this comment](https://github.com/spring-projects/spring-boot/issues/20707#issuecomment-628076147), it is less important/urgent to upgrade an internally managed dependency. We do so when we could benefit from a new feature or the dependency fixed an issue we're facing. Otherwise, such upgrade happens in due course as part of a general chore similar to how we apply bomr upgrades.

**Comment by dreis2211** [comment]
I think the perfect solution is teaching Bomr to handle internal dependencies, too - as suggested in #21439 . That avoids manual work 👍

**Pull request closed without merging**
