### PR TITLE
Polish

### PR DESCRIPTION
**Pull request by izeye**
This PR fixes some typos and polishes trivial stuff.

### CODE REVIEW

**Comment by mhalbritter** [comment]
Hi @izeye, thanks for the PR. The last file change doesn't match the other file changes (documentation updates), i think it belongs to a new PR. Apart from that, the PR looks good. Could you please move the last file change to a separate PR?

**Comment by izeye** [comment]
@mhalbritter Thanks for the feedback!

I thought that mixing the two is okay in this repo when they all belong to trivial polishing like https://github.com/spring-projects/spring-boot/pull/29157. If the suggested arrangement is preferred, I'm happy to follow. Just let me know.

**Comment by mhalbritter** [comment]
Hey, ignore my comment. Just learned that we split the commits if we need to.

I think the doc changes are applicable to earlier versions of Spring Boot (2.5.x), too. I'll merge the PR.

**Comment by mhalbritter** [comment]
Merged, thanks a lot!

**Pull request closed without merging**
