### PR TITLE
Fix doc root detection when running in IntelliJ IDEA

### PR DESCRIPTION
**Pull request by JoeKerouac**
Fix doc-root not found when running in IDEA.
#14246

### CODE REVIEW

**Comment by snicoll** [comment]
@JoeKerouac in the future could you please run the build locally and check rather than pushing those individual commits? That generates quite some unnecessary notification noise. Thanks.

**Comment by JoeKerouac** [comment]
@snicoll OK.

**Comment by wilkinsona** [comment]
Thanks for the PR, @JoeKerouac. Unfortunately, I'm not too keen on having the amount of IDE-specific code in `DocumentRoot`, particularly as that class isn't only used during development. Can you please describe the problem that you're facing and why these changes are necessary to solve it?

**Comment by JoeKerouac** [comment]
When I run the Spring-boot project in Idea, my project contains JSP, there may be a problem with my usage, spring-boot does not find my JSP page correctly, I found the problem by debug Doc-root, When I try to add the above code, he can work normally. In addition, I was in the construction of the Spring-boot project itself has been an error, the environment is CENTOS+OPENJDK8, with the project mvnw.
@wilkinsona

**Comment by JoeKerouac** [comment]
Sorry, this problem appeared in our project. I thought it was a spring-boot problem. I didn’t confirm it afterwards. I just found a simple demo and found that the problem has not been reproduced. It may be that our project may also have problems. It is an environmental issue, I will confirm it again. Finally, thank you for your patience. @wilkinsona

**Comment by wilkinsona** [comment]
Thanks for following up. I'll close this one for now. If we need to revisit this, it's probably best to use #14246 to precisely identify the problem and determine a solution.

**Pull request closed without merging**
