### PR TITLE
Document Settings as jooq supported auto-configuration type

### PR DESCRIPTION
**Pull request by djarnis73**
It is being loaded here: https://github.com/spring-projects/spring-boot/blob/62faab6e60681e90d5ce2ee4280b06de116e7032/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jooq/JooqAutoConfiguration.java#L111

See also https://stackoverflow.com/questions/57542573/how-to-configure-jooq-settings-using-spring-boot-config/58701946#58701946

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@djarnis73 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18870)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18870) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by djarnis73** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@djarnis73 This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by pivotal-issuemaster** [comment]
@djarnis73 This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by snicoll** [comment]
@djarnis73 good catch and thank you for making your first contribution to Spring Boot.

**Pull request closed without merging**
