### PR TITLE
Axibase Time-Series Database Metric Writer.

### PR DESCRIPTION
**Pull request by alexandertokarev**
Enables built-in and custom metric persistence into ATSD (Axibase Time-Series Database) using HTTP API endpoint.

### CODE REVIEW

**Comment by alexandertokarev** [comment]
I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

**Comment by rodionos** [comment]
Greetings. Can we see some progress on this PR? It's been sitting in the triage queue for quite a while. Failing boot db init tests have been merged on Oct 5. Go/NoGo/Discuss?

**Comment by rodionos** [comment]
Thanks, Phil. Let me know if you need any info to kick off a discussion on the ATSD writer integration. ATSD is developed by Axibase and commit to two things: a) keep the right synchronized with ATSD API changes and b) resolve issues raised directly in spring-boot with an ETA of 5 days for critical and ETA of 2 weeks for other defects.

**Comment by philwebb** [comment]
Thanks for the PR, I'm afraid we're probably not going to have time to get this into 1.4. We'll review again and consider it for 1.5.

**Comment by rodionos** [comment]
@philwebb Good to know. The code is rather simple, it's based on other storage drivers' code to minimize the footprint. What's the ETA for 1.5?

**Comment by philwebb** [comment]
@rodionos We've got no ETA as yet. Still trying to get 1.4 out the door :)

**Comment by pivotal-issuemaster** [comment]
@alexandertokarev Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=4066) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by philwebb** [comment]
Sorry for the very long delay in getting to this. We're not keen to add direct ATSD integration into Boot itself at the moment and we feel like this would be better as a third-party project. You can find some details about creating a starter in the [reference docs](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter).

Thanks!

**Pull request closed without merging**
