### PR TITLE
Fix typos and formatting errors in documentation

### PR DESCRIPTION
**Pull request by ngocnhan-tran1996**
I fixed typo document

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks. The `tag::code[]` comments should not be required, are you seeing problems with those samples?

**Comment by wilkinsona** [comment]
As shown in the docs, the Kotlin snippets are empty at the moment: https://docs.spring.io/spring-boot/reference/io/jta.html#io.jta.mixing-xa-and-non-xa-connections

**Comment by philwebb** [comment]
Thanks @wilkinsona. We might want to go the other way and update the Java samples to remove the code tag, that way imports can be shown in the sample.

**Comment by ngocnhan-tran1996** [comment]
@philwebb 
I removed the code tag in Java sample and reverted the code tag in Kotlin sample in local. The result is the code snippets are empty, both Java and Kotlin

**Comment by wilkinsona** [comment]
I think the includes need to be updated as well to remove `[tag=*]`.

**Comment by ngocnhan-tran1996** [comment]
Thanks @wilkinsona 

It works. I will update PR

**Comment by philwebb** [comment]
Thanks very much @ngocnhan-tran1996

**Pull request closed without merging**
