### PR TITLE
Check if a bean of type Client is not already registered in the context.

### PR DESCRIPTION
**Pull request by ptahchiev**
If I decide to create my own instance of the elasticsearch `Client` bean than my app fails to start because it finds 2 instances - one from boot and my instance. I think a `@ConditionalOnMissingBean` annotation needs to be added.

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks but please push a single commit with on your change (and no unrelated formatting). You can push force on this branch to update the PR.

**Comment by ptahchiev** [comment]
I have fixed the formatting but it is still several commits. I don't know the command to make it a single commit :(

**Comment by snicoll** [comment]
`git rebase` and squash them. But that's ok, I can manage that for you.

**Comment by ptahchiev** [comment]
Thanks

**Comment by snicoll** [comment]
Thanks for the PR but I got conflict when rebasing it due to the unrelated commit in this PR so since it was one line long, it was much easier for me to roll my own (that gave me the opportunity to create a test for it as well).

**Pull request closed without merging**
