### PR TITLE
Add reference to amqp-rabbit-spring-boot-autoconfigure

### PR DESCRIPTION
**Pull request by EugeneMsv**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@EugeneMsv Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=17537)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=17537) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by snicoll** [comment]
@EugeneMsv Thanks for the proposal. This starter does not comply with our naming requirements, I've created https://github.com/EugeneMsv/spring-amqp-rabbit-configurator/issues/1

**Comment by pivotal-issuemaster** [comment]
@EugeneMsv Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=17537)!

**Comment by snicoll** [comment]
Thanks for the update @EugeneMsv

**Pull request closed without merging**
