### PR TITLE
Add docker-java-spring-boot-starter

### PR DESCRIPTION
**Pull request by jliu666**
Add a docker-java-spring-boot-starter. It's a docker api client. I think many people need it.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jliu666 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=12532)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=12532) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jliu666 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=12532)!

**Comment by jliu666** [comment]
What happened? I just edit one file!

**Comment by jliu666** [comment]
What happened? I just edit one file!

**Comment by jliu666** [comment]
What happened? I just edit one file!

**Pull request closed without merging**
