### PR TITLE
Do not replace a request factory when creating a new `TestRestTemplate` with `withBasicAuth`

### PR DESCRIPTION
**Pull request by nosan**
See gh-15443

### CODE REVIEW

**Comment by mbhave** [comment]
@nosan Thanks for the PR but I don't think this is how we intended to fix it. We want to avoid using the same `reuqestFactory` instance when using `withBasicAuth`. For more details on why, take a look at the [commit message](https://github.com/spring-projects/spring-boot/commit/db7268b841b9b90d498822b4ab37981792303126) here.

I think what we'd want to do instead is use the supplier to create a new instance of the custom `requestFactory` class and if that fails, fallback to the current behavior. @bclozel WDYT?

**Comment by bclozel** [comment]
I agree with your analysis @mbhave (and sorry about the late reply, that notification got lost in my inbox).

**Comment by mbhave** [comment]
Thanks @bclozel. 

@nosan Do you want to update the PR to do what I've mentioned above?

**Comment by nosan** [comment]
@mbhave 
Sorry for the long delay, sure, I can update the PR. I am not sure, that I understood you correctly, hence, just to make sure, could you please provide more information about your approach? 
Thanks in advance.

**Comment by bclozel** [comment]
@nosan in the current PR, `withBasicAuth` is retrieving the current request factory instance from the embedded `RestTemplate` and reusing it. This line doesn't really change the behavior we're trying to fix.

Several HTTP client libraries are caching the authentication information at the connection pooling level. This means that reusing the same request factory will result in sending the Cookie request header even if the authentication was not meant to be included.

Creating a brand new instance of the configured request factory class (or as Madhura mentioned, falling back to the current behavior in case of problems) should avoid those issues. You can look at the `ClientHttpRequestFactorySupplier` to check how factories are instantiated.

**Comment by nosan** [comment]
@mbhave @bclozel Thanks, 
I have updated the PR, please let me know.

**Comment by mbhave** [comment]
Thanks again, @nosan. This is now on master along with [this additional test](https://github.com/spring-projects/spring-boot/blob/0611eb49c87f367d3e34a1a3bcf04eb70150d180/spring-boot-project/spring-boot-test/src/test/java/org/springframework/boot/test/web/client/TestRestTemplateTests.java#L112).

**Comment by nosan** [comment]
@mbhave Thanks!

**Pull request closed without merging**
