### PR TITLE
Update htmlunit.version to 2.23

### PR DESCRIPTION
**Pull request by ylu999**
Fix issue #7232

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ylu999 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7233)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7233) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ylu999 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7233)!

**Comment by wilkinsona** [comment]
This needs to be merged with care. Up till now, we've used the same property for HTML Unit and Selenium's HTML Unit Driver, however they've diverged in 2.23 where the driver's had a couple of bug fixes so its version should be 2.23.2. That means we'll have to start using a separate property for the driver.

**Comment by philwebb** [comment]
Thanks for the PR. As Andy mentioned we'll need a new property to deal with the drift. I've added that and will push shortly.

**Pull request closed without merging**
