### PR TITLE
fix typo in javadoc

### PR DESCRIPTION
**Pull request by rtack**
{@code tomat-embedded.jar} --> {@code tomcat-embedded.jar}

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks. Have you signed the CLA?

**Comment by wilkinsona** [comment]
@snicoll I think a one character typo correction falls into the trivial bucket so there's no need for the CLA, imo

**Comment by snicoll** [comment]
I realized that 5 minutes after asking and forgot to correct. Need more coffee over here. Sorry @rtack

**Comment by snicoll** [comment]
Merged, thanks!

**Pull request closed without merging**
