### PR TITLE
Allow MetricsFilter to be configured to include HTTP method in metric name

### LINKED ISSUE #4913: Allow MetricsFilter to be configured to include HTTP method in metric name
We're providing an REST API that uses the same URI with different methods (GET, POST, PUT, DELETE).
By coincidence we chose status codes allowing us to distinguish between those methods (200, 201, 204), but that is certainly not the case for similar applications. Although this helps with counter metrics, the gauge metric is reported without the status being included in the metric name, such that distinguishing the execution time fails even for our lucky status choices.

So it would be great to have a property with which to enable that. I'd come up with a PR if you're supportive of the idea.

### PR DESCRIPTION
**Pull request by sebastiankirsch**
Allow MetricsFilter to be configured to include HTTP method in metric name

### CODE REVIEW

**Comment by sebastiankirsch** [comment]
My contributor agreement's confirmation number is 161720160206115804

**Comment by philwebb** [comment]
I've squashed the commits and tweaked a few things here [1]. I think we should consider the names of the new properties before merging.

[1] https://github.com/philwebb/spring-boot/tree/gh-4913

**Comment by sebastiankirsch** [comment]
Sure thing, naming is the hardest part of this PR. I tried to use the terms @wilkinsona was using... please choose whatever you feel suits best.

**Comment by philwebb** [comment]
Thanks, I've merged with a few tweaks.

**Pull request closed without merging**
