### PR TITLE
Add Mono and Flux REST endpoints to spring-boot-samples/spring-boot-s…

### PR DESCRIPTION
**Pull request by daggerok**
Hello, I've just added few reactor-like REST-endpoints to make spring-boot-sample-webflux project more helpful for developers who wants see usage of it in action in regular spring REST-controllers

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@daggerok Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8496)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8496) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@daggerok Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8496)!

**Comment by snicoll** [comment]
@daggerok thank you for the pull request but we don't use the samples as a way to learn the actual features. In Spring Boot land we use the samples to show how you can put the bits together from an infrastructure standpoint. That's exactly what this sample is doing and I'd be more in favour of a Spring WebFlux guide. Having said that, our only current method could return a `Mono` indeed.

What do you think @bclozel ?

**Comment by daggerok** [comment]
hello, @snicoll
I understand
so should I close this pull request?

**Comment by philwebb** [comment]
@daggerok I've closed this one, but if you're interested in submitting a guide they're at https://github.com/spring-guides

**Pull request closed without merging**
