### PR TITLE
Run CompositeHealthIndicator in parallel

### PR DESCRIPTION
**Pull request by RikEnde**
See https://github.com/spring-projects/spring-boot/issues/2652

**Problem:** 
The CompositeHealthIndicator polls all the HealthIndicators in the registry sequentially. I have a number of HealtIndicator components that poll remote systems and report on latency and status, and the latency really adds up, especially if there are time-outs involved. 

**Solution:** 
This PR polls the HealthIndicators concurrently. It preserves the original ordering, and outputs the same as the old implementation, except the runtime is proportional to that of the slowest component, rather than the aggregate of all components. The impact of this change should be very small, unless someone's code absolutely depends on HealthIndicators being polled sequentially but in unknown order.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@RikEnde Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15770)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15770) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@RikEnde Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15770)!

**Comment by RikEnde** [comment]
I'm pretty sure my commit didn't break the build or cause that timeout...

**Comment by snicoll** [comment]
@RikEnde you are right, your change did not break the build.

We have a task execution infrastructure now in place and we'd rather use that if it's available rather than using `parallelStream`. Thanks for the PR, in any case.

**Comment by RikEnde** [comment]
Fair enough. Are you referring to the ConcurrentTaskExecutor, or something new?

**Pull request closed without merging**
