### PR TITLE
Allow configuring WebDriver with TestNG

### PR DESCRIPTION
**Pull request by cdalexndr**
Accessible webdriver test execution listener for testng:
`@TestExecutionListeners({WebDriverTestExecutionListener.class})`

Access `WebDriverScope.NAME` outside package to be used by user webdriver implementations. Needs matching name to be picked up by autoconfiguration.
```
@Bean(name = WebDriverScope.NAME)
public WebDriver customWebDriver() {...
```

See https://github.com/spring-projects/spring-boot/issues/27921

### CODE REVIEW

**Comment by cdalexndr** [comment]
Should I add `@since` when the feature was originally created, or current version when I made them public?

**Comment by wilkinsona** [comment]
When they were made public, please.

**Comment by wilkinsona** [comment]
@cdalexndr Thanks for the pull request. Unfortunately, we can't merge this until we understand why it's needed so that we can justify increasing the surface area of our public API. As [@philwebb requested](https://github.com/spring-projects/spring-boot/issues/27921#issuecomment-917536318), can you please provide a sample for #27921?

**Comment by wilkinsona** [comment]
We [have a sample](https://github.com/spring-projects/spring-boot/issues/27921#issuecomment-931345119) so I don't think we're waiting for feedback.

**Comment by wilkinsona** [comment]
We made changes in the past – such as [these](https://github.com/spring-projects/spring-boot/pull/7630) – in support of TestNG. 3.0 gives us an opportunity to decide if supporting TestNG is something with which we want to continue.

**Pull request closed without merging**
