### PR TITLE
Trim whitespace from configured value for a log level

### PR DESCRIPTION
**Pull request by dileepbapat**
This is to remove unwanted spaces in the configuration file for log level.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dileepbapat Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15143)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15143) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dileepbapat Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=15143)!

**Comment by philwebb** [comment]
@dileepbapat Did you have a specific issue that lead you to wanting this change? I'm curious how you were specifying the logging levels (YAMl, Properties, Environment Variable).

I'm also wondering if the code wouldn't be better in the `coerceLogLevel` method. We should also add a test for this.

**Comment by dileepbapat** [comment]
Yes, setting in property file or environment variable are having this issue. I haven't checked with yaml.

Yeah it make sense to move it to coerceLogLevel and add tests. will check no that

**Comment by wilkinsona** [comment]
@dileepbapat Thank you very much for making your first contribution to Spring Boot. I have merged your changes into master along with a [polish commit](
https://github.com/spring-projects/spring-boot/commit/e1ad5641d5f8c37b42e66a436fb470fe52049697) that, primarily, makes the change suggested by @philwebb and adds a test.

**Pull request closed without merging**
