### PR TITLE
Default to optimized launch of the JVM when using spring-boot:run

### PR DESCRIPTION
**Pull request by dosdebug**
Fix for #16222

### CODE REVIEW

**Comment by dosdebug** [comment]
@wilkinsona Thank you for the feedback. I have updated the PR with suggestions. Please review when you have time and suggest if there is anything I missed or should have done in a better way. Thanks a lot.

**Comment by dosdebug** [comment]
I see that it's failing because of the format, fixing it, will push in few minutes.

**Comment by snicoll** [comment]
Interesting to see that that `-Xverify:none` is deprecated in Java 13 https://bugs.openjdk.java.net/browse/JDK-8218003

**Comment by snicoll** [comment]
@dosdebug thank you for making your first contribution to Spring Boot. This is now merged in `master` with a [polish commit](https://github.com/spring-projects/spring-boot/commit/4cdb5a8ecb31dcdc5a43c0172002dfbc277a2284).

@wilkinsona I didn't notice you were assigned until I had everything ready to go, hope there isn't any wasted effort there.

**Comment by wilkinsona** [comment]
No problem, @snicoll. I hadn't started work on merging it. I've just reverted the issue's title back to the [one is used earlier](https://github.com/spring-projects/spring-boot/pull/16941#event-2367156139) which aligns it with the corresponding issue for Gradle.

**Pull request closed without merging**
