### PR TITLE
TestRestTemplate does not allow redirects to be customized

### PR DESCRIPTION
**Pull request by quaff**
Closes GH-27360

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks @quaff. I've simplified things a bit in 8b83afdb681a9e889857dd06c4df557a27e1c042 so that we're no longer needing so many changes to `TestRestTemplateBuilder`. For folks that want specific redirect behavior they can pass in a configured `RestTemplateBuilder` and use your new `redirects(...)` method.

There's still some more improvements I'd like to make to `TestRestTemplateBuilder` in #43422, but those can wait until 3.5

**Comment by quaff** [comment]
> Thanks @quaff. I've simplified things a bit in [8b83afd](https://github.com/spring-projects/spring-boot/commit/8b83afdb681a9e889857dd06c4df557a27e1c042) so that we're no longer needing so many changes to `TestRestTemplateBuilder`. For folks that want specific redirect behavior they can pass in a configured `RestTemplateBuilder` and use your new `redirects(...)` method.
> 
> There's still some more improvements I'd like to make to `TestRestTemplateBuilder` in #43422, but those can wait until 3.5

@philwebb You removed `TestRestTemplate::withRedirects` in [8b83afd](https://github.com/spring-projects/spring-boot/commit/8b83afdb681a9e889857dd06c4df557a27e1c042), then how to create a new `TestRestTemplate` base on the injected one?

**Comment by philwebb** [comment]
That's a good point, I overlooked the injection. I was keen to not add more public API to `TestRestTemplate`, but duplicating `org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer.TestRestTemplateFactory` in tests will be a bit cumbersome.

I'll reopen the issue to consider things a bit more.

**Comment by philwebb** [comment]
Thanks again for the feedback @quaff. I've added a `withRequestFactorySettings` methods that should allow you to apply settings that include alternative redirects. Let me know if that works for you.

**Comment by quaff** [comment]
> Thanks again for the feedback @quaff. I've added a `withRequestFactorySettings` methods that should allow you to apply settings that include alternative redirects. Let me know if that works for you.

Still not able to update redirects base on underlying settings, I created https://github.com/spring-projects/spring-boot/pull/43444.

**Comment by philwebb** [comment]
@quaff Do you need to be able to update just the redirects? I assumed that using a complete `ClientHttpRequestFactorySettings` would be enough for most people.

**Comment by quaff** [comment]
> @quaff Do you need to be able to update just the redirects?

Yes.

**Comment by quaff** [comment]
I like the `UnaryOperator` as customizer, thanks. @philwebb

**Pull request closed without merging**
