### PR TITLE
Add support for descriptions of record components in configuration metadata generation

### PR DESCRIPTION
**Pull request by An1s9n**
Hello everyone!

While working on PR #29010 I've noticed that now there is no way to automatically generate descriptions in configuration metadata if you use `@ConfigurationProperties` with record class. Indeed, there are no explicit fields to put regular field-level Javadocs on. But there is an official way for records to do so: descriptions should be provided via class-level Javadoc tag `@param`.

I've added support for such usage, added test and mentioned it in reference documentation. I assume test is clear enough for understanding what I've done. Hope build will pass :)

### CODE REVIEW

**Comment by Peksa** [comment]
Hi! Has there been any updates and/or design work on this?

**Comment by tudburley** [comment]
Are there any news on this issue?

**Comment by wilkinsona** [comment]
@tudburley Please see my [earlier comment](https://github.com/spring-projects/spring-boot/pull/29403#issuecomment-1568785317).

**Comment by JWT007** [comment]
Hello Spring team, any updates on this - one year since last update...came here with same problem.

**Comment by wilkinsona** [comment]
@JWT007, please read the preceding comments before adding one of your own. This has already been [answered above](https://github.com/spring-projects/spring-boot/pull/29403#issuecomment-1568785317).

**Comment by JWT007** [comment]
> @JWT007, please read the preceding comments before adding one of your own. This has already been [answered above](https://github.com/spring-projects/spring-boot/pull/29403#issuecomment-1568785317).

@wilkinsona I of course read the preceding comments- Your last comment regarding status was one year ago and your last comment with real content regarding the issue is over two years old.  In the meantime Java records have solidly arrived and I thought *just maybe* there was some progress or new information.

**Comment by philwebb** [comment]
Thanks very much for the PR @An1s9n, and for your patience whilst we got around to merging it.

I've just merged this into main so that it will be available as part of the 3.3 release. Ordinarily we wouldn't make changes like this post RC, but I think it's worth making an exception for this one since it's relatively isolated and a lot of folks have voted on the issue.

For anyone watching this issue, please give the SNAPSHOT a try (when https://github.com/spring-projects/spring-boot/actions/runs/8788352195 has finished) and let us know if there are problems. We have a few weeks to iron out any issues.

**Pull request closed without merging**
