### PR TITLE
Set a default paths for fixed static version

### PR DESCRIPTION
**Pull request by kazuki43zoo**
I've set a default paths(`/**`) for allow as following settings:

* `src/main/resources/application.yml`

```yaml
spring:
  resources:
    chain:
      strategy:
        fixed:
          enabled: true
          version: 1.0.0
#        paths: /**
```

Currently, in this case, the `NullpointerException` occurred as follow:

```console
...
Caused by: java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203) ~[na:1.8.0_66]
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813) ~[na:1.8.0_66]
	at java.util.Arrays.asList(Arrays.java:3800) ~[na:1.8.0_66]
	at org.springframework.web.servlet.resource.VersionResourceResolver.addFixedVersionStrategy(VersionResourceResolver.java:123) ~[spring-webmvc-4.3.0.BUILD-20160505.171705-382.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$ResourceChainResourceHandlerRegistrationCustomizer.getVersionResourceResolver(WebMvcAutoConfiguration.java:432) ~[spring-boot-autoconfigure-1.4.0.BUILD-SNAPSHOT.jar:1.4.0.BUILD-SNAPSHOT]
...
```

- [x] I have signed the CLA

### CODE REVIEW

**Comment by wilkinsona** [comment]
@bclozel What's your take on this? Should we provide a default (and if so is `/**` a sensible default) or should we fail fast if `paths` isn't specified?

**Comment by bclozel** [comment]
When using resource chain strategies, one usually end up with one of the following use cases:

1. Configuring a unique content strategy to get resource paths like `/css/main-b4df00d.css`; in that case, the default path mapping `/**` for that strategy is a good choice. This is already the default
2. Configuring a unique fixed version strategy to get resource paths like `/v1.0.0/css/main.css`; in that case, the default `/**` is also a good choice.
3. Configuring both strategies to have a content strategy for css/images like `/css/main-b4df00d.css` and a fixed version for JavaScript modules, like `/v1.0.0/lib/module.js`

For use case number 3, keeping the default paths would result in a "collision"; in fact, since the content strategy is configured *after* the fixed strategy in MVC, the `/**` mapping is then only associated with the content strategy. Resource URLs won't be rewritten using the fixed strategy.

With all that in mind, I don't see any reason not to add `/**` as a default in that case.

In order to avoid such collisions, MVC could log/throw errors when different strategies share the same patterns.

**Comment by wilkinsona** [comment]
@bclozel Thanks!

**Comment by wilkinsona** [comment]
@kazuki43zoo Thanks for the PR. I've merged it into master.

**Comment by kazuki43zoo** [comment]
@wilkinsona , thanks for merging and fix the document !!

**Pull request closed without merging**
