### PR TITLE
If at least one couchbase node is connected to the cluster, couchbase is in up the health indicator

### PR DESCRIPTION
**Pull request by Rohatsahin**
In the couchbase java sdk [documentation](https://docs.couchbase.com/java-sdk/current/howtos/health-check.html), the cluster state diagnostic is specified as degraded when at least one node is connected.
However, cluster state is expected online for couchbase health indicator in method isCouchbaseUp in class CouchbaseHealth and this makes the application look unhealthy while couchbase is at least operational.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Rohatsahin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=25726)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=25726) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Rohatsahin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=25726)!

**Comment by wilkinsona** [comment]
Thanks for the suggestion but it is contrary to [the recommendation](https://github.com/spring-projects/spring-boot/issues/14685#issuecomment-429707626) that we received from the Couchbase team. We could perhaps make the mapping of ClusterState.DEGRADED configurable, but I don't think we should change the default behaviour.

**Comment by Rohatsahin** [comment]
> Thanks for the suggestion but it is contrary to [the recommendation](https://github.com/spring-projects/spring-boot/issues/14685#issuecomment-429707626) that we received from the Couchbase team. We could perhaps make the mapping of `ClusterState.DEGRADED` configurable, but I don't think we should change the default behaviour.

**Comment by Rohatsahin** [comment]
thanks @wilkinsona, we encountered this situation when a node exits the cluster and this situation affects the readiness probe in Kubernetes. I think then we'll have to remove the couchbase health indicator

**Comment by wilkinsona** [comment]
It's worth giving some thought to which external services belong in the readiness group as, if that service is shared, a single outage can lead to cascading failures as all application instances report that they aren't ready to handle traffic.

If you'd like us to consider making whether `DEGRADED` maps to `UP` or `DOWN` configurable, please open an issue. Thanks again for the pull request, but I think it's best that we close this one as we don't want to change the default behaviour.

**Pull request closed without merging**
