### PR TITLE
Remove an unnecessary statement

### PR DESCRIPTION
**Pull request by izeye**

### CODE REVIEW

**Comment by snicoll** [comment]
What makes you think it's unnecessary?

**Comment by izeye** [comment]
@snicoll I just thought it's added accidentally. Sorry but could you explain the purpose of the statement?

**Comment by snicoll** [comment]
Sorry I had to look at the code in the ide to figure things out. It's indeed unnecessary, thanks for spotting that!

**Comment by izeye** [comment]
@snicoll No problem :+1:

**Pull request closed without merging**
