### PR TITLE
Fix: additional-spring-configuration-metadata.json is not being merged when building with Gradle 4

### LINKED ISSUE #9732: additional-spring-configuration-metadata.json is not being merged when building with Gradle 4
Set up the simplest possible app according to the documentation wrt generating spring configuration metadata along with `additional-spring-configuration-metadata.json` for those additional "hints" to be merged into the main metadata file. It does not seem to work.

https://github.com/dima767/additional-config-metadata-not-working

Try `./gradlew clean build` or `./gradlew clean bootRun`

This is Boot `1.5.4` and Gradle `4.0`

/cc @mmoayyed

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes #9732 

As an additional check, try to locate the json metadata by taking into account the presence of a new 'java' directory in the path.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Sure thing. Coming right up. Thanks for the review.

**Comment by mmoayyed** [comment]
I spent a bit more time on this and updated the pull request based on what I think you had in mind. Please review, and if the approach used here checks out, I'll happily proceed to add test cases.

**Comment by mmoayyed** [comment]
Just to elaborate a bit, you will see two commits pushed up here. The first commit is where I experimented with `getParentFile()` to locate the resources directory recursively to then build the right path. Having done that, I then realized that might not be needed since I can simply just build the resources folder explicitly as a `File` object and then use that, thus the subsequent commit. 

The only bit I am not sure about is the hardcoding of `main` in there which feels a bit iffy but I suspect it's on the safe side. Let me know what you think.

**Comment by wilkinsona** [comment]
Thanks, @mmoayyed. I think you were right to abandon the `getParentFile()` approach. Sorry for sending you off in that direction.

I think we can actually simplify things even further and avoid hardcoding the use of `main`. I believe that this will work:

```java
// Gradle keeps things separate
String path = file.getPath();
int index = path.lastIndexOf(CLASSES_FOLDER);
if (index >= 0) {
	File resourcesFolder = new File(path.substring(0, index)
			+ RESOURCES_FOLDER + "/" + classOutputLocation.getName());
	file = new File(resourcesFolder, ADDITIONAL_METADATA_PATH);
}
```

Where `classOutputLocation` is a `File` derived from the `FileObject` returned from:

```java
this.environment.getFiler().getResource(StandardLocation.CLASS_OUTPUT, "", "")
```

**Comment by mmoayyed** [comment]
Thanks very much! I'll resume testing a bit and then will follow-up with actual unit tests :) Changes upcoming.

**Comment by mmoayyed** [comment]
So played around with this some more. This:

```java
FileObject classOutputLocation = this.environment.getFiler().getResource(StandardLocation.CLASS_OUTPUT, "", "");
```

Causes this:

```bash
warning: Unable to merge additional metadata
warning: java.lang.IllegalArgumentException: Invalid relative name: 
        at com.sun.tools.javac.file.JavacFileManager.getFileForOutput(JavacFileManager.java:737)
        at com.sun.tools.javac.processing.JavacFiler.getResource(JavacFiler.java:467)
        at org.springframework.boot.configurationprocessor.MetadataStore.getAdditionalMetadataStream(MetadataStore.java:114)
        at org.springframework.boot.configurationprocessor.MetadataStore.readAdditionalMetadata(MetadataStore.java:78)
        at org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.mergeAdditionalMetadata(ConfigurationMetadataAnnotationProcessor.java:412)
```

See the comments in the source code please.

I ended up providing a "dummy" relative path in order to bypass the error and then was able to look up the `main` directory path. 

```java
FileObject classOutputLocation = this.environment.getFiler().getResource(StandardLocation.CLASS_OUTPUT, "", "dummy");
```

In reality, it looks like `dummy` can be anything except blank. Still somewhat iffy, but perhaps the best we can do for the time being? Let me know how you feel about the workaround and I'll continue with tests, etc.

Thanks for your time, as always.

**Comment by wilkinsona** [comment]
What a ridiculous API! Sorry, again, for pointing you in a slightly awkward direction. Rather than looking for `dummy`, how about looking for `META-INF` and then we can go up one directory to get the class output location and can go "down" to get the additional metadata JSON file?

We'd like to release 1.5.5 in the next few hours, and we'd also like to include a fix for this issue in that release. You've already spent a lot of time on this which is much appreciated. If you have time to make a final round of updates and add some tests then that would be great. Equally, if you don't have time right now, we're more than happy to merge what you've done thus far and make the necessary additions and refinements on top. Just let us know. Thanks.

**Comment by mmoayyed** [comment]
Thanks very much for the merge. All good. If it's OK with you, I'd like to continue working on this and implement a non-dummy solution :) I assume that's OK? I would not have been able to get it done in that particular time-frame but happy to resume work.

**Comment by wilkinsona** [comment]
@mmoayyed Thank you for your efforts on the PR. No need for a non-dummy solution. I did that as part of merging this. Please see https://github.com/spring-projects/spring-boot/commit/e0be40cd94680f8c0baa483651d2e632dcae32b0 for details.

**Comment by mmoayyed** [comment]
​Sweet! Look forward to trying this out in 1.5.5. ​

**Comment by mmoayyed** [comment]
​Sweet! Look forward to trying this out in 1.5.5. ​

**Pull request closed without merging**
