### PR TITLE
Allow to configure stack trace addition to Model via properties

### PR DESCRIPTION
**Pull request by Stummi**
Hi,

the logic to add the stacktrace to the model in case of errors is currently the following:

- If the response is HTML, don't add a stack trace
- else add the stack trace, if the request contains the parameter trace

I would like to improve this because of two reasons:

- In development environment you may want to add stacktrace information to both, html and non-html-models
- In production you may want to remove the ability of exposing stacktraces completly, even for non-html-responses

So I made the behavior configurable via two new properties, error.trace and error.trace.html, which can either be `ALWAYS`, `NEVER` or `REQUEST`. I preserved the current behavior as sensible default.

Please review and consider merging the PR.

Thanks,
Michael

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks. Have you signed the CLA?

**Comment by Stummi** [comment]
Yes I have signed the CLA. Do you need the confirmation number?

**Comment by philwebb** [comment]
No that's fine. We just needed confirmation.

**Comment by philwebb** [comment]
@dsyer any thoughts on this one?

**Comment by dsyer** [comment]
I like it.

**Comment by snicoll** [comment]
I've looked at the PR and polished it a bit in https://github.com/snicoll/spring-boot/commit/e77fcba8cc9d3a6403d31ad2f671371430e5755d 

I don't like the `error.*` prefix but that's not new so I am not sure if we can change that for 1.3 still (the `error.whitelabel.enabled` flag would have to move as well).

@philwebb can you have a quick look at my version before I merge it? I am not 100% sure yet. Thanks!

**Comment by philwebb** [comment]
Thanks for the PR. We've reworked things a bit so that there is now just a single `error.include-stacktrace` property (rather than one for HTML and one or other). By default both `@RequestMappings` now don't include the trace.

Hopefully the single attribute is enough for your needs, I think it probably will work for most users. If you do need a different result based on `produces` you can override `BasicErrorController.isIncludeStackTrace`.

**Pull request closed without merging**
