### PR TITLE
Update spring-boot-sample-amqp to use @EnableRabbit and @RabbitListener

### LINKED ISSUE #3451: Update spring-boot-sample-amqp to use @EnableRabbit and @RabbitListener
We recently updated the documentation to include details about using AMQP with Spring Boot (issue #3348)

I believe that it would be nice to update the **spring-boot-sample-amqp** code to match what we included in the documentation (using @EnableRabbit and @RabbitListener).

I'd be glad to help updating this code. I'll prepare a PR if you guys think that it is nice to update the examples.

@snicoll what do you think?

### PR DESCRIPTION
**Pull request by lucassaldanha**
Recently updated the documentation to include details about using AMQP with
Spring Boot. I have updated the spring-boot-sample-amqp to match the docs.

Fixes #3451

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks. Have you signed the CLA?

**Comment by lucassaldanha** [comment]
> Thanks. Have you signed the CLA?

Yes! :)

**Comment by snicoll** [comment]
This has been done in the meantime, thanks for the PR!

**Comment by lucassaldanha** [comment]
Sure! ☺

**Pull request closed without merging**
