### PR TITLE
Support @Timed annotation for WebFlux

### LINKED ISSUE #18680: Support @Timed annotation for WebFlux
We recently switched an application from WebMvc to WebFlux. We used the `@Timed` annotation on our controller methods to get custom timing metrics with custom percentiles. After switching to WebFlux, this stopped working. There is the default metric created by the `MetricsWebFilter`, but I couldn't find a way to configure the percentiles recorded.

It would be great if you could also support the `@Timed` annotation for WebFlux for maximum flexibility.
Alternatively, it would also help us if we could globally configure the percentiles for the timer recorded by the `MetricsWebFilter`.

### PR DESCRIPTION
**Pull request by anshlykov**
Fixes #18680

### CODE REVIEW

**Review by mehmetanbaki — COMMENTED** [review]
nice work

**Comment by patpatpat123** [comment]
Hello Team, 

I am currently using 2.4.1 recently released.
The issue is still here I believe.

Created an out of the box Webflux project out of spring.io.
No @Timed annotation, can see the usual

```
# TYPE http_server_requests_seconds summary
http_server_requests_seconds_count{exception="None",method="POST",outcome="SUCCESS",status="200",uri="/myRoute",} 1.0
http_server_requests_seconds_sum{exception="None",method="POST",outcome="SUCCESS",status="200",uri="/myRoute",} 0.610389546
# HELP http_server_requests_seconds_max  
# TYPE http_server_requests_seconds_max gauge
http_server_requests_seconds_max{exception="None",method="POST",outcome="SUCCESS",status="200",uri="/myRoute",} 0.610389546

```

However, annotated my controller with @Timed("pleasefindme")
and getting the exact same under /prometheus endpoint.

A little help please?
Thank you

**Comment by snicoll** [comment]
@patpatpat123 please stop [pasting the same comment](https://github.com/spring-projects/spring-boot/issues/18680#issuecomment-744156411) on several issues.

**Comment by philwebb** [comment]
Thanks very much @anshlykov, this has now been merged to master and will be in Spring Boot 2.5

**Comment by philwebb** [comment]
Reopening to update the docs at https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-metrics-web-flux

**Comment by patpatpat123** [comment]
Many thanks all. good day!

**Pull request closed without merging**
