### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by dstine**
Just a small typo fix.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dstine Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7085)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=7085) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by dstine** [comment]
The way I read `CONTRIBUTING.MD`, the CLA is only required for a "non-trivial patch".

**Comment by snicoll** [comment]
@pivotal-issuemaster this is an obvious fix

**Comment by pivotal-issuemaster** [comment]
@dstine This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by pivotal-issuemaster** [comment]
@dstine This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Pull request closed without merging**
