### PR TITLE
Obvious Fix: Spell check

### PR DESCRIPTION
**Pull request by yaman-jain**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@yaman-jain Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=12996)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=12996) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by snicoll** [comment]
@pivotal-issuemaster this is an obvious fix

**Comment by pivotal-issuemaster** [comment]
@yaman-jain This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by snicoll** [comment]
@yaman-jain thanks a lot for your first contribution to Spring Boot. This is now merged.

**Pull request closed without merging**
