### PR TITLE
Clarify how to specify main class

### PR DESCRIPTION
**Pull request by tomasaschan**
To someone quite new to the Java ecosystem, the wording "in the usual way" is exceedingly unhelpful. Instead, I added an example of how to configure this in the pom.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@tomasaschan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=17003)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=17003) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@tomasaschan Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=17003)!

**Comment by philwebb** [comment]
Thanks, that's a lot more helpful.

**Comment by mbhave** [comment]
@tomasaschan Thank you for making your first contribution to Spring Boot. This has now been merged into master.

**Pull request closed without merging**
