### PR TITLE
Generated metadata documentation does not escape the | character

### PR DESCRIPTION
**Pull request by vivganes**

### CODE REVIEW

**Comment by vivganes** [comment]
@snicoll is there a place where i can see the final output of the docs created by the build server?  That way i can do a final check myself.

**Comment by snicoll** [comment]
Our README has a section on how you can [generate the reference documentation](https://github.com/spring-projects/spring-boot/blob/master/README.adoc#building-reference-documentation).

**Comment by vivganes** [comment]
[spring-boot-reference.pdf](https://github.com/spring-projects/spring-boot/files/3448269/spring-boot-reference.pdf)
PDF file created locally after the changes - This escapes table properly 
To find the related table entry, search for string "Comma-separated list of additional unencoded" in the attached PDF file.

**Comment by snicoll** [comment]
@vivganes thank you very much for making your first contribution to Spring Boot.

**Pull request closed without merging**
