### PR TITLE
Consider using Arrays.toString to convert the array into a readable

### PR DESCRIPTION
**Pull request by mnhock**
The code invokes `toString` on an array, which will generate a fairly useless result. Consider using `Arrays.toString` to convert the array into a readable String that gives the contents of the array.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. Have you [signed the CLA](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#sign-the-contributor-license-agreement)?

**Comment by mnhock** [comment]
Thanks, I just singed the CLA.

**Comment by wilkinsona** [comment]
Thanks again for the PR. I've merged the changes into master.

**Comment by mnhock** [comment]
Thanks!

**Pull request closed without merging**
