### PR TITLE
Add Log4jdbc Starter reference

### PR DESCRIPTION
**Pull request by candrews**

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks, i've quickly reviewed and created https://github.com/candrews/log4jdbc-spring-boot-starter/issues/2

**Comment by candrews** [comment]
@snicoll I've made the improvement you suggested (thanks for raising that issue!), so can this PR now be merged?

**Comment by snicoll** [comment]
Thanks for the reminder and sorry about the delay.

**Comment by snicoll** [comment]
Fixed in a1452f6

**Pull request closed without merging**
