### PR TITLE
Add maxInMemorySize property for ReactiveRestClientAutoConfiguration …

### PR DESCRIPTION
**Pull request by sjlzcj**
…and add username and password in ClientConfiguration when username or password is not null

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sjlzcj Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20393)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20393) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sjlzcj Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=20393)!

**Comment by sjlzcj** [comment]
Add maxInMemorySize property for ReactiveRestClientAutoConfiguration and add username and password in ClientConfiguration when username or password is not null

**Comment by wilkinsona** [comment]
We already have a [proposal for making the max in-memory size configurable](https://github.com/spring-projects/spring-boot/pull/20205). It is currently scheduled for inclusion in Spring Boot 2.3.

The username and password are already applied by the existing auto-configuration:

https://github.com/spring-projects/spring-boot/blob/7aa5eb169c7e637e9ecb9915be380c341da28883/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/elasticsearch/ReactiveRestClientAutoConfiguration.java#L78-L82

Thanks anyway for your pull request.

**Pull request closed without merging**
