### PR TITLE
Upgrading spring kafka to 1.3.6

### PR DESCRIPTION
**Pull request by shivangshah**
Upgrading Spring Kafka to 1.3.6

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@shivangshah Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=14128)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=14128) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@shivangshah Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=14128)!

**Comment by mbhave** [comment]
Thanks for the PR but we don't upgrade to minor releases of dependencies in a maintenance release of Spring Boot. As you mentioned in #14129, you can explicitly override the version yourself.

**Comment by shivangshah** [comment]
@mbhave fair enough

**Pull request closed without merging**
