### PR TITLE
Deal with several holes in the article

### PR DESCRIPTION
**Pull request by caojiele**
These holes has a total of three places：
1.{spring-boot-docs-current},  there is no jump links.
2.{github-code}[getinvolved],  there is no jump links.
3. * *Running your code*,         the lack of punctuation":".

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@caojiele Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16065)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16065) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by spencergibb** [comment]
Those links get properly resolved when the documentation is built. See https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/htmlsingle/#boot-documentation-about

**Comment by pivotal-issuemaster** [comment]
@caojiele Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16065)!

**Comment by caojiele** [comment]
> Those links get properly resolved when the documentation is built. See https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/htmlsingle/#boot-documentation-about

ok,tks.

**Comment by wilkinsona** [comment]
Thanks anyway, @caojiele. As you may recall, the missing `:` has already been taken care of in https://github.com/spring-projects/spring-boot/pull/16056.

**Comment by caojiele** [comment]
> Thanks anyway, @caojiele. As you may recall, the missing `:` has already been taken care of in #16056.
OK,  thanks for reminding.

**Pull request closed without merging**
