### PR TITLE
storage configuration through application.properties for embedded mongodb autoconfigure

### PR DESCRIPTION
**Pull request by yogeshlonkar**
Added feature to configuration custom dbpath of embedded mongodb with spring boot
- [X] I have signed the CLA

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the pull request. A few comments:

- The new property shouldn't be added to `MongoProperties` as it's specific to embedded Mongo. Instead, it should be added to `EmbeddedMongoProperties`.
- I think the `dbpath` property could have a better name. The `Storage` type takes three arguments: `databaseDir`, `replSetName`, and `oplogSize`. I think it would be better to have our own `Storage` class nested in `EmbeddedMongoProperties` with a `databaseDir` property. That would match the naming of embedded Mongo and also make it easy to add `replSetName` and `oplogSize` properties in the future.
- The `getDbpath` method on `EmbeddedMongoAutoConfiguration is unnecessary. Calling the getter on the properties class directly would be better.

**Comment by yogeshlonkar** [comment]
Thanks will work on it. should I close this and later create new pull request?

**Comment by snicoll** [comment]
You can push force on your existing branch and this will update this PR, thanks!

**Comment by yogeshlonkar** [comment]
travis build failure fixed in EmbeddedMongoAutoConfigurationTests.java file by changing no accessible databaseDir path

**Comment by wilkinsona** [comment]
@yogeshlonkar Thanks. I fixed that as part of the merge, which I realise now I didn't comment about. Sorry and thanks for the PR. It's now in master.
 
PS Just for future reference, I had to tidy things up a bit as your PR included a revert of an unrelated commit.

**Pull request closed without merging**
