### PR TITLE
Avoid repeated calls of Web(Mvc|Flux)Registrations' getters

### PR DESCRIPTION
**Pull request by mruzicka**
Make sure the `WebMvcRegistrations`' and `WebFluxRegistrations`' getter methods are not called twice thus avoiding possible throw away construction of the returned objects in case the getter methods are implemented such that they construct a new object on each invocation.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mruzicka Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=23999)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=23999) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mruzicka Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=23999)!

**Comment by wilkinsona** [comment]
Thanks for the proposal, @mruzicka. This looks to me like a good change to make. Out of interest, have you seen the repeated invocations of the getters cause a problem in the real world or is this more theoretical?

**Comment by wilkinsona** [comment]
If/when we merge this, we should make a similar change to `EnableWebFluxConfiguration` when it's calling getters on `WebFluxRegistrations`.

**Comment by mruzicka** [comment]
> Thanks for the proposal, @mruzicka. This looks to me like a good change to make. Out of interest, have you seen the repeated invocations of the getters cause a problem in the real world or is this more theoretical?

Hi @wilkinsona, I noticed it while evaluating the [openapi-generator](https://github.com/OpenAPITools/openapi-generator) in a demo project. I happened to need a custom implementation of `RequestMappingHandlerAdapter` (to prioritize a custom `HandlerMethodArgumentResolver`s before the standard ones). I used a trivial `WebMvcRegistrations` implementation to create one (on each invocation of the respective getter method) and noticed that it was being created twice.
Did it have a measurable impact? No, but it might have if the creation of the custom `RequestMappingHandlerAdapter` was expensive.

I've added similar changes to the `EnableWebFluxConfiguration`.

**Comment by wilkinsona** [comment]
@mruzicka Thanks very much for making your first contribution to Spring Boot. The proposed changes have been merged into 2.3 and 2.4.

**Comment by mruzicka** [comment]
Thank you!

**Pull request closed without merging**
