### PR TITLE
Some code that can be optimized.

### PR DESCRIPTION
**Pull request by JiangXi-YuYan**
1.New LinkedHashMap and putAll(something) can be replaced by new LinkedHashMap<>(something).
2.Method reference is better than lambda.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@JiangXi-YuYan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18307)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18307) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@JiangXi-YuYan Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=18307)!

**Comment by JiangXi-YuYan** [comment]
Seems like the CI failures have nothing to do with my change, is there anything I can do?

**Comment by snicoll** [comment]
@JiangXi-YuYan thanks for asking, I believe your working copy of `master` was outdated. Next time, please make sure you're up-to-date with `origin/master` before creating a branch for a PR. I am reviewing the PR, no action required on your end at this point.

**Comment by JiangXi-YuYan** [comment]
Ok, thank you for your letter.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Stéphane Nicoll"<notifications@github.com&gt;; 
发送时间: 2019年9月23日(星期一) 晚上7:15
收件人: "spring-projects/spring-boot"<spring-boot@noreply.github.com&gt;; 
抄送: "MR.mister"<845058547@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [spring-projects/spring-boot] Some code that can be optimized. (#18307)




@JiangXi-YuYan thanks for asking, I believe your working copy of master was outdated. Next time, please make sure you're up-to-date with origin/master before creating a branch for a PR. I am reviewing the PR, no action required on your end at this point.

**Comment by snicoll** [comment]
Turns out that every single change proposed here already exist on `master`. I am going to close this now, thanks for the PR anyway.

**Pull request closed without merging**
