### PR TITLE
Added a simple way to check property named enabled with a new Condition

### PR DESCRIPTION
**Pull request by idosu**
Added a new Condition to put on a ConfigurationProperties, that checks value for "${prefix}.enabled" is "true", It's called ConditionalOnEnabledProperty.

I have one question(see OnEnabledPropertyCondition.java:46)

### CODE REVIEW

**Comment by idosu** [comment]
Hi, Can you help me figure out why does travis fail?

**Comment by idosu** [comment]
I found out that I have an error, so closing this pull request for now

**Comment by philwebb** [comment]
@idosu We'd recommend using the existing `@ConditionalOnProperty` annotation for this. I wouldn't be keen to add another for such a narrow use-case.

**Comment by idosu** [comment]
@philwebb I've read your argument and you are right, I just think that the framework should contain an easy solution to this widely used problem.

Almost always where you use `@ConditionalOnProperty(... name="enabled" ...)` you should have a `@ConfigurationProperties` alongside(I've checkd some of autoconfigure project's classes)

When using `@ConditionalOnProperty` your code looks like thins:
``` java
@ConfigurationProperties(PROPERTY)
class FooProperties {
    // To prevent a code duplication you should create a constant
    protected static final String PROPERTY = "spring.foo";
}

@ConditionalOnProperty(prefix=FooProperties .PROPERTY, name="enabled", havingValue="true")
@EnableConfigurationProperties(FooProperties.class)
class Foo {
}
```
My solution should be:
``` java
@ConfigurationProperties("spring.foo")
class FooProperties {
}

@ConditionalOnEnabledProperty // Or something like this
@EnableConfigurationProperties(FooProperties.class)
class Foo {
}
```

I think that your argument could also be applied to `@ConditionalOnEnabledEndpoint` `@ConditionalOnEnabledHealthIndicator` and `@ConditionalOnEnabledInfoContributor`, the only difference is that they manage spring's properties(endpoints, management.health and management.info)

**Comment by wilkinsona** [comment]
The three conditions you have mentioned are all more complex than the one that you have proposed. Each checks the value of two different properties: one that's specific and one that's a general fallback. Unlike what you've proposed here, none of them could be replaced with a single `@ConditionalOnProperty`

**Pull request closed without merging**
