### PR TITLE
Remove explicit type arguments

### PR DESCRIPTION
**Pull request by izeye**
This PR removes explicit type arguments which can be inferred.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks, @izeye. Out of interest, how did you find these? It'd be nice to rely on inference where possible in 1.5.x as well and cherry picking this back might not be straightforward.

**Comment by izeye** [comment]
@wilkinsona I just filtered them using `\.<[^/a-z]` regex first and checked them manually 😅

**Comment by wilkinsona** [comment]
The equivalent changes don't work will on 1.5.x, I think due to different type inferencing in javac when it's targeting 1.6-compatible byte code. Let's just make these changes in master.

**Comment by wilkinsona** [comment]
Thanks once again, @izeye. This change is now in master. Just FYI, I dropped the changes to the JOOQ-generated source as they'll get clobbered the next time the source is regenerated.

**Pull request closed without merging**
