### PR TITLE
Updated CONTRIBUTING.adoc file with Maven wrapper info etc

### PR DESCRIPTION
**Pull request by rdm100**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rdm100 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=19695)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=19695) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by wilkinsona** [comment]
It looks like this was opened in error.

**Comment by rdm100** [comment]
This was the issue I was responding to https://github.com/quick-perf/quickperf/issues/19

**Comment by wilkinsona** [comment]
That's a separate repository in a separate organisation. The address that issue you'll need to make changes to https://github.com/quick-perf/quickperf/blob/master/CONTRIBUTING.md and submit a pull request to https://github.com/quick-perf/quickperf.

**Pull request closed without merging**
