### PR TITLE
make InMemoryTraceRepository thread safe

### PR DESCRIPTION
**Pull request by obourgain**
InMemoryTraceRepository has at least 3 race conditions
- reverse can be set by a thread and read by an other without happens before relationship
- capacity can be set by a thread and read by an other without happens before relationship
- the collection returned by findAll() is a view on the still mutable List `traces`

edit : 
a forth race condition :
- capacity may be modified by an other thread during the while loop, same for reverse and may result in the wrong entry being evicted

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks. Have you [signed the CLA](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#sign-the-contributor-license-agreement)?

**Comment by wilkinsona** [comment]
Rather than marking `reverse` and `capacity` as `volatile` and taking local copies in `add`, I think it makes the intent clearer if the two setters synchronize on `this.traces`.

**Comment by obourgain** [comment]
CLA signed.

I think having the setters synchronize is ok as they are probably rarely (never ?) called outside of bean construction. I will update the PR when I got some time.

As a side node, using a ring buffer instead of the LinkedList would make collecting traces generate less garbage.

**Comment by wilkinsona** [comment]
> I think having the setters synchronize is ok as they are probably rarely (never ?) called outside of bean construction.

Indeed. I don't think it was ever the intention for the configuration to be changed once the application context has been refreshed. I'd actually prefer to make both fields final and have them configured via the constructor. Unfortunately, that would be a breaking API change so that ship has sailed (for 1.2.x at least).

>  I will update the PR when I got some time.

Thanks, but there's no need to update the PR, I'll make the changes as part of the merge.

**Comment by obourgain** [comment]
OK, thanks.

**Pull request closed without merging**
