### PR TITLE
Output generated by Gradle plugin's bootRun task is color-coded when pos...

### PR DESCRIPTION
**Pull request by Nowheresly**
...sible.

Fixes gh-747

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks! Have you signed the CLA?

**Comment by Nowheresly** [comment]
Yes, I have

**Comment by Nowheresly** [comment]
Is there anything else I should do?

**Comment by philwebb** [comment]
I wonder why the `isConsoleAvailableMethod` works when it is in the gradle script but not in the running application? I assume it's because `System.console()` returns `null` in the running app.

Duplicating the entire method in `BootRunTask` is a little smelly and I'm also wondering if setting `spring.output.ansi.enabled` to `always` might interfere with any user defined setting. Perhaps we should instead add an environment variable for `spring.output.ansi.console-available` which could then be picked up by `AnsiOutput`?

**Comment by Nowheresly** [comment]
> Duplicating the entire method in BootRunTask is a little smelly

I'm not really proud of it, I admit...

> Perhaps we should instead add an environment variable for spring.output.ansi.console-available which could then be picked up by AnsiOutput?

I adapted my initial PR trying to follow your advice. 
Thanks for taking time to review.

**Comment by philwebb** [comment]
Merged for 1.3. with a few additional tweaks to save duplicating the `isConsoleAvailableMethod()` logic.

Thanks!

**Pull request closed without merging**
