### PR TITLE
Add docker-api starter on spring-boot-starters' README

### PR DESCRIPTION
**Pull request by jliu666**
Add docker-java starter on spring-boot-starters readme.

### CODE REVIEW

**Comment by bclozel** [comment]
@jliu666 I've created a few issues on your starter. Could you take a look at those first?

**Comment by jliu666** [comment]
@bclozel OK! Thank you.

**Comment by jliu666** [comment]
@bclozel I have answered some questions. Could you give me more suggestions?

**Comment by bclozel** [comment]
I've opened jliu666/docker-api-spring-boot#1, jliu666/docker-api-spring-boot#2 and jliu666/docker-api-spring-boot#3.

**Comment by jliu666** [comment]
OK! Thank you very much!
Now those issues may be resolved now.

**Comment by jliu666** [comment]
@bclozel 
Hello. This is my first pull request. Could you please tell me the status of the pull request?. I don't know the label `type:task`'s meaning.

**Comment by bclozel** [comment]
It's been merged with b23befc (I polished a bit your commit). It's live already.
Thanks!

**Pull request closed without merging**
