### PR TITLE
Polish some Collectors

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

this trivial PR replaces usages like `Collectors.toCollection(ArrayList::new)` with `Collectors.toList()`.

Let me know what you think.
Cheers,
Christoph

### CODE REVIEW

**Comment by philwebb** [comment]
Although internally `Collectors.toList()` returns an `ArrayList` the javadoc made me nervous enough to not use it:

> here are no guarantees on the type, mutability, serializability, or thread-safety of the List returned

It's probably very unlikely to change in future versions, but you never know. I'll flag this one and see what the rest of the team think.

**Comment by snicoll** [comment]
FTR, I've seen `Collectos.toList()` being used in many places so if we don't like that, we should probably change those as well.

**Comment by wilkinsona** [comment]
It all depends on how the list is used. If it's only used internally then it's probably fine. Problems are more likely to arise when it's passed to another component that relies on certain behaviour.

**Comment by dreis2211** [comment]
I guess this PR is safe in that regards. The lists/sets/collections we're talking about do not rely on anything special imho, but please check for yourself.

**Comment by philwebb** [comment]
Yeah, double checking those changes and I think they are all safe. The only one that's a bit iffy is the result of `AutoConfigurations.sort` which I guess someone might expect to be always mutable.

**Comment by snicoll** [comment]
Agreed, I've reverted that last change as I think we should enforce the fact we expect an order for the list there.

**Pull request closed without merging**
