### PR TITLE
Add health indicator for ElasticSearch cluster

### PR DESCRIPTION
**Pull request by binwei**
Add health indicator for ElasticSearch cluster, checking health of all or specified indices

### CODE REVIEW

**Comment by philwebb** [comment]
Nice, thanks. We'll take a look at this for 1.3.

Have you signed the CLA?

**Comment by binwei** [comment]
Sounds good. Yes I signed agreement, and I can provide confirmation # if necessary.

**Comment by wilkinsona** [comment]
Thanks. I've merged this with some additional changes. See 03b109a2 for details.

**Comment by christian-laakmann** [comment]
Sadly, the changes introduced in 03b109a broke the actual health-check. I've added #2812 to fix this

**Comment by bclozel** [comment]
This HealthIndicator is indeed a nice addition to Boot.
There are many deployment environments where using the native ElasticSearch client is not possible, nor querying the cluster API.

For example, [Sagan](https://github.com/spring-io/sagan/) is hosted on [Pivotal Web Services](https://run.pivotal.io) and is using a searchly.com marketplace service; this service only gives access to the HTTP REST API and denies access to the cluster API, since this is a shared environment.

FYI, I've created a [simple HealthIndicator](https://github.com/spring-io/sagan/blob/e003b6a50342629f4ca75a79a00941f572c81c73/sagan-site/src/main/java/sagan/support/health/ElasticsearchHealthIndicator.java) that is using the JestClient and the Stats Index API to query the index state.

**Comment by wilkinsona** [comment]
@bclozel Can you please open a separate issue for providing JestClient-based support?

**Pull request closed without merging**
