### PR TITLE
Fix incorrect detection of Amazon Redshift

### LINKED ISSUE #25128: Incorrect detection of Amazon Redshift
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Problem
Detection of Amazon Redshift in [org.springframework.boot.jdbc.DataBaseDriver](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/jdbc/DatabaseDriver.java#L73) is incorrect.  The Redshift JDBC driver returns [`Redshift` as the `productName`](https://github.com/aws/amazon-redshift-jdbc-driver/blob/3c337cb9bb6590fe23a1aa9f5f121a7e29a3655e/src/main/java/com/amazon/redshift/jdbc/RedshiftDatabaseMetaData.java#L153) but we are using `Amazon Redshift` as the `productName`.

## Solution
Update the [`DatabaseDriver`](https://github.com/spring-projects/spring-boot/blob/301e80be8c4da73dd734d93f915088de4997c88c/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/jdbc/DatabaseDriver.java) enum with the right value for the `productName` for `Redshift`.

Update [the tests](https://github.com/spring-projects/spring-boot/blob/301e80be8c4da73dd734d93f915088de4997c88c/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/jdbc/DatabaseDriverTests.java) to ensure that the right `DatabaseDriver.fromProductName()` works for `Redshift`.

## Steps to Fix 
 
- [ ] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

### PR DESCRIPTION
**Pull request by melburne**
Resolves #25128

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@melburne Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=25265)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=25265) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@melburne Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=25265)!

**Comment by melburne** [comment]
Hi @snicoll I've made the changes requested in the issue description. Please let me know if I need to change any other files.

**Comment by snicoll** [comment]
@melburne thank you for making your first contribution to Spring Boot.

**Pull request closed without merging**
