### PR TITLE
Rename ElasticSearchJestHealthIndicatorAutoConfiguration

### PR DESCRIPTION
**Pull request by ayudovin**
Rename `ElasticSearchJestHealthIndicatorAutoConfiguration` to `ElasticsearchJestHealthIndicatorAutoConfiguration`
this [task](https://github.com/spring-projects/spring-boot/issues/15705)

### CODE REVIEW

**Comment by mbhave** [comment]
#14881 is a similar issue which is currently on hold for the deprecated auto-config support which will enable it to be implemented in a non-breaking manner. It seems inconsistent to do this before #14860 given that moving a class is less of a breaking change than renaming it since the IDE will be able to find it in the former case.

**Comment by ayudovin** [comment]
@mbhave, do you want that I add changes for this [#14881](https://github.com/spring-projects/spring-boot/issues/14881) in this pull request?

**Comment by ayudovin** [comment]
@mbhave, does it mean that this pull request should be on hold until #14860 is done?

**Comment by mbhave** [comment]
@ayudovin Sorry, I should've been a bit more clear about what I meant. The comment was for the team to consider that there could be such inconsistencies before merging the PR. The milestone would be decided based on what the team decides.

**Comment by ayudovin** [comment]
@mbhave, ok, no problem

**Comment by snicoll** [comment]
Thank you for the PR but there are actually 3 auto-configuration classes with the same problem and we don't believe adding a breaking change in 2.2 for this is worthwhile. We can reconsider when #14860  is implemented and we can group all three in a single auto-configuration. Right now they are split to benefit from the optimization of skipping the auto-configuration if the client library is not on the classpath.

**Pull request closed without merging**
