### PR TITLE
creating ReactiveJwtDecoder by issuer uri

### PR DESCRIPTION
**Pull request by ayudovin**
creating ReactiveJwtDecoder bean by oidc issuer location 
this [enhancement](https://github.com/spring-projects/spring-boot/issues/14166)

### CODE REVIEW

**Comment by mbhave** [comment]
@ayudovin thanks for the PR. For the future, before creating a PR, please check that there is no one assigned to the original issue in order to avoid duplicating effort.

**Comment by ayudovin** [comment]
@mbhave, oh sorry for this,  my fault, i'll be more careful

**Comment by mbhave** [comment]
Thanks @ayudovin. This is now on master.

**Comment by ayudovin** [comment]
@mbhave  Thank you1
Again sorry for my mistake.

**Comment by mbhave** [comment]
no problem. thank you for contributing!

**Pull request closed without merging**
