### PR TITLE
Add missing .class to @RunWith(SpringExtension) in references docs

### LINKED ISSUE #16207: Typo in 'Testing Spring Boot Applications' note on JUnit 5
There is a typo in the documentation. It currently states:

>If you are using JUnit 4, don’t forget to also add @RunWith(SpringRunner.class) to your test, otherwise the annotations will be ignored. If you are using JUnit 5, there’s no need to add the equivalent @ExtendWith(SpringExtension) as @SpringBootTest and the other @…Test annotations are already annotated with it.

The `.class` is missing, so it should be:

>  ....equivalent @ExtendWith(SpringExtension.class) as....

### PR DESCRIPTION
**Pull request by orangeroad0922**
Fix #16207  (Typo in 'Testing Spring Boot Applications' note on JUnit 5)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@orangeroad0922 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16213)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16213) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@orangeroad0922 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16213)!

**Comment by pivotal-issuemaster** [comment]
@orangeroad0922 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=16213)!

**Comment by snicoll** [comment]
@orangeroad0922 thank you very much for making your first contribution to Spring Boot. This is now merged in `2.1.x` and `master`.

**Pull request closed without merging**
