### PR TITLE
Mojibake happen in not UTF-8 console.

### PR DESCRIPTION
**Pull request by megascus**

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. Can you please explain why you want to make this change.

**Comment by megascus** [comment]
In Japanese Windows, console encoding is Windows-31J. (not UTF8)
I think in the most of OS console encoding is controled by 'LANG' environment and, it is appropriate without change.

**Comment by wilkinsona** [comment]
It's not just the OS's console encoding that matters here. Logback uses the configured charset when it's converting a `String` into a `byte[]`. There may be many people relying on this conversion being done using UTF-8. We can consider making it configurable (in the same way as LOG_PATH, LOG_FILE, etc). In the meantime, you can, of course, provide your own logback.xml that configures the console appender with a charset that's appropriate for your environment.

**Comment by megascus** [comment]
OK, I`m wating the time. Thanks.

**Pull request closed without merging**
