### PR TITLE
Indenting SpringApplication javadoc code

### PR DESCRIPTION
**Pull request by rafael-rollo**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rafael-rollo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8039)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8039) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rafael-rollo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=8039)!

**Comment by snicoll** [comment]
Thanks for the PR!

**Comment by rafael-rollo** [comment]
It was a pleasure

**Pull request closed without merging**
