### PR TITLE
fix missing trailing slash in spring.resources.static-locations

### PR DESCRIPTION
**Pull request by szantopeter**
If the value of `spring.resources.static-locations` is not ending with a trailing slash then no resources are loaded from the specified folder. The current code already provided a solution for adding a trailing slash, but that processing was done in the wrong place, so I moved it to a location where it really takes effect.

### CODE REVIEW

**Comment by szantopeter** [comment]
@snicoll @philwebb what do you think about this PR?

**Comment by philwebb** [comment]
> that processing was done in the wrong place, so I moved it to a location where it really takes effect.

@szantopeter Can you provide a bit more background on why the existing code isn't working for you? Do you have a sample application you can share that shows the problem?

**Comment by szantopeter** [comment]
@philwebb I created a sample here https://github.com/szantopeter/spring-boot-static-locations There are two tests, both should pass, but one fails. The only difference between them is a trailing slash

**Comment by philwebb** [comment]
Thanks.

**Comment by philwebb** [comment]
We might be able to shift that logic to `setStaticLocations`

**Comment by wilkinsona** [comment]
@szantopeter Thanks very much for the PR. As suggested by @philwebb, we've taken a slightly different approach to fixing the problem. Please see https://github.com/spring-projects/spring-boot/commit/ad629055faf690e5cbd4d63e89b259783744c1cb for details.

**Comment by szantopeter** [comment]
@wilkinsona it took me some efforts to identify the bug and find the solution so I was hoping that I will have a commit in Spring Boot, but apart from that final solution is good as well!

**Comment by wilkinsona** [comment]
@szantopeter Sorry. We would normally have taken a bit more time to give you a chance to make the suggested updates but we're trying to finish off 1.5.4 which is due on Thursday. Please don't misinterpret the PR not being merged as us not appreciating your efforts.

**Pull request closed without merging**
