### PR TITLE
Add auto-configuration support for Spring Data GemFire Repositories.

### PR DESCRIPTION
**Pull request by jxblum**
The commit message/title for this PR says it all.
- [X] I have signed the CLA

### CODE REVIEW

**Comment by jxblum** [comment]
@wilkinsona and _Spring Boot_ team- Just an FYI, I need to update the _Spring Boot_ [Ref Guide](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-gemfire) and specifically make note of the _Spring Data GemFire_, Repositories auto-configuration support.  I will do this first thing tomorrow, PST.  Thanks - John


Thanks,
John

**Comment by jxblum** [comment]
All updates done; this PR is ready for review and merging as appropriate.

**Comment by snicoll** [comment]
@jxblum this issue is scheduled for 1.5. What is going on with this PR?

**Comment by jxblum** [comment]
@snicoll Sorry, I renamed the branch upon which this PR was based and it closed the PR apparently.  This is still needed.

**Comment by jxblum** [comment]
This PR has been replaced by PR #6952.

**Pull request closed without merging**
