### PR TITLE
Added loading logging config file from file system

### LINKED ISSUE #4061: Allow log config files to be loaded from non-classpath locations
`AbstractLoggingSystem.findConfig(String[])` only ever tests for config file located in the classpath. It would be nice to allow other (e.g. URL-based) locations.

### PR DESCRIPTION
**Pull request by spacanowski**
Will resolve #4061

### CODE REVIEW

**Comment by spacanowski** [comment]
Reason of test failures is fixed in #4088

**Comment by philwebb** [comment]
@spacanowski Thanks! Have you signed the CLA?

**Comment by spacanowski** [comment]
Just now ; )
Sorry, didn't read FAQ and requirements - my bad.

**Comment by philwebb** [comment]
Thanks for the PR but I think we'd rather change `loadConfiguration` to take a `Resource` rather than `String`.

**Comment by guptalav108** [comment]
According to this, we can load logging configuration either from class path or file system.
Is there any way to fetch the logging configuration from git repository directly as we do for other application related property files ?

**Comment by philwebb** [comment]
@guptalav108 We've not fixed #4061 yet, but when we do it should be possible to load from anything that can be represented as a Spring `Resource`.

**Comment by guptalav108** [comment]
Thanks philwebb for the quick reply :)

**Pull request closed without merging**
