### PR TITLE
Add @ConfigurationPropertyValue annotation

### PR DESCRIPTION
**Pull request by thombergs**
Adds the `@ConfigurationPropertyValue `annotation as proposed in issue #7986. Fixes issue #7986 if merged.

The annotation supports defining a fallback property to bind if the original property is not available and defining a default value which is bound if the fallback property also fails (or is not defined).

Changes are covered with unit tests and I added a short example of the annotation to the feature docs.

Looking forward to feedback :).

### CODE REVIEW

**Comment by thombergs** [comment]
...investigating the cause for the build failure...

**Comment by snicoll** [comment]
Thanks for the PR. Unfortunately, we are currently rewriting the binding mechanism from scratch (almost) which would make the core of this PR outdated. I am not sure when that's going to land in master but surely everything else (including the test) should be a very good base.

WDYT @philwebb ?

**Comment by thombergs** [comment]
I'll ask next time before starting on an issue :-). I'll gladly re-implement this feature on top of the new binding mechanism (if it's not included yet) if you give me a trigger here once it's merged.

**Comment by thombergs** [comment]
Will using `@ConfigurationProperties` on an interface be possible with the new binding mechanism? I just wanted to add a unit test for that case, since the "defaultValue" feature implemented in this PR only really makes sense with an interface and I noticed it's not possible yet, as far as I can see.

**Comment by philwebb** [comment]
@thombergs The plan is to support interface based binding. It's turning out to be be quite a chunk of work so it's not yet ready to merge into master.

**Comment by snicoll** [comment]
@thombergs I might give this a try next week with current `master`. As things stand, we'd be looking at the `fallback` property for now only (more to come later). Would you be willing to rework your PR with the new binding mechanism?

**Comment by thombergs** [comment]
Sure, just give me a heads-up when you're done.

Just to be sure: only the fallback mechanism for now and leave the default value mechanism for later, correct?

**Comment by snicoll** [comment]
> Sure, just give me a heads-up when you're done.

Sorry that wasn't clear. If you don't have time to rework the PR, I'll give it a try as we'd like this feature to go in. So please let me know if you have time to work on that short term.

> only the fallback mechanism for now and leave the default value mechanism for later, correct?

Yes (we don't have interface binding yet so that's not necessary for now)

**Comment by thombergs** [comment]
I misunderstood. I thought you meant you were going to do the binding mechanism rework, but that obviously already happened.

I will look into it starting tonight and will probably need a couple nights to grasp the new binding concepts and re-integrate the fallback mechanism. I will submit a new PR then.

**Comment by philwebb** [comment]
@thombergs Thanks. If you get anywhere could you please do a force push to this branch, rather than opening a new PR.

**Comment by thombergs** [comment]
Will do.

**Comment by thombergs** [comment]
I force pushed a re-implementation on top of the new binding mechanism.

The `@ConfigurationPropertyValue` annotation and the fallback feature are implemented in commit 0a759da.

For a fallback to function over different property namespaces, I had to remove a check that skipped binding when no property was found in a namespace (see commit 47d4559). I couldn't see any side effects, but you probably should look into it.

Implementing this on top the refactored binding mechanism was a lot more straight forward than on the old version, so the refactoring definitely pays off ;).

**Comment by thombergs** [comment]
updated this pull request to work with current master

**Comment by thombergs** [comment]
Updated this PR again on top of current master and squashed it to a single commit.

**Comment by philwebb** [comment]
Thanks for the update. I think we'll need to review this as part of the wider push to support interface based configuration properties. Unfortunately, that's unlikely to happen until Boot 2.1 now :(

**Comment by philwebb** [comment]
We've been discussing configuration properties again today as a team and we're starting to feel like the supporting fallback options might not be the best idea in the long run. It feels like a feature that could persuade users to create overly complex property structures.

We've decided that for now, we're better off suggesting that people implement fallback scenarios directly in their code.

Thanks very much for your efforts with this, and I'm sorry that we didn't manage to solidify our thoughts sooner.

**Pull request closed without merging**
