### PR TITLE
support webEnvironment accessor

### PR DESCRIPTION
**Pull request by mbenson**
Title says it all

- [X] I have signed the CLA

### CODE REVIEW

**Comment by philwebb** [comment]
What's actually driving the change? Most of the setters in `SpringApplication` don't have getters.

**Comment by wilkinsona** [comment]
I would guess it's to avoid duplicating the deduction logic. The same argument would apply here as for adding a getter for the main class (gh-4801).

**Comment by philwebb** [comment]
I guess that makes sense. It's just that you could also look at the `Environment` class type or use `@ConditionalOnWebApplication` (depending on the use-case).

**Comment by mbenson** [comment]
My thinking was indeed along the lines that Andy guessed. I feel that having an accessor would lead to cleaner code than using an `instanceof` to check the _results_ of `web` being set to `true` as opposed to simply checking the source.

**Comment by philwebb** [comment]
OK, sold :)

**Pull request closed without merging**
