### PR TITLE
Support for JOOQ

### PR DESCRIPTION
**Pull request by aahlenst**
I'm using [JOOQ](http://www.jooq.org/) for interaction with SQL databases. JOOQ requires quiet some plumbing for proper integration with Spring so I thought having a starter for Spring Boot would be handy and save others some time.

This PR is my first attempt to create a starter and I'm looking for feedback and whether you're interested in including it at all. The integration follows [the example provided by the JOOQ project](https://github.com/jOOQ/jOOQ/tree/master/jOOQ-examples/jOOQ-spring-example/src/main/java/org/jooq/example/spring). Please have a look whether the code I borrowed from the JOOQ project is correctly attributed, too.

If you're fine with the PR I could add some documentation if you like me to.

### CODE REVIEW

**Comment by philwebb** [comment]
Thanks. Have you signed the CLA? We might also need CLA agreement from @lukaseder since you are also reusing his code.

**Comment by philwebb** [comment]
This PR might also have an impact on the Spring IO platform, especially given that there are different JOOQ editions.

/cc @wilkinsona

**Comment by aahlenst** [comment]
Yes, I have signed the CLA (December 2014).

Would you prefer that I replace the reused code? Might be a bit tricky. There aren't so many ways to do it.

**Comment by lukaseder** [comment]
I'm happy to sign any CLA that is needed for you to re-use ASL 2.0 licensed jOOQ stuff that was taken from GitHub. In the case of the aforementioned code, all code is ASL 2.0 licensed.

Let me know where I can sign it.

**Comment by philwebb** [comment]
Thanks Lukas. The CLA form is available here: https://support.springsource.com/spring_committer_signup

**Comment by lukaseder** [comment]
I have signed the CLA - which covers express contributions from my side (e.g. to fix things in the future). The code that has been included by @aahlenst already includes all the licenses required by Pivotal via ASL 2.0. [Some people think](https://blog.openshift.com/keep-calm-and-merge-on-lowering-barriers-to-open-source-contributions-with-apache-v2/) that CLAs are unnecessary when both parties publish code under the terms of the ASL 2.0.

By the way, @aahlenst: Thank you very much for doing this, this is greatly appreciated!

**Comment by philwebb** [comment]
Thanks for signing the CLA @lukaseder, I appreciate it.

**Comment by lukaseder** [comment]
This is excellent news (working through vacation backlog...) We'll look into covering a story on the jOOQ blog pretty soon!

**Pull request closed without merging**
